project:
  type: book
  output-dir: docs

book:
  title: "Three States Records"
  author: ""
  date: "7/1/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Wèi"
      chapters:
        - 1wei/01.qmd
        - 1wei/02.qmd
        - 1wei/03.qmd
        - 1wei/04.qmd
        - 1wei/05.qmd
        - 1wei/06.qmd
        - 1wei/07.qmd
        - 1wei/08.qmd
        - 1wei/09.qmd
        - 1wei/10.qmd
        - 1wei/11.qmd
        - 1wei/12.qmd
        - 1wei/13.qmd
        - 1wei/14.qmd
        - 1wei/15.qmd
        - 1wei/16.qmd
        - 1wei/17.qmd
        - 1wei/18.qmd
        - 1wei/19.qmd
        - 1wei/20.qmd
        - 1wei/21.qmd
        - 1wei/22.qmd
        - 1wei/23.qmd
        - 1wei/24.qmd
        - 1wei/25.qmd
        - 1wei/26.qmd
        - 1wei/27.qmd
        - 1wei/28.qmd
        - 1wei/29.qmd
        - 1wei/30.qmd
    - part: "Shǔ"
      chapters:
        - 2shu/31.qmd
        - 2shu/32.qmd
        - 2shu/33.qmd
        - 2shu/34.qmd
        - 2shu/35.qmd
        - 2shu/36.qmd
        - 2shu/37.qmd
        - 2shu/38.qmd
        - 2shu/39.qmd
        - 2shu/40.qmd
        - 2shu/41.qmd
        - 2shu/42.qmd
        - 2shu/43.qmd
        - 2shu/44.qmd
        - 2shu/45.qmd
    - part: "Wú"
      chapters:
        - 3wu/46.qmd
        - 3wu/47.qmd
        - 3wu/48.qmd
        - 3wu/49.qmd
        - 3wu/50.qmd
        - 3wu/51.qmd
        - 3wu/52.qmd
        - 3wu/53.qmd
        - 3wu/54.qmd
        - 3wu/55.qmd
        - 3wu/56.qmd
        - 3wu/57.qmd
        - 3wu/58.qmd
        - 3wu/59.qmd
        - 3wu/60.qmd
        - 3wu/61.qmd
        - 3wu/62.qmd
        - 3wu/63.qmd
        - 3wu/64.qmd
        - 3wu/65.qmd
    - part: "Appendices"
      chapters:
        - 4appendices/1.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



