## Index {.unnumbered}

In-Progress: [9/65]

### 1 Annals of Emperor Wǔ
武帝紀

+ [Cáo Cāo 曹操](1wei/01.qmd#caocao)
    + [grandfather Cáo Téng 曹騰](1wei/01.qmd#caoteng)
    + [father Cáo Sōng 曹嵩](1wei/01.qmd#caosong)

### 2 Annals of Emperor Wén
文帝紀

+ [Cáo Pī 曹丕](1wei/02.qmd#caopi)

### 3 Annals of Emperor Míng
明帝紀

+ [Cáo Ruì 曹叡](1wei/03.qmd#caorui)
     + [Hǎo Zhāo 郝昭](1wei/03.qmd#haozhao)
     + [Qín Lǎng 秦朗](1wei/03.qmd#qinlang)

### 4 Annals of Three Young Emperors
三少帝紀

+ [Cáo Fāng 曹芳](1wei/04.qmd#caofang)
    + [Zhāng Tè 張特](1wei/04.qmd#zhangte)
    + [Guō Xiū 郭脩](1wei/04.qmd#guoxiu)
+ [Cáo Máo 曹髦](1wei/04.qmd#caomao)
     + [Yīng Yú 應余](1wei/04.qmd#yingyu)
     + [Zhèng Xiǎotóng 鄭小同](1wei/04.qmd#zhengxiaotong)
+ [Cáo Huàn 曹奐](1wei/04.qmd#caohuan)

### 5 Biographies of Empresses and Consorts
后妃傳

+ [Biàn 卞](1wei/05.qmd#wuxuan)
     + [Dīng 丁](1wei/05.qmd#dingshi)
     + [younger brother Biàn Bǐng 卞秉](1wei/05.qmd#bianbing)
     + [younger brother's son Biàn Lán 卞蘭](1wei/05.qmd#bianlan)
     + [younger brother's great-granddaughter Cáo Máo's Empress Biàn 卞](1wei/05.qmd#caomaobian)
     + [younger brother's granddaughter Cáo Huàn's Empress Biàn 卞](1wei/05.qmd#caohuanbian)
+ [Zhēn 甄](1wei/05.qmd#wenzhao)
    + [cousin's grandson's adopted heir Zhēn Dé 甄德](1wei/05.qmd#zhende)
    + [elder brother's granddaughter Cáo Fāng's Empress Zhēn 甄](1wei/05.qmd#caofangzhen)
+ [Guō 郭](1wei/05.qmd#wende)
    + [elder cousin Guō Biǎo 郭表](1wei/05.qmd#guobiao)
    + [elder sister's son Mèng Wǔ 孟武](1wei/05.qmd#mengwu)
+ [Máo 毛](1wei/05.qmd#mingdao)
    + [father Máo Jiā 毛嘉](1wei/05.qmd#maojia)
    + [younger brother Máo Zēng 毛曾](1wei/05.qmd#maozeng)
+ [Guō 郭](1wei/05.qmd#mingyuan)
    + [father's younger brother's son Guō Jiàn 郭建](1wei/05.qmd#guojian)

### 6 Biographies of Dŏng, Two Yuán, Liú
董二袁劉傳

+ [Dǒng Zhuó 董卓](1wei/06.qmd#dongzhuo)
    + [Hé Jìn 何進](1wei/06.qmd#hejin)
    + [Hé Miáo 何苗](1wei/06.qmd#hemiao)
    + [daughter's husband Niú Fǔ 牛輔](1wei/06.qmd#niufu)
    + [Lǐ Jué 李傕](1wei/06.qmd#lijue)
    + [Guō Sì 郭汜](1wei/06.qmd#guosi)
    + [Mǎ Téng 馬騰](1wei/06.qmd#mateng)
    + [Hán Suì 韓遂](1wei/06.qmd#hansui)
    + [Yáng Fèng 楊奉](1wei/06.qmd#yangfenghanxian)
    + [Hán Xiān 韓暹](1wei/06.qmd#yangfenghanxian)
+ [Yuán Shào 袁紹](1wei/06.qmd#yuanshao)
    + [son Yuán Tán 袁譚](1wei/06.qmd#yuantan)
    + [son Yuán Xī 袁熙](1wei/06.qmd#yuanxi)
    + [son Yuán Shàng 袁尚](1wei/06.qmd#yuanshang)
    + [Jū Shòu 沮授](1wei/06.qmd#jushou)
    + [Húmǔ Bān 胡毋班](1wei/06.qmd#humuban)
    + [Qū Yì 麴義](1wei/06.qmd#quyi)
    + [Guō Tú 郭圖](1wei/06.qmd#guotu)
    + [Tián Fēng 田豐](1wei/06.qmd#tianfeng)
    + [Páng Jì 逢紀](1wei/06.qmd#pangji)
    + [Shěn Pèi 審配](1wei/06.qmd#shenpei)
    + [Hán Héng 韓珩](1wei/06.qmd#hanheng)
+ [Yuán Shù 袁術](1wei/06.qmd#yuanshu)
    + [son Yuán Yào 袁燿](1wei/06.qmd#yuanyao)
    + [Chén Wēn 陳溫](1wei/06.qmd#chenwen)
    + [Mǎ Mìdī 馬日磾](1wei/06.qmd#mamidi)
    + [Chén Guī 陳珪](1wei/06.qmd#chengui)
+ [Liú Biǎo 劉表](1wei/06.qmd#liubiao)
    + [son Liú Qí 劉琦](1wei/06.qmd#liuqi)
    + [son Liú Cóng 劉琮](1wei/06.qmd#liucong)
    + [Zhāng Xiàn 張羨](1wei/06.qmd#zhangxian)
    + [Fù Xùn 傅巽](1wei/06.qmd#fuxun)
    + [Kuǎi Yuè 蒯越](1wei/06.qmd#kuaiyue)
    + [Hán Sōng 韓嵩](1wei/06.qmd#hansong)
    + [Dèng Xī 鄧羲](1wei/06.qmd#dengxi)
    + [Liú Xiān 劉先](1wei/06.qmd#liuxian)

### 7 Biographies of Lǚ Bù, Zāng Hóng
呂布臧洪傳

+ [Lǚ Bù 呂布](1wei/07.qmd#lvbu)
    + [Zhāng Miǎo 張邈](1wei/07.qmd#zhangmiao)
    + [Chén Gōng 陳宮](1wei/07.qmd#chengong)
    + [Chén Dēng 陳登](1wei/07.qmd#chendeng)
+ [Zāng Hóng 臧洪](1wei/07.qmd#zanghong)
    + [Chén Róng 陳容](1wei/07.qmd#chenrong)

### 8 Biographies of Two Gōngsūn, Táo, Four Zhāng
二公孫陶四張傳第八

+ [Gōngsūn Zàn 公孫瓚](1wei/08.qmd#gongsunzan)
    + [Liú Yù 劉虞](1wei/08.qmd#liuyu)
    + [Xiānyú Fǔ 鮮于輔](1wei/08.qmd#xianyufu)
+ [Táo Qiān 陶謙](1wei/08.qmd#taoqian)
+ [Zhāng Yáng 張楊](1wei/08.qmd#zhangyang)
+ [Gōngsūn Dù 公孫度](1wei/08.qmd#gongsundu)
    + [Gongsūn Kāng 公孫康](1wei/08.qmd#gongsunkang)
    + [Gōngsūn Yuān 公孫淵](1wei/08.qmd#gongsunyuan)
+ [Zhāng Yàn 張燕](1wei/08.qmd#zhangyan)
+ [Zhāng Xiù 張繡](1wei/08.qmd#zhangxiu)
+ [Zhāng Lŭ 張魯](1wei/08.qmd#zhanglu)

### 9 Biographies of the Various Xiàhóu and Cáo
諸夏侯曹傳

+ [Xiàhóu Dūn 夏侯惇](1wei/09.qmd#xiahoudun)
    + [Xiàhóu Mào 夏侯楙](1wei/09.qmd##xiahoumao)
    + [Hán Hào 韓浩](1wei/09.qmd#hanhao)
    + [Shǐ Huàn 史渙](1wei/09.qmd#shihuan)
+ [Xiàhóu Yuān 夏侯淵](1wei/09.qmd#xiahouyuan)
    + [Xiàhóu Bà 夏侯霸](1wei/09.qmd#xiahouba)
+ [Cáo Rén 曹仁](1wei/09.qmd#caoren)
    + [Cáo Chún 曹純](1wei/09.qmd#caochun)
+ [Cáo Hóng 曹洪](1wei/09.qmd#caohong)
+ [Cáo Xiū 曹休](1wei/09.qmd#caoxiu)
    + [Cáo Zhào 曹肇](1wei/09.qmd#caozhao)
+ [Cáo Zhēn 曹真](1wei/09.qmd#caozhen)
    + [Cáo Shuǎng 曹爽](1wei/09.qmd#caoshuang)
        + [Hé Yàn 何晏](1wei/09.qmd#heyan)
+ [Xiàhóu Shàng 夏侯尚](1wei/09.qmd#xiahoushang)
    + [Xiàhóu Xuán 夏侯玄](1wei/09.qmd#xiahouxuan)
        + [Xǔ Yǔn 許允](1wei/09.qmd#xuyun)
        + [Wáng Jīng 王經](1wei/09.qmd#wangjing)

### 10 Biographies of Xún Yù, Xún Yōu, Jiǎ Xǔ
荀彧荀攸賈詡傳

+ [Xún Yù 荀彧](1wei/10.qmd#xunyu)
+ [Xún Yōu 荀攸](1wei/10.qmd#xunyou)
+ [Jiǎ Xǔ 賈詡](1wei/10.qmd#jiaxu)


11. Yuán Huàn, Zhāng Fàn, Liáng Mào, Guó Yuān, Tián Chóu, Wáng Xiū, Bǐng Yuán, Guǎn Níng
12. Cuī Yǎn (Kǒng Róng), Máo Jiè, Xú Yì, Hé Kuí, Xíng Yóng, Bào Xūn, Sīmǎ Zhī
13. Zhōng Yáo (Yù), Huà Xīn, Wáng Lǎng (Sù)
14. Chéng Yù, Guō Jiā, Dǒng Zhāo, Liú Yè, Jiǎng Jì, Liú Fàng (Sūn Zī)
15. Liú Fǔ, Sīmǎ Lǎng, Liáng Xí, Zhāng Jì, Wēn Huī, Jiǎ Kuí (Chōng)
16. Rén Jùn, Sū Zé, Dù Jī, Zhèng Hún, Cāng Cí
17. Zhāng Liáo, Yuè Jìn, Yú Jīn, Zhāng Hé, Xǔ Huǎng (Zhū Líng)
18. Lǐ Diǎn, Lǐ Tōng, Zāng Bà, Wén Pín, Lǚ Qiān, Xǔ Chǔ, Diǎn Wéi, Páng Dé, Páng Yù, Yán Wēn
19. Cáo Zhāng, Cáo Zhí, Cáo Xiōng
20. Sons of Wǔ, Sons of Wén
21. Wáng Càn, Wèi Jì, Liú Yì, Liú Shào, Fù Gǔ
22. Huán Jiē, Chén Qún (Tài), Chén Jiǎo, Xú Xuān, Wèi Zhēn, Lú Yù
23. Hé Qià, Cháng Lín, Yáng Jùn, Dù Xí, Zhào Yǎn, Péi Qián
24. Hán Jì, Cuī Lín, Gāo Róu, Sūn Lǐ, Wáng Guàn
25. Xīn Pí, Yáng Fù, Gāotáng Lóng
26. Mǎn Chǒng, Tián Yù, Qiān Zhāo, Guō Huái
27. Xú Miǎo, Hú Zhì, Wáng Chǎng, Wáng Jī
28. Wáng Líng, Guànqiū Jiǎn, Zhūgě Jǐn, Dèng Ài, Zhōng Huì
29. Huà Tuó, Dù Kuí, Zhū Jiànpíng, Zhōu Xuān, Guǎn Lù
30. Wūhuán, Xiānbēi, Fūyú, Gāogōulí, Dōngwòjǔ, Yìlóu, Huì, Hán, Wō, [Xīóng]
31. Liú Yān, Liú Zhāng
32. Liú Bèi
33. Liú Shàn
34. Gān, Wú, Zhāng, Zhāng, Liú Yǒng, Liú Lǐ, Liú Xuán
35. Zhūgě Liàng (Qiáo, Zhān)
36. Guān Yǔ, Zhāng Fēi, Mǎ Chāo, Huáng Zhōng, Zhào Yún
37. Páng Tǒng, Fǎ Zhèng
38. Xǔ Jìng, Mí Zhú, Sūn Qián, Jiǎn Yōng, Yī Jí, Qín Mì
39. Dǒng Hé, Liú Bā, Mǎ Liáng, Chén Zhēn, Dǒng Yǔn, Lǚ Yì
40. Liú Fēng, Péng Yáng, Liáo Lì, Lǐ Yán, Liú Yǎn, Wèi Yán, Yáng Yí
41. Huò Jùn, Wáng Lián, Xiàng Lǎng, Zhāng Yí, Yáng Hóng, Fèi Shī
42. Dù Wēi, Zhōu Qún,  Dù Qióng,  Xǔ Cí,  Mèng Guāng, Lái Mǐn, Yǐn Mò, Lǐ Zhuàn, Qiáo Zhōu, Xì Zhèng
43. Huáng Quán, Lǐ Huī, Lǚ Kǎi, Mǎ Zhōng, Wáng Píng, Zhāng Nì
44. Jiǎng Wǎn, Fèi Yī, Jiāng Wéi
45. Dèng Zhī, Zhāng Yì, Zōng Yù, Yáng Xì
46. Sūn Jiān, Sūn Cè
47. Sūn Quán
48. Sūn Liàng, Sūn Xiū, Sūn Hào
49. Liú Yáo, Tàishǐ Cí, Shì Xiè
50. Wú, Xiè, Xú, Bù, Wáng, Wáng, Pān, Quán, Zhū, Hé, Téng
51. Sūn Jìng, Sūn Bēn, Sūn Fǔ, Sūn Yí, Sūn Kuāng, Sūn Sháo, Sūn Huán
52. Zhāng Zhāo, Gù Yōng, Zhūgě Jǐn, Bù Zhì
53. Zhāng Hóng, Yán Jùn, Chéng Bǐng, Kàn Zé, Xuē Zōng
54. Zhōu Yú, Lǔ Sù, Lǚ Méng
55. Chéng Pǔ, Huáng Gài, Hán Dāng, Jiǎng Qīn, Zhōu Tài, Chén Wǔ, Dǒng Xí, Gān Níng, Líng Tǒng, Xú Shèn, Pān Zhāng, Dīng Fèng
56. Zhū Zhì, Zhū Rán, Lǚ Fàn, Zhū Huán
57. Yú Fān, Lù Jì, Zhāng Wēn, Luò Tǒng, Lù Mào, Wú Càn, Zhū Jù
58. Lú Xùn (Kàng)
59. Sūn Dēng, Sūn Lǜ, Sūn Hé, Sūn Bà, Sūn Fèn
60. Hè Qí, Quán Cóng, Lǚ Dài, Zhōu Fáng, Zhōnglí Mù
61. Pān Jùn, Lù Kǎi
62. Shì Yí, Hú Zōng
63. Wú Fàn, Liú Dūn, Zhào Dá
64. Zhūgě Kè, Téng Yìn, Sūn Jùn, Sūn Chēn, Púyáng Xīng
65. Wáng Fán, Lóu Xuán, Hè Shào, Wéi Yào, Huà Hé