# Annals of Emperor Wén  {#caopi}

## Yánkāng (220) {.unnumbered}

::: {.columns}
::: {.column width="70%"}
Wén Huángdì  forbidden name Pī appellation Zǐhuán, was Wǔ-dì’s Heir-Apparent. Zhōngpíng Fourth Year [187] Winter, born at Qiáo. <a href="#annotation-1" id="source-1">[1]</a> Jiàn’ān Sixteenth Year [211], became Five Office Central Cadet General, aide to the Assistant Chancellor. Twenty-Second Year [217], established as Wèi Heir-Apparent. <a href="#annotation-2" id="source-2">[2]</a> When Tàizǔ passed away, succeeded the positions of Assistant Chancellor, King of Wèi. <a href="#annotation-3" id="source-3">[3]</a> Honored the Royal Queen as Royal Dowager Queen.  Changed Jiàn’ān Twenty-Fifth Year to Yánkāng Inaugural Year.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
文皇帝諱丕，字子桓，武帝太子也。中平四年冬，生于譙。〔一〕建安十六年，為五官中郎將、副丞相。二十二年，立為魏太子〔二〕。太祖崩，嗣位為丞相、魏王。〔三〕尊王后曰王太后。改建安二十五年為延康元年。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-1" id="annotation-1">[1]</a> Wèi shū states: At the time when the Emperor was born, there was a mist cyan and round like a chariot’s canopy above him, to the end of day. An interpreter of mist  believed that it was a confirmation of utmost nobility, not the mist of a servant of men. Aged eight years, he was able to compose prose. He had outstanding talent, and therefore widely worked through the books of the classics and hundred schools of thought from antiquity to the present. He excelled in riding and shooting, and enjoyed sword fencing. Nominated as Abundant Talent, not enacted.  

Xiàn-dì Qǐjū zhù states: Jiàn’ān Thirteenth Year [208], he was by Excellency over the Masses Zhào Wēn recruited.  Tàizǔ memorialized: “[Zhào] Wēn has recruited from Your Servant’s junior relatives, the selection and nomination therefore cannot be genuine.” Sent Attendant Central observing Minister of Staff Chī Lǜ Holding Stave to present the certificate dismissing [Zhào] Wēn from office.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書曰：帝生時，有雲氣青色而圜如車蓋當其上，終日，望氣者以為至貴之證，非人臣之氣。年八歲，能屬文。有逸才，遂博貫古今經傳諸子百家之書。善騎射，好擊劍。舉茂才，不行。獻帝起居注曰：建安十（五）〔三〕年，為司徒趙溫所辟。太祖表「溫辟臣子弟，選舉故不以實」。使侍中守光祿勳郗慮持節奉策免溫官。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-2" id="annotation-2">[2]</a> Wèi lüè states: Tàizǔ did not timely establish the Heir-Apparent, the Heir-Apparent doubted himself.  At the time there was a Gāo Yuánlǚ,  excelled in physiognomy, thus called and asked him, and he replied saying: “Your nobility cannot be spoken of.”  Asked: “How long is my lifespan?” Yuánlǚ said: “As for lifespan, reaching forty there will be a small hardship, passing that there will be no worries.” Later very soon he was established as the Royal Heir-Apparent, reaching years of forty then he died.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　魏略曰：太祖不時立太子，太子自疑。是時有高元呂者，善相人，乃呼問之，對曰：「其貴乃不可言。」問：「壽幾何？」元呂曰：「其壽，至四十當有小苦，過是無憂也。」後無幾而立為王太子，至年四十而薨。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-3" id="annotation-3">[3]</a> Yuán Hóng’s Hàn jì  records the Hàn Emperor’s Edict stating: “Wèi Heir-Apparent [Cáo] Pī: in the past August Heaven provided your illustrious father to assist Our Imperial family, therefore forcefully he eliminated the crowds of evils, expanded and settled the Nine Provinces, vast achievements and abundant accomplishments, radiant through the cosmos. We employed folded hands and back against the screen  for over twenty years. Heaven could not leave me one elder, to forever protect my one person, early departed and concealed as a spirit, I mourn and lament in deep pain. [Cáo] Pī, you accumulated generations of renown and enlightenment, and should grasp the civil and the martial, to carry on and expand the previous legacy. Now send Envoy Holding Stave Censorate Grandee Huà Xīn to present the conferment Edict to grant [Cáo] Pī the Assistant Chancellor’s Seal and Ribbon, the King of Wèi’s Ruler’s Seal and Cord, designate Jì Province Governor. Right now the exterior has remnant caitiffs, distant Yí not yet guests, flags and drums are still at the frontier borders, shields and spears cannot be cased and sheathed. This then is the season for spreading and raising vast exploits, establishing achievement and passing down name. How can you cultivate the rituals of the mourning rooms and seek the ambitions of Zēng and Mǐn?  Thus respectfully obey Our command: restrain and stop your mourning and sorrow, follow and revere this legacy, in time shine with numerous achievements, to fulfill Our intention. Oh alas, you cannot but exhort yourself!”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔三〕　袁宏漢紀載漢帝詔曰：「魏太子丕：昔皇天授乃顯考以翼我皇家，遂攘除群凶，拓定九州，弘功茂績，光於宇宙，朕用垂拱負扆二十有餘載。天不憖遺一老，永保余一人，早世潛神，哀悼傷切。丕奕世宣明，宜秉文武，紹熙前緒。今使使持節御史大夫華歆奉策詔授丕丞相印綬、魏王璽紱，領冀州牧。方今外有遺虜，遐夷未賓，旗鼓猶在邊境，干戈不得韜刃，斯乃播揚洪烈，立功垂名之秋也。豈得脩諒闇之禮，究曾、閔之志哉？其敬服朕命，抑弭憂懷，旁祗厥緒，時亮庶功，以稱朕意。於戲，可不勉與！」
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Inaugural Year Second Moon [220 Mar 22 – Apr 20] <a href="#annotation-4" id="source-4">[4]</a> Rénxū [220 Apr 6], appointed Grand Central Grandee Jiǎ Xǔ as Grand Commandant, Censorate Grandee Huà Xīn as Chancellor of State, Minister Judge Wáng Lǎng as Censorate Grandee.  Installed Cavalier Regular Attendants and Attendant Cadets, each four men.  That eunuchs who held office were not to exceed the various bureau directors was made into a written order on metal tablets, stored in the Stone Room.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
元年二月〔一〕王戌，以大中大夫賈詡為太尉，御史大夫華歆為相國，大理王朗為御史大夫。置散騎常侍、侍郎各四人，其宦人為官者不得過諸署令；為金策著令，藏之石室。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-4" id="annotation-4">[4]</a> Wèi shū records the Gēngxū [220 Mar 25] Order stating: “Passes and ferries are for connecting merchant travelers, reservoirs and parks are for defending against disasters and famines. Setting restrictions and increasing taxes is not the way to convenience the people. Thus abolish reservoir and park restrictions, and decrease pass and ferry taxes, all reduced to one tenth.” Xīnhài [Mar 26], bestowed on the various marquesses and kings, officers, ministers, and below with grain of ten thousand hú, silk of a thousand pǐ,  gold and silver each on distinct basis. Sent envoys to tour the prefectures and states, and if there were those that violated law, extorted the people, or were tyrannical, to cite their crimes.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書載庚戌令曰：「關津所以通商旅，池苑所以禦災荒，設禁重稅，非所以便民；其除池籞之禁，輕關津之稅，皆復什一。」辛亥，賜諸侯王將相已下將粟萬斛，帛千匹，金銀各有差等。遣使者循行郡國，有違理掊克暴虐者，舉其罪。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Previously, in Hàn’s Xīpíng Fifth Year [176],  a Yellow Dragon was sighted at Qiáo. Radiant Grandee Qiáo Xuán  asked Grand Scribe Director Shàn Yáng:  “What is this omen?” [Shān] Yáng said: “This state later will have a ruler rise. Not reaching fifty years, it will again be seen. Heaven’s affairs are constant in signs, this will be fulfilled.” Nèihuáng’s Yīn Dēng  secretly recorded this. Reaching to the forty-fifth year, [Yīn] Dēng was still alive. Third Moon [220 Apr 21 – May 19], a Yellow Dragon was sighted at Qiáo. [Yīn] Dēng heard this and said: “Are Shàn Yáng’s words are thus verified now?” <a href="#annotation-5" id="source-5">[5]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
初，漢熹平五年，黃龍見譙，光祿大夫橋玄問太史令單颺：「此何祥也？」颺曰：「其國後當有王者興，不及五十年，亦當復見。天事恆象，此其應也。」內黃殷登默而記之。至四十五年，登尚在。三月，黃龍見譙，登聞之曰：「單颺之言，其驗茲乎！」〔一〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-5" id="annotation-5">[5]</a> Wèi shū states: The King summoned and met [Yīn] Dēng, and said to him: “In the past Chéng Fēng heard the divination of Chǔqiū and so respectfully treated Jì Yǒu.  Dèng Chén believed Shàogōng’s words and submitted himself to Guāng-Wǔ.  [Yīn] Dēng, you as a venerable elder, devoted to divination techniques, recorded and understand Heaven’s ways, is it so [the same situation]?” Bestowed on [Yīn] Dēng grain of three hundred hú, sent him to return home.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書曰：王召見登，謂之曰：「昔成風聞楚丘之繇而敬事季友，鄧晨信少公之言而自納光武。登以篤老，服膺占術，記識天道，豈有是乎！」賜登穀三百斛，遣歸家。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Yǐmǎo [220 Apr 23], Front General Xiàhóu Dūn became General-in-Chief. The Huìmò and Fúyú Chányú and the Yānqí and Yútián kings all each sent envoys to present tribute. <a href="#annotation-6" id="source-6">[6]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
已卯，以前將軍夏侯惇為大將軍。濊貊、扶餘單于、焉耆、于闐王皆各遣使奉獻。〔一〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-6" id="annotation-6">[6]</a> Wèi shū states: Bǐngxū [220 Apr 30], ordered the scribal officials to restore the Chóng, Lí, Xī, Hé offices, to venerate the August Heavens, record the changes of form of the sun, moon, and stars to serve Heaven’s seasons. 

Your Servant Sōngzhī notes: Wèi shū has this claim but one does not hear of these offices.

Dīnghài [220 May 1] Order said: “Former Secretariat Writers Deputy Director Máo Jiè, Ministers of Presentations Wáng Xiū, Liáng Mào, Minister of Cadets Yuán Huàn, Minister Treasurers Xiè Huàn, Wàn Qián, Central Commandants Xú Yì, Guó Yuān  and others, all were loyal and upright at Court, walked with benevolence and righteousness, all early to leave the world, but their sons and grandsons are in decline. Anguished and pitying this, thus appoint all their sons as Cadet Centrals.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書曰：丙戌，令史官奏修重、黎、羲、和之職，欽若昊天，歷象日月星辰以奉天時。臣松之案：魏書有是言而不聞其職也。丁亥令曰：「故尚書僕射毛玠、奉常王脩、涼茂、郎中令袁渙、少府謝奐、萬潛、中尉徐奕、國淵等，皆忠直在朝，履蹈仁義，並早即世，而子孫陵遲，惻然愍之，其皆拜子男為郎中。」
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Summer, Fourth Moon, Dīngsì [220 May 31], Ráo’ān county reported a white pheasant sighting. <a href="#annotation-7" id="source-7">[7]</a> Gēngwǔ [220 Jun 13], General-in-Chief Xiàhóu Dūn died. <a href="#annotation-8" id="source-8">[8]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
夏四月丁巳，饒安縣言白雉見。〔一〕庚午，大將軍夏侯惇薨。〔二〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-7" id="annotation-7">[7]</a> Wèi shū states: Bestowed on Ráo’ān farm tax [exemptions], on Bóhǎi prefecture oxen and alcohol per hundred households,  greatly drinking for three days. Minister of Ceremonies with Grand Offering sacrificed at the Ancestral Temples.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書曰：賜饒安田租，勃海郡百戶牛酒，大酺三日；太常以太牢祠宗廟。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-8" id="annotation-8">[8]</a> Wèi shū states: The King wore mourning clothes and visited Yè’s east city gate to hold mourning.

Sūn Shèng states: By Ritual, Heaven’s Son weeps for those of the same surname outside the Ancestral Temple gates. Weeping at the city gate was mistaken in its position.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　魏書曰：王素服幸鄴東城門發哀。孫盛曰：在禮，天子哭同姓於宗廟門之外。哭於城門，失其所也。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Fifth Moon, Wùyín [220 Jun 21], Heaven’s Son mandated that the King posthumously honor his august grandfather the Grand Commandant [Cáo Sōng] as Tài-wáng and his consort Dīng-shì as Tài-wánghòu,  and enfeoffed the King’s son [Cáo] Ruì as Marquess of Wǔdé. <a href="#annotation-9" id="source-9">[9]</a> That moon, Píngyì mountain bandits Zhèng Gān and Wáng Zhào led their multitudes to surrender,  both enfeoffed as Ranked Marquesses. <a href="#annotation-10" id="source-10">[10]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
五月戊寅，天子命王追尊皇祖太尉曰太王，夫人丁氏曰太王后，封王子叡為武德侯。〔一〕是月，馮翊山賊鄭甘、王照率眾降，皆封列侯。〔二〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-9" id="annotation-9">[9]</a> Wèi lüè states: Appointed Attendant Central Zhèng Chēng  as the Marquess of Wǔdé’s Tutor. The Order said: “Lóngyuán and Tài’ē were produced from Kūnwú’s metal.  Hé-shì’s jade annulus came from a well village’s field.  Honing them with whetstones, polishing them with other mountains, therefore they were able to reach a price of multiple cities and become world famous treasures. Study also is the whetstone for men. [Zhèng] Chēng is diligent in study and a great classicist,  encouraged to use classical scholarship to support the Marquess, and should from dawn to dusk enter to attend, to enlighten his ambitions.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏略曰：以侍中鄭稱為武德侯傅，令曰：「龍淵、太阿出昆吾之金，和氏之璧由井里之田；礱之以砥礪，錯之以他山，故能致連城之價，為命世之寶。學亦人之砥礪也。稱篤學大儒，勉以經學輔侯，宜旦夕入侍，曜明其志。」
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-10" id="annotation-10">[10]</a> Wèi shū states: Previously, Zhèng Gān and Wáng Zhào with the Lúshuǐ Hú  led their associates to come surrender. The King obtained the surrender letter and showed it to the Court saying: “Formerly there was wish for an Order for me to suppress the Xiānbēi, I did not agree and yet they surrendered. Also there was wish to send me this autumn to suppress the Lúshuǐ Hú, I did not listen, and now they also surrender. In the past Wèi Marquess Wǔ in one plan was successful and had a self-pleased expression, meeting with ridicule from Lǐ Kuī.  I now speak of this, not because it is this situation, but only from a belief that sitting and having them surrender is an achievement greater than mobilizing soldiers and armor.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　魏書曰：初，鄭甘、王照及盧水胡率其屬來降，王得降書以示朝曰：「前欲有令吾討鮮卑者，吾不從而降；又有欲使吾及今秋討盧水胡者，吾不聽，今又降。昔魏武侯一謀而當，有自得之色，見譏李悝。吾今說此，非自是也，徒以為坐而降之，其功大於動兵革也。」
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Jiǔquán’s Huáng Huà and Zhāngyè’s Zhāng Jìn  and others each seized their Administrators to rebel. Jīnchéng Administrator Sū Zé  suppressed [Zhāng] Jìn and beheaded him. [Huáng] Huà surrendered. <a href="#annotation-11" id="source-11">[11]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
酒泉黃華、張掖張進等各執太守以叛。金城太守蘇則討進，斬之。華降。〔一〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-11" id="annotation-11">[11]</a> [Huáng] Huà later became Yǎn Province Inspector. See Wáng Líng zhuàn.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　華後為兗州刺史，見王淩傳。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Sixth Moon, Xīnhài [220 Jul 24], Drilled Troops in the East Suburbs. <a href="#annotation-12" id="source-12">[12]</a> Gēngwǔ [220 Aug 12], therefore campaigned south. <a href="#annotation-13" id="source-13">[13]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
六月辛亥，治兵于東郊，〔一〕庚午，遂南征。〔二〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-12" id="annotation-12">[12]</a> Wèi shū states: The Excellencies and Ministers managed ceremonies, the King rode canopied chariot, observing the beats of the metal drums.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書曰：公卿相儀，王御華蓋，視金鼓之節。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-13" id="annotation-13">[13]</a> Wèi lüè states: The King was about to set out on campaign. Limiting Expenses Central Cadet General Xīnpíng’s Huò Xìng  sent up memorial remonstrating that said: “Your Servant has heard that in the matter of King Wén and Zhòu,  at the time Heaven’s Under ‘closed sacks to avoid blame,’  altogether hundreds of noble men, none willing to give counsel. Now you Great King embody the model of Qián and Kūn,  widely opening to listen in four [directions], allowing the worthy and the foolish to each establish their judgments. In prostration considering that the Former King [Cáo Cāo] in achievements is without compare, but now of what can be said, he was not praised for virtue. Therefore the sagely man states: ‘Obtain the pleased hearts of the Hundred Surnames,’  the military books states: ‘Battle is a dangerous affair.’  Therefore, the six states fiercely battled and powerful Qín took advantage of their exhaustion,  the King of Bīn did not fight and Zhōu’s ways thus prospered.  I humbly say that you Great King for the time being should entrust the heavy [responsibilities] to the current Court and ‘maintain the feminine,’  restrain power as a tiger crouching, and your achievements and enterprise can be completed. But now at the initiation of the foundations, you yet again raise troops. Troops are a violent tool, certainly there will be violent disturbances, disturbances then lead to thoughts of chaos, chaos appears without expecting it. Your Servant says this precariousness is the precariousness of stacked eggs.  In the past Xià Qǐ was in seclusion for three years,  the Yì has ‘do not go far and so return,’  the Lún has ‘do not fear change.’  Sincerely may you the Great King consider the past and investigate the present, deeply plan and distantly consider, with the three serving grandees  calculate the strengths and shortcomings. Your Servant was immersed in the Former King’s treatment, and also at the first change in government further received heavy responsibility, and though I know that speaking will disturb dragon scales  and that flattery is near to fortune, I humbly am emotionally moved of having read of ‘precarious and yet not supported.’”  The memorial was sent, the Emperor was furious, sent inspectors of treason to interrogate, in the end killing him.  Shortly after he regretted it, pursued to pardon but was too late.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　魏略曰：王將出征，度支中郎將新平霍性上疏諫曰：「臣聞文王與紂之事，是時天下括囊無咎，凡百君子，莫肯用訊。今大王體則乾坤，廣開四聰，使賢愚各建所規。伏惟先王功無與比，而今能言之類，不稱為德。故聖人曰『得百姓之歡心』。兵書曰『戰，危事也』是以六國力戰，彊秦承弊，豳王不爭，周道用興。愚謂大王且當委重本朝而守其雌，抗威虎臥，功業可成。而今創基，便復起兵，兵者凶器，必有凶擾，擾則思亂，亂出不意。臣謂此危，危于累卵。昔夏啟隱神三年，易有『不遠而復』，論有『不憚改』。誠願大王揆古察今，深謀遠慮，與三事大夫算其長短。臣沐浴先王之遇，又初改政，復受重任，雖知言觸龍鱗，阿諛近福，竊感所誦，危而不持。」奏通，帝怒，遣刺奸就考，竟殺之。既而悔之，追原不及。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Autumn, Seventh Moon, Gēngchén [220 Aug 22], Order said: “Xuānyuán had discussions at Míngtái, Fàngxūn had inquiries at Qúshì,  all in order to widely consult their subordinates. <a href="#annotation-14" id="source-14">[14]</a> The Hundred Officials and relevant managers thus are to attend to exhaustively remonstrating based on their duties, officers to directly lay out military methods, court servicemen to make clear system regulations, governors and administrators to describe government affairs, the pierced girdles to investigate the Six Arts. I will completely read them.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
秋七月庚辰，令曰：「軒轅有明臺之議，放勛有衢室之問，皆所以廣詢於下也。〔一〕百官有司，其務以職盡規諫，將率陳軍法，朝士明制度，牧守申政事，縉紳考六藝，吾將兼覽焉。」
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-14" id="annotation-14">[14]</a> Guǎn-zǐ states: That Huáng-dì established the discussions at Míngtái was to above observe the troops.  That Yáo had the inquiries at Qúshì was to below listen to the people.  Shùn had banners for announcing excellence so the ruler would not be ignorant.  Yǔ set established drums in Court to prepare to judge cases.  Tāng had the hall of Zǒngjiē in order to see the people’s criticisms.  King Wǔ had the park at Língtái so the worthies advanced.  These were how the ancient sagely emperors and enlightened kings were able to possess and not lose, to obtain and not forget.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　管子曰：黃帝立明臺之議者，上觀於兵也；堯有衢室之問者，下聽於民也；舜有告善之旌，而主不蔽也；禹立建鼓於朝，而備訴訟也；湯有總街之廷，以觀民非也；武王有靈臺之囿，而賢者進也：此古聖帝明王所以有而勿失，得而勿忘也。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Sūn Quán sent envoy to present tribute. Shǔ officer Mèng Dá led his multitudes to surrender.  Wǔdū’s Dī King Yáng Pú  led his tribesmen inward to submit, residing in Hànyáng prefecture. <a href="#annotation-15" id="source-15">[15]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
孫權遣使奉獻。蜀將孟達率眾降。武都氐王楊僕率種人內附，居漢陽郡。〔一〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-15" id="annotation-15">[15]</a> Wèi lüè records the King’s own handwritten Order stating: “In former days  [I] sent envoys to announce the state’s authority and spirit, and [Mèng] Dá at once came. I ponder the Chūnqiū commending Yífù,  and at once enfeoff and appoint [Mèng] Dá, sending him back as designate Xīnchéng Administrator.  Recently again there are those supporting their old and carrying their young to head toward the ruler’s influence. I have heard that the people of Sùshā themselves bound their lord to submit to Shénnóng,  the multitudes of Bīn state carried their children on their backs to enter Fēng and Hào.  How could herding or plunder or coercion or threats have caused this? Therefore it was social influence stirring their emotions, and benevolence and righteousness moving their inner feelings, joyous hearts from within issuing out that caused it to be so. From this extrapolating, the west and south for ten thousand lǐ will not be exterior, and [Sūn] Quán and [Liú] Bèi will have whom to defend them to the death?”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏略載王自手筆令曰：「（吾）〔日〕前遣使宣國威靈，而達即來。吾惟春秋褒儀父，即封拜達，使還領新城太守。近復有扶老攜幼首向王化者。吾聞夙沙之民自縛其君以歸神農，豳國之眾襁負其子而入豐、鎬，斯豈驅略迫脅之所致哉？乃風化動其情而仁義感其衷，歡心內發使之然也。以此而推，西南將萬里無外，權、備將與誰守死乎？」
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Jiǎwǔ [220 Sep 5], the army stopped at Qiáo, greatly feasted the Six Armies  and Qiáo’s elders and Hundred Surnames to the city’s east. <a href="#annotation-16" id="source-16">[16]</a> Eighth Moon [220 Sep 15 – Oct 14], Shíyì county reported fènghuáng gathering.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
甲午，軍次於譙，大饗六軍及譙父老百姓於邑東。〔一〕八月，石邑縣言鳳皇集。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-16" id="annotation-16">[16]</a> Wèi shū states: Set dancers and musicians in hundreds of performances. Order said: “The Former Kings all delighted their places of birth, Ritual is to never forget one’s roots. Qiáo is a country of hegemons and kings, where True Men come from. Thus exempt Qiáo taxes for two years.” The Three-Elder  and officials and civilians sent up wishes for long life, from dawn to dusk and then finishing. Bǐngshēn [220 Sep 7], personally sacrificed at Qiáo’s tombs.

Sūn Shèng states: In the past the Former Kings used filial piety to govern Heaven’s Under, inside restraining natural instincts, outside extending to the Four Seas, to the surviving thorough in their respect, to the departed utmost in their mourning, pondering and remembering in the mourning rooms,  entrusting government to the senior ministers, and therefore it is said: “The Three Years of Mourning applies from Heaven’s Son to the common people.”  That being so, therefore the relationships of the three will be genuine,  the affection of servants and subjects sincere, the transformation of harmony and prosperity expand, the ways of managing the state firm, how the sagely man is able to connect to Heaven and Earth, thicken human relationships, spread utmost teachings, esteem social customs. This is a standard that for ten thousand generations did not change, a system that the Hundred Kings  submitted to and embraced. Therefore in mourning rituals of white cap, the Kuài people wrote the ridicule of “if only seeing,”  Zǎi Yú shortened the mourning period and Zhòngní sighed that it was not benevolent,  Zǐtuí forgot his grief and the noble man believed it delighting in disaster,  the Marquess of Lǔ changed clothes and the Chūnqiū knew he would not last to the end.  How were these not the decline of the sincere heart of utmost pain, the disappointment of the great principles of mourning dirges? Therefore even at the end of the three finalities or at the destitution of the seven powers,  yet there never was an abandonment of mourning clothes between ten days and a moon, or a releasing of coarse cane on the day of weeping. Reaching to Hàn Wén,  there was a change from the ancient systems, generations of human principles abandoned in one morning, mourning clothes seized away by the Utmost Honored,  the Four Seas dispersed the restrictions of silence,  righteous feelings lost by the various lords, great cultivation fallen from the lord’s kin. Although the intention was to reduce and economize, the thoughts on weaving threads,  as for cultivating virtue and bequeathing reputation, honoring influence and transforming customs, assuredly the morality was less than in past years, customs degenerated over a hundred generations. Moreover King Wǔ conveyed tablet and Mǔyè did not have battle lines,  Jìn Xiāng wore black mourning hemp and three commanders became captives.  In responding to duties and accomplishing achievements, mourning clothes have what harm? The King of Wèi both imitated Hàn’s systems and discarded the Great Rituals, during the heaviest of mourning yet set feasting music, at the beginning of the succession yet discarded the foundations of the ruler’s influence, and reaching to the acceptance of the abdication, he prominently accepted the two daughters, forgetting his utmost sorrow to falsely imitate the ancient sages.  Heaven’s heart was lost,  so how could he last to the end? Therefore one can know that the King’s life would not be long, and divine that the period of [his state’s] reign would be short.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書曰：設伎樂百戲，令曰：「先王皆樂其所生，禮不忘其本。譙，霸王之邦，真人本出，其復譙租稅二年。」三老吏民上壽，日夕而罷。丙申，親祠譙陵。孫盛曰：昔者先王之以孝治天下也，內節天性，外施四海，存盡其敬，亡極其哀，思慕諒闇，寄政冢宰，故曰「三年之喪，自天子達於庶人」；夫然，故在三之義惇，臣子之恩篤，雍熙之化隆，經國之道固，聖人之所以通天地，厚人倫，顯至教，敦風俗，斯萬世不易之典，百王服膺之制也。是故喪禮素冠，鄶人著庶見之譏，宰予降期，仲尼發不仁之歎，子頹忘戚，君子以為樂禍，魯侯易服，春秋知其不終，豈不以墜至痛之誠心，喪哀樂之大節者哉？故雖三季之末，七雄之弊，猶未有廢縗斬於旬朔之間，釋麻杖於反哭之日者也。逮於漢文，變易古制，人道之紀，一旦而廢，縗素奪於至尊，四海散其遏密，義感闕於群后，大化墜於君親；雖心存貶約，慮在經綸，至於樹德垂聲，崇化變俗，固以道薄於當年，風頹於百代矣。且武王載主而牧野不陳，晉襄墨縗而三帥為俘，應務濟功，服其焉害？魏王既追漢制，替其大禮，處莫重之哀而設饗宴之樂，居貽厥之始而墜王化之基，及至受禪，顯納二女，忘其至恤以誣先聖之典，天心喪矣，將何以終！是以知王齡之不遐，卜世之期促也。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Winter, Tenth Moon, Guǐmǎo [220 Nov 13], Order said: “The various officers go on campaign, of the soldiers that died some are not yet collected, I extremely mourn this. Thus announce to the prefectures and states to provide caskets and cases for their burials, <a href="#annotation-17" id="source-17">[17]</a> send them to their homes, government offices set sacrifices for them. <a href="#annotation-18" id="source-18">[18]</a> Bǐngwǔ [220 Nov 19], traveled and reached Qǔlí.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
冬十（一）月癸卯，令曰：「諸將征伐，士卒死亡者或未收斂，吾甚哀之；其告郡國給槥櫝殯斂，〔一〕送致其家，官為設祭。」〔二〕丙午，行至曲蠡。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-17" id="annotation-17">[17]</a> Huì (“casket”) pronounced Wèi.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕槥音衛。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-18" id="annotation-18">[18]</a> Hàn shū: Gāozǔ’s Eighth Moon Order states: “For the soldiers in the army that died, make caskets.”

Yīng Shào states: “Caskets are small coffins, now called as cases.” 

Yīng Qú’s Bǎi Yī Shī states: “Casket carriages on the road, campaign soldiers cannot rest.” 

Lù Jī’s Dà Mù Fù states: “Seeing narrow wood and feeling despondent, observing immense cases and remembering caskets.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　漢書高祖八月令曰：「士卒從軍死，為槥。」應劭曰：「槥，小棺也，今謂之櫝。」應璩百一詩曰：「槥車在道路，征夫不得休。」陸機大墓賦曰：「觀細木而悶遲，睹洪櫝而念槥。」
:::
:::
:::

## The Abdication {.unnumbered}

::: {.columns}
::: {.column width="70%"}
The Hàn Emperor, because the expectations of the masses were on Wèi, thus summoned the various Excellencies and Ministers and servicemen, <a href="#annotation-19" id="source-19">[19]</a> announced and sacrificed at Gāo Temple.  Sent concurrent Censorate Grandee Zhāng Yīn  Holding Stave to present the Ruler’s Seal and Ribbon to abdicate the throne, the conferment said: “Oh you the King of Wèi:  In the past the Emperor Yáo abdicated the throne to Yú Shùn, and Shùn also passed the Mandate to Yǔ.  Heaven’s Mandate is not constant, and only goes to those with virtue. Hàn’s Way has fallen and declined, its generations losing their order, declining to reach Our person, great chaos and growing confusion, crowds of vicious unrestrained in rebellion, the cosmos overturned. Relying on King Wǔ’s [Cáo Cāo’s] divine martial power, rescuing the Four Quarters from the growing disasters, purifying the regions of Xià, to protect and pacify our Ancestral Temples. How was it only my one person who obtained peace? It enabled the Nine Regions  to truly receive this bestowment. Now you the King respectfully continue the former threads, radiate the virtues, expand the great enterprise of the civil and martial, shining your late father’s vast exploits. The August Spirits give down the signs, men and deities report the omens, oh pondering shining qualities,  multitudes informing Our mandate,  all say your capability accords with Yú Shùn; employing our Táng standards,  I respectfully abdicate to you the throne. Alas! ‘Heaven’s calendar calculations are upon your person, justly maintain the correct, [or else] Heaven’s blessings forever end.’  You must respectfully follow the great rituals, provide for all states, to solemnly carry on Heaven’s Mandate.” <a href="#annotation-20" id="source-20">[20]</a> Thus made a platform at Fányáng.
Gēngwǔ [220 Dec 10], the King ascended the platform and accepted the throne, the Hundred Offices in accompanying seats.  The matter finished, descended the platform, oversaw the burnings to complete the ritual and returned. Changed Yánkāng to Huángchū. Great Amnesty.<a href="#annotation-21" id="source-21">[21]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
漢帝以眾望在魏，乃召群公卿士，〔一〕告祠高廟。使兼御史大夫張音持節奉璽綬禪位，冊曰：「咨爾魏王：昔者帝堯禪位於虞舜，舜亦以命禹，天命不于常，惟歸有德。漢道陵遲，世失其序，降及朕躬，大亂茲昏，群兇肆逆，宇內顛覆。賴武王神武，拯茲難於四方，惟清區夏，以保綏我宗廟，豈予一人獲乂，俾九服實受其賜。今王欽承前緒，光于乃德，恢文武之大業，昭爾考之弘烈。皇靈降瑞，人神告徵，誕惟亮采，師錫朕命，僉曰爾度克協于虞舜，用率我唐典，敬遜爾位。於戲！天之曆數在爾躬，允執其中，天祿永終；君其祗順大禮，饗茲萬國，以肅承天命。」〔二〕乃為壇於繁陽。庚午，王升壇即阼，百官陪位。事訖，降壇，視燎成禮而反。改延康為黃初，大赦。〔三〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-19" id="annotation-19">[19]</a> Yuán Hóng’s Hàn jì records the Hàn Emperor’s Edict saying: “We have been on the throne for thirty and two years, encountered Heaven’s Under shaken and overturned, by fortune relied on the spirits of my ancestors, was endangered but yet survived. However looking up to gaze on Heaven’s signs, looking down to examine the people’s hearts, the calculations of flame’s essence is already finished, the transitioning fate is on the Cáo clan. Therefore the previous King had cultivated divine martial accomplishments, the present King also radiates brilliant virtue to answer this phase, and so the calendar calculations are shining clear, and truly can be known. ‘In the enactment of the great way, Heaven’s Under is public, select the worthy and give to the able.’  Therefore Táng Yáo did not selfishly give to his own son, and so his fame spread without bound. We admire and desire this, now thus follow the legacy of Yáo’s standards, and abdicate the throne to the King of Wèi.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　袁宏漢紀載漢帝詔曰：「朕在位三十有二載，遭天下蕩覆，幸賴祖宗之靈，危而復存。然仰瞻天文，俯察民心，炎精之數既終，行運在乎曹氏。是以前王既樹神武之績，今王又光曜明德以應其期，是曆數昭明，信可知矣。夫大道之行，天下為公，選賢與能，故唐堯不私於厥子，而名播於無窮。朕羨而慕焉，今其追踵堯典，禪位于魏王。」
:::
:::
:::

::: {.callout-note appearance="minimal"}

::: {.columns}
::: {.column width="70%"}
<a href="#source-20" id="annotation-20">[20]</a> Xiàn-dì zhuàn records the abdication succession’s many matters stating:
Left Central Cadet General Lǐ Fú  memorialized the King of Wèi stating: “In the past when the Former King first established Wèi state, those beyond the borders heard of it but did not investigate the details, and all believed he was appointed a King. Wǔdū’s Lǐ Shù and Jiāng Hé  were traveling and lodging in Hànzhōng, and said to Your Servant: ‘It certainly is as Duke (gōng) of Wèi, not yet as a King. The one to settle Heaven’s Under is “Wèi Gōng Zǐ Huán.”  What the deities have mandated will accord with signs and omens, to answer the positions of Heaven and Man.’ Your Servant reported [Jiāng] Hé’s words to Defending South General Zhāng Lǔ.  [Zhāng] Lǔ also asked [Jiāng] Hé: ‘What book produced this?’ [Jiāng] Hé said: ‘It is Kǒng-zǐ Yùbăn.  The calendar calculations of Heaven’s Son even for a hundred generations can be known.’ From then after over a moon, there was a deserter who came, wrote down the conferment text, and indeed it was as [Jiāng] Hé had said. [Jiāng] Hé excels in Inner Studies,  reputation known west of the passes. Though [Zhāng] Lǔ had a heart devoted to the state, he was immersed in heterodox teachings and changes, and was not fully awakened by [Jiāng] Hé’s words. Later he secretly with Your Servant discussed a plan to send hostages [to surrender], the state’s people did not agree, some wished to go west [to join Liú Bèi]. [Zhāng] Lǔ immediately was furious and said: “Better to be the Duke of Wèi’s slave than Liú Bèi’s most honored guest!” His words came from sorrow and pain, truly instinctual. [Jiāng] Hé first welcomed the King’s brigades, and in past years fell ill and died at Yè. From since Your Servant was at Court, every time I discussed this intention with my intimates, the time was not yet appropriate, and I did not dare publicly speak of it. In this first year of Your Highness succeeding the throne, the auspicious portents are numerous, every day and every moon arriving; there is a mandate from Heaven, shining clear and obviously seen. Thus your sagely virtue penetrates and pervades, the signs in advance are clear, truly Qián and Kūn extend congratulations, all states give pledge. Your Servant every time in offering congratulations wished to speak of [Jiāng] Hé’s verification, but in serving lord with thorough ritual, people believe it flattery. Moreover Your Servant’s reputation and conduct are base and lowly, my days since entering Court are few, speaking of it would be an incredible crime, and I restrained myself and nothing more. Now your vast grace covers the four borders, your spiritual mercy reaches Heaven and Earth, Within the Seas in close harmony, foreign quarters come to submit, foretelling and fulfillments both accumulate, to raise up the glorious mandate, beginning to end completely good. Your Servant cannot contain my happiness, and solemnly present memorial to inform.”
The King’s Order said: “Show this to the exterior. How can a man of meager virtue [like myself] have attracted this? I do not dare presume. This assuredly is the Former King’s utmost virtue communicating with the divine intelligence, assuredly not the work of man.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　獻帝傳載禪代眾事曰：左中郎將李伏表魏王曰：「昔先王初建魏國，在境外者聞之未審，皆以為拜王。武都李庶、姜合羈旅漢中，謂臣曰：『必為魏公，未便王也。定天下者，魏公子桓，神之所命，當合符讖，以應天人之位。』臣以合辭語鎮南將軍張魯，魯亦問合知書所出？合曰：『孔子玉版也。天子曆數，雖百世可知。』是後月餘，有亡人來，寫得冊文，卒如合辭。合長于內學，關右知名。魯雖有懷國之心，沈溺異道變化，不果寤合之言。後密與臣議策質，國人不協，或欲西通，魯即怒曰：『寧為魏公奴，不為劉備上客也。』言發惻痛，誠有由然。合先迎王師，往歲病亡於鄴。自臣在朝，每為所親宣說此意，時未有宜，弗敢顯言。殿下即位初年，禎祥眾瑞，日月而至，有命自天，昭然著見。然聖德洞達，符表豫明，實乾坤挺慶，萬國作孚。臣每慶賀，欲言合驗；事君盡禮，人以為諂。況臣名行穢賤，入朝日淺，言為罪尤，自抑而已。今洪澤被四表，靈恩格天地，海內翕習，殊方歸服，兆應並集，以揚休命，始終允臧。臣不勝喜舞，謹具表通。」王令曰：「以示外。薄德之人，何能致此，未敢當也；斯誠先王至德通於神明，固非人力也。」
:::
:::

::: {.columns}
::: {.column width="70%"}
The King of Wèi’s Attendant Centrals Liú Yì, Xīn Pí, Liú Yè, Secretariat Writers Director Huán Jiē, Secretariat Writers Chén Jiǎo, Chén Qún, Dispensing Affairs Yellow Gate Attendant Cadets Wáng Bì, Dǒng Yù,  and others said: “Your Servants in prostration read Left Central Cadet General Lǐ Fú’s sent up matter, investigated the reports of the Tú and Wěi,  and in their effectiveness in answering the divine intelligence, examining to ancient times, there has never been any incorrect. Therefore when Yáo said the calendar calculations were on his person, Xuánjī illuminated Heaven’s way;  Zhōu Wǔ had not yet battled and yet the red crow carried the message;  Hàn [Gāo]Zǔ was not yet prominent and yet the divine mother reported the signs;  Xiào-Xuān was lowly and humble but words appeared on tree leaves;  Guāng-Wǔ was in plain clothes and his name was already engraved in the Chén.  These were what Heaven mandated in order to prove the sagely, not what the sound of speech or the smell of fragrance can obtain and understand, it only hangs signs to show to people and trifling objects to express intentions. From since the waning of Hàn’s virtue, gradually it contaminated several generations, to the end of Huán and Líng, the Imperial standards were not established, and to now from the great chaos it has been over twenty years. Heaven does not obliterate, but creates enlightened sages to resolve these disasters, and therefore signs and prophecies are in advance written, to make clear their utmost virtue. Your Highness’s succession to the throne has not yet been a year, and yet the spiritual signs change above, crowds of omens answer below. The uninhibited people of the Four Quarters submit their hearts toward righteousness, only fearing to be too late. Even of what is recorded by the ancient records, there are none that compare to the flourishing of the present. Of Your Servants far and near, none are not ducks in the grasses.” 

The King’s Order said: “The stripes of plowing oxen resemble tigers. The sprouts of weeds resemble grains. Situations have those that resemble the true but which are actually false. The present day is only that. Seeing these reported matters, they actually emphasize my lack of virtue.” Therefore the Secretariat Writers Deputy Director announced report to the bureaucracy offices, for all to hear of and know.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
魏王侍中劉廙、辛毗、劉曄、尚書令桓階、尚書陳矯、陳群、給事黃門侍郎王毖、董遇等言：「臣伏讀左中郎將李伏上事，考圖緯之言，以效神明之應，稽之古代，未有不然者也。故堯稱曆數在躬，璇璣以明天道；周武未戰而赤烏銜書；漢祖未兆而神母告符；孝宣仄微，字成木葉；光武布衣，名已勒讖。是天之所命以著聖哲，非有言語之聲，芬芳之臭，可得而知也，徒縣象以示人，微物以效意耳。自漢德之衰，漸染數世，桓、靈之末，皇極不建，暨於大亂，二十餘年。天之不泯，誕生明聖，以濟其難，是以符讖先著，以彰至德。殿下踐阼未期，而靈象變於上，群瑞應於下，四方不羈之民，歸心向義，唯懼在後，雖典籍所傳，未若今之盛也。臣妾遠近，莫不鳧藻。」王令曰：「犁牛之駮似虎，莠之幼似禾，事有似是而非者，今日是已。睹斯言事，良重吾不德。」於是尚書僕射宣告官寮，咸使聞知。
:::
:::

::: {.columns}
::: {.column width="70%"}
Xīnhài [Nov 21], Grand Scribe Deputy Xǔ Zhī  catalogued the observed prophecies of Wèi’s succession to Hàn for the King of Wèi stating:
Yì Zhuàn  states: “The sagely man receives the Mandate and rules as King, Yellow Dragon on a Wù or Jǐ day is seen.” Seventh Moon Fourth Day Wùyín [220 Aug 20], Yellow Dragon sighted. This is the most obvious and clear of the corresponding omens of Emperors and Kings receiving the Mandate. It also states: “First Six: Treading Frost” is “Yīn begins to condense.”  Also there was an accumulation of vermin in a large hole in the Palace of Heaven’s Son, its calamity verified. Now the locust sightings are its answer. It also states: “The sagely man by virtue is close with Heaven’s Under, benevolence and grace applied everywhere, its answer is the qílín  in a Wù or Jǐ day arriving, its answer is the sagely man receiving the Mandate.” It also states: “The sagely man pure and clean, conduct correct and upright, the worthy man’s fortunes arrive, the people follow the mandate, its answer is the qílín coming.” 
Chūnqiū Hàn Hán Zī states: “Hàn by Wèi, Wèi by portents.” 
Chūnqiū Yùbǎn Chèn states: “The successor of the Red is Wèi Gōngzǐ.” 
Chūnqiū Zuǒzhùqī states: “Hàn by Promising [xǔ] Prosperity [chāng] loses Heaven’s Under.”  Former Báimǎ Magistrate Lǐ Yún’s  sent up matter said: “Xǔ prosperous aura seen at ‘on the road high.’ The ‘on the road high’ will prosper at Xǔ.”  ‘On the road high’ is Wèi. The symbol Wèi is the two-watchtower gate. What is on a street and high is Wèi. Wèi will succeed Hàn.  Now Wèi’s foundations prospered at Xǔ, Hàn’s portents are severed at Xǔ,  thus now the verifications are seen, like Lǐ Yún’s words, Xǔ and Chāng answer one another. Zuǒzhùqī also states: “Hàn by ignorant descendant perishes.” Those explaining it believe the ‘ignorant descendant’ is Hàn’s twenty-fourth Emperor, young and ignorant, foolish and confused, by feebleness perishes.  Others believe in variant writings to make ignorant one’s descendant is to lose Heaven’s Under, believing the Hàn Emperor was not the proper successor, as a youth was called Marquess Dǒng, his name not correct, making ignorant and chaotic, leading to confusion, and his descendants by feebleness perish. 
Xiàojīng Zhōnghuáng Chèn  states: “Sun rides east, extinguishing fire’s light. Not across one, sagely intelligent brilliance. Beyond four hundred, change surname and rule, Heaven’s Under submits to achievement, reaching Grand Peace, occupying eight shells, sharing ritual and music, correcting myriad peoples, commendable music families harmonized and mixed.” This is the King of Wèi’s surname and forbidden name written in chart prophecies. 
Yì Yùnqī Chèn  states: “Speech resides east, west has noon, two suns together shine, sun resides below. That which was ruler instead becomes supporter. Five eight forty, yellow aura received, True Man appears.” Speech and noon form the Xǔ character. Two suns form the Chāng [“prosper”] character.  Hàn will by Xǔ perish, Wèi will by Xǔ prosper. Now the phase of conjunction is at Xǔ [city], this is its great verification. Yì Yùnqī also states: “Ghost at mountain, grain and woman joined, rules Heaven’s Under.” 
Your Servant has heard that Emperors and Kings are the essence of the Five Transitions, the signs of changing surnames, the meetings of succession and rising, take seven hundred twenty years as one course. Those with virtue exceed it, reaching to eight hundred, those without virtue do not reach it, arriving at four hundred years. Therefore the Zhōu House was eight hundred sixty-seven years, the Xià House four hundred and several tens of years, Hàn enacted the Xià Standard [calendar], reaching to the present is four hundred twenty-six years. Also when Gāozǔ received the Mandate, although the numbering began at Yǐwèi,  however the omen portents began at the capture of the Lín. From the capture of the Lín onward has been over seven hundred years,  Heaven’s calendar calculations will be exhausted and completed. The risings of Emperors and Kings are not constantly one surname. Within Tàiwēi [asterism], Huángdìzuò [“Yellow Emperor’s Seat” star] was constantly bright, but Chìdìzuò [“Red Emperor’s Seat” star] was constantly unseen,  meaning the Yellow House would rise and the Red House decline, the omen of the inauspicious and perishing. From then onward by over forty years, also Yínghuò [Mars] lost color and was not bright for ten and some years. Jiàn’ān Tenth Year [205], a comet first passed through Zǐwēi.  Twenty-Third Year [218], it further swept through Tàiwēi.  From since a New Heaven’s Son aura was seen in the southeast, in twenty-three years,  a white rainbow crossed the sun,  the moon eclipsed Yínghuò,  in recent years on a Jǐhài, Rénzǐ, Bǐngwǔ the sun was eclipsed;  all are signs of water extinguishing fire. Your Highness succeeded the throne, first ascending the steps, virtue matching Heaven and Earth, conduct according with the divine intelligence, favor and grace overflowing, widely covering the four borders, reaching to the highest and lowest. Therefore yellow dragons were repeatedly seen, fènghuáng frequently soared, qílín all arrived, white tigers effected benevolence, beginning to end offering sightings in the suburb outskirts.  Sweet dew and sweet springs,  fantastic beasts and divine objects, multitudes of signs together appear. These all are the correspondences to Emperors and Kings receiving the Mandate and the changing of surnames. In the past Huáng-dì received the Mandate, Fēnghòu received the Hé tú;  Shùn and Yǔ possessed Heaven’s Under, Fènghuáng soared and the Luò produced documents;  Tāng became King, the white bird was the correspondence;  Wén-wáng became Xībó, the red bird carried the cinnabar text;  Wǔ-wáng attacked Yīn, the white fish jumped into the boat;  Gāozǔ first rose, the white snake was the portent.  Tremendous signs and omen verifications all are by the rise of sagely men. Observing Hàn’s beginning to end great calamities and the present time’s corresponding omens, investigating the allotted fates of the Tú and Chèn, judging what the Hé and Luò have discerned, nothing compares to the present Great Wèi’s greatest magnificence. The one who obtains the Suìxīng [Jupiter],  their way begins to rise. In the past when Wǔ-wáng attacked Yīn, Suì was at Chúnhuǒ, which is Zhōu’s Field Allocation.  Gāozǔ entered Qín, the Five Planets assembled at Dōngjīng, which is in Hàn’s Field Allocation.  Now presently Suìxīng is at Dàliáng, which is Wèi’s Field Allocation.  And Heaven’s omen verifications all gather together and come, the Four Quarters submit and attach, carrying their children on their back and arriving, the millions of people happy and supportive, all joyous and celebrating. Chūnqiū Dàzhuàn states: “Why did Zhōu-gōng not go to Lǔ? Probably he believed that though there was a lord to continue the succession and maintain culture, it did not hinder a sage in accepting the Mandate and ruling.”  Zhōu-gōng returned governance, the Shī-zǐ believes that Kǒng-zǐ criticized this, believing Zhōu-gōng was not a sage as he did not serve the millions of people.  Jīng Fáng’s Yì Zhuàn states: “For those who are King, if evil remove them, if feeble replace them. In changing surnames and transferring dynasties, Heaven’s Mandate answers constantly, men plan or ghosts plan, the Hundred Surnames go with the capable.”  In prostration considering that Your Highness embodies the flourishing enlightenment of Yáo and Shùn, receives a seven hundred abdication of dynasties, meets the allotted fates of Tāng and Wǔ, encounters the shifting and receiving of Heaven’s Mandate, what the Hé and Luò reveal, what the charts and prophecies convey, are clear and obvious, what the scholars of Heaven’s Under all see. Your Servant’s duties are in the Scribal Office, examining signs and investigating portents, the charts and prophecies verifications seen, the phase of the conjunction, I solemnly send up report.”

The King’s Order said: “In the past, Zhōu Wén possessed two thirds of Heaven’s Under, by this served Yīn, and Zhòngní sighed in admiration of his utmost virtue;  Gōng Dàn assumed the responsibilities of Heaven’s Son, judged the cases of Heaven’s Under, in the end then ‘returned to the son the glorious power,’ the Shū praised his person.  Although my virtue does not reach those two sages, dare I forget the meanings of high mountains and scenic journeys?  As for the deeds of Táng Yáo, Shùn, Yǔ, they all by sagely character and abundant virtue accomplished them, and therefore were able to above harmonize with spirits and deities, below pacify the myriad surnames, leaving legacies to the present day. Now my virtue is utmostly meager, my person utmostly low, encountered a coincidence, by chance succeeded to the Former King’s [Cáo Cāo’s] unfinished enterprise, my grace does not yet cover the Four Seas, my favor not yet reached Heaven’s Under, and though I pour out the granaries and empty the treasuries to rouse Wèi state’s Hundred Surnames, yet those who are cold are not yet all warmed, those who are hungry are not yet all fed. Morning to night apprehensive, not daring to have leisure, I only wish to preserve my hair and teeth, long maintain the present situation, to go into the ground, to preserve Wèi state, going down to meet the Former King, to fulfill the responsibilities of my burden. My expectations are limited and ambitions narrow, maintaining these and nothing more. Although repeatedly immersed in auspicious omens, I meet them with violent fear, my expressions without control. Words like those of [Xǔ] Zhī, how can I listen to them? My heart trembles and hands shake, when writing cannot form words, when speaking cannot express heart. During leisure I composed a poem that states:
> Death and chaos lasting beyond ages
> White bones crisscrossing myriad leagues
> Sorrowful, sorrowful people below with none to rely on
> I will assist the times and set order
> ‘Return to the son the glorious power’ and retire from service
I only wish to maintain these words to my own end, to death without false words. Appropriately announce and show to the far and near, to make clear my red heart.” 

Thereupon Attendant Centrals Xīn Pí and Liú Yè, Cavalier Regular Attendants Fù Xùn and Wèi Zhēn, Secretariat Writers Director Huán Jiē, Secretariat Writers Chén Jiǎo, Chén Qún, Dispensing Affairs Central Academic Scholar Cavalry Commandant Sū Lín, Dǒng Bā,  and others memorialized stating: “In prostration observing Grand Scribe Deputy Xǔ Zhī’s sent up signs of Wèi state receiving the mandate: the Order letter is earnest and sincere, genuinely insisting on modestly declining; even of Shùn, Yǔ, Tāng, Wén, in righteousness none would surpass it. However, that the ancient former worthy kings received Heaven’s Mandate without declining, was truly that they urgently complied with the intentions of August Heaven, served the expectations of the millions of people, and could not but do so. Moreover, the Yì states: ‘Observe Heaven’s patterns to investigate time’s changes, observe Human patterns to influence and complete Heaven’s Under.’  It also states: ‘Heaven bequeaths signs, showing good and bad fortunes, the sages modeled after it. The Hé produced charts, the Luò produced documents, the sages imitated it.’  This means that Heaven’s patterns because of men change. As for the writings of the Hé and Luò, they were written in the Hóngfàn,  and so Yīn and Zhōu imitated and employed them. These reports truly are the enlightened signs of Emperors and Kings, the great essentials of Heaven’s Way. Therefore, those that by virtue answer fate will successively rise to the front, those that lose the way and whose calculations are exhausted will repeatedly fall to the rear. The Zhuàn ridicules Cháng Hóng’s desire to raise what Heaven had destroyed,  and speaks of Cài Mò’s explanation of ‘Léi riding Qián,’  making clear that the survival or destruction of the Divine Vessels is not what the strength of Man is able to establish. Now the Hàn House has declined and been replaced, the Emperor’s network degenerated and fallen, the Edicts of Heaven’s Son are extinguished and not listened to, the August Heavens about to abandon the old and mandate the new, the Hundred Surnames have left Hàn and joined Wèi, manifest and obvious, and so can be known. The Former King dispelled the chaos and pacified the world, about to establish a vast foundation; as for Your Highness, by utmost virtue you meet the fate of the calendar calculations, from since your succession to the throne, Heaven’s verifications and human affairs are clearly greatly provided, the divinities and spirits, charts and registers, all continuing from past antiquity, the glorious portents and auspicious omens surpass over previous eras. Thus the prophecies of your surname and forbidden name that [Xǔ] Zhī selected from Zhōnghuáng and Yùnqī, these writings then were written in previous ages, with Hàn coexisting. By this speaking of it, Heaven’s Mandate has already long been settled, not what Your Highness is able to obtain but then refuse. The intentions of the divine intelligence wait and expect sacrificial offerings, the millions of people reverently watch all concentrated on auspicious wishes. May Your Highness read the obvious writings of the charts and registers, urgently value the just righteousness of Heaven’s Under, at once announce Order to the interior and exterior, widely inform the provinces and prefectures, to have them know that the signs of the mandate are obvious and clear, but Your Highness intends to modestly decline.”

The Order said: “Sending down to the Four Quarters to explain my sincere heart, that is correct. As for reading the remaining statements, how was that what I said? How can it be endured? You sirs in your directions and opinions are not as careful as my own self-examination. This empty talk and mistaken praise are what my lowly self cannot bear. Moreover it is heard that in the recent eastern campaign, weaving through the prefectures and counties, passing through the Garrison Farms, the faces of the Hundred Surnames had expressions of hunger, of the clothes some are short and worn and incomplete, the fault is all on me. Therefore above I am humiliated by the multitudes of omens, below ashamed for the servicemen and people. By this speaking of it, my virtue is not worthy to be a regional King, so why speak of Emperor? It is appropriate to stop this discussion, to not increase my lack of virtue, so that after my passing, I will not be shameful to the noble men of posterity.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
辛亥，太史丞許芝條魏代漢見讖緯于魏王曰：「易傳曰：『聖人受命而王，黃龍以戊己日見。』七月四日戊寅，黃龍見，此帝王受命之符瑞最著明者也。又曰：『初六，履霜，陰始凝也。』又有積蟲大穴天子之宮，厥咎然，今蝗蟲見，應之也。又曰：『聖人以德親比天下，仁恩洽普，厥應麒麟以戊己日至，厥應聖人受命。』又曰：『聖人清淨行中正，賢人福至民從命，厥應麒麟來。』春秋漢含孳曰：『漢以魏，魏以徵。』春秋玉版讖曰：『代赤者魏公子。』春秋佐助期曰：『漢以許昌失天下。』故白馬令李雲上事曰：『許昌氣見于當塗高，當塗高者當昌於許。』當塗高者，魏也；象魏者，兩觀闕是也；當道而高大者魏。魏當代漢。今魏基昌于許，漢徵絕于許，乃今效見，如李雲之言，許昌相應也。佐助期又曰：『漢以蒙孫亡。』說者以蒙孫漢二十四帝，童蒙愚昏，以弱亡。或以雜文為蒙其孫當失天下，以為漢帝非正嗣，少時為董侯，名不正，蒙亂之荒惑，其子孫以弱亡。孝經中黃讖曰：『日載東，絕火光。不橫一，聖聰明。四百之外，易姓而王。天下歸功，致太平，居八甲；共禮樂，正萬民，嘉樂家和雜。』此魏王之姓諱，著見圖讖。易運期讖曰：『言居東，西有午，兩日並光日居下。其為主，反為輔。五八四十，黃氣受，真人出。』言午，許字。兩日，昌字。漢當以許亡，魏當以許昌。今際會之期在許，是其大效也。易運期又曰：『鬼在山，禾女連，王天下。』臣聞帝王者，五行之精；易姓之符，代興之會，以七百二十年為一軌。有德者過之，至于八百，無德者不及，至四百載。是以周家八百六十七年，夏家四百數十年，漢行夏正，迄今四百二十六歲。又高祖受命，數雖起乙未，然其兆徵始于獲麟。獲麟以來七百餘年，天之曆數將以盡終。帝王之興，不常一姓。太微中，黃帝坐常明，而赤帝坐常不見，以為黃家興而赤家衰，凶亡之漸。自是以來四十餘年，又熒惑失色不明十有餘年。建安十年，彗星先除紫微，二十三年，復掃太微。新天子氣見東南以來，二十三年，白虹貫日，月蝕熒惑，比年己亥、壬子、丙午日蝕，皆水滅火之象也。殿下即位，初踐阼，德配天地，行合神明，恩澤盈溢，廣被四表，格于上下。是以黃龍數見，鳳皇仍翔，麒麟皆臻，白虎效仁，前後獻見于郊甸；甘露醴泉，奇獸神物，眾瑞並出。斯皆帝王受命易姓之符也。昔黃帝受命，風后受河圖；舜、禹有天下，鳳皇翔，洛出書；湯之王，白鳥為符；文王為西伯，赤鳥銜丹書；武王伐殷，白魚升舟；高祖始起，白蛇為徵。巨跡瑞應，皆為聖人興。觀漢前後之大災，今茲之符瑞，察圖讖之期運，揆河洛之所甄，未若今大魏之最美也。夫得歲星者，道始興。昔武王伐殷，歲在鶉火，有周之分野也。高祖入秦，五星聚東井，有漢之分野也。今茲歲星在大梁，有魏之分野也。而天之瑞應，並集來臻，四方歸附，襁負而至，兆民欣戴，咸樂嘉慶。春秋大傳曰：『周公何以不之魯？蓋以為雖有繼體守文之君，不害聖人受命而王。』周公反政，尸子以為孔子非之，以為周公不聖，不為兆民也。京房作易傳曰：『凡為王者，惡者去之，弱者奪之。易姓改代，天命應常，人謀鬼謀，百姓與能。』伏惟殿下體堯舜之盛明，膺七百之禪代，當湯武之期運，值天命之移受，河洛所表，圖讖所載，昭然明白，天下學士所共見也。臣職在史官，考符察徵，圖讖效見，際會之期，謹以上聞。」王令曰：「昔周文三分天下有其二，以服事殷，仲尼歎其至德；公旦履天子之籍，聽天下之斷，終然復子明辟，書美其人。吾雖德不及二聖，敢忘高山景行之義哉？若夫唐堯、舜、禹之蹟，皆以聖質茂德處之，故能上和靈祇，下寧萬姓，流稱今日。今吾德至薄也，人至鄙也，遭遇際會，幸承先王餘業，恩未被四海，澤未及天下，雖傾倉竭府以振魏國百姓，猶寒者未盡煖，飢者未盡飽。夙夜憂懼，弗敢遑寧，庶欲保全髮齒，長守今日，以沒於地，以全魏國，下見先王，以塞負荷之責。望狹志局，守此而已；雖屢蒙祥瑞，當之戰惶，五色無主。若芝之言，豈所聞乎？心慄手悼，書不成字，辭不宣心。吾閒作詩曰：『喪亂悠悠過紀，白骨縱橫萬里，哀哀下民靡恃，吾將佐時整理，復子明辟致仕。』庶欲守此辭以自終，卒不虛言也。宜宣示遠近，使昭赤心。」於是侍中辛毗、劉曄、散騎常侍傅巽、衛臻、尚書令桓階、尚書陳矯、陳群、給事中博士騎都尉蘇林、董巴等奏曰：「伏見太史丞許芝上魏國受命之符；令書懇切，允執謙讓，雖舜、禹、湯、文，義無以過。然古先哲王所以受天命而不辭者，誠急遵皇天之意，副兆民之望，弗得已也。且易曰：『觀乎天文以察時變，觀乎人文以化成天下。』又曰：『天垂象，見吉凶，聖人則之；河出圖，洛出書，聖人效之。』以為天文因人而變，至于河洛之書，著于洪範，則殷、周效而用之矣。斯言，誠帝王之明符，天道之大要也。是以由德應錄者代興于前，失道數盡者迭廢于後，傳譏萇弘欲支天之所壞，而說蔡墨『雷乘乾』之說，明神器之存亡，非人力所能建也。今漢室衰替，帝綱墮墜，天子之詔，歇滅無聞，皇天將捨舊而命新，百姓既去漢而為魏，昭然著明，是可知也。先王撥亂平世，將建洪基；至於殿下，以至德當曆數之運，即位以來，天應人事，粲然大備，神靈圖籍，兼仍往古，休徵嘉兆，跨越前代；是芝所取中黃、運期姓緯之讖，斯文乃著於前世，與漢並見。由是言之，天命久矣，非殿下所得而拒之也。神明之意，候望禋享，兆民顒顒，咸注嘉願，惟殿下覽圖籍之明文，急天下之公義，輒宣令外內，布告州郡，使知符命著明，而殿下謙虛之意。」令曰：「下四方以明孤款心，是也。至于覽餘辭，豈余所謂哉？寧所堪哉？諸卿指論，未若孤自料之審也。夫虛談謬稱，鄙薄所弗當也。且聞比來東征，經郡縣，歷屯田，百姓面有飢色，衣或短褐不完，罪皆在孤；是以上慚眾瑞，下愧士民。由斯言之，德尚未堪偏王，何言帝者也！宜止息此議，無重吾不德，使逝之後，不愧後之君子。」
:::
:::

::: {.columns}
::: {.column width="70%"}
Guǐchǒu [Nov 23], announced and informed the various offices. Commanding Army Censorate Central Deputy Sīmǎ Yì, Attendant Censors Zhèng Hún, Yáng Mì, Bào Xūn, Wǔ Zhōu  and others said: “The Order is to the left. In prostration reading Grand Scribe Deputy Xǔ Zhī’s sent up matters of the signs of the mandate, Your Servants have heard that when Yǒu Táng’s reign declined, Heaven’s Mandate was on Yú, and when the Yú clan’s reign declined, Heaven’s Mandate was on Xià.  That being the case the vitality of Heaven and Earth, the fates of the calendar calculations, the signs of leaving and arriving, are only by where there is virtue. Therefore Kǒng-zǐ said: ‘The fèng bird does not arrive, the Hé does not produce charts, I am finished!’  Now the Hàn House has declined, from Ān, Hé, Chōng, Zhì, the state’s succession was repeatedly severed,  Huán and Líng were dissolute and licentious, fortunes left the ruling house.  This then was Heaven’s Mandate departing and arriving, ‘not [the result of] one morning or one evening,’  its origins were from long ago. Your Highness ascended the throne, utmost virtue spread and covered, reaching above and below, Heaven and Man emotionally moved and answer, signs and omens all arrive, and investigating the ancient histories, there were none as flourishing as the present day. For a great man, ‘when acting before Heaven then Heaven does not oppose him, when acting after Heaven then complies with Heaven’s timing.’  For Heaven’s timing to have already arrived and yet modestly decline, Shùn and Yǔ would not do, and therefore the living people were immersed in the kindness of rescue and relief, all sorts received the bestowal of nurturing and growth. Now the Eight Directions  reverently watch, large and small focus gaze, the August Heavens gives favor, Divinities and Humanity together plan, nine out of ten have pledged submission, the situation surpassing Zhōu Wén,  what is called excessive deference. Your Servants above and below in prostration are not at ease.”

The Order said: “What the world is lacking in is morality and righteousness, what it has in excess is negligence and presumptuousness. The nature of an ordinary man is to disparage what they lack and value what they have in excess. Therefore it was said: ‘Do not worry of lacking position, worry of reason to be appointed.’  Though I am scant in virtue, I would avoid an ordinary man’s values. Thus ‘a stone can be broken but cannot be robbed of its hardness, cinnabar can be pulverized but cannot be robbed of its red.’  Cinnabar and stone are trifling objects and yet can protect their qualities, so all the more when I am at the end of a line of servicemen, having received teachings from noble men. Moreover, Wūlíng Zhòngzǐ took benevolence as wealth,  Bǎichéng Zǐgāo took righteousness as nobility,  Bào Jiāo was emotionally moved by Zǐgòng’s words and discarded his vegetables and withered to death,  the firewood-collector ridiculed Jì Zhá for wrongly speaking;  all discarded treasures without a glance. I alone am what sort of man? In the past Zhōu Wǔ was a great sage, sent Shū Dàn to swear alliance with Jiāo Gé at Sìnèi, sent Shào-gōng to make covenant with Wēi-zǐ at Gòngtóu,  and therefore Bó Yí and Shū Qí together laughed at them saying: ‘In the past Shénnóng-shì’s possession of Heaven’s Under did not ruin others for one’s own accomplishments and did not make others lowly to make oneself high,’ believing that Zhōu’s attack on Yīn was cruelty.  My virtue is not of Zhōu Wǔ, my righteousness shameful to [Bó] Yí and [Shū] Qí. I wish to distance from losing morality by negligence and presumptuousness, establish the unstealable of cinnabar and stone, stride what Wūlíng [Zhòngzǐ] held as wealth, tread what Bǎichéng [Zǐgāo] took as nobility, grasp Bào Jiāo’s chaste cultivation, follow the firewood-collector’s pure integrity. Therefore it is said: ‘The Three Armies can be robbed of their commander; a common fellow cannot be robbed of his will.’  This will of mine, who can rob me of it?”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
癸丑，宣告群寮。督軍御史中丞司馬懿、侍御史鄭渾、羊祕、鮑勛、武周等言：「令如左。伏讀太史丞許芝上符命事，臣等聞有唐世衰，天命在虞，虞氏世衰，天命在夏；然則天地之靈，曆數之運，去就之符，惟德所在。故孔子曰：『鳳鳥不至，河不出圖，吾已矣夫！』今漢室衰，自安、和、沖、質以來，國統屢絕，桓、靈荒淫，祿去公室，此乃天命去就，非一朝一夕，其所由來久矣。殿下踐阼，至德廣被，格于上下，天人感應，符瑞並臻，考之舊史，未有若今日之盛。夫大人者，先天而天弗違，後天而奉天時，天時已至而猶謙讓者，舜、禹所不為也，故生民蒙救濟之惠，群類受育長之施。今八方顒顒，大小注望，皇天乃眷，神人同謀，十分而九以委質，義過周文，所謂過恭也。臣妾上下，伏所不安。」令曰：「世之所不足者道義也，所有餘者苟妄也；常人之性，賤所不足，貴所有餘，故曰『不患無位，患所以立』。孤雖寡德，庶自免于常人之貴。夫『石可破而不可奪堅，丹可磨而不可奪赤』。丹石微物，尚保斯質，況吾託士人之末列，曾受教于君子哉？且於陵仲子以仁為富，柏成子高以義為貴，鮑焦感子貢之言，棄其蔬而槁死，薪者譏季札失辭，皆委重而弗視。吾獨何人？昔周武，大聖也，使叔旦盟膠鬲于四內，使召公約微子於共頭，故伯夷、叔齊相與笑之曰：『昔神農氏之有天下，不以人之壞自成，不以人之卑自高。』以為周之伐殷以暴也。吾德非周武而義慚夷、齊，庶欲遠苟妄之失道，立丹石之不奪，邁於陵之所富，蹈柏成之所貴，執鮑焦之貞至，遵薪者之清節。故曰：『三軍可奪帥，匹夫不可奪志。』吾之斯志，豈可奪哉？」
:::
:::

::: {.columns}
::: {.column width="70%"}
Yǐmǎo [220 Nov 25], the conferment Edict on the King of Wèi to abdicate and transfer Heaven’s Under said: “On Yánkāng Inaugural Year Tenth Moon Yǐmǎo, the Imperial Emperor states: Oh you King of Wèi, fate transfers between Pǐ and Tài,  in accordance to virtue rises and falls. The Three Dynasties’ divination of years  is written in the Chūnqiū, and therefore that Heaven’s Mandate is not constant, Emperors and Kings not of one surname, has been so from since long ago. Hàn’s way is fallen and declined, and has been for a long time. From Ān and Shùn on down, the generations lost their sequence, Chōng and Zhì had short blessings, three generations without successors,  the Imperial network began to fail, the Emperor’s standards collapsing and destroyed. Reaching to Our person, Heaven sent down calamities, I encountered the convergence of undeserved misfortunes,  happened upon the phase of flame’s essence imprisoned and concealed. Rebellion rose at the carriage spokes, the disasters by the castrate eunuchs.  Dǒng Zhuó took advantage of the rifts, his evil as extreme as Jiāo and Yì,  he stole away the government reins, burned away the Palaces and Temples, and therefore caused the Nine Provinces to be split apart, strong enemies fighting like tigers, the Huáxià  a boiling cauldron, venomous snakes blocking the roads. At that time, not a chǐ of land remained as Hàn’s possession, could a single person remain as Our people? By good fortune relying on King Wǔ’s [Cáo Cāo’s] virtue receiving the signs and fates, he exerted and raised his divine warfare, cut down the vicious and cruel, purified and settled the regions of Xià, protected and ordered the Imperial House. Now you the King inherit and continue these former threads, utmost virtue radiant and shining, driving the reins without wavering, spreading virtue to the distant, the sounds of your teachings cover the Four Seas, benevolence air through to desolate regions, and therefore the Four Quarters present treasures, Man and Divinity resonate in answer, Heaven’s calendar calculations truly are upon your person. In the past Yú Shùn had great achievements of twenty and so Fàngxūn abdicated to him Heaven’s Under;  Dà Yǔ had the accomplishment of dredging and channeling and so Chónghuá abdicated to him the Emperor’s throne.  Hàn inherits Yáo’s fate, has the righteousness of passing to the sagely, adds obedience to the spirits and deities, continues Heaven’s brilliant Mandate, and so grants two daughters to be consorts of Wèi.  Send Envoy Holding Stave Enacting Censorate Grandee affairs the Minister of Ceremonies [Zhāng] Yīn,  to present the Imperial Emperor’s Ruler’s Seal and Ribbon. The King is thus to forever be lord over the myriad states,  to respectfully enact Heaven’s authority, to justly maintain the correct, [or else] Heaven’s blessings forever end. Would you respect it?”

Therefore Secretariat Writers Director Huán Jiē and others memorialized stating: “The Hàn dynasty abdicates the throne of Heaven’s Son to Your Majesty,  Your Majesty by the virtue of sagely enlightenment, the sequence of the calendar calculations, receives the abdication of Hàn, indeed matching Heaven’s intention. Heaven’s Mandate cannot be declined, the expectations of the millions of people cannot be opposed. Your Servants request to convene the Ranked Marquesses, the various officers, the various ministers and accompanying scribes, to open the Ruler’s Seal marked letter, obey Heaven’s Mandate, and prepare the ceremony and successive memorials.”

The Order said: “You should discuss my intention to refuse to the end, and nothing more. I am yet hunting, and when I return I will have an Order.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
乙卯，冊詔魏王禪代天下曰：「惟延康元年十月乙卯，皇帝曰，咨爾魏王：夫命運否泰，依德升降，三代卜年，著于春秋，是以天命不于常，帝王不一姓，由來尚矣。漢道陵遲，為日已久，安、順已降，世失其序，沖、質短祚，三世無嗣，皇綱肇虧，帝典頹沮。暨于朕躬，天降之災，遭無妄厄運之會，值炎精幽昧之期。變興輦轂，禍由閹宦。董卓乘釁，惡甚澆、豷，劫遷省御，（太僕）〔火撲〕宮廟，遂使九州幅裂，彊敵虎爭，華夏鼎沸，蝮蛇塞路。當斯之時，尺土非復漢有，一夫豈復朕民？幸賴武王德膺符運，奮揚神武，芟夷兇暴，清定區夏，保乂皇家。今王纘承前緒，至德光昭，御衡不迷，布德優遠，聲教被四海，仁風扇鬼區，是以四方效珍，人神響應，天之曆數實在爾躬。昔虞舜有大功二十，而放勳禪以天下；大禹有疏導之績，而重華禪以帝位。漢承堯運，有傳聖之義，加順靈祇，紹天明命，釐降二女，以嬪于魏。使使持節行御史大夫事太常音，奉皇帝璽綬，王其永君萬國，敬御天威，允執其中，天祿永終，敬之哉？」於是尚書令桓階等奏曰：「漢氏以天子位禪之陛下，陛下以聖明之德，曆數之序，承漢之禪，允當天心。夫天命弗可得辭，兆民之望弗可得違，臣請會列侯諸將、群臣陪隸，發璽書，順天命，具禮儀列奏。」令曰：「當議孤終不當承之意而已。猶獵，還方有令。」
:::
:::

::: {.columns}
::: {.column width="70%"}
The Secretariat Writers Director and the rest again memorialized stating: “In the past Yáo and Shùn abdicated at Wénzǔ.  Reaching to the Hàn dynasty by military campaign receiving the Mandate, in fear of Heaven’s authority they did not dare be negligent or idle, and so succeeded the throne in the land of wherever they were traveling.  Now in receiving the mandate of the abdicating dynasty, it is appropriate to convene the hundred offices and various managers, the servicemen of the Six Armies, for all to go to their seats, to have all witness Heaven’s Mandate. Inside the camps is compact and narrow, we can on a flat and spacious location establish a platform stage, to receive and answer the glorious mandate. Your Servants at once with the Attendant Centrals and Regular Attendants meet to discuss the ceremonies, the Grand Scribe offices to select an auspicious date, and when finished will again memorialize.”

The Order said: “I absolutely do not dare to accept this, why does the exterior presume on the matter?”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
尚書令等又奏曰：「昔堯、舜禪於文祖，至漢氏，以師征受命，畏天之威，不敢怠遑，便即位行在所之地。今當受禪代之命，宜會百寮群司，六軍之士，皆在行位，使咸睹天命。營中促狹，可於平敞之處設壇場，奉答休命。臣輒與侍中常侍會議禮儀，太史官擇吉日訖，復奏。」令曰：「吾殊不敢當之，外亦何豫事也！」
:::
:::

::: {.columns}
::: {.column width="70%"}
Attendant Central Liú Yì, Regular Attendant Wèi Zhēn and others memorialized comments stating: “The Hàn dynasty complies with the discussions of Táng Yáo sharing Heaven’s Under, Your Majesty by sagely virtue receives the cycles of the calendar calculations, Heaven and Humanity together joyous, nothing is not in its place, it is appropriate to obey the spiritual signs, and quickly ascend the Imperial steps. Asking the Grand Scribe Deputy Xǔ Zhī, the present moon’s seventeenth day Jǐwèi [220 Nov 29], Zhí Chéng,  can accept the abdication mandate, and so at once we prepare the location of the platform stage, and what should be put into effect will be in separate memorials.”

The Order said: “Happening to go out and see the exterior, there is the building of a platform stage. What is the meaning of this? Now I will decline and not accept the Edict. Only outside the tents open the Ruler’s Seal marked letter, with the authoritative ceremonies as usual.  Moreover the weather is cold, dismiss the servicemen building the platform and send them home.”

At the opening of the Ruler’s Seal marked letter, the King’s Order said: “I will respectfully return the Ruler’s Seal and Ribbon with a Response of declining. How can I accept this Edict and receive this bestowal? In the past Yáo yielded Heaven’s Under to Xǔ Yóu and Zǐzhōu Zhīfǔ, Shùn also yielded to Shàn Juǎn, Shíhù zhī Nóng, Běirén Wúzé.  One withdrew and plowed the Yǐng’s sunny bank,  one declined and claimed depression illness,  one went far into the mountains and forest so none knew where he was,  one took his children to the sea and to the end would not return,  one believed it a disgrace and threw himself into the abyss.  Moreover Yán Zhú feared that Grand Simplicity would not be preserved and maintained the wisdom of knowing contentment,  Wángzǐ Sōu was happy to live in seclusion in the cinnabar caves and when smoked did not come out,  Liǔxià Huì would not for the nobility of the Three Excellencies exchange his integrity,  Zēng Shēn would not for the wealth of Jìn and Chǔ exchange his benevolence.  These nine servicemen all had high integrity and esteemed righteousness, contemptuous of wealth and disdainful of nobility, and therefore their names were written for a thousand years and praised to the present. Seeking benevolence obtains benevolence, how is benevolence far away?  How can I alone not compare? Righteousness is to walk into the eastern sea and die,  and not accept the Hàn Court’s Edict. Urgently send up Response returning the Ruler’s Seal and Ribbon, announce it to Heaven’s Under, to have all hear of it.”

Jǐwèi [220 Nov 29], announced and reported to the various offices, sent down to Wèi [fief state], also sent down to Heaven’s Under.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
侍中劉廙、常侍衛臻等奏議曰：「漢氏遵唐堯公天下之議，陛下以聖德膺曆數之運，天人同歡，靡不得所，宜順靈符，速踐皇阼。問太史丞許芝，今月十七日己未直成，可受禪命，輒治壇場之處，所當施行別奏。」令曰；「屬出見外，便設壇場，斯何謂乎？今當辭讓不受詔也。但於帳前發璽書，威儀如常，且天寒，罷作壇士使歸。」既發璽書，王令曰：「當奉還璽綬為讓章。吾豈奉此詔承此貺邪？昔堯讓天下於許由、子州支甫，舜亦讓于善卷、石戶之農、北人無擇，或退而耕潁之陽，或辭以幽憂之疾，或遠入山林，莫知其處，或攜子入海，終身不反，或以為辱，自投深淵；且顏燭懼太樸之不完，守知足之明分，王子搜樂丹穴之潛處，被熏而不出，柳下惠不以三公之貴易其介，曾參不以晉、楚之富易其仁：斯九士者，咸高節而尚義，輕富而賤貴，故書名千載，于今稱焉。求仁得仁，仁豈在遠？孤獨何為不如哉？義有蹈東海而逝，不奉漢朝之詔也。亟為上章還璽綬，宣之天下，使咸聞焉。」己未，宣告群僚，下魏，又下天下。
:::
:::

::: {.columns}
::: {.column width="70%"}
Supporting the State General and Marquess of Qīngyuàn Liú Ruò  and others of one hundred twenty people sent up letter that said: “In prostration reading the Order letter, deeply insisting on restraint and refusal, your sagely intentions are earnest and sorrowful, utmost sincerity outwardly revealed, We Your Servants are thus not at ease. Why is this? Shíhù and Běirén were ordinary fellows of deranged extremism, their conduct not in accordance with righteousness, their matters not seen in the classics, and therefore the Scribe [Sīmǎ] Qiān said it was not so,  truly not what sagely enlightenment should admire. Moreover, Yǒu Yú did not oppose Fàngxūn’s abdication, Xià Yǔ also had no speech of declining the throne,  therefore the Zhuàn states: ‘Shùn ascended the Emperor’s Throne, as if he inherently possessed it.’  This truly was a sagely man understanding that Heaven’s Mandate cannot be opposed, the calendar calculations cannot be declined. In prostration considering that Your Majesty answers Heaven’s signs and cycles, utmost virtue spread and heard, ascending to shine the heavens, thus the Three Spirits  send down omens, Man and Divinity thus harmonize, magnificent portents mingle together, myriad states resonate in answer, and even if you wish to not be employed, how can you escape it? And yet you stubbornly maintain modesty, disobeying Heaven and opposing the masses, admiring the trifling fame of ordinary fellows, turning back on where the highest sages have tread, disobeying the explicit writings of the classics and prophecies, trusting in the digging of the hundred schools.  This is not how to serve and answer Heaven’s Mandate, glorify and comfort the expectations of the masses. We Your Servants risk death to plead: at once organize the platform stage, on reaching the auspicious day accept the mandate, as in previous memorials, and separately write Orders to announce down.”

The King’s Order said: “In the past Bǎichéng Zǐgāo declined Xià Yǔ and hid in the wilderness, Yán Hé declined Lǔ’s gifts and went far away;  the heavy importance of rulers, the nobility of vassal lords, yet these two sirs thought little of it. Why was this? Because their integrity was high. Therefore ardent martyrs seek glory and fame, righteous men esteem resolute integrity, and even if they eat vegetables and ladle water, they are happy in it. Therefore Zhòngní took as teacher Wáng Tái,  and Zǐ Chǎn praised Shēntú.  Now you ministers all are my legs and arms and belly and heart,  able to understand me, but that now you all are like this, then it is that you ministers are roaming inside form and structure, while I seek to be beyond form and structure: that we do not understand one another is not enough to be a great surprise. Urgently send up Response to return the Ruler’s Seal and Ribbon, and do not again clamor about it.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
輔國將軍清苑侯劉若等百二十人上書曰：「伏讀令書，深執克讓，聖意懇惻，至誠外昭，臣等有所不安。何者？石戶、北人，匹夫狂狷，行不合義，事不經見者，是以史遷謂之不然，誠非聖明所當希慕。且有虞不逆放勛之禪，夏禹亦無辭位之語，故傳曰：『舜陟帝位，若固有之。』斯誠聖人知天命不可逆，曆數弗可辭也。伏惟陛下應乾符運，至德發聞，升昭于天，是三靈降瑞，人神以和，休徵雜沓，萬國響應，雖欲勿用，將焉避之？而固執謙虛，違天逆眾，慕匹夫之微分，背上聖之所蹈，違經讖之明文，信百氏之穿鑿，非所以奉答天命，光慰眾望也。臣等昧死以請，輒整頓壇場，至吉日受命，如前奏，分別寫令宣下。」王令曰：「昔柏成子高辭夏禹而匿野，顏闔辭魯幣而遠跡，夫以王者之重，諸侯之貴，而二子忽之，何則？其節高也。故烈士徇榮名，義夫高貞介，雖蔬食瓢飲，樂在其中。是以仲尼師王駘，而子產嘉申徒。今諸卿皆孤股肱腹心，足以明孤，而今咸若斯，則諸卿遊于形骸之內，而孤求為形骸之外，其不相知，未足多怪。亟為上章還璽綬，勿復紛紛也。」
:::
:::

::: {.columns}
::: {.column width="70%"}
The Supporting the State General and others of one hundred twenty men again memorialized stating: “Your Servant has heard that signs of the mandate do not appear without reason, the hearts of the masses cannot be disobeyed, and therefore Kǒng-zǐ said: ‘Was Zhōu-gōng thus not a sage? To decline Heaven’s Under is like Heaven and Earth and the Sun and Moon thoughtlessly abandoning all things.’  Therefore Shùn oversaw Heaven’s Under, not bowing and accepting the Mandate. Now Fire’s Virtue and aura are exhausted, Flame sends up calculations of completion, Emperor title shifts to enlightened virtue, the blessings pass to Great Wèi. The signs and omens are obvious and clear, receiving the mandate already assured, glorifying under the Heavens, Divinities and Humanity together answer, even Yǒu Yú’s ceremonious fèng and Chéng Zhōu’s leaping fish,  when compared to the present situation, are not enough to compare. Yet Your Majesty disobeys Heaven’s Mandate to embellish petty conduct, opposes the hearts of the people to uphold selfish ambitions, above disobeying the intentions of the caring mandate of the august firmament, in the middle forgetting the calculations of the comprehensive understandings of the sages, below abandoning your subjects looking up in hope; this is not the way to raise up the high road of the way of sages and carry on boundless exemplary merits. Your Servants have heard that serving lord has ways of proffering the appropriate and replacing the unsuitable, that serving superiors has the righteousness of firmly contesting inverted scales,  Your Servants dare to risk death to plead.”

The Order said: “In the government of the ancient sage kings, utmost virtue accorded with Qián and Kūn, kindness and beneficence equaled natural change, ritual and education improved even the insects, benevolence and favor penetrated even the grasses and trees, all that the sun and moon shined upon, all the sorts of breathing living things supporting the heavens and treading the earth, none were not covered and enveloped in the pure aura, bathed and immersed in profound virtue. Therefore metal and leather did not rise,  oppression and evil were not created, wind and rain complied with the seasons, auspicious omens of all sorts appeared. Now of the Hundred Surnames, those cold are not yet warmed, those hungry not yet fed, the widowers not yet married, the widows not yet wed, [Sūn] Quán and [Liú] Bèi still survive, cannot be subdued by dancing with shield and battle-ax, and must be set right with the sharp ax.  Military campaigns have not yet ceased on the exterior, servicemen and civilians are not yet safe in the interior, ears do not yet hear songs of Kāngzāi,  eyes do not yet see games of hitting soil,  infants cannot yet be entrusted to high nests, surplus grain cannot yet be left in the fields overnight.  Human affairs are not yet provided for to this extent. The night has not yet been illuminated by the Jǐng star,  governance has not yet connected with the True Man,  the Hé has not produced a dragon horse,  the mountains have not produced an elephant chariot,  míngjía have not yet been planted in the courtyard steps,  shàpú have not grown in the kitchens,  the Wángmǔ has not yet presented a white jade ring,  the Qúsōu have not yet revealed precious furs.  Auspicious signs are not yet verified, also to that degree. In the past Dōnghù Jìzǐ, Róngchéng, Dàtíng, Xuānyuán, Hèxū, these lords all by obtaining these accomplished their achievements and engraved their names.  Now you ministers alone, cannot you lend me a little leave to be thorough in heart and exhaustive in consideration, to harmonize with Heaven and Humanity, to reach utmost reason, to allow those multitudes of affairs to be prepared, the various auspicious signs to be verified, and only afterward then discuss this? Why so hurriedly and shamefully pressure like this? Hurriedly make the decline Response, send up and return the Ruler’s Seal and Ribbon, to not increase my lack of virtue.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
輔國將軍等一百二十人又奏曰：「臣聞符命不虛見，眾心不可違，故孔子曰：『周公其為不聖乎？以天下讓。是天地日月輕去萬物也。』是以舜嚮天下，不拜而受命。今火德氣盡，炎上數終，帝遷明德，祚隆大魏。符瑞昭晳，受命既固，光天之下，神人同應，雖有虞儀鳳，成周躍魚，方今之事，未足以喻。而陛下違天命以飾小行，逆人心以守私志，上忤皇穹眷命之旨，中忘聖人達節之數，下孤人臣翹首之望，非所以揚聖道之高衢，乘無窮之懿勳也。臣等聞事君有獻可替否之道，奉上有逆鱗固爭之義，臣等敢以死請。」令曰：「夫古聖王之治也，至德合乾坤，惠澤均造化，禮教優乎昆蟲，仁恩洽乎草木，日月所照，戴天履地含氣有生之類，靡不被服清風，沐浴玄德；是以金革不起，苛慝不作，風雨應節，禎祥觸類而見。今百姓寒者未煖，飢者未飽，鰥者未室，寡者未嫁；權、備尚存，未可舞以干戚，方將整以齊斧；戎役未息於外，士民未安於內，耳未聞康哉之歌，目未睹擊壤之戲，嬰兒未可託於高巢，餘糧未可以宿於田畝：人事未備，至於此也。夜未曜景星，治未通真人，河未出龍馬，山未出象車，蓂莢未植階庭，萐莆未生庖廚，王母未獻白環，渠搜未見珍裘：靈瑞未效，又如彼也。昔東戶季子、容成、大庭、軒轅、赫胥之君，咸得以此就功勒名。今諸卿獨不可少假孤精心竭慮，以和天人，以格至理，使彼眾事備，群瑞效，然後安乃議此乎，何遽相愧相迫之如是也？速為讓章，上還璽綬，無重吾不德也。」
:::
:::

::: {.columns}
::: {.column width="70%"}
Attendant Central Liú Yì and others memorialized stating: “In prostration considering that Your Majesty by the pure virtue of a great sage bears the calendar calculations of Heaven’s Mandate, in observing Heaven’s Images then the auspicious signs are proven and clear, in investigating the charts and prophecies then the written meanings are shining and luminous, in inspecting human affairs then the Four Seas are unified in heart, in examining the previous dynasties then different eras have the same results, but yet you firmly refuse the abdication mandate, have not yet ascended to the honored throne, your sagely intentions earnest and sorrowful, do We Your Servants dare not accept your Edict? At once we prepare Response and send the envoy.”

Presented Order said: “Tàibó thrice declined Heaven’s Under, the people had no ability to praise him, Zhòngní sighed at this utmost virtue.  I alone am what sort of man?”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
侍中劉廙等奏曰：「伏惟陛下以大聖之純懿，當天命之曆數，觀天象則符瑞著明，考圖緯則文義煥炳，察人事則四海齊心，稽前代則異世同歸；而固拒禪命，未踐尊位，聖意懇惻，臣等敢不奉詔？輒具章遣使者。」奉令曰：「泰伯三以天下讓，人無得而稱焉，仲尼歎其至德，孤獨何人？」
:::
:::

::: {.columns}
::: {.column width="70%"}
Gēngshēn [220 Nov 30], the King of Wèi sent up letter that said: “Imperial Emperor, Your Majesty: Receiving this Moon’s Yǐmǎo [220 Nov 25] Ruler’s Seal marked letter, in prostration listening to the conferment mandate, my five internal organs  were startled and shaken, my vitality scattered about, not knowing what to do. Your Servant previously sent up and returned my Chancellor’s position, withdrawing to maintain my vassal state, and your sagely grace permitted it. Although Your Servant is without the will of the ancients to self-determine position by measuring virtue and judging myself, protecting myself and preserving my nature truly is my selfish hope. Unexpectedly Your Majesty condescended to transmit excessively mistaken mandate, issue an irregular Edict, to apply on a servant without virtue. Moreover I have heard that Yáo abdicated to Chónghuá to elevate his virtue of ability to harmonize, and Shùn conferred to Wénmìng to select his beauty of overwhelming sagacity, yet still below consulted the Sìyuè and above observed the Xuánjī.  Now Your Servant’s virtue is not that of Yú or Xià, conduct not of those two lords, and yet receive consultation on the calendar calculations, answer mandate of selection and conferment, inside considering and estimating myself, I have no virtue to be praised. Moreover Xǔ Yóu was an ordinary fellow and yet refused the Emperor’s throne, Shàn Juàn was in plain clothes but yet opposed Yú’s [Shùn’s] Edict.  Although Your Servant is lowly and ignorant, dare I forget integrity to accept this great mandate? I cannot bear your utmost wishes. I sincerely bow to present this Response to explain my feelings, sending Acting as Chancellor of State the Yǒngshòu Minister Treasurer Your Dirtied Servant Máo Zōng  to memorialize, and also send up the Ruler’s Seal and Ribbon.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
庚申，魏王上書曰：「皇帝陛下：奉被今月乙卯璽書，伏聽冊命，五內驚震，精爽散越，不知所處。臣前上還相位，退守藩國，聖恩聽許。臣雖無古人量德度身自定之志，保己存性，實其私願。不寤陛下猥損過謬之命，發不世之詔，以加無德之臣。且聞堯禪重華，舉其克諧之德，舜授文命，采其齊聖之美，猶下咨四嶽，上觀璿璣。今臣德非虞、夏，行非二君，而承曆數之諮，應選授之命，內自揆撫，無德以稱。且許由匹夫，猶拒帝位，善卷布衣，而逆虞詔。臣雖鄙蔽，敢忘守節以當大命，不勝至願。謹拜章陳情，使行相國永壽少府糞土臣毛宗奏，并上璽綬。」
:::
:::

::: {.columns}
::: {.column width="70%"}
Xīnyǒu [220 Dec 1], Dispensing Affairs Central Academic Scholars Sū Lín and Dǒng Bā  sent up memorial that said: “Heaven has Twelve Stations forming the Field Allocations, the states of kings and dukes each have their affiliation.  Zhōu is at Chúnhuǒ, Wèi is at Dàliáng. Suìxīng travels through the Twelve Stations and states, Heaven’s Son receives the Mandate, the vassal lords are enfeoffed. When Zhōu King Wén first received the Mandate, Suì was at Chúnhuǒ, reaching King Wǔ attacking Zhòu in the thirteenth year, Suìxīng again was at Chúnhuǒ, and therefore the Chūnqiū Zhuàn states: ‘King Wǔ attacked Zhòu, Suì was at Chúnhuǒ. Where Suì is located, is our Yǒu Zhōu’s field allocation.’  In the past in Guānghé Seventh Year [184], Suì was at Dàliáng, King Wǔ [Cáo Cāo] first received a mandate at the time to command the suppression of Huángjīn. That year was changed to Zhōngpíng Inaugural Year. Jiàn’ān Inaugural Year [196], Suì again was at Dàliáng, he was first appointed General-in-Chief. Thirteenth Year [208] again at Dàliáng, first appointed Assistant Chancellor. Now it is the Twenty-Fifth Year [220], Suì again is at Dàliáng, Your Majesty receives the Mandate. This is Wèi obtaining Suì in correspondence to Zhōu King Wén receiving the Mandate. This year Qīnglóng is at a Gēngzǐ,  the Shī Tuīdùzāi states: ‘Gēng is change, Zǐ is growth, the sage is mandated, Heaven’s Under is governed.’ It also states: ‘The ruler spreads virtue in Zǐ, governance achieved in Chǒu.’  This says that this year Heaven will change its mandate to a sagely man to regulate and govern Heaven’s Under, to spread virtue to the people. Wèi by reorganizing Heaven’s Under will accord with the Shī.  When Zhuānxū received the mandate, Suì was at Shǐwéi; when Wèi occupied that territory, also was at Shǐwéi; therefore the Chūnqiū Zhuàn states: ‘Wèi is the ruins of Zhuānxū.’  In the present Tenth Moon where the Dǒu established  then was the allocation of Zhuānxū receiving the Mandate, Wèi in the Eleventh Moon receives the Mandate, this is the same verification of the sign of Shǐzǔ receiving the Mandate.  Wèi’s ruling clan originated from Zhuānxū, with Shùn having a common ancestor, as seen in the Chūnqiū Shìjiā.  Shùn by Earth Virtue succeeded Yáo’s Fire, now Wèi also by Earth Virtue succeeds Hàn’s Fire, thus in the transitioning fates, it is in agreement with the succession of Yáo and Shùn granting and receiving. Your Servant has heard that the departures and arrivals of Heaven assuredly have constant allocations, the sagely man complies with it, understands clearly without doubt, and therefore Yáo disinherited his bone and flesh to instead abdicate to Yǒu Yú,  to the end without stingy expression. Shùn came from farm fields and yet ruled Heaven’s Under as if intrinsically possessing it. In their accepting and giving to one another, the interim was without a gap. Heaven’s Under was already transmitted, so they were urgent in Heaven’s Mandate, because Heaven’s Under cannot for one day be without its ruler. Now Hàn’s allotted fate has already ended, the strange signs of the termination already investigated, Your Majesty has received the Mandate of Heaven, the auspicious signs report the portents, the urgings detailed and comprehensive, again repeatedly prepared and arrive, and even using language to describe it is unable to substitute for it. Now the Edict is already issued, the Ruler’s Seal and Ribbon you have not yet used, stubbornly holding to modestly declining, above rebelling against Heaven’s Mandate, below disobeying the people’s hopes. Your Servant solemnly cites the ancient canons and registers, consults the charts and prophecies, Wèi’s transitioning fate and Heaven’s Way are present, the verification of accepting the honorifics is in the present year and this moon, manifestly evident and distinctly clear. May Your Majesty shift your thinking and change your considerations, timely succeed the throne, clearly announce to the God of Heaven and announce to Heaven’s Under, and afterward revise the Standard Moon,  change uniform colors, rectify great title, and Heaven’s Under’s fortunes would be extreme.”

The Order said: “All this should be by sagely virtue, and therefore it is said: ‘If it is not the [right] person, the way will not act in vain.’  Though Heaven’s auspicious signs are manifest, it must wait for virtue and then shine. I am a man of meager virtue; how can I be enough to match it? Now I decline, and hope to see and hear permission, the exterior and interior are all made to hear and know.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
辛酉，給事中博士蘇林、董巴上表曰：「天有十二次以為分野，王公之國，各有所屬，周在鶉火，魏在大梁。歲星行歷十二次國，天子受命，諸侯以封。周文王始受命，歲在鶉火，至武王伐紂十三年，歲星復在鶉火，故春秋傳曰：『武王伐紂，歲在鶉火；歲之所在，即我有周之分野也。』昔光和七年，歲在大梁，武王始受命，（為）〔於〕時將討黃巾。是歲改年為中平元年。建安元年，歲復在大梁，始拜大將軍。十三年復在大梁，始拜丞相。今二十五年，歲復在大梁，陛下受命。此魏得歲與周文王受命相應。今年青龍在庚子，詩推度災曰：『庚者更也，子者滋也，聖命天下治。』又曰：『王者布德於子，治成於丑。』此言今年天更命聖人制治天下，布德於民也。魏以改制天下，與（時）〔詩〕協矣。顓頊受命，歲在豕韋，衛居其地，亦在豕韋，故春秋傳曰：『衛，顓頊之墟也。』今十月斗之建，則顓頊受命之分也，始魏以十月受禪，此同符始祖受命之驗也。魏之氏族，出自顓頊，與舜同祖，見于春秋世家。舜以土德承堯之火，今魏亦以土德承漢之火，於行運，會于堯舜授受之次。臣聞天之去就，固有常分，聖人當之，昭然不疑，故堯捐骨肉而禪有虞，終無恡色，舜發隴畝而君天下，若固有之，其相受授，閒不替漏；天下已傳矣，所以急天命，天下不可一日無君也。今漢期運已終，妖異絕之已審，階下受天之命，符瑞告徵，丁寧詳悉，反覆備至，雖言語相喻，無以代此。今既發詔書，璽綬未御，固執謙讓，上逆天命，下違民望。臣謹案古之典籍，參以圖緯，魏之行運及天道所在，即尊之驗，在于今年此月，昭晰分明。唯階下遷思易慮，以時即位，顯告天帝而告天下，然後改正朔，易服色，正大號，天下幸甚。」令曰：「凡斯皆宜聖德，故曰：『苟非其人，道不虛行。』天瑞雖彰，須德而光；吾德薄之人，胡足以當之？今讓，冀見聽許，外內咸使聞知。」
:::
:::

::: {.columns}
::: {.column width="70%"}
Rénxū [220 Dec 2], conferment Edict said: “The Imperial Emperor inquires of the King of Wèi saying: The dispatched [Máo] Zōng presenting your Gēngshēn [220 Nov 30] letter arrived, and what it states and explains, I have heard it. We consider that the Hàn House’s reigns have exceeded twenty, its years surpassed four hundred, the fate cycle calculations completed, the transition of blessings already finished, Heaven’s heart already shifted, the millions of people’s expectations severed, what Heaven has discarded is of its own accord. Now the Great Mandate has where it settles and rests, the Divine Vessels should go to sagely virtue, disobeying the masses is not favorable, opposing Heaven is not auspicious. You the King thus embody Yǒu Yú’s flourishing virtue, answer the auspicious conjunction of the calendar calculations, and therefore auspicious signs report the correspondences, the charts and prophecies present the records, Divinity and Humanity the same in answer, accepting the Mandate is completely appropriate. We are in awe of Highest God  and convey the throne to you King. Heaven cannot be disobeyed; the masses cannot be discarded. Moreover Chónghuá did not oppose Yáo’s mandate, Dà Yǔ did not decline Shùn’s throne, as for ordinary fellows as [Xǔ] Yóu and [Shàn] Juān, they are not recorded in registers of sages, assuredly not what Imperial material or a vessel to be Emperor should praise and admire. Now send [Zhāng] Yīn to present the Imperial Emperor’s Ruler’s Seal and Ribbon, the King is to ascend the Emperor’s throne, not oppose Our mandate, to respectfully serve Heaven’s intentions thus.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
壬戌，冊詔曰：「皇帝問魏王言：遣宗奉庚申書到，所稱引，聞之。朕惟漢家世踰二十，年過四百，運周數終，行祚已訖，天心已移，兆民望絕，天之所廢，有自來矣。今大命有所厎止，神器當歸聖德，違眾不順，逆天不祥。王其體有虞之盛德，應曆數之嘉會，是以禎祥告符，圖讖表錄，神人同應，受命咸宜。朕畏上帝，致位于王；天不可違，眾不可拂。且重華不逆堯命，大禹不辭舜位，若夫由、卷匹夫，不載聖籍，固非皇材帝器所當稱慕。今使音奉皇帝璽綬，王其陟帝位，無逆朕命，以祗奉天心焉。」
:::
:::

::: {.columns}
::: {.column width="70%"}
Thereupon Secretariat Writers Director Huán Jiē and others memorialized saying: “Now Hàn’s envoy [Zhāng] Yīn presenting Ruler’s Seal marked letter arrives, We Your Servants believe that Heaven’s Mandate cannot be delayed, the Divine Vessels cannot be disrespected. Zhōu Wǔ in midstream had the verification of the white fish, did not wait for the appointment of the brigades and his great title was already established. Shùn received the great forest,  the shade of the mulberry tree had not yet shifted and he had already ascended the Emperor’s throne.  All, in order to respectfully serve Heaven’s Mandate, were as quick as this. Therefore there is no righteousness in stubbornly declining, no taking of maintaining limitation as nobility, one must place faith in the divinities, in accordance with Heaven and Earth and nothing more. The Yì states: ‘The receiving of mandate is like an echo, whether far or near or secluded or deep, all know what will come. If it is not the utmost profoundness of Heaven’s Under, how would it be able to be like this?’  Now Your Majesty answers the calculations of allotted fate, taken by August Heaven as son,  but yet again delay and obstruct with declining, drawing back from the great title, it is not the way to model after the way of Heaven and Earth and fulfill the hopes of the myriad states. We Your Servants dare to risk death to plead, to at once order relevant mangers to build the platform stage, select an auspicious day, receive the abdication mandate, and open the Ruler’s Seal and Ribbon.”

The Order said: “I hoped to thrice decline but was not listened to. Why the rush in this?”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
於是尚書令桓階等奉曰：「今漢使音奉璽書到，臣等以為天命不可稽，神器不可瀆。周武中流有白魚之應，不待師期而大號已建，舜受大麓，桑蔭未移而已陟帝位，皆所以祗承天命，若此之速也。故無固讓之義，不以守節為貴，必道信於神靈，符合於天地而已。易曰：『其受命如響，無有遠近幽深，遂知來物，非天下之至賾，其孰能與於此？』今陛下應期運之數，為皇天所子，而復稽滯於辭讓，低回於大號，非所以則天地之道，副萬國之望。臣等敢以死請，輒敕有司修治壇場，擇吉日，受禪命，發璽綬。」令曰：「冀三讓而不見聽，何汲汲于斯乎？」
:::
:::

::: {.columns}
::: {.column width="70%"}
Jiǎzǐ [220 Dec 4], the King of Wèi sent up letter stating: “Receiving this moon’s Rénxū [220 Dec 2] Ruler’s Seal marked letter, again bearing your sagely command, in prostration listening to the conferment announcement, my liver and guts trembled in fear, not knowing what to do. Heaven’s Under’s Divine Vessels and abdication successions are heavy affairs, and therefore when Yáo was about to abdicate to Shùn, ‘he appointed him to the great forest,’  and at Shùn’s mandate on Yǔ, dark jade tablet reported his achievements.  Fierce winds did not confuse them, the Nine Provinces were tranquil and pacified, ‘inquired on affairs and investigated statements,’  and only afterward then mandated, and yet they still held to modestly declining that their virtue was not enough to be a successor. All the more for Your Servant of stubbornness, my character not of those two sages, to then answer Heaven’s governance and receive in the end your enlightened Edict, I dare maintain my trifling integrity, submit my ambitions to Jī mountain,  unable to bear your great wish. I solemnly bow and present explanation of my feelings, and send also to present up the Ruler’s Seal and Ribbon.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
甲子，魏王上書曰：「奉今月壬戌璽書，重被聖命，伏聽冊告，肝膽戰悸，不知所措。天下神器，禪代重事，故堯將禪舜，納于大麓，舜之命禹，玄圭告功；烈風不迷，九州攸平，詢事考言，然後乃命，而猶執謙讓于德不嗣。況臣頑固，質非二聖，乃應天統，受終明詔；敢守微節，歸志箕山，不勝大願。謹拜表陳情，使并奉上璽綬。」
:::
:::

::: {.columns}
::: {.column width="70%"}
Attendant Central Liú Yì and others memorialized stating: “We Your Servants have heard that a sagely emperor does not oppose the times, an enlightened ruler does not defy the people, and therefore the Yì says to ‘connect the will of Heaven’s Under,’ ‘break the doubts of Heaven’s Under.’  In prostration we consider that Your Majesty embodies the upper sagacity of Yǒu Yú, bears the transitioning fate of Earth’s Virtue, meets the conjunction of Kàngyáng and Míngyí,  answers the calculation of the completion of the blessings of the Hàn clan, accords with the Imperial standard, corresponds to the Two Polarities.  Therefore sagely auspicious signs present portents, Heaven’s Under together answers, the calendar fates leave and arrive, deeply and sharply proven and clear. In debating Heaven’s Mandate, there is nothing to discuss. In comparing the suitability of timing, there is nothing to argue. Therefore for the period for receiving the mandate, the season is pure and sun is clear, shining vitality spreading radiance, glorious aura of clouds drifting. This then is Heaven’s Way pleased and rejoicing, the people’s hearts rejoicing and supportive, and yet again they meet with obstruction and refusal, by ritual this is what conduct? Moreover the crowds of the living cannot for one day be without a ruler, the Divine Vessels cannot for an instant be without governance, and therefore servants have disobedience to lords to achieve enterprises, subordinates have rectifying of superiors to establish affairs, We Your Servants dare to not begrudge death to plead.”

The King’s Order said: “Heaven’s Under is a precious vessel, the ruler’s legitimacy; by sagely virtue assume them, yet still have fearful heart. I am what sort of man? Moreover the Excellencies and Ministers have not yet reached to lacking a ruler; this is such a small matter, for the time being it is appropriate to wait to after my firmly declining, and only then again discuss the possibilities.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
侍中劉廙等奏曰：「臣等聞聖帝不違時，明主不逆人，故易稱通天下之志，斷天下之疑。伏惟陛下體有虞之上聖，承土德之行運，當亢陽明夷之會，應漢氏祚終之數，合契皇極，同符兩儀。是以聖瑞表徵，天下同應，曆運去就，深切著明；論之天命，無所與議，比之時宜，無所與爭。故受命之期，時清日晏，曜靈施光，休氣雲蒸。是乃天道悅懌，民心欣戴，而仍見閉拒，于禮何居？且群生不可一日無主，神器不可以斯須無統，故臣有違君以成業，下有矯上以立事，臣等敢不重以死請。」王令曰：「天下重器，王者正統，以聖德當之，猶有懼心，吾何人哉？且公卿未至乏主，斯豈小事，且宜以待固讓之後，乃當更議其可耳。」
:::
:::

::: {.columns}
::: {.column width="70%"}
Dīngmǎo [220 Dec 7], conferment Edict on the King of Wèi said: “Heaven has concluded Hàn’s blessings, the star signs are shown clear, We respect Heaven’s Mandate, convey the Throne to you King, and yet again explain the calendar calculations in Edict of conferment, describe the corresponding fates with brush and ink. The Divine Vessels cannot be dismissed and refused, the Imperial throne cannot be modestly declined. The delays of Heaven’s Mandate have reached to the second and third. Moreover the Four Seas cannot for one day be without a ruler, the myriad affairs cannot for an instant be without governance, and therefore one who establishes a great enterprise is not restrained by minor limits, one who understands Heaven’s Mandate is not bound by trifling things. Therefore Shùn accepted the mandate of the great enterprise and was without humble yielding refusals. The sagely man in transcending limits, is it not far? Now send [Zhāng] Yīn to present the Imperial Emperor’s Ruler’s Seal and Ribbon, the King is to respectfully accept, to reply to Heaven’s Under’s expectations of answer.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
丁卯，冊詔魏王曰：「天訖漢祚，辰象著明，朕祗天命，致位於王，仍陳曆數於詔冊，喻符運於翰墨；神器不可以辭拒，皇位不可以謙讓，稽於天命，至於再三。且四海不可以一日曠主，萬機不可以斯須無統，故建大業者不拘小節，知天命者不繫細物，是以舜受大業之命而無遜讓之辭，聖人達節，不亦遠乎！今使音奉皇帝璽綬，王其欽承，以答天下嚮應之望焉。」
:::
:::

::: {.columns}
::: {.column width="70%"}
Chancellor of State Huà Xīn, Grand Commandant Jiǎ Xǔ, Censorate Grandee Wáng Lǎng with the Nine Ministers  sent up word stating: “We Your Servants have been summoned and arrived, in prostration observed Grand Scribe Deputy Xǔ Zhī and Left Central Cadet General Lǐ Fú’s sent up charts and prophecies and signs of the mandate, Attendant Central Liú Yì and other’s announced explanations of the hearts of the masses; humanity and spirits together planned. Also the Hàn Court knows Your Majesty’s sagely influence connects with the divine intelligence, sagely virtue matches with Yú and Xià, because signs and verifications completely arrive, it heeds where the calendar calculations are located, and therefore proffers Ruler’s Seal and Ribbon, firmly yielding the Honored Title. Of those able to speak, none do not applaud and dance. The Hé Tú and Luò Shū give the signs and verifications of Heaven’s Mandate, human affairs harmonize with Heaven’s timing, the people’s speech harmonize with Heaven’s narratives. But Your Majesty by nature maintains diligence and modesty, in conduct esteems restraint and refusal, the enlightened edict earnest and sincere, not yet willing to listen and agree. Of the ministers and servants and lesser men, none are not melancholy and anxious. We Your Servants have heard that from antiquity to the present, those that possessed Heaven’s Under were not always of one surname. Examining virtue and power, then flourishing and decline are by strength and weakness. Discussing the ends and beginnings, then downfall and rising are by allotted fates. Táng’s and Yú’s calendar calculations were not with their sons, but with Shùn and Yǔ. Although Shùn and Yǔ had thoughts of declining, they were compelled by the crowds of lords grasping silk and jade to hold Court for them,  the millions of people joyously supportive and submitting to them, all the lands raising songs and ballads to eulogize them. Therefore the restraints of maintaining limits cannot be obtained and always held, the expedience of transcending limits cannot be obtained and long avoided, and therefore some resign the throne and are not stingy, some receive the abdication and do not decline. The one not stingy does not necessarily loathe Imperial favor, the one not declining does not necessarily thirst for the Emperor’s blessings. Each was compelled by Heaven’s Mandate and could not do as they wished. After the abdication, then the sons of the Táng clan were the guests of Yǒu Yú, the descendants of the Yú clan were the guests of the Xià dynasty.  That being the case, the meaning of abdication succession is not only the receivers truly answering Heaven’s fortunes, the givers also enjoy hereditary celebrations. Hàn from Zhāng and Hé onward, the generations had many changes and misfortunes, gradually declining.  Reaching to Xiào-Líng, he was not constant in heart,  oppressed the worthy and harmed the benevolent,  hoarded wealth without limit,  governance was with his favorite castrates,  saw the people as enemies, therefore causing Heaven Above to shake in anger, the Hundred Surnames shifted allegiance like following the winds. At that time then the Four Seas were a boiling cauldron, and at his passing then disaster issued from the Palace courts, favor and power both exhausted, the Emperor’s House therefore brought low. Like how at the final end of the Emperor Shùn he yet selected a sagely successor and conferred on him, how the Jīng man carried uncut jade and yet yearned for a skilled craftsman to carve it,  all the more for the Hàn state already gone, none able to rectify it; transferring the vessels and shifting lords, entrusting to the sagely and wise, assuredly is appropriate. The Hàn Court entrusts its pledge, and already wishes for the ritual of abdication to be quickly settled. Heaven blesses all the lands, certainly there must be a ruler. A ruler of all the lands, if not Your Majesty then who can be appointed for it? It is what is called: in discussing virtue there are none who can compare, in examining achievements there can be no refusal and decline. Heaven’s Mandate cannot be long delayed, the people’s hopes cannot be long disobeyed. Your Servants are anxious and cannot bear our great hopes. In prostration we request Your Majesty cut off from your ambitions of modesty, prepare the rituals for accepting the abdication, to accord with the intentions of Humanity and Divinity, and comfort the hopes of the exterior and the interior.”

The Order said: “In virtue then I am insufficient, in timing then the warfare and rebels are not yet extinguished. If by the spirits of the various worthies I am able to protect my head and neck, ending as lord over Wèi state, to me it would be sufficient. One like me, how am I worth disgracing the Four Seas? As for Heaven’s signs and human affairs, all are the remnant celebrations of the Former King’s sagely virtue, what do I have to do with it? Therefore I do not dare hear of the Mandate.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
相國華歆、太尉賈詡、御史大夫王朗及九卿上言曰：「臣等被召到，伏見太史丞許芝、左中郎將李伏所上圖讖、符命，侍中劉廙等宣敘眾心，人靈同謀。又漢朝知陛下聖化通于神明，聖德參于虞、夏，因瑞應之備至，聽曆數之所在，遂獻璽綬，固讓尊號。能言之倫，莫不抃舞，河圖、洛書，天命瑞應，人事協于天時，民言協于天敘。而陛下性秉勞謙，體尚克讓，明詔懇切，未肯聽許，臣妾小人，莫不伊邑。臣等聞自古及今，有天下者不常在乎一姓；考以德勢，則盛衰在乎彊弱，論以終始，則廢興在乎期運。唐、虞曆數，不在厥子而在舜、禹。舜、禹雖懷克讓之意迫，群后執玉帛而朝之，兆民懷欣戴而歸之，率土揚歌謠而詠之，故其守節之拘，不可得而常處，達節之權，不可得而久避；是以或遜位而不恡，或受禪而不辭，不恡者未必厭皇寵，不辭者未必渴帝祚，各迫天命而不得以已。既禪之後，則唐氏之子為賓于有虞，虞氏之冑為客于夏代，然則禪代之義，非獨受之者實應天福，授之者亦與有餘慶焉。漢自章、和之後，世多變故，稍以陵遲，洎乎孝靈，不恆其心，虐賢害仁，聚斂無度，政在嬖豎，視民如讎，遂令上天震怒，百姓從風如歸；當時則四海鼎沸，既沒則禍發宮庭，寵勢並竭，帝室遂卑，若在帝舜之末節，猶擇聖代而授之，荊人抱玉璞，猶思良工而刊之，況漢國既往，莫之能匡，推器移君，委之聖哲，固其宜也。漢朝委質，既願禮禪之速定也，天祚率土，必將有主；主率土者，非陛下其孰能任之？所謂論德無與為比，考功無推讓矣。天命不可久稽，民望不不可久違，臣等慺慺，不勝大願。伏請陛下割撝謙之志，脩受禪之禮，副人神之意，慰外內之願。」令曰：「以德則孤不足，以時則戎虜未滅。若以群賢之靈，得保首領，終君魏國，於孤足矣。若孤者，胡足以辱四海？至乎天瑞人事，皆先王聖德遺慶，孤何有焉？是以未敢聞命。」
:::
:::

::: {.columns}
::: {.column width="70%"}
Jǐsì [220 Dec 9], the King of Wèi sent up letter stating: “Your Servant has heard that Shùn had the accomplishment of the guests at the four gates and thus received the abdication from Táo Táng,  that Yǔ had the achievement of preserving states of seven hundred and thus inherited fortunes from Yǒu Yú.  Your Servant is sheltered and ignorant, my virtue not of those two sages, shamefully meet Heaven’s governance, and do not dare hear your mandate. I dare repeatedly resist and petition, roughly explaining my private wishes, hoping my Response reaches the purple courts, to be able to preserve my meager integrity, my feelings communicated to the palace summit, forever maintain my original ambition. But [Zhāng] Yīn once again carries mandate, extending Regulation Edict on Your Servant, Your Servant truly trembles in fear, and will not open the Ruler’s Seal marked letter, but [Zhāng] Yīn is constrained by a strict Edict, and does not dare return from his mandate. May Your Majesty urgently send galloping relays, to summon [Zhāng] Yīn back to the terraces. I cannot bear my utmost sincerity, and solemnly send [Máo] Zōng to present letter.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
己巳，魏王上書曰：「臣聞舜有賓于四門之勳，乃受禪於陶唐，禹有存國七百之功，乃承祿於有虞。臣以蒙蔽，德非二聖，猥當天統，不敢聞命。敢屢抗疏，略陳私願，庶章通紫庭，得全微節，情達宸極，永守本志。而音重復銜命，申制詔臣，臣實戰惕，不發璽書，而音迫于嚴詔，不敢復命。願陛下馳傳騁驛，召音還臺。不勝至誠，謹使宗奉書。」
:::
:::

::: {.columns}
::: {.column width="70%"}
Chancellor of State [Huà] Xīn, Grand Commandant [Jiǎ] Xǔ, Censorate Grandee [Wáng] Lǎng with the Nine Ministers memorialized stating: “We Your Servants in prostration read the Edict letter, our anxiety increasingly extreme. We Your Servants have heard that the Yì states that the sagely man serves Heaven’s timing,  the Lúnyǔ says that the noble man is awed by Heaven’s Mandate,  Heaven’s Mandate has its leaving and arriving, and only afterward do Emperors have abdication successions. Therefore Táng abdicated to Yú because the mandate was on his body, Yú obeyed Táng calling it acceptance of completion. Yáo understood that Heaven’s Mandate had left him and therefore was not able to not abdicate to Shùn, Shùn understood that the calendar calculations were upon himself and therefore did not dare not accept. Not able to not abdicate is serving Heaven’s timing. Not daring to not accept is fearing Heaven’s Mandate. Although the Hàn Court continues as the remnant of a final end of decline, yet it attends to serving Heaven’s Mandate to model after Yáo’s way, and therefore hopes to abdicate the Emperor’s throne and marry off two daughters. But Your Majesty right at the beginning of Great Wèi receiving the Mandate opposes the transcending integrity of Yú and Xià and esteems the declining and refusal of Yánlíng,  and so what is twisted is the large, what is straightened is the small, what is detailed is the light, what is rough is the heavy, even mediocre men and ordinary servicemen yet for Your Majesty disparage it. If the gone have awareness, then Chónghuá is certainly indignant and resentful in Cāngwú’s Shénmù,  Dà Yǔ is certainly melancholy and anxious in Kuàijī’s Shānyīn,  Wǔ-wáng is certainly displeased in Gāolíng’s Xuángōng.  Therefore We Your Servants dare to risk death to plead. Moreover Hàn’s governance was with the castrate eunuchs, fortunes had left the Emperor’s household for seven reigns,  and therefore there was the accumulation of arrows and stones in the Palace Halls, and so the two capitals became graves and ruins.  At that time, the Four Seas were swept away and overturned, Heaven’s Under divided and collapsed, Wǔ-wáng personally wore armor and donned helmet, bathed in rain and combed by wind, pleaded for the lives of the people, then saved the myriad states, for the world subdued the chaos, then delivering the rise of peace, assembled the people and established leaders, built offices and installed officials, person by person without faults who lost their previous enterprise yet began to have contributions to the Huáxià. Your Majesty succeeded the throne, radiantly shining culture and virtue, to complement the martial achievements, diligently giving relief to the people’s sufferings, treating them like the injured, the afraid you calmed, the labored you rested, the cold you warmed, the hungry you fed, the estranged by your virtue submitted, the enemies by your grace surrendered, spreading grace and planting virtue, radiance covering the four borders. In studying antiquity and sincere amiability, your abundance exceeds Fàngxūn; as a net releasing a boat swallower,  your generosity surpasses Zhōu Wén. Therefore when your spreading of governance has not yet been a year, humanity and divinity are both harmonized, August Heaven then sent down sweet dew and delivered the four spirituals,  Lordly Earth then grew up zhīcǎo  and spurted out sweet springs. Tigers and leopards and deer and hares, all white in color, pheasants and turtledoves and swallows and sparrows, also white in feathers, trees growing joined as one, melons sharing a core, fish of five colors, rare auspicious signs and objects, mixed together in between, none are not completely prepared.  The ancients had a saying: ‘Without Yǔ I would be a fish!’  Without Great Wèi, then We Your Servants would be white bones scattered across the wilderness. In prostration examining the exterior and interior various ministers’ beginning to end replies and memorials, the explanations and narrations of Your Majesty’s correspondence to the mandate, none are not of the Hé’s and Luò’s chart and document, according with the signs and verifications of Heaven and Earth, enabled by the Hàn Court’s authentic sincerity, announcing the myriad quarters’ admiring adherence, it can be said to be believable and proven. The Three Kings have nothing to compare, the Five Emperors have nothing to add.  The lives of the people have hung on Wèi’s country, the hearts of the people have been bound with Wèi’s government, for over thirty years. This then is the conjunction of a thousand ages of time arriving, the autumn of one encounter in ten thousand years. Transcending limits and broadening tolerance are appropriate to shine at this interval; restraint by small details should not be applied at this time. In the long delay of Heaven’s Mandate, the crime is on Us Your Servants. At once we build the platform stage, prepare the ritual ceremonies, select an auspicious day, clearly announce to the Vast Heavens Highest God, order the rituals of the various divinities, wait for the sacrifices to complete, gather the various bureaus at the Court Hall, discuss a Year Name, Standard Calendar, and uniform colors to put into effect, and send it up.”

Response Order said: “In the past Dà Shùn ate dried grains and wild grasses, about to do so to the end of his life ; this then was my former ambition. When he received Yáo’s abdication, he was covered in robes of furs, married [Yáo’s] two daughters, as if he intrinsically had them;  this then was obeying Heaven’s Mandate. The various Excellencies and Ministers and servicemen sincerely believe Heaven’s Mandate cannot be refused, the people’s hopes cannot be disobeyed, how can I yet decline?”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
相國歆、太尉詡、御史大夫朗及九卿奏曰：「臣等伏讀詔書，於邑益甚。臣等聞易稱聖人奉天時，論語云君子畏天命，天命有去就，然後帝者有禪代。是以唐之禪虞，命在爾躬，虞之順唐，謂之受終；堯知天命去己，故不得不禪舜，舜知曆數在躬，故不敢不受；不得不禪，奉天時也，不敢不受，畏天命也。漢朝雖承季末陵遲之餘，猶務奉天命以則堯之道，是以願禪帝位而歸二女。而陛下正於大魏受命之初，抑虞、夏之達節，尚延陵之讓退，而所枉者大，所直者小，所詳者輕，所略者重，中人凡士猶為陛下陋之。沒者有靈，則重華必忿憤于蒼梧之神墓，大禹必鬱悒于會稽之山陰，武王必不悅于（商）〔高〕陵之玄宮矣。是以臣等敢以死請。且漢政在閹宦，祿去帝室七世矣，遂集矢石於其宮殿，而二京為之丘墟。當是之時，四海蕩覆，天下分崩，武王親衣甲而冠冑，沐雨而櫛風，為民請命，則活萬國，為世撥亂，則致升平，鳩民而立長，築宮而置吏，元元無過，罔于前業，而始有造于華夏。陛下即位，光昭文德，以翊武功，勤恤民隱，視之如傷，懼者寧之，勞者息之，寒者以煖，飢者以充，遠人以（恩復）〔德服〕，寇敵以恩降，邁恩種德，光被四表；稽古篤睦，茂于放勛，網漏吞舟，弘乎周文。是以布政未期，人神並和，皇天則降甘露而臻四靈，后土則挺芝草而吐醴泉，虎豹鹿兔，皆素其色，雉鳩燕雀，亦白其羽，連理之木，同心之瓜，五采之魚，珍祥瑞物，雜遝於其間者，無不畢備。古人有言：『微禹，吾其魚乎！』微大魏，則臣等之白骨交橫于曠野矣。伏省群臣外內前後章奏，所以陳敘陛下之符命者，莫不條河洛之圖書，據天地之瑞應，因漢朝之款誠，宣萬方之景附，可謂信矣（省）〔著〕矣；三王無以及，五帝無以加。民命之懸於魏〔邦，民心之繫於魏〕政，三十有餘年矣，此乃千世時至之會，萬載一遇之秋；達節廣度，宜昭於斯際，拘牽小節，不施於此時。久稽天命，罪在臣等。輒營壇場，具禮儀，擇吉日，昭告昊天上帝，秩群神之禮，須禋祭畢，會群寮於朝堂，議年號、正朔、服色當施行，上。」復令曰：「昔者大舜飯糗茹草，將終身焉，斯則孤之前志也。及至承堯禪，被（珍）〔袗〕裘，妻二女，若固有之，斯則順天命也。群公卿士誠以天命不可拒，民望不可違，孤亦曷以辭焉？」
:::
:::

::: {.columns}
::: {.column width="70%"}
Gēngwǔ [220 Dec 10], conferment Edict on the King of Wèi said: “In the past Yáo matched Heaven in virtue, maintained the heaviness of the Six Directions,  but yet observed the calculations of the calendar fates had shifted to Yǒu Yú, entrusted and yielded the Emperor’s throne as suddenly as leaving a footprint. Now Heaven has already completed our Hàn’s mandate and thus turns to look north, the enterprise of Emperors and Imperials truly on Great Wèi. We maintain an empty title to seek ancient meanings, look toward past affairs, yet have shamed virtue, and so the King has modestly declined reaching to the third and fourth, and We are afraid. One who does not decline the throne of ten thousand chariots  is one who understands the Mandate and calculations of transcending limits. The lords of Yú and Xià occupied it without doubt, and therefore their accomplishments and exploits were bequeathed for ten thousand years, their beautiful reputation transmitted without end. Now send Observing Secretariat Writers Director Attendant Central [Wèi] Jì  to explain, that the King is to quickly ascend the Emperor’s throne, to follow the hearts of Heaven and Humanity, and complete Our great wish.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
庚午，冊詔魏王曰：「昔堯以配天之德，秉六合之重，猶睹曆運之數，移於有虞，委讓帝位，忽如遺跡。今天既訖我漢命，乃眷北顧，帝皇之業，實在大魏。朕守空名以竊古義，顧視前事，猶有慚德，而王遜讓至于三四，朕用懼焉。夫不辭萬乘之位者，知命達節之數也，虞、夏之君，處之不疑，故勳烈垂于萬載，美名傳于無窮。今遣守尚書令侍中（顗）〔覬〕喻，王其速陟帝位，以順天人之心，副朕之大願。」
:::
:::

::: {.columns}
::: {.column width="70%"}
Thereupon Secretariat Writers Director Huán Jiē and others memorialized stating: “Now the Hàn clan’s mandate has already four times arrived, yet Your Majesty beginning to end firmly declined. We Your Servants in prostration believe Highest God’s bequeathing on your sagely virtue, the prosperity of the allotted fate of Great Wèi, how has it only been for a few years? The Zhuàn says that Zhōu’s possession of Heaven’s Under was not on the morning of Jiǎzǐ and Yīn’s leaving of the Emperor’s throne was not on the day of Mùyě;  therefore the Shī in introducing Shāng Tāng traces his roots up to Xuán-wáng and in narrating Jī Zhōu goes up to record the birth of Hòu Jì,  and so their receiving of the mandate was already assured, their virtue did not waver. The Hàn clan has declined and fallen, their transition ended and already severed, the Three Celestials  bequeath their portents, the scribal offices have written the verifications, the aged elders recorded the divinations of former antiquity, the Hundred Surnames harmonize with the sound of songs and ballads. Your Majesty answers Heaven and receives the abdication, should quickly ascend the platform stage, burn sacrifices to Highest God, sincerely should not long delay the Divine Vessels and resist the wishes of the numerous millions. Your Servants at once send down to the Grand Scribe Director to select the inaugural time, that this moon’s twenty-ninth day [220 Dec 11] can be for ascending the platform to receive the mandate, and request an Edict on the kings and dukes and various ministers, and prepare articles on the ritual ceremonies in a separate memorial.”

Order said: “Permitted.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
於是尚書令桓階等奏曰：「今漢氏之命已四至，而陛下前後固辭，臣等伏以為上帝之臨聖德，期運之隆大魏，斯豈數載？傳稱周之有天下，非甲子之朝，殷之去帝位，非牧野之日也，故詩序商湯，追本玄王之至，述姬周，上錄后稷之生，是以受命既固，厥德不回。漢氏衰廢，行次已絕，三辰垂其徵，史官著其驗，耆老記先古之占，百姓協歌謠之聲。陛下應天受禪，當速即壇場，柴燎上帝，誠不宜久停神器，拒億兆之願。臣輒下太史令擇元辰，今月二十九日，可登壇受命，請詔王公群卿，具條禮儀別奏。」令曰：「可。」
:::
:::

:::

::: {.callout-note appearance="minimal"}

::: {.columns}
::: {.column width="70%"}
<a href="#source-21" id="annotation-21">[21]</a> Xiàn-dì zhuàn states: Xīnwèi [220 Dec 11], the King of Wèi ascended the platform and received the abdication, the Excellencies and Ministers, Ranked Marquesses, various Generals, Xiōngnú Chányú, Four Yí attenders of Court,  several tens of thousands of people in accompanying seats, burned sacrifices to Heaven and Earth, the Five Peaks, the Four Streams,  stating: “Imperial Emperor Your Servant [Cáo] Pī dares employ Dark Bull to announce to Huáng Huáng Hòu Dì:  Hàn has passed through reigns of twenty and four, tread through years of four hundred twenty and six,  the Four Seas are destitute and impoverished, the Three Networks not established,  the Five Latitudes interlocked in transition,  ominous and auspicious signs together seen. Those employing methods of calculation, considering the ancient ways, all believe the calendar calculations of Heaven have completed phase at this generation, all the various auspicious signs and intentions of the people and divinities show clearly the end of Yǒu Hàn’s  calculations completion and the signs of the Wèi House receiving the Mandate. The Hàn ruler believes the Divine Vessels should be conferred on Your Servant, following the example of Yǒu Yú, and conveys the throne to [me, Cáo] Pī. [I, Cáo] Pī tremble in fear of Heaven’s Mandate, though praised not praised.  The various Excellencies and many intendants and people of the Six Affairs,  outside with the officers and servicemen, reaching to the Mán-Yí chieftains,  all state: ‘Heaven’s Mandate cannot be declined and refused, the Divine Vessels cannot be long neglected, the various ministers cannot be without master, the myriad tasks cannot be without governance.’ [I, Cáo] Pī respectfully serve the Imperial images, dare I not respectfully serve? Divining by tortoise shell, the omen was Dà Héng.  Stalk divining by the Three Yì, the omen was the Gé omen.  Solemnly selecting an Inaugural Day, with the various bureaus ascending the platform to accept the Emperor’s Ruler’s Seal and Ribbon, announcing declaration to you Great Divinity: May you of divinity accept the sacrifices and forever bless the hopes of the millions of people, blessings on Yǒu Wèi  for generations to enjoy.” Therefore Regulation Edict on the Three Excellencies: “From when high antiquity first had lords, they certainly esteemed generous influence, to beautify social customs, so that the Hundred Surnames would obey teachings and that punishments and executions be set away. Now We continue the thread of Emperors and Kings, thus have Yánkāng Inaugural Year become Huángchū Inaugural Year, discuss revising the Standard Calendar, change uniform colors, distinguish insignia and titles, unify standards and measures, undertake the Earth Transition, Great Amnesty on Heaven’s Under. From the death penalty on down, all that are unsuitable to obtain pardon, all pardon and spare them.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔三〕　獻帝傳曰：辛未，魏王登壇受禪，公卿、列侯、諸將、匈奴單于、四夷朝者數萬人陪位，燎祭天地、五嶽、四瀆，曰：「皇帝臣丕敢用玄牡昭告于皇皇后帝：漢歷世二十有四，踐年四百二十有六，四海困窮，三綱不立，五緯錯行，靈祥並見，推術數者，慮之古道，咸以為天之曆數，運終茲世，凡諸嘉祥民神之意，比昭有漢數終之極，魏家受命之符。漢主以神器宜授於臣，憲章有虞，致位于丕。丕震畏天命，雖休勿休。群公庶尹六事之人，外及將士，洎于蠻夷君長，僉曰：『天命不可以辭拒，神器不可以久曠，群臣不可以無主，萬幾不可以無統。』丕祗承皇象，敢不欽承。卜之守龜，兆有大橫，筮之三易，兆有革兆，謹擇元日，與群寮登壇受帝璽綬，告類于爾大神；唯爾有神，尚饗永吉，兆民之望，祚于有魏世享。」遂制詔三公：「上古之始有君也，必崇恩化以美風俗，然百姓順教而刑辟厝焉。今朕承帝王之緒，其以延康元年為黃初元年，議改正朔，易服色，殊徽號，同律度量，承土行，大赦天下；自殊死以下，諸不當得赦，皆赦除之。」
:::
:::

::: {.columns}
::: {.column width="70%"}
Wèishì Chūnqiū states: The Emperor ascended the platform and the ritual completed, looking back he said to the various ministers: “The affairs of Shùn and Yǔ, I have experienced them.”

:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
魏氏春秋曰：帝升壇禮畢，顧謂群臣曰：「舜、禹之事，吾知之矣。」
:::
:::

::: {.columns}
::: {.column width="70%"}
Gān Bǎo’s Sōushénjì states: “Sòng Grandee Xíngshǐ Zǐchén  understood Heaven’s Way. Zhōu King Jìng’s Thirty-Seventh Year [483 BC], Duke Jǐng  inquired stating: “Heaven’s Way has what omens?” Replied stating: “Afterward in the Fifth Year Fifth Moon Dīnghài, I Your Servant will die. After I die in the Fifth Year Fifth Moon Dīngmǎo, Wú will be destroyed. After it is destroyed in the Fifth Year, you my lord will end. After you end in four hundred years, Zhū will rule Heaven’s Under.” Eventually it was all as he said. What it says of Zhū ruling Heaven’s Under was speaking of the rise of Wèi. Zhū was of the Cáo surname, Wèi also was of the Cáo surname, both were Zhū’s posterity.  The year calculation then is mistaken; it is unknown if Xíngshǐ erred in his calculation, or if the years and generations so far away that the copyists while transmitting had an error.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
干竇搜神記曰：宋大夫邢史子臣明於天道，周敬王之三十七年，景公問曰：「天道其何祥？」對曰：「後五（十）年五月丁亥，臣將死；死後五年五月丁卯，吳將亡；亡後五年，君將終；終後四百年，邾王天下。」俄而皆如其言。所云邾王天下者，謂魏之興也。邾，曹姓，魏亦曹姓，皆邾之後。其年數則錯，未知邢史失其數邪，將年代久遠，注記者傳而有謬也？
:::
:::

:::

## Huángchū 1 - 3 (220 - 222) {.unnumbered}

::: {.columns}
::: {.column width="70%"}
Huángchū Inaugural Year, Eleventh Moon, Guǐyǒu [220 Dec 13], used ten thousand households from Hénèi’s Shānyáng city to serve the Hàn Emperor as Duke of Shānyáng, to enact Hàn’s Standard Calendar, to use the Rituals of Heaven’s Son in Suburb Sacrifices, in sending up letter to not call himself a Servant, and when the capital had affairs in Tài Temple to be delivered sacrificial meat.  Enfeoffed four sons of the Duke as Ranked Marquesses.  Posthumously honored the late Imperial grandfather Tài-wáng as Tài Huángdì, late father Wǔ-wáng as Wǔ Huángdì, honored the Royal Dowager Queen as Imperial Dowager Empress.  Bestowed on adult males noble rank of level one, and those serving as their father’s posterity and those that were Filial-Fraternal and Diligent-Farmers level two.  Appointed Hàn’s vassal kings as Esteemed Virtue Marquesses, Ranked Marquesses as Inside the Passes Marquesses.  Converted Yǐngyīn’s Fányáng precinct to Fánchāng county.  Enfeoffed nobles and increased ranks each on distinct basis. Changed Chancellor of State to Excellency over the Masses, Censorate Grandee to Excellency of Works, Minister of Presentations to Minister of Ceremonies, Minister of Cadets to Minister of Staff, Minister Judge to Minister of Justice, Minister Agriculturalist to Minister of Agriculture.  Of the prefectures and states and counties and cities many were changed. Again conferred on the Xiōngnú Southern Chányú Hūchúquán a Wèi Ruler’s Seal and Ribbon,  bestowed an Azure Canopy Chariot, carriage sedan, treasure sword, jade annulus.
Twelfth Moon [221 Jan 11 – Feb 9], began construction of Luòyáng Palace, Wùwǔ [221 Jan 27], visited Luòyáng. <a href="#annotation-22" id="source-22">[22]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
黃初元年十一月癸酉，以河內之山陽邑萬戶奉漢帝為山陽公，行漢正朔，以天子之禮郊祭，上書不稱臣，京都有事于太廟，致胙；封公之四子為列侯。追尊皇祖太王曰太皇帝，考武王曰武皇帝，尊王太后曰皇太后。賜男子爵人一級，為父後及孝悌力田人二級。以漢諸侯王為崇德侯，列侯為關中侯。以潁陰之繁陽亭為繁昌縣。封爵增位各有差。改相國為司徒，御史大夫為司空，奉常為太常，郎中令為光祿勳，大理為廷尉，大農為大司農。郡國縣邑，多所改易。更授匈奴南單于呼廚泉魏璽綬，賜青蓋車、乘輿、寶劍、玉玦。十二月，初營洛陽宮，戊午幸洛陽。〔一〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-22" id="annotation-22">[22]</a> Your Servant Sōngzhī notes: Various books record that at the time the Emperor resided in the North Palace, in Jiànshǐ Hall held Court with the various ministers, the gates called Chéngmíng.  Chén King Sī [Cáo] Zhí’s poem stating “Visiting the Emperor in Chéngmíng house” was this.  Reaching the time of Emperor Míng, they first at Hàn’s South Palace’s Chóngdé Hall’s location raised Tàijí and Zhāoyáng various Halls. 
Wèi shū states: As Xià’s calculations followed Heaven, therefore continued to use the Xià Standard, but uniform colors esteemed Yellow. 
Wèi lüè states: Edict believed: Hàn was the Fire Transition, Fire dreads Water, and therefore “Luò” removed “water” and added “auspicious.” Wèi in the Transition Sequence is Earth. Earth is Water’s restraint, Water on obtaining Earth thus flows, Earth obtaining Water is then movable, and therefore remove “auspicious” and add “water,” change “Luò” to “Luò.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　臣松之案：諸書記是時帝居北宮，以建始殿朝群臣，門曰承明，陳思王植詩曰「謁帝承明廬」是也。至明帝時，始於漢南宮崇德殿處起太極、昭陽諸殿。魏書曰：以夏數為得天，故即用夏正，而服色尚黃。魏略曰：詔以漢火行也，火忌水，故「洛」去「水」而加「佳」。魏於行次為土，土，水之牡也，水得土而乃流，土得水而柔，故除「佳」加「水」，變「雒」為「洛」。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
That year, Cháng River Colonel Dài Líng  remonstrated that it was not appropriate to repeatedly go shooting and hunting, the Emperor was greatly furious. [Dài] Líng was spared the death penalty by one degree.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
是歲，長水校尉戴陵諫不宜數行弋獵，帝大怒；陵減死罪一等。
:::
:::

::: {.columns}
::: {.column width="70%"}
Second Year, Spring, Standard Moon [221 Feb 10 – Mar 10], Suburb Sacrifices to Heaven and Earth and at Míngtáng.  Jiǎxū [221 Feb 12], hunted reaching to Yuánlíng, sent envoy to offer Grand Offering to sacrifice to Hàn Shìzǔ.  Yǐhài [221 Feb 13], Morning Sun in the East Suburbs. <a href="#annotation-23" id="source-23">[23]</a> First ordered prefectures and states with population of at least ten thousand to each year nominate a Filial-Incorruptible [candidate] of one man; if there were any especially unusual, no restrictions based on population. Xīnsì [221 Feb 19], divided the Three Excellencies’ fiefs to enfeoff a junior relative, each one man, as a Ranked Marquess.  Rénwǔ [221 Feb 20], exempted Yǐngchuān prefecture one year’s field taxes. <a href="#annotation-24" id="source-24">[24]</a> Changed Xǔ county to Xǔchāng county.  Converted Wèi prefecture’s east part to Yángpíng prefecture, west part to Guǎngpíng prefecture. <a href="#annotation-25" id="source-25">[25]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
二年春正月，郊祀天地、明堂。甲戌，校獵至原陵，遣使者以太牢祠漢世祖。乙亥，朝日于東郊。〔一〕初令郡國口滿十萬者，歲察孝廉一人；其有秀異，無拘戶口。辛巳，分三公戶邑，封子弟各一人為列侯。壬午，復潁川郡一年田租。〔二〕改許縣為許昌縣。以魏郡東部為陽平郡，西部為廣平郡。〔三〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-23" id="annotation-23">[23]</a> Your Servant Sōngzhī believes: Heaven’s Son in the Spring Equinox has the Morning Sun, in the Autumn Equinox the Evening Moon. Observing that this year’s Standard Moon Suburb Sacrifices has a moon but no date and the Yǐhài Morning Sun then a date but no moon, probably there are missing characters. Note that Emperor Míng’s Morning Sun and Evening Moon were all as in Ritual writings, and therefore one knows that these Annals are in error.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　臣松之以為禮天子以春分朝日，秋分夕月；尋此年正月郊祀，有月無日，乙亥朝日，則有日無月，蓋文之脫也。案明帝朝日夕月，皆如禮文，故知此紀為誤者也。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-24" id="annotation-24">[24]</a> Wèi shū records the Edict stating: “Yǐngchuān was where the Former Emperor raised troops on campaign. In the Guāndù campaign, the Four Quarters were collapsing apart, far and near waiting and watching, but this prefecture held to righteousness, the young and strong carrying spears, the old and weak carrying grain. In the past Hàn Zǔ used Qín’s center as his state’s root, Guāng-Wǔ relied on Hénèi as his ruling foundation,  now We also here ascended the platform to receive the abdication, Heaven by this prefecture assisted the completion of Great Wèi.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　魏書載詔曰：「潁川，先帝所由起兵征伐也。官渡之役，四方瓦解，遠近顧望，而此郡守義，丁壯荷戈，老弱負糧。昔漢祖以秦中為國本，光武恃河內為王基，今朕復於此登壇受禪，天以此郡翼成大魏。」
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-25" id="annotation-25">[25]</a> Wèi lüè states: Changed Cháng’ān, Qiáo, Xǔchāng, Yè, Luòyáng to be the Five Capitals.  Set a stone boundary, the west bordering Yíyáng, the north following the Tàiháng [mountain range], the northeast bordering Yángpíng, the south following Lǔyáng, the east bordering Tán, to define the central capital region. Ordered that those in Heaven’s Under that moved within be exempted five years [taxation and conscription], later also increased this exemption.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔三〕　魏略曰：改長安、譙、許昌、鄴、洛陽為五都；立石表，西界宜陽，北循太行，東北界陽平，南循魯陽，東界郯，為中都之地。令天下聽內徙，復五年，後又增其復。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Edict said: “In the past Zhòngní possessed the talent of a great sage, held the capacity of Emperors and Kings, right at the end of declining Zhōu, without the fate of receiving the Mandate, was at the Courts of Lǔ and Wèi,  spreading teachings above the Zhū and Sì,  miserably and mournfully, hurriedly and anxiously, wishing to subdue himself to preserve the way, diminish his body to save the world. At the time of the Kings and Dukes in the end none were able to employ him, thus he withdrew and studied the rituals of five dynasties, cultivated the works of an unrecognized king, used the Lǔ shǐ to compile the Chūnqiū, met the Grand Preceptor and corrected the Yǎ and Sòng,  so that after a thousand years, none do not model after his writings in narration and composition, look up to his sagacity to achieve plans. Alas! He can be called a destined great sage, a teacher and model for a hundred million years. Encountering Heaven’s Under in Great Chaos, a hundred sacrifices were abandoned and destroyed, the temple of his old residence is damaged and not repaired, the posterity of Bāochéng is cut off and not inherited.  Quēlǐ does not hear the sounds of lectures and eulogies,  the four seasons do not see the seats of the Zhēng and Cháng.  How can this be called esteeming virtue and repaying achievement, raising the virtue that for a hundred generations must receive sacrifices? Thus appoint Consultant Cadet Kǒng Xiàn as Zōngshèng Marquess,  fief of a hundred households, to provide for Kǒng-zǐ’s sacrifices.” Ordered Lǔ prefecture to repair and rebuild the old temple, install a hundred households of clerks and soldiers to maintain and guard it, and also outside expanded and built residences to house scholars.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
詔曰：「昔仲尼資大聖之才，懷帝王之器，當衰周之末，無受命之運，在魯、衛之朝，教化乎洙、泗之上，悽悽焉，遑遑焉，欲屈己以存道，貶身以救世。于時王公終莫能用之，乃退考五代之禮，脩素王之事，因魯史而制春秋，就太師而正雅頌，俾千載之後，莫不宗其文以述作，仰其聖以成謀，咨！可謂命世之大聖，億載之師表者也。遭天下大亂，百祀墮壞，舊居之廟，毀而不脩，褒成之後，絕而莫繼，闕里不聞講頌之聲，四時不睹蒸嘗之位，斯豈所謂崇禮報功，盛德百世必祀者哉！其以議郎孔羨為宗聖侯，邑百戶，奉孔子祀。」令魯郡脩起舊廟，置百戶吏卒以守衛之，又於其外廣為室屋以居學者。
:::
:::

::: {.columns}
::: {.column width="70%"}
Third Moon [221 Apr 10 – May 9], added office to Liáodōng Administrator Gōngsūn Gōng as Chariots and Cavalry General.  First restored the wǔzhū coinage.  Summer, Fourth Moon [221 May 10 – Jun 7], appointed Chariots and Cavalry General Cáo Rén as General-in-Chief.
Fifth Moon [221 Jun 8 – Jul 7], Zhèng Gān again rebelled, sent Cáo Rén to suppress and beheaded him.
Sixth Moon [221 Jul 8 – Aug 5], Gēngzǐ [221 Jul 8], first sacrificed to the Five Peaks and Four Streams, ranked all the various sacrifices. <a href="#annotation-26" id="source-26">[26]</a> Dīngmǎo [221 Aug 4], the consort Zhēn-shì died.  Wùchén [221 Aug 5], last day of the moon, the sun was eclipsed, relevant managers memorialized to dismiss the Grand Commandant. Edict said: “The appearance of disastrous and strange omens is to reprimand the leading head.  To instead assign the fault to the legs and arms, how is it the righteousness of Yǔ and Tāng punishing themselves?  Thus Order the hundred offices to each be reverent in their duties, and afterward if there are faults in Heaven and Earth, do not again impeach the Three Excellencies.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
（春）三月，加遼東太守公孫恭為車騎將軍。初復五銖錢。夏四月，以車騎將軍曹仁為大將軍。五月，鄭甘復叛，遣曹仁討斬之。六月庚子，初祀五嶽四瀆，咸秩群祀。〔一〕丁卯，夫人甄氏卒。戊辰晦，日有食之，有司奏免太尉，詔曰：「災異之作，以譴元首，而歸過股肱，豈禹、湯罪己之義乎？其令百官各虔厥職，後有天地之眚，勿復劾三公。」
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-26" id="annotation-26">[26]</a> Wèi shū states: Jiǎchén [221 Jul 7], as the capital’s Ancestral Temples were not yet complete, the Emperor personally sacrificed to Wǔ Huángdì [Cáo Cāo] in Jiànshǐ Hall, personally bowing and carrying the food and libations, as in the Rituals to a family member.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書：甲辰，以京師宗廟未成，帝親祠武皇帝于建始殿，躬執饋奠，如家人之禮。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Autumn, Eighth Moon [221 Sep 5 – Oct 3], Sūn Quán sent envoy to present Response, and also sent Yú Jīn and others to return.  Dīngsì [221 Sep 23], sent Minister of Ceremonies Xíng Zhēn Holding Stave to appoint [Sūn] Quán as General-in-Chief, enfeoffed as King of Wú, applied the Nine Bestowments. 
Winter, Tenth Moon [221 Nov 3 – Dec 1], honored Yáng Biāo as Radiant Grandee. <a href="#annotation-27" id="source-27">[27]</a> As Grain was expensive, abolished the wǔzhū coinage. <a href="#annotation-28" id="source-28">[28]</a> Jǐmǎo [221 Dec 14], General-in-Chief Cáo Rén became Marshal-in-Chief.
Twelfth Moon [222 Jan 1 – Jan 29], traveled on eastern tour.
That year built Língyún Terrace.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
秋八月，孫權遣使奉章，并遣于禁等還。丁巳，使太常邢貞持節拜權為大將軍，封吳王，加九錫。冬十月，授楊彪光祿大夫。〔一〕以穀貴，罷五銖錢。〔二〕己卯，以大將軍曹仁為大司馬。十二月，行東巡。是歲築陵雲臺。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-27" id="annotation-27">[27]</a> Wèi shū states: Jǐhài [221 Nov 4], the Excellencies and Ministers held Court on the morning of the first day of the moon, together welcoming former Hàn Grand Commandant Yáng Biāo, treated with the Rituals for a guest. Edict said: “The Former Kings instituted the bestowments of table and cane, in order to use the Rituals for a guest for the yellowed and wrinkled, to honor and esteem foremost elders. In the past Kǒng Guāng and Zhuó Mào both for their admirable virtue and high years received these commendations and bestowments.  Your Excellency was formerly Hàn’s foremost minister, from your ancestors onward for generations famed in reputation and integrity, your years have passed seventy and your conduct without transgressions,  and can be said to be an aged and accomplished man, and should be distinctly favored to make clear your old virtues. Thus bestow on Your Excellency a Longevity Cane and Supporting Table.  On days of visiting and requesting, then use the cane to enter, and you also can use deer skin headdress.”  [Yáng] Biāo declined and would not listen, and indeed wore plain unlined robe and plain skin cap for meetings.

Xù Hànshū states: [Yáng] Biāo observed Hàn’s blessings were about to end, himself believed as [his family] for generations had been Three Excellencies, it would be disgraceful to be a Wèi minister, and therefore claimed leg cramps and no longer walked. After over ten years, the Emperor [Cáo Pī] ascended the King’s throne, wished to appoint him Grand Commandant, and ordered his close ministers to announce the intention. [Yáng] Biāo declined stating: “Having served the Hàn Court in the Three Excellencies, I encountered a world of decline and chaos and was not able to establish a chǐ or cùn of benefit. If I were to again be made a Wèi minister, for the selections of the state, it also would not be an honor.” The Emperor did not force his intentions. Huángchū Fourth Year [223], Edict appointed him Radiant Grandee, salaried Central Two Thousand dàn, in Court meetings seated second to the Three Excellencies, as by the precedent of Kǒng Guāng. [Yáng] Biāo sent up Response firmly declining, the Emperor did not listen, and also for his gates granted sawhorses,  conveyed clerks and soldiers, to especially honor him. At eighty-four years, in the Sixth Year [225] he died.

For his son [Yáng] Xiū see Chén Sī-wáng zhuàn. 
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書曰：己亥，公卿朝朔旦，并引故漢太尉楊彪，待以客禮，詔曰：「夫先王制几杖之賜，所以賓禮黃耇褒崇元老也。昔孔光、卓茂皆以淑德高年，受茲嘉錫。公故漢宰臣，乃祖已來，世著名節，年過七十，行不踰矩，可謂老成人矣，所宜寵異以章舊德。其賜公延年杖及馮几；謁請之日，便使杖入，又可使著鹿皮冠。」彪辭讓不聽，竟著布單衣、皮弁以見。續漢書曰：彪見漢祚將終，自以累世為三公，恥為魏臣，遂稱足攣，不復行。積十餘年，帝即王位，欲以為太尉，令近臣宣旨。彪辭曰：「嘗以漢朝為三公，值世衰亂，不能立尺寸之益，若復為魏臣，於國之選，亦不為榮也。」帝不奪其意。黃初四年，詔拜光祿大夫，秩中二千石，朝見位次三公，如孔光故事。彪上章固讓，帝不聽，又為門施行馬，致吏卒，以優崇之。年八十四，以六年薨。子脩，事見陳思王傳。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-28" id="annotation-28">[28]</a> Wèi shū states: Eleventh Moon [221 Dec 2 – Dec 31], Xīnwèi [221 Dec 6], Defending West General Cáo Zhēn  ordered his multitudes and officers with the provincial and prefecture soldiers to suppress and defeated the Hú [leaders] Zhìyuánduō, Lúshuǐ, Fēngshǎng and others,  cutting off the heads of over fifty thousand, capturing alive a hundred thousand, sheep of one million one hundred ten thousand, cattle of eighty thousand, the Hé’s west was therefore pacified. The Emperor had previously heard that the Hú had breached the river to flood Xiǎnměi,  and said to his Left and Right and various officers saying: “In the past Wěi Áo flooded Lüèyáng and so Guāng-Wǔ took advantage of his weariness and advanced soldiers to exterminate him.  Now the Hú breach the river to flood Xiǎnměi, this situation is exactly in resemblance, report of defeating the Hú will now arrive before long.” In ten days, dispatch reporting the defeat of the Hú arrived, the Superior greatly laughed and said: “I strategized it within the curtains, the various officers exerted and struck across ten thousand lǐ, the mutual correspondence like fitting a tally and stave.  Beginning to end in battle successes and capturing of caitiffs, there has never been any like this.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　魏書曰：十一月辛未，鎮西將軍曹真命眾將及州郡兵討破叛胡治元多、盧水、封賞等，斬首五萬餘級，獲生口十萬，羊一百一十一萬口，牛八萬，河西遂平。帝初聞胡決水灌顯美，謂左右諸將曰：「昔隗囂灌略陽，而光武因其疲弊，進兵滅之。今胡決水灌顯美，其事正相似，破胡事今至不久。」旬日，破胡告檄到，上大笑曰：「吾策之於帷幕之內，諸將奮擊於萬里之外，其相應若合符節。前後戰克獲虜，未有如此也。」
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Third Year, Spring, Standard Moon [222 Jan 30 – Feb 28], Bǐngyín [222 Jan 30], first day of the moon, the sun was eclipsed. Gēngwǔ [221 Feb 3], traveled to visit Xǔchāng Palace. Edict said: “The calculations and filial  of the present are the tribute of servicemen of antiquity. ‘In a town of ten households, certainly there are those of loyalty and faith.’  If there is a limitation by age and only afterward a seeking of servicemen, then Lǚ Shàng and Zhōu Jìn would not have been famed in previous generations.  Thus Order that the prefectures and states in their selections are not to be constrained by old age or youth. Classicists who understand the classics and arts, clerks who comprehend literature and law, on arriving are all to be tested in employment. Relevant managers are to investigate and cite those not genuine.” <a href="#annotation-29" id="source-29">[29]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
三年春正月丙寅朔，日有蝕之。庚午，行幸許昌宮。詔曰：「今之計、（考）〔孝〕，古之貢士也；十室之邑，必有忠信，若限年然後取士，是呂尚、周晉不顯於前世也。其令郡國所選，勿拘老幼；儒通經術，吏達文法，到皆試用。有司糾故不以實者。」〔一〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-29" id="annotation-29">[29]</a> Wèi shū states: Guǐhài,  Sūn Quán sent up letter to explain: “Liú Bèi’s branch faction of forty thousand men, horses of two to three thousand, have set out Zǐguī.  I request to go sweep them away, to use victory as my contribution.” The Emperor’s reply said: “In the past in Wěi Áo’s destruction, the disaster came from Xúnyì, in [Gōngsūn Shù] Zǐyáng’s capture, the change rose at Hàn’guān.  General, you will exert yourself to raise military power, strive to enact exceptional achievements, to accord with my intentions.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書曰：癸亥，孫權上書，說：「劉備支黨四萬人，馬二三千匹，出秭歸，請往掃撲，以克捷為效。」帝報曰：「昔隗囂之弊，禍發栒邑，子陽之禽，變起扞關，將軍其亢厲威武，勉蹈奇功，以稱吾意。」
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Second Moon [222 Mar 1 – Mar 29], the Shànshàn, Qiūcí, and Yútián Kings each sent envoys to present tribute.  Edict said: “The Western Róng submitting to obedience, the Dī and Qiāng coming to the King, the Shī and Shū eulogized these. Recently the Western Regions outer Yí together thumped at the passes to inwardly submit, <a href="#annotation-30" id="source-30">[30]</a> thus send envoys to show appreciation for their labors.” From this afterward the Western Regions were therefore connected, installed a Wùjǐ Colonel.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
二月，鄯善、龜茲、于闐王各遣使奉獻，詔曰：「西戎即敘，氐、羌來王，詩、書美之。頃者西域外夷並款塞內附，〔一〕其遣使者撫勞之。」是後西域遂通，置戊己校尉。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-30" id="annotation-30">[30]</a> Yīng Shào’s Hàn shū zhù states: Thumped is knocked. All knocked at the pass gates to come submit to obedience.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　應劭漢書注曰：款，叩也；皆叩塞門來服從。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Third Moon [222 Mar 30 – Apr 28], Yǐchǒu [222 Mar 30], enthroned the Duke of Qí [Cáo] Ruì as King of Píngyuán, and the Emperor’s younger brothers the Duke of Yānlíng [Cáo] Zhāng and others of eleven men all as Kings.  First set the system of enfeoffing the King’s non-successor sons as Dukes of villages, successor King’s non-successor sons as Marquesses of precincts, Duke’s non-successor sons as Earls of precincts. Jiǎxū [222 Apr 8], enthroned Imperial son [Cáo] Lín as King of Hédōng.  Jiǎwǔ [222 Apr 28], traveled to visit Xiāngyì. 

Summer, Fourth Moon [222 Apr 29 – May 27], Wùshēn [222 May 12], enthroned the Marquess of Juànchéng [Cáo] Zhí as King of Juànchéng.  Guǐhài [222 May 27], traveled to return to Xǔchāng Palace.

Fifth Moon [222 May 28 – June 26], used Jīng’s and Yáng’s eight prefectures beyond the Jiāng to form Jīng Province, in order to designate Sūn Quán as its Governor; Jīng Province’s various prefectures north of the Jiāng became Yǐng Province. 
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
三月乙丑，立齊公叡為平原王，帝弟鄢陵公彰等十一人皆為王。初制封王之庶子為鄉公，嗣王之庶子為亭侯，公之庶子為亭伯。甲戌，立皇子霖為河東王。甲午，行幸襄邑。夏四月戊申，立鄄城侯植為鄄城王。癸亥，行還許昌宮。五月，以荊、揚、江表八郡為荊州，孫權領牧故也；荊州江北諸郡為郢州。
:::
:::

::: {.columns}
::: {.column width="70%"}
Intercalary Moon [222 July 26 – Aug 24], Sūn Quán defeated Liú Bèi at Yílíng.  Previously, the Emperor had heard that [Liú] Bèi’s troops had gone east downstream, with [Sūn] Quán engaging in battle, planting fences to link camps over seven hundred lǐ, and said to the various ministers: “[Liú] Bèi does not understand warfare. How can camps spread seven hundred lǐ be able to repel an enemy? Those who position their armies in vegetation and marshes and difficult terrain will be taken by the enemy. This is what warfare dreads. Sūn Quán sending up report will now arrive.” Seven days later, letter of defeating [Liú] Bèi arrived.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
閏月，孫權破劉備于夷陵。初，帝聞備兵東下，與權交戰，樹柵連營七百餘里，謂群臣曰：「備不曉兵，豈有七百里營可以拒敵者乎！『苞原隰險阻而為軍者為敵所禽』，此兵忌也。孫權上事今至矣。」後七日，破備書到。
:::
:::

::: {.columns}
::: {.column width="70%"}
Autumn, Seventh Moon [222 Aug 25 – Sep 23], Jì Province great locusts outbreak, the people starved, sent Secretariat Writer Dù Jī  Holding Stave to open the granaries to relieve them.

Eighth Moon [222 Sep 24 – Oct 22], Shǔ chief officer Huáng Quán led his multitudes to surrender. <a href="#annotation-31" id="source-31">[31]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
秋七月，冀州大蝗，民饑，使尚書杜畿持節開倉廩以振之。八月，蜀大將黃權率眾降。〔一〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-31" id="annotation-31">[31]</a> Wèi shū states: [Huáng] Quán with designate Nán prefecture Administrator Shǐ Hé  and others of three hundred eighteen people went to the Jīng Province Inspector to present up their false seals and ribbons, tallies and halberds, banners and flags, ivory gates, and drum chariots. [Huáng] Quán and the rest went to visit where [Cáo Pī] was traveling, the Emperor set alcohol and posted musicians, summoning them to meet at Chéngguāng Hall.  [Huáng] Quán, [Shǐ] Hé and the rest person by person advanced to introduce themselves, the Emperor with them discussed and conversed on the determination of army success or failure and leaving or arriving, of the various officers none were not pleased. Bestowed on [Huáng] Quán gold and silk, chariots and horses, robes and furs, curtains and tents, wives and concubines, down reaching to the Auxiliary and Supplemental [Generals], all on distinct basis. Appointed [Huáng] Quán as Attendant Central, Defending South General, enfeoffed a Ranked Marquess, and that day summoned and sent him a carriage of four horses; also enfeoffed Shǐ Hé and others of forty-two men all as Ranked Marquesses, those that became Generals or Cadet Generals were over a hundred men.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書曰：權及領南郡太守史郃等三百一十八人，詣荊州刺史奉上所假印綬、棨戟、幢麾、牙門、鼓車。權等詣行在所，帝置酒設樂，引見于承光殿。權、郃等人人前自陳，帝為論說軍旅成敗去就之分，諸將無不喜悅。賜權金帛、車馬、衣裘、帷帳、妻妾，下及偏裨皆有差。拜權為侍中鎮南將軍，封列侯，即日召使驂乘；及封史郃等四十二人皆為列侯，為將軍郎將百餘人。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Ninth Moon [222 Oct 23 – Nov 21], Jiǎwǔ [222 Oct 25], Edict said: “Women participating in government is the root of chaos. From now on afterward, the various ministers are not to memorialize affairs to the Dowager Empress, the families of the empress’s clan are not to hold appointments of assisting in governing,  and also are not to unreasonably receive noble ranks of reeds and soil. Have this Edict passed to later generations. If there are violations, Heaven’s Under is to together punish it.” <a href="#annotation-32" id="source-32">[32]</a> Gēngzǐ [222 Oct 31], enthroned as Imperial Empress Guō-shì.  Bestowed on Heaven’s Under’s adult males noble ranks at level two, on widowers and widowed and the seriously incapacitated and the poor and unable to support themselves bestowed grain.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
九月甲午，詔曰：「夫婦人與政，亂之本也。自今以後，群臣不得奏事太后，后族之家不得當輔政之任，又不得橫受茅土之爵；以此詔傳後世，若有背違，天下共誅之。」〔一〕庚子，立皇后郭氏。賜天下男子爵人二級；鰥寡篤癃及貧不能自存者賜穀。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-32" id="annotation-32">[32]</a> Sūn Shèng states: The administering of states and managing of governance certainly relies on the support of the eminent and wise, worthy transcendence and good virtue must reside in appointments of participating in governance. Therefore, even in the flourishing of the Zhōu House, there were women participating. In that case, the Earthly  way supports Heaven, those facing south are not two,  the courtesy of the Three Followings is called as utmost compliance.  As for commanding orders through Heaven’s Son, controlling the enactment of memorialized affairs, these are not of the ancient principles.  In the past Shēn and Lǚ truly rectified Yǒu Zhōu.  If one takes Heaven’s Under as heart and only virtue is used, then in the conferment of the close or the distant, utmost impartiality is universal, and why must one reach to the Empress’s clan and necessarily expel and distance them? In the final reigns of the Two Hàn, the king’s way had declined, and therefore caused the in-law relations to rely on favor to hold office and disorder rankings. At these times of confusing ways and decline, the fated blessings about to shift, even if there are no troubles of Wáng or Lǚ,  how is there a lack of disasters of Tián and Zhào?  But if later generations observe things like this, they will deeply consider the warnings of toxic poisons. As for Wèi Wén [Cáo Pī], he then issued an Edict without exceptions, it can be said to be the blunt words of one having knowledge, not the profound considerations of an Emperor.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　孫盛曰：夫經國營治，必憑俊哲之輔，賢達令德，必居參亂之任，故雖周室之盛，有婦人與焉。然則坤道承天，南面罔二，三從之禮，謂之至順，至於號令自天子出，奏事專行，非古義也。昔在申、呂，實匡有周。苟以天下為心，惟德是杖，則親疏之授，至公一也，何至后族而必斥遠之哉？二漢之季世，王道陵遲，故令外戚憑寵，職為亂階。（於）此自時昏道喪，運祚將移，縱無王、呂之難，豈乏田、趙之禍乎？而後世觀其若此，深懷酖毒之戒也。至于魏文，遂發一概之詔，可謂有識之爽言，非帝者之宏議。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Winter, Tenth Moon [222 Nov 22 – Dec 20] Jiǎzǐ [222 Nov 24], specified Shǒuyáng mountain’s east as his funerary tomb, composed the Final Regulations  stating: “By Ritual, when the state’s lord ascends the throne he makes his ellipse <a href="#annotation-33" id="source-33">[33]</a> to while living not forget death. <a href="#annotation-34" id="source-34">[34]</a> In the past Yáo was buried at Gǔlín, completely covered by the trees; Yǔ was buried at Kuàijī, the farmers did not change fields. <a href="#annotation-35" id="source-35">[35]</a> Therefore burial in mountains and woods then is to merge with the mountains and woods. The systems of mounds and trees  is not of high antiquity, I will not have it. The funerary tomb will use the mountain as body, without mound or trees, without establishment of a Resting Hall, building of Park Village, or connecting of a Spirit Road.  To bury is to hide, to wish people be unable to see. Bones are without awareness of pain or itch; burial mounds are not the residence of an inhabiting spirit. Ritual is to not offer sacrifices at the grave, wishing for the surviving and the perished to not be desecrated. Make the coffin and casing sufficient to decay the bones, the burial clothes sufficient to decay the flesh and nothing more. Therefore I build at this land of desolate hills without food, wishing that after a change in dynasties that none know its location. Do not apply reeds and ash,  do not store gold or silver or copper or iron, entirely use pottery, in accordance with the meaning of the clay chariots and straw effigies of antiquity.  The coffin is only to lacquer the juncture meetings in three passes, the mouth is not to contain pearls or jade, do not apply pearl jacket or jade casing; these all are the doings of foolish and crude customs .  When the Jìsūn used jade gems in burial, Kǒng-zǐ went up the steps and rescued the situation, describing it as exposing the body in the central plains.  When the Duke of Sòng was lavishly buried, noble men said Huà Yuán and Yuè Jǔ were not proper servants, believing it abandoning their lord to evil.  That Hàn Emperor Wén was not excavated was because Bàlíng had nothing to seek.  That Guāng-Wǔ was dug up was because Yuánlíng had mound and trees.  In the preservation of Bàlíng, the achievement was on [Zhāng] Shìzhī.  In the digging up of Yuánlíng, the crime was on [Hàn] Emperor Míng.  It was [Zhāng] Shìzhī’s loyalty that benefited his lord, Emperor Míng’s love that harmed his parent. A loyal servant and filial son should think of the words of Zhòngní, [Zuǒ] Qiūmíng, [Zhāng] Shìzhī,  and reflect on the warnings of Huà Yuán, Yuè Jǔ, Emperor Míng. Preservation is how to secure lord and settle parent, to enable the soul for ten thousand years to be without danger; this then is the loyalty and filial piety of worthies and sages. From antiquity to the present, there has never been a state that did not perish, and also no grave that was not dug up. From since the death and chaos onward, of the Hàn clan’s various tombs none were not excavated and dug up, going as far as to burn to extract the jade cases and gold threads, the skeletal bones completely destroyed. This punishment of burning, how is it not a heavy sorrow? The disaster comes from lavish burial and mounds and trees. ‘Sāng and Huò are my warnings,’  is it not also clear? As for the Imperial Empress and Noble Ladies on down, for those that accompany a king to their state,  on death all are to be buried to the mountain stream’s west, previously also having specified the location. Probably when Shùn was buried at Cāngwú, his two consorts did not accompany him. Yánlíng buried his son far away at Yíng and Bó.  If the soul has awareness, nowhere it cannot reach. The separation of one mountain stream is not enough to be considered far away. If there is violation of the present Edict, rashly making any changes or revisions in the construction or implementation, I will be killed and desecrated below the ground, killed and yet again killed, dead and yet again dead. A servant or son who disregards their dead lord or father is not loyal and not filial. If the dead have awareness they will not bless you. Thus have this Edict stored in the Ancestral Temple, copies in the Secretariat Writers, Confidential Writers, and Three Offices.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
冬十月甲子，表首陽山東為壽陵，作終制曰：「禮，國君即位為椑，〔一〕存不忘亡也。〔二〕昔堯葬穀林，通樹之，禹葬會稽，農不易畝，〔三〕故葬於山林，則合乎山林。封樹之制，非上古也，吾無取焉。壽陵因山為體，無為封樹，無立寢殿，造園邑，通神道。夫葬也者，藏也，欲人之不得見也。骨無痛痒之知，冢非棲神之宅，禮不墓祭，欲存亡之不黷也，為棺槨足以朽骨，衣衾足以朽肉而已。故吾營此丘墟不食之地，欲使易代之後不知其處。無施葦炭，無藏金銀銅鐵，一以瓦器，合古塗車、芻靈之義。棺但漆際會三過，飯含無以珠玉，無施珠襦玉匣，諸愚俗所為也。季孫以璵璠斂，孔子歷級而救之，譬之暴骸中原。宋公厚葬，君子謂華元、樂莒不臣，以為棄君於惡。漢文帝之不發，霸陵無求也；光武之掘，原陵封樹也。霸陵之完，功在釋之；原陵之掘，罪在明帝。是釋之忠以利君，明帝愛以害親也。忠臣孝子，宜思仲尼、丘明、釋之之言，鑒華元、樂莒、明帝之戒，存於所以安君定親，使魂靈萬載無危，斯則賢聖之忠孝矣。自古及今，未有不亡之國，亦無不掘之墓也。喪亂以來，漢氏諸陵無不發掘，至乃燒取玉匣金縷，骸骨并盡，是焚如之刑，豈不重痛哉！禍由乎厚葬封樹。『桑、霍為我戒』，不亦明乎？其皇后及貴人以下，不隨王之國者，有終沒皆葬澗西，前又以表其處矣。蓋舜葬蒼梧，二妃不從，延陵葬子，遠在嬴、博，魂而有靈，無不之也，一澗之閒，不足為遠。若違今詔，妄有所變改造施，吾為戮尸地下，戮而重戮，死而重死。臣子為蔑死君父，不忠不孝，使死者有知，將不福汝。其以此詔藏之宗廟，副在尚書、祕書、三府。」
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-33" id="annotation-33">[33]</a> Ellipse [bì] is pronounced Fú and Lì together.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕椑音扶歷反。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-34" id="annotation-34">[34]</a> Your Servant Sōngzhī notes: By Ritual, the coffins of Heaven’s Son and vassal lords each have multiple layers. The coffin closest to the body is called the ellipse.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　臣松之按：禮，天子諸侯之棺，各有重數；棺之親身者曰椑。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-35" id="annotation-35">[35]</a> Lǚshì Chūnqiū: Yáo was buried at Gǔlín, completely covered by the trees; Shùn was buried at Jì, the market places did not change their shops; Yǔ was buried at Kuàijī, not changing the people’s walking.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔三〕　呂氏春秋：堯葬于穀林，通樹之；舜葬于紀，市廛不變其肆；禹葬會稽，不變人徒。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
That Moon, Sūn Quán again rebelled.  Reverted Yǐng Province to Jīng Province. The Emperor from Xǔchāng campaigned south, the various armies and soldiers together advanced, [Sūn] Quán overlooked the Jiāng to resist and defend.

Eleventh Moon [222 Dec 21 – 223 Jan 19], Xīnchŏu [222 Dec 31], traveled to visit Yuān.  Gēngshēn [223 Jan 19], the last day of the moon, the sun was eclipsed.

That year, dug Língzhī pond.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
是月，孫權復叛。復郢州為荊州。帝自許昌南征，諸軍兵並進，權臨江拒守。十一月辛丑，行幸宛。庚申晦，日有食之。是歲，穿靈芝池。
:::
:::


## Huángchū 4 - 6 (223 - 225) {.unnumbered}

::: {.columns}
::: {.column width="70%"}
Fourth Year, Spring, Standard Moon [223 Feb 18 – Mar 19], Edict said: “Since the death and chaos onward, weapons and armor are not yet put away, the people of Heaven’s Under killing one another. Now Within the Seas is beginning to be settled, anyone that dares take private revenge will all be clan exterminated.” Built Nánxún Terrace at Yuān. 
Third Moon [223 Apr 18 – May 17], Bǐngshēn [223 Apr 25], traveled from Yuān back to Luòyáng Palace. Guǐmǎo [223 May 2], the moon crossed Xīn’s center large star. <a href="#annotation-36" id="source-36">[36]</a> Dīngwèi [223 May 6], Marshal-in-Chief Cáo Rén died. That moon, great plague.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
四年春正月，詔曰：「喪亂以來，兵革未戢，天下之人，互相殘殺。今海內初定，敢有私復讎者皆族之。」築南巡臺于宛。三月丙申，行自宛還洛陽宮。癸卯，月犯心中央大星。〔一〕丁未，大司馬曹仁薨。是月大疫。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-36" id="annotation-36">[36]</a> Wèi shū records the Bǐngwǔ [223 May 5] Edict stating: “Sūn Quán oppresses and harms the people, We believe banditry cannot [be allowed to] spread, and therefore separately mandated fierce officers on three roads to together campaign. Now the Campaigning East various armies with [Sūn] Quán’s faction’s Lǚ Fàn and others battled on the rivers, then cutting off heads of forty thousand, capturing boats of ten thousand.  The Marshal-in-Chief occupies and defends Rúxū, those killed and captured also in the tens of thousands.  The Central Army and Campaigning South attack and besiege Jiānglíng,  Left General Zhāng Hé and others on sterns and bows directly cross, striking their southern islets, the rebels that fled into the rivers and drowned to death were several thousand men.  Also making tunnels to attack the city, inside and outside the city sparrows and mice are not able to exit or enter, this is only served up meat on a table! But among the rebels there is plague and disease, spreading on both sides of the Jiāng and smearing the ground, and one fears cross-contamination. In the past Zhōu Wǔ attacked Yīn and turned back the brigades at Mèngjīn,  Hàn Zǔ campaigned against Wěi Áo and returned the army to Gāopíng,  both understanding Heaven’s timing and measuring the enemy’s condition. Moreover Chéng Tāng opened three sides of a net and Heaven’s Under submitted to the benevolence.  Now lift the siege of Jiānglíng, to delay the taking of the already dead. For the time being rest the labor campaigns, cease and reduce conscription and garrisons, nurture and raise the servicemen and civilians, have all securely rest.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書載丙午詔曰：「孫權殘害民物，朕以寇不可長，故分命猛將三道並征。今征東諸軍與權黨呂範等水戰，則斬首四萬，獲船萬艘。大司馬據守濡須，其所禽獲亦以萬數。中軍、征南，攻圍江陵，左將軍張郃等舳艫直渡，擊其南渚，賊赴水溺死者數千人，又為地道攻城，城中外雀鼠不得出入，此几上肉耳！而賊中癘氣疾病，夾江塗地，恐相染污。昔周武伐殷，旋師孟津，漢祖征隗囂，還軍高平，皆知天時而度賊情也。且成湯解三面之網，天下歸仁。今開江陵之圍，以緩成死之禽。且休力役，罷省繇戍，畜養士民，咸使安息。」
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Summer, Fifth Moon [223 June 16 – July 15], there were pelican birds gathering at Língzhī pond. Edict said: “This is what the poets called ‘dirtied marsh,’  the Cáo ode’s criticizing Duke Gōng as distancing from noble men and drawing close to petty men.  Now are there worthy and wise servicemen occupying low positions? If not, then why did the birds arrive? Thus broadly nominate Heaven’s Under’s eminent and virtuous abundant talents and solitary noble men, to answer the Cáo men’s criticism.” <a href="#annotation-37" id="source-37">[37]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
夏五月，有鵜鶘鳥集靈芝池，詔曰：「此詩人所謂污澤也。曹詩『刺恭公遠君子而近小人』，今豈有賢智之士處於下位乎？否則斯鳥何為而至？其博舉天下雋德茂才、獨行君子，以答曹人之刺。」〔一〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-37" id="annotation-37">[37]</a> Wèi shū states: Xīnyǒu [223 Jul 19], relevant managers memorialized to construct two temples, to establish Tài Huángdì [Cáo Sōng] Temple, with the Chief Prolonging Autumn Specially Advanced Marquess [Cáo Téng] and the great-great-grandfather [Cáo Mēng] in combined sacrifices, and when degree of relation was exhausted to demolish in order, and to specially establish Wǔ Huángdì Temple, in the four seasons enjoying sacrifices, as Wèi Tàizǔ, for ten thousand years to not be demolished.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書曰：辛酉，有司奏造二廟，立太皇帝廟，大長秋特進侯與高祖合祭，親盡以次毀；特立武皇帝廟，四時享祀，為魏太祖，萬載不毀也。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Sixth Moon [223 July 16 – Aug 13], Jiǎxū [223 Aug 1], the King of Rènchéng [Cáo] Zhāng died in the capital.  Jiǎshēn [223 Aug 11], Grand Commandant Jiǎ Xǔ died. Tàibái during daytime was seen. That moon heavy rain, the Yī and Luò overflowed, killing people and destroying houses. <a href="#annotation-38" id="source-38">[38]</a> Autumn, Eighth Moon [223 Sep 13 – Oct 11], Dīngmǎo [223 Sep 23], appointed Minister of Justice Zhōng Yáo as Grand Commandant. <a href="#annotation-39" id="source-39">[39]</a> Xīnwèi [223 Sep 27], inspection hunt at Xíngyáng, then toured the east.  Discussed the achievements of the campaign against Sūn Quán, the various officers on down were advanced in noble rank and increased in fief revenue each on distinct basis.
Ninth Moon [223 Oct 12 – Nov 10], Jiǎchén [223 Oct 30], traveled to visit Xǔchāng Palace. <a href="#annotation-40" id="source-40">[40]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
六月甲戌，任城王彰薨於京都。甲申，太尉賈詡薨。太白晝見。是月大雨，伊、洛溢流，殺人民，壞廬宅。〔一〕秋八月丁卯，以廷尉鍾繇為太尉。〔二〕辛未，校獵于滎陽，遂東巡。論征孫權功，諸將已下進爵增戶各有差。九月甲辰，行幸許昌宮。〔三〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-38" id="annotation-38">[38]</a> Wèi shū states: Seventh Moon [223 Aug 14 – Sep 12], Yǐwèi [223 Aug 22], the main army was about to set out, sent the Minister of Ceremonies with bull ox of one to report and sacrifice in the suburbs. 

Your Servant Sōngzhī notes: Within a memorial on Wèi’s Suburb Sacrifices, Secretariat Writer Lú Yù  commented on sacrifices for matters of danger and calamity saying: “Furnish sacrificial animal and sacrificial vessels, like in the ritual of the beginning to end brigades setting out being reported in the suburbs.” According to this, then when the Wèi dynasty sent out the brigades all were reported in the suburbs.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書曰：七月乙未，大軍當出，使太常以特牛一告祠于郊。臣松之按：魏郊祀奏中，尚書盧毓議祀厲殃事云：「具犧牲祭器，如前後師出告郊之禮。」如此，則魏氏出師，皆告郊也。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-39" id="annotation-39">[39]</a> Wèi shū states: Relevant managers memorialized to revise the Hàn dynasty’s Ancestral Temple’s Ānshì Music to Zhèngshì Music, Jiāzhì Music to Yínglíng Music, Wǔdé Music to Wǔsòng Music, Zhāoróng Music to Zhāoyè Music, Yúnqiáo Dance to Fèngxiáng Dance, Yùmìng Dance to Língyīng Dance, Wǔdé Dance to Wǔsòng Dance, Wénshǐ Dance to Dàsháo Dance, Wǔxíng Dance to Dàwǔ Dance.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　魏書曰：有司奏改漢氏宗廟安世樂曰正世樂，嘉至樂曰迎靈樂，武德樂曰武頌樂，昭容樂曰昭業樂，雲（翻）〔翹〕舞曰鳳翔舞，育命舞曰靈應舞，武德舞曰武頌舞，文（昭）〔始〕舞曰大（昭）〔韶〕舞，五行舞曰大武舞。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-40" id="annotation-40">[40]</a> Wèi shū states: Twelfth Moon [224 Jan 9 – 224 Feb 7], Bǐngyín [224 Jan 20], bestowed on the Duke of Shānyáng’s consort [Cáo Jié] Tāngmùyì and the Duke’s daughter [Liú] Màn as Chánglè prefecture Princess, fief of each five hundred households.  That winter, Sweet Dew fell in Fānglín Garden. 

Your Servant Sōngzhī notes: Fānglín Garden is the present Huálín Garden. When the King of Qí [Cáo] Fāng succeeded the throne, it was changed to Huálín.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔三〕　魏書曰：十二月丙寅，賜山陽公夫人湯沐邑，公女曼為長樂郡公主，食邑各五百戶。是冬，甘露降芳林園。臣松之按：芳林園即今華林園，齊王芳即位，改為華林。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Fifth Year, Spring, Standard Moon [224 Feb 8 – Mar 7], first ordered that only for cases of plotting treason and great rebellion would there be permission to report on one another, all other cases would not be heard and judged; any that dared falsely report on another would be punished by the accused crime. 
Third Moon [224 Apr 7 – May 5], traveled from Xǔchāng back to Luòyáng Palace.
Summer, Fourth Moon [224 May 6 – Jun 4], established the Grand Academy,  set the methods for the courses and examinations on the Five Classics, installed Chūnqiū Gǔliáng Academic Scholars. 
Fifth Moon [224 June 5 – Jul 3], relevant managers believed as the Excellencies and Ministers held Court on the first days of the new moons they should take advantage to memorialize on doubtful affairs, listen and judge on great governance, discuss and distinguish gains and losses. 
Autumn, Seventh Moon [224 Aug 3 – Aug 31], traveled on eastern tour, visited Xǔchāng Palace.
Eighth Moon [224 Sep 1 – Sep 30], made a navy, personally rode dragon boat, followed the Cài and Yǐng, sailed the Huái, visited Shòuchūn.  Yáng Province’s border officers and clerks and servicemen and civilians that had violations of five years punishment on down were all pardoned and released. 
Ninth Moon [224 Oct 1 – Oct 29], therefore reached Guǎnglíng, amnesty on Qīng and Xú two provinces, changed and replaced the various officers and administrators.
Winter, Tenth Moon [224 Oct 30 – Nov 28], Yǐmǎo [224 Nov 4], Tàibái during daytime seen. Traveled back to Xǔchāng Palace. <a href="#annotation-41" id="source-41">[41]</a>
Eleventh Moon [224 Nov 29 – Dec 27], Gēngyín [224 Dec 9], because Jì Province was in famine, sent envoys to open the granaries to relieve them. Wùshēn [224 Dec 27], last day of the moon, the sun was eclipsed.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
五年春正月，初令謀反大逆乃得相告，其餘皆勿聽治；敢妄相告，以其罪罪之。三月，行自許昌還洛陽宮。夏四月，立太學，制五經課試之法，置春秋穀梁博士。五月，有司以公卿朝朔望日，因奏疑事，聽斷大政，論辨得失。秋七月，行東巡，幸許昌宮。八月，為水軍，親御龍舟，循蔡、潁，浮淮，幸壽春。揚州界將吏士民，犯五歲刑已下，皆原除之。九月，遂至廣陵，赦青、徐二州，改易諸將守。冬十月乙卯，太白晝見。行還許昌宮。〔一〕十一月庚寅，以冀州饑，遣使者開倉廩振之。戊申晦，日有食之。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-41" id="annotation-41">[41]</a> Wèi shū records the Guǐyǒu [224 Nov 22] Edict stating: “If the near are not soothed, how can the far be embraced? Now tasks are many but the people are few, above and below use written law to damage one another, the Hundred Surnames have no way to use their hands and feet. In the past the weeper at Tàishān believed that an oppressive government was more ferocious than tigers.  I am equipped with the airs of the classicists, submit to the remnant teachings of the sages, how can I amuse my eyes with their words but yet in conduct violate their prohibitions? Widely discuss lightening punishments, to give kindness to the Hundred Surnames.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書載癸酉詔曰：「近之不綏，何遠之懷？今事多而民少，上下相弊以文法，百姓無所措其手足。昔太山之哭者，以為苛政甚于猛虎，吾備儒者之風，服聖人之遺教，豈可以目翫其辭，行違其誡者哉？廣議輕刑，以惠百姓。」
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Twelfth Moon [224 Dec 28 – 225 Jan 26], Edict said: “The Former Kings regulated Ritual, in order to manifest filial piety and serve the ancestors, the largest then were the Suburb and Altars, the next the Ancestral Temples, the Three Celestials and Five Transitions, the famed mountains and great rivers.  Those not of this kind are not in the sacrificial canon. In the final eras of decline and chaos, there is veneration and faith in witchcraft and seers, reaching into the Palace Halls and among the doors and windows, none are not flooded in libations, so extreme is the confusion. From now on, those that dare set offerings for improper sacrifices or speak of witchcraft prayers, all are to be arrested for deviant ways and theories. Make this known in orders and law.” That year dug Tiānyuān pond.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
十二月，詔曰：「先王制禮，所以昭孝事祖，大則郊社，其次宗廟，三辰五行，名山大川，非此族也，不在祀典。叔世衰亂，崇信巫史，至乃宮殿之內，戶牖之閒，無不沃酹，甚矣其惑也。自今，其敢設非祀之祭，巫祝之言，皆以執左道論，著于令典。」是歲穿天淵池。
:::
:::

::: {.columns}
::: {.column width="70%"}
Sixth Year, Spring, Second Moon [225 Feb 25 – Mar 26], sent envoys to travel from Xǔchāng on east thoroughly to Pèi prefecture, to inquire the people of their pains and sufferings, and give support and loans to the poor. <a href="#annotation-42" id="source-42">[42]</a> Third Moon [225 Mar 27 – Apr 25], traveled to visit Shàolíng, connected Tǎolǔ Canal.  Yǐsì [Apr 23], returned to Xǔchāng Palace. Bìng Province Inspector Liáng Xí suppressed the Xiānbēi [chieftain] Kē Bĭnéng, greatly defeated him.  Xīnwèi,  the Emperor made navy on eastern campaign.
Fifth Moon [225 Jun 24 – Jul 22], Wùshēn [225 Jun 25], visited Qiáo. Rénxū [225 Jul 9], Yínghuò entered Tàiwēi.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
六年春二月，遣使者循行許昌以東盡沛郡，問民所疾苦，貧者振貸之。〔一〕三月，行幸召陵，通討虜渠。乙巳，還許昌宮。并州刺史梁習討鮮卑軻比能，大破之。辛未，帝為舟師東征。五月戊申，幸譙。壬戌，熒惑入太微。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-42" id="annotation-42">[42]</a> Wèi lüè records the Edict stating: “In the past Xuānyuán established titles on four sides, Zhōu Wǔ said: ‘I have governing officials of ten men.’  These probably were how the former sages systemized the state and ruled the people, brightened and achieved Heaven’s labors, treated having many worthies as nobility. Now the interior has the Excellencies and Ministers to defend the capital, the exterior establishes Governors and Earls to supervise the Four Quarters. As for the primary army going out on campaign, then the army’s center should also have the stone pillar of a worthy commander, and where the heavy supplies are located also should have an important minister to defend and maintain, and only then afterward the Chariot Carriage can travel around Heaven’s Under without worrying of the interior or exterior. I now will campaign against rebels, and wish to maintain this for accumulated years. Thus appoint the Secretariat Writers Director and Marquess of Yǐng village Chén Qún as Defending Army General-in-Chief and the Secretariat Writers Deputy-Director and Marquess of Xī village Sīmǎ Yì as Succoring Army General-in-Chief.  If I overlook the Jiāng to confer on the various officers policies and strategies, then the Succoring Army will remain at Xǔchāng to command the rear’s various armies and manage the rear Terrace’s written document affairs, and the Defending Army will accompany the Chariot Carriage to direct and command the multitudes and armies and manage the traveling Secretariat Writers affairs. Both are Lent Staves and drums and horns, given Central Army soldiers and cavalry of six hundred men. I wish to build Palace Residences several lǐ from the Jiāng, go back and forth from it, and on seeing an appearance of when the rebels can be struck, to then send out surprise troops to strike them, and if perhaps they cannot [be struck], then I will deploy the Six Armies with hunting expeditions, feast and bestow on the army servicemen.”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏略載詔曰：「昔軒轅建四面之號，周武稱『予有亂臣十人』，斯蓋先聖所以體國君民，亮成天工，多賢為貴也。今內有公卿以鎮京師，外設牧伯以監四方，至於元戎出征，則軍中宜有柱石之賢帥，輜重所在，又宜有鎮守之重臣，然後車駕可以周行天下，無內外之慮。吾今當征賊，欲守之積年。其以尚書令潁鄉侯陳群為鎮軍大將軍，尚書僕射西鄉侯司馬懿為撫軍大將軍。若吾臨江授諸將方略，則撫軍當留許昌，督後諸軍，錄後臺文書事；鎮軍隨車駕，當董督眾軍，錄行尚書事；皆假節鼓吹，給中軍兵騎六百人。吾欲去江數里，築宮室，往來其中，見賊可擊之形，便出奇兵擊之；若或未可，則當舒六軍以遊獵，饗賜軍士。」
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Sixth Moon [225 Jul 23 – Aug 21], Lìchéng prefecture soldier Cài Fāng and others with the prefecture rebelled, killing Administrator Xú Zhì.  Sent Garrison Cavalry Colonel Rén Fú and Infantry Colonel Duàn Zhāo with the Qīng Province Inspector to suppress and pacified them.  Those that had met with coercion and those that had deserted were all pardoned for their crimes.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
六月，利成郡兵蔡方等以郡反，殺太守徐質。遣屯騎校尉任福、步兵校尉段昭與青州刺史討平之；其見脅略及亡命者，皆赦其罪。
:::
:::

::: {.columns}
::: {.column width="70%"}
Autumn, Seventh Moon [225 Aug 22 – Sep 19], enthroned the Imperial son [Cáo] Jiàn as King of Dōngwǔyáng. 
Eighth Moon [225 Sep 20 – Oct 19], the Emperor therefore with the navy from Qiáo followed the Guō to enter the Huái, followed land roads to visit Xú [Province]. Ninth Moon [225 Oct 20 – Nov 17], built Dōngxún Terrace. 
Winter, Tenth Moon [225 Nov 18 – Dec 17] traveled to visit Guǎnglíng former city, overlooked the Jiāng to observe the soldiers, the military troops over a hundred thousand, banners and flags across several hundred lǐ. <a href="#annotation-43" id="source-43">[43]</a> That year, great cold, the waterways froze, the boats could not enter the Jiāng, thus drew back and returned.
Eleventh Moon [225 Dec 18 – 226 Jan 15], the King of Dōngwǔyáng [Cáo] Jiàn died.
Twelfth Moon [226 Jan 16 – Feb 14], traveled from Qiáo, passed Liáng, sent envoy with Grand Offering to sacrifice to former Hàn’s Grand Commandant Qiáo Xuán.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
秋七月，立皇子鑒為東武陽王。八月，帝遂以舟師自譙循渦入淮，從陸道幸徐。九月，築東巡臺。冬十月，行幸廣陵故城，臨江觀兵，戎卒十餘萬，旌旗數百里。〔一〕是歲大寒，水道冰，舟不得入江，乃引還。十一月，東武陽王鑒薨。十二月，行自譙過梁，遣使以太牢祀故漢太尉橋玄。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-43" id="annotation-43">[43]</a> Wèi shū records the Emperor’s on horseback composed poem stating:
> Observing troops overlooking the Jiāng’s waters
> The water’s flow how it rushes and rushes!
> Spears and pikes create a mountain forest
> Dark armor gleams in the sun’s light
> Fierce officers harbor violent rage
> Courageous spirit right about to be unleashed
> Who says the Jiāng’s waters are wide?
> One reed could be a boat 
> Without battle subduing enemy caitiffs
> Restraining weapons is praised as worthy and good
> Gǔ-gōng residing at Qíyì
> Truly was the beginning of cutting down Yīn-Shāng 
> Mèng Xiàn camped at Hǔláo
> The Zhèng man were afraid and bowed head 
> Chōngguó attended to plowing and planting
> The Xiānlíng on their own were broken and destroyed 
> Raising farms between the Huái and Sì
> Building house and capital in Xú region 
> Measuring appropriate fortune and expedient strategy
> The Six Armies all pleased and quiet
> How can it be like Dōngshān’s ode?
> Many, many, its numerous sorrows and wounds.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書載帝於馬上為詩曰：「觀兵臨江水，水流何湯湯！戈矛成山林，玄甲耀日光。猛將懷暴怒，膽氣正從橫。誰云江水廣，一葦可以航，不戰屈敵虜，戢兵稱賢良。古公宅岐邑，實始翦殷商。孟獻營虎牢，鄭人懼稽顙。充國務耕植，先零自破亡。興農淮、泗間，築室都徐方。量宜運權略，六軍咸悅康；豈如東山詩，悠悠多憂傷。」
:::
:::
:::

## Huángchū 7 (226) {.unnumbered}

::: {.columns}
::: {.column width="70%"}
Seventh Year, Spring, Standard Moon [226 Feb 15 – Mar 15], about to visit Xǔchāng, Xǔchāng city’s south gate without reason on its own collapsed. The Emperor in his heart hated this, and therefore did not enter.  Rénzǐ [226 Feb 24], traveled back to Luòyáng Palace.
Third Moon [226 Apr 15 – May 13], built Jiǔhuá Terrace. 
Summer, Fifth Moon [226 Jun 13 – Jul 11], Bǐngchén [226 Jun 28], the Emperor was critically ill, summoned Central Army General-in-Chief Cáo Zhēn, Defending Army General-in-Chief Chén Qún, Campaigning East General-in-Chief Cáo Xiū, Succoring Army General-in-Chief Sīmǎ [Yì] Xuān-wáng, to together receive Legacy Edict to assist the successor ruler.  Dismissed the Rear Palace’s Shūyuán and Zhāoyí on down to return to their families.  Dīngsì [226 Jun 29], the Emperor passed away in Jiāfú Hall, at the time his years forty.  <a href="#annotation-44" id="source-44">[44]</a>
Sixth Moon [226 Jul 12 – Aug 10], Wùyín [226 Jul 20], buried at Shǒuyánglíng. From the encoffining to the burial, all followed the specifications in his Final Regulations. <a href="#annotation-45" id="source-45">[45]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
七年春正月，將幸許昌，許昌城南門無故自崩，帝心惡之，遂不入。壬子，行還洛陽宮。三月，築九華臺。夏五月丙辰，帝疾篤，召中軍大將軍曹真、鎮軍大將軍陳群、征東大將軍曹休、撫軍大將軍司馬宣王，並受遺詔輔嗣主。遣後宮淑媛、昭儀已下歸其家。丁巳，帝崩于嘉福殿，時年四十。〔一〕六月戊寅，葬首陽陵。自殯及葬，皆以終制從事。〔二〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-44" id="annotation-44">[44]</a> Wèi shū states: Encoffined in Chónghuá Front Hall.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書曰：殯於崇華前殿。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-45" id="annotation-45">[45]</a> Wèishì Chūnqiū states: Emperor Míng  was about to escort the burial, Cáo Zhēn, Chén Qún, Wáng Lǎng and others due to the [dangerous] summer heat firmly remonstrated, so he stopped.

Sūn Shèng states: The task of burying the grave is the filial son’s utmost pain. Of the ways of human affairs, in this none are heavier. Therefore, ‘Heaven’s Son in the Seventh Moon is buried, those of the same course completely arrive.’  Even for the emotions of righteous feeling, yet one would be thorough in the grieving at facing the burial tunnel, so all the more for natural feelings coming from within, the respect of Ritual would value it! The virtue of the Wèi dynasty was not a foundation for many generations. In the past Huà Yuán lavishly buried and noble men believed it abandoning his lord to evil.  The remonstrations of [Chén] Qún and the rest, the abandonment was how much more extreme!

The Marquess of Juànchéng [Cáo] Zhí  made an elegy that said:

“On Huángchū Seventh Year Fifth Moon Seventeenth Day,  the Greatly Departed Imperial Emperor Passed Away.  Alas the Sorrow! At the time Heaven thundered and Earth quaked, collapsing mountains and falling frost, the sun’s essence dimmed in light, the Five Latitudes traveled wrong,  the Hundred Surnames cried aloud, Myriad States sorrowful and pained, like mourning for deceased father and deceased mother, melancholy and longing surpassing Táng [Yáo],  beating chest and stomping in the suburbs and wilderness, looking up to ponder the vast blue [sky], all saying: ‘What crime [was there], to early perish and fall? Alas the Sorrow!’ Grieving for the Greatly Departed, suddenly how light is extinguished, forever abandoning the Myriad States, clouds departing and rain dried away. Continuing to ask into the desolation, confused and dumb choking with sobs, from the sleeve drawing the blade, sighing to seek my own death, to chase after the Three Good Men,  willing in heart to share a grave, in emotion pondering the South Wind,  thoughts melancholy and slow, to in the end accompany in destruction, pointing to the sun as oath. Investigating the various former records, searching for wise words: life is like a floating passing, only virtue can be discussed; in morning heard and at evening dying, what Kǒng’s records preserved.  Though the Imperial is gone, Heaven’s blessings forever extend. How to narrate virtue? Memorialize it on white silks. How to sing of achievements? Declare it in pipes and strings. Thus I made an elegy saying:

‘Bright bright the Grand Essence, the Two Polarities first separated, the center harmonizing to create matter, originating human order,  thus reaching the Three Augusts, they filled and maintained the true way, passing down to the Five Emperors, they continued it with exemplary purity,  the Three Dynasties made systems, followed the footsteps to establish achievement.  The last successors did not maintain, the [social] fabric slackened to Qín, collapsing music and extinguishing scholarship, classicists buried and ritual [books] burned, two generations and then destroyed.  The Hàn clan then followed, not seeking the ancient teachings, Yíng Zhèng was imitated,  the King’s networks and Emperor’s canons thus were quieted and not heard. The fading light was secluded and dark, the Way exhausted and fortunes shifted, Qián and Kūn cycled in calendar, selected the sagely and appointed the worthy, thus embracing the Greatly Departed, to entrust him with the numerous individuals.  A dragon flying to initiate the blessings, in accord with the highest mysteries, the Five Transitions settled in order, he changed the title and revised the year,  brilliant brilliant radiant radiant, he received the Mandate from Heaven. His benevolent air descended on all, virtue by ritual spread, his auspicious nature and sagely character, towering in youthful beauty. He mastered the Six Canons,  learned without leaving the courtyard,  devoted heart without fail, raising his will to the azure sky. Talent and refinement elegant and bright, like the luster of jade, he heard and discerned the soundless, gazed and saw the invisible. His firmness was like metal, his integrity like jasper, like the purity of ice, like the evenness of whetstones. He granted noble titles without bias, punished criminals without lenience, his heart reflected on all affairs, illuminated the feelings of those below. Wishing for good arms and legs [assistant ministers], praising the past’s Yī [Yǐn] and Lǚ [Shàng], he searched and raised up the low, citing [Shāng] Tāng and imitating [Xià] Yǔ, he drew out talents from mountain caves, chose servicemen from disheveled doors, only virtue was considered, no constraints by ancestry. On the surface of the settled land, morality and righteousness was his planning, not blocking away by rugged terrain, the Six Directions were his concern. Fair covenant was universally honored, below to purify the people, he expanded and developed standards and regulations, continuing on from predecessors. Law codes and rank systems, praised or censured by cause. He rode the chariots of Yīn, enacted the seasons of Xià.  Gold Root Yellow Canopy,  kingfisher feathers and dragon scales, robes and crown esteemed and beautiful, hanging tassels renewed, venerable and solemn in ritual expression, he appeared like a divinity. Regional governors wonderfully raised, reverent in sympathizing with the people, tiger officers carried insignia, defending the four borders. Wherever the vermilion flags cut down, the Nine Soils were shaken,  who dared not comply, who dared not be a servant? Hanging banners by the sea, across ten thousand lǐ there was no dust. The caitiff [Liú] Bèi viciously pierced, birds falling at the Jiāng and Mín, [Sūn] Quán like a beached fish, dried and shriveled scales,  the Sùshèn paid tribute, the Yuècháng delivered treasures, the Tiáozhī in cutoff regions sent sons as attendants to inwardly submit.  Virtue comparable to the Former Imperials, achievements comparable to grand antiquity. The spirits above sent down signs, the Yellow Beginning [Huángchū] received the blessings, the Hé’s dragon and Luò’s turtle,  crossed waves to roam downstream, level and balanced as measuring ropes, divine birds soared and danced, numerous jiá in the steps sprouted,  restrained winds fanned away summer heat, white beasts and white birds, flew and ran in the suburbs and wilds, divine bells and treasure cauldrons, forms emerging from old earth,  clouds blossoming sweet dew, rained and applied on the roofs, Língzhī grew in ponds, Zhūhuá shaded the shores.  Swirling swirling the gentle wind, vast vast the sweet rain, sowed and reaped in abundance, our grain and our millet. Families girdled in the kindness of the lord, households immersed in the compassion of the father. He planned to deliver Grand Harmony,  according with virtue and preserving righteousness, right about to ascend Jièshān, with the Former Imperial forming a pair,  engraving stone to chronicle the merits, simultaneously recording the multitudes of omens, expanding the Fēng-Shàn [sacrifices],  assigning the achievement to Heaven and Earth, host rituals for the hundred spirits, the standards of merit and fate observed, the Viewing Sacrifices to the Four Peaks,  burning and conferring offered firewood, solemn in the South Suburbs, ancestral sacrifices to the Highest God, three sacrificial animals all provided,  summer Dì autumn Cháng [sacrifices],  inaugural lords accompanied in sacrifices, proffering jade rings and presenting jade tablets. Phoenix carriage shadowy and vast,  dragon flag grand ceremonies, thus reaching Tài Temple, bells and drums sounded and sounded, eulogizing virtue and singing of achievement, eight rows of dancers swaying and swaying.  The Imperial Ancestors thus fed, the illustrious father [Cáo Cāo] came to feast, the spirit satisfied and liquor finished, sending down good fortune. Heaven and Earth quaked and shook, so the Greatly Departed calmed them. The three celestials were dark and hidden, so the Greatly Departed illuminated them. The Imperial bonds were cut off, so the Greatly Departed weaved them. The Divine Vessels were not gathered, so the Greatly Departed managed them. Ritual and Music were neglected, so the Greatly Departed spread them. Benevolence and Righteousness were submerged, so the Greatly Departed raised them. Hidden Dragon Concealed Phoenix, so the Greatly Departed flew them. The distant Dí abandoned prosperity,  so the Greatly Departed rectified them. On the Throne seven years, the foundational achievement was yet raised, about to have eternal Grand Harmony, surpassing the legacies of the Three [Augusts] and Five [Emperors], he should have been a teacher for all, expanding as a divine ruler, lifespan outlasting metal and stone, equaling the count of Dōngfù,  how could he suddenly be lost, sending body to Lordly Earth, leaving us desolate desolate, without one to gaze to and without one to rely on. Oh august heavens, how can you be so cruel? Alas the Sorrow! Clearly investigating good or bad fortune, understanding from afar survival or destruction, he deeply passed down canon regulations, extending to the successor Imperial [Cáo Ruì]. The sagely ascended [Cáo Ruì] reverently serves [Cáo Pī’s Final Regulations], to follow and to enact, thus creates the Dark Rooms, foundation at Shǒuyáng,  following the path of Gǔlín, recalling Yáo of admirable Táng,  with the mountain sharing tomb, no trees no boundaries, pottery carriages and straw effigies, pearls and jade not stored.  A hundred divinities alert in attention, coming guests in the secluded hall, farm birds field beasts, watch for the flight of the soul. Therefore, waiting for the great Passage’s completion, xī, selecting the auspicious time’s good fortune.  Concealing flowery body in the catalpa coffin, xī, resting in the Main Hall to house the spirit.  Looking back to the see the successor’s wails, xī, observing the attendees’ sorrowful sounds.  Mourning that the Delayed Carriage is already prepared, xī, emotional at the Appearance Chariot’s fast journey.  Floating the flying soul to the light clouds, xī, to the yellow ruins to extinguish the [bodily] form.  Turning back on the Three Lights shining clear, xī, returning to the Dark Room’s gloomy depths.  Oh once gone there is no return, xī, pained by the closed doors forever locked. Oh Your Distant Servant’s solitary distance, xī, moved by the horrific unspeakable to grief and shock.  Heart isolated and cutoff with nowhere to express [my sorrow], xī, numerous flowing tears crossing the neck.  Pondering your grace and glory to rashly run [to you], xī, obstructed by the gate passes’ lofty towers. Looking back to my mourning sash to recklessly set out, xī, constrained by the passes binding me.  Wishing to fly high and distantly rest [at your tomb], xī, fearing the far spread of Heaven’s Net.  Distantly throwing my bones to the foot of your mountain, xī, to repay your kindness and nurture in the Lower Court.  Indignantly beating chest and self-lamenting, xī, fearing that your bestowals were heavy and my life is light. Sighing, the trifling drive to action, xī, sweetly willing for nine deaths and forgetting life. Almost in the director of life’s conscription registers,  xī, before the yellow haired  to fall and wither. Heaven covers high but examines the low, xī, I hope that the divine intelligence listens to us. Alone and desolate but with none to tell, xī, I look back to my shadow and pity the form. Presenting this document to write thoughts, xī, I join brush and ink to lay out my sincerity. Alas the Sorrow!’”
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　魏氏春秋曰：明帝將送葬，曹真、陳群、王朗等以暑熱固諫，乃止。孫盛曰：夫窀穸之事，孝子之極痛也，人倫之道，於斯莫重。故天子七月而葬，同軌畢至。夫以義感之情，猶盡臨隧之哀，況乎天性發中，敦禮者重之哉！魏氏之德，仍世不基矣。昔華元厚葬，君子以為棄君於惡，群等之諫，棄孰甚焉！鄄城侯植為誄曰：「惟黃初七年五月七日，大行皇帝崩，嗚呼哀哉！于時天震地駭，崩山隕霜，陽精薄景，五緯錯行，百姓呼嗟，萬國悲傷，若喪考妣，（恩過慕）〔思慕過〕唐，擗踊郊野，仰想穹蒼，僉曰何辜，早世殞喪，嗚呼哀哉！悲夫大行，忽焉光滅，永棄萬國，雲往雨絕。承問荒忽，惛懵哽咽，袖鋒抽刃，歎自僵斃，追慕三良，甘心同穴。感惟南風，惟以鬱滯，終於偕沒，指景自誓。考諸先記，尋之哲言，生若浮寄，唯德可論，朝聞夕逝，孔志所存。皇雖一沒，天祿永延，何以述德？表之素旃。何以詠功？宣之管絃。乃作誄曰：皓皓太素，兩儀始分，中和產物，肇有人倫，爰暨三皇，實秉道真，降逮五帝，繼以懿純，三代制作，踵武立勳。季嗣不維，網漏于秦，崩樂滅學，儒坑禮焚，二世而殲，漢氏乃因，弗求古訓，嬴政是遵，王綱帝典，闃爾無聞。末光幽昧，道究運遷，乾坤迴曆，簡聖授賢，乃眷大行，屬以黎元。龍飛啟祚，合契上玄，五行定紀，改號革年，明明赫赫，受命于天。仁風偃物，德以禮宣；祥惟聖質，嶷在幼妍。庶幾六典，學不過庭，潛心無罔，抗志青冥。才秀藻朗，如玉之瑩，聽察無嚮，瞻睹未形。其剛如金，其貞如瓊，如冰之潔，如砥之平。爵公無私，戮違無輕，心鏡萬機，攬照下情。思良股肱，嘉昔伊、呂，搜揚側陋，舉湯代禹；拔才巖穴，取士蓬戶，唯德是縈，弗拘禰祖。宅土之表，道義是圖，弗營厥險，六合是虞。齊契共遵，下以純民，恢拓規矩，克紹前人。科條品制，褒貶以因。乘殷之輅，行夏之辰。金根黃屋，翠葆龍鱗，紼冕崇麗，衡紞維新，尊肅禮容，矚之若神。方牧妙舉，欽於恤民，虎將荷節，鎮彼四鄰；朱旗所剿，九壤被震，疇克不若？孰敢不臣？縣旌海表，萬里無塵。虜備凶徹，鳥殪江岷，權若涸魚，乾腊矯鱗，肅慎納貢，越裳效珍，條支絕域，侍子內賓。德儕先皇，功侔太古。上靈降瑞，黃初叔祜：河龍洛龜，淩波游下；平鈞應繩，神鸞翔舞；數莢階除，系風扇暑；皓獸素禽，飛走郊野；神鍾寶鼎，形自舊土；雲英甘露，瀸塗被宇；靈芝冒沼，朱華蔭渚。回回凱風，祁祁甘雨，稼穡豐登，我稷我黍。家佩惠君，戶蒙慈父。圖致太和，洽德全義。將登介山，先皇作儷。鐫石紀勳，兼錄眾瑞，方隆封禪，歸功天地，賓禮百靈，勳命視規，望祭四嶽，燎封奉柴，肅于南郊，宗祀上帝。三牲既供，夏禘秋嘗，元侯佐祭，獻璧奉璋。鸞輿幽藹，龍旂太常，爰迄太廟，鍾鼓鍠鍠，頌德詠功，八佾鏘鏘。皇祖既饗，烈考來享，神具醉止，降茲福祥。天地震蕩，大行康之；三辰暗昧，大行光之；皇紘絕維，大行綱之；神器莫統，大行當之；禮樂廢弛，大行張之；仁義陸沈，大行揚之；潛龍隱鳳，大行翔之；疏狄遐康，大行匡之。在位七載，元功仍舉，將永太和，絕跡三五，宜作物師，長為神主，壽終金石，等算東父，如何奄忽，摧身后土，俾我〈煢，去冖〉〈煢，去冖〉，靡瞻靡顧。嗟嗟皇穹，胡寧忍務？嗚呼哀哉！明監吉凶，體遠存亡，深垂典制，申之嗣皇。聖上虔奉，是順是將，乃創玄宇，基為首陽，擬跡穀林，追堯慕唐，合山同陵，不樹不疆，塗車芻靈，珠玉靡藏。百神警侍，來賓幽堂，耕禽田獸，望魂之翔。於是，俟大隧之致功兮，練元辰之淑禎，潛華體於梓宮兮，馮正殿以居靈。顧望嗣之號咷兮，存臨者之悲聲，悼晏駕之既脩兮，感容車之速征。浮飛魂於輕霄兮，就黃墟以滅形，背三光之昭晰兮，歸玄宅之冥冥。嗟一往之不反兮，痛閟闥之長扃。咨遠臣之眇眇兮，感凶諱以怛驚，心孤絕而靡告兮，紛流涕而交頸。思恩榮以橫奔兮，閡闕塞之嶢崢，顧衰絰以輕舉兮，迫關防之我嬰。欲高飛而遙憩兮，憚天網之遠經，遙投骨於山足兮，報恩養於下庭。慨拊心而自悼兮，懼施重而命輕，嗟微驅之是效兮，甘九死而忘生，幾司命之役籍兮，先黃髮而隕零，天蓋高而察卑兮，冀神明之我聽。獨鬱伊而莫愬兮，追顧景而憐形，奏斯文以寫思兮，結翰墨以敷誠。嗚呼哀哉！」
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Previously, the Emperor enjoyed literary scholarship, attended to writing and composition, what he personally collated and completed was bequeathed as a hundred volumes. He also employed various classicists to compile the classics and commentaries, by their type joined with one another, altogether over a thousand volumes, titled as the Huánglǎn. <a href="#annotation-46" id="source-46">[46]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
初，帝好文學，以著述為務，自所勒成垂百篇。又使諸儒撰集經傳，隨類相從，凡千餘篇，號曰皇覽。〔一〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-46" id="annotation-46">[46]</a> Wèi shū states: When the Emperor was previously at the East Palace,  an epidemic greatly rose, at the time people suffered and died.  The Emperor was deeply emotional and sighed, and to Minister Judge Wáng Lǎng, whom he always respected, wrote a letter that said: “Living, there is seven chǐ of body. Dead, there is only one coffin of soil. Only by establishing virtue and raising reputation can there be no decay. After that there is nothing as good as writing books. Epidemics have repeatedly risen, servicemen and people dying and falling. I alone am what man, to be able to preserve this lifespan?” Therefore he considered and compiled what he had written, the Diǎnlùn,  poems, rhapsodies, altogether over a hundred volumes, gathered various classicists within Sùchéng’s gates,  discussing and debating great meanings, consistently without tiring. He always praised Hàn Emperor Wén’s conduct as a lord, lenient and benevolent, mysterious and silent, attending to the desire to influence the people by virtue, having the airs of a worthy sage. At the time of the literary scholars and various classicists, some believed that although Xiào-Wén was worthy, his intelligence and understanding of state systems did not compare to Jiǎ Yì.  The Emperor because of this wrote the Tàizōng Lùn  stating: “In the past Yǒu Miáo did not submit and Chónghuá danced with shield and battle-axe, Wèi Tuó declared himself Emperor and Xiào-Wén succored him with merciful virtue,  the King of Wú did not attend Court, [Xiào-Wén] bestowed him with table and cane to succor his thoughts, and Heaven’s Under depended on this for calm.  Thus he spread the teachings of the Three Clauses,  the influence of contentedness and fraternity, wishing to allow those people who in past times accumulated fatigue, to be able to stride forward and openly discuss without fearful hearts. Something like Jiǎ Yì’s talent and cleverness, planning and preparing state government, is only the talent of a worthy minister, the quality of Guǎn [Zhòng] and Yàn [Yīng].  How could it compare to Xiào-Wén’s capacity as a great man?” During the Third Year, as Sūn Quán would not submit, he again issued Tàizōng Lùn to Heaven’s Under, to clearly show that he had not wanted to go to war. On another day he also casually said: “Looking back, I also have three matters that I cannot seek to imitate from Hàn Emperor Wén: killing Bó Zhāo,  favoring Dèng Tōng,  and having the consort Shèn wear clothes that did not touch the ground and gather up document bags to make curtains.  I believe that Hàn Wén’s frugality was beyond propriety. To the family of his mother’s brother, he should have only cared for them with favor and should not have lent them authority, so that they violated criminal law and also could not but come to harm.” His desire was to maintain the center way, believing that Emperors and Kings in bearing should be like this.

Hú Chōng’s Wú lì  states: The Emperor had a silk book of his composed Diǎnlùn and poems and rhapsodies gifted to Sūn Quán, and also had a paper copy sent to Zhāng Zhāo.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書曰：帝初在東宮，疫癘大起，時人彫傷，帝深感歎，與素所敬者大理王朗書曰：「生有七尺之形，死唯一棺之土，唯立德揚名，可以不朽，其次莫如著篇籍。疫癘數起，士人彫落，余獨何人，能全其壽？」故論撰所著典論、詩賦，蓋百餘篇，集諸儒於肅城門內，講論大義，侃侃無倦。常嘉漢文帝之為君，寬仁玄默，務欲以德化民，有賢聖之風。時文學諸儒，或以為孝文雖賢，其於聰明，通達國體，不如賈誼。帝由是著太宗論曰：「昔有苗不賓，重華舞以干戚，尉佗稱帝，孝文撫以恩德，吳王不朝，錫之几杖以撫其意，而天下賴安；乃弘三章之教，愷悌之化，欲使曩時累息之民，得闊步高談，無危懼之心。若賈誼之才敏，籌畫國政，特賢臣之器，管、晏之姿，豈若孝文大人之量哉？」三年之中，以孫權不服，復頒太宗論于天下，明示不願征伐也。他日又從容言曰：「顧我亦有所不取于漢文帝者三：殺薄昭；幸鄧通；慎夫人衣不曳地，集上書囊為帳帷。以為漢文儉而無法，舅后之家，但當養育以恩而不當假借以權，既觸罪法，又不得不害矣。」其欲秉持中道，以為帝王儀表者如此。胡沖吳曆曰：帝以素書所著典論及詩賦餉孫權，又以紙寫一通與張昭。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Appraisal States: Emperor Wén was naturally endowed with literary elegance, on using brush completed a work, widely learned and strong memory, talents and arts both furnished. <a href="#annotation-47" id="source-47">[47]</a> If only he had added to it an expansive and broad tolerance, strove with fair and impartial sincerity, chased his ambitions while preserving the way, achieved and expanded a virtuous heart, then compared to the worthy rulers of antiquity, how would there be such a distance?
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
評曰：文帝天資文藻，下筆成章，博聞彊識，才蓺兼該；〔一〕若加之曠大之度，勵以公平之誠，邁志存道，克廣德心，則古之賢主，何遠之有哉！
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-47" id="annotation-47">[47]</a> (1)	In Diǎnlùn the Emperor’s Self Narration states: In Chūpíng’s Inaugural [190], Dǒng Zhuó killed the Ruler and poisoned the [Dowager] Empress, overthrew and overturned the Ruling House.  At the time the Four Seas were already destitute from the government of Zhōngpíng [184 - 189], and further loathing [Dǒng] Zhuó’s vicious rebellion, family after family worried of chaos, man after man feared themselves in danger. East of the mountains the Governors and Administrators all used the Chūnqiū’s principle of “Wèi men suppressed Zhōuyù at Pú”  to say that man after man all were able to suppress rebels. Thereupon there was a great raising of Righteous Troops, famed heroes and great vigilantes, wealthy houses and powerful clans, whirling and rising like clouds gathering, ten thousand lǐ joining one another. The brigades of Yǎn and Yù [Provinces] battled at Xíngyáng, the armor of Hénèi militarized Mèngjīn. [Dǒng] Zhuó therefore moved the Great Carriage, shifting the capital west to Cháng’ān. And so east of the mountains, the large linked prefectures and states, the middle fortified cities and towns, the small assembled paths and streets, in turn swallowing and exterminating one another. It happened the Huángjīn flourished in Hǎi and Dài,  mountain bandits were violent in Bìng and Jì [Provinces], riding victories to turn and attack, engulfing and going south. Villages and cities spotted smoke and fled, city walls saw dust [of approaching armies] and dispersed, the Hundred Surnames perished and died, exposed bones like weeds. At the time I was aged five years, and my father, because the world was disturbed and in chaos, taught me to learn to shoot. At six years I knew how to shoot, and he also taught me to ride horse. At eight years I was able to ride and shoot. Because at the time there were many dangers, in every campaign I always accompanied. At Jiàn’ān’s beginning [196], my father campaigned south against Jīng Province, reached Yuān, and Zhāng Xiù surrendered. Within ten days he rebelled, and I lost my elder brother the Filial-Incorruptible [Cáo Áng] Zǐxiū, and my elder cousin Ānmín came to harm.  At the time I was aged ten years, and rode horse to escape. The ways of the civil and military, each according to the times are used. I was born at the end of Zhōngpíng [184 – 189], grew up among weapons and soldiers, and therefore from youth enjoyed the bow and horse, and to now I have not declined, chasing game for ten lǐ, galloping and shooting always at a hundred bù, the days many and body strong, my heart never tired of it. Jiàn’ān Tenth Year [205], having just settled Jì Province, the Huìmò sent tribute of excellent bows, Yān and Dài proffered famed horses.  At the time it was the end of spring, Gōumáng directing the season,  mild breeze fanning things, bow dry and hand supple, grass shallow and beasts fat, with my elder cousin Zǐdān  we hunted to Yè’s west, at the end of the day we hand captured deer of nine, pheasants and hares of thirty. Later the army campaigned south and stopped at Qǔlí, Secretariat Writers Director Xún Yù served a mission to present comforts to the army, and after meeting and conversing with me, [Xún] Yù said: “I have heard that you are skilled at shooting with both left and right. This is a truly difficult ability.” I said: “Your Honor has not yet seen launching from neck and unleashing by mouth, bending down to the horse hooves and looking up to the targets.” [Xún] Yù laughed and said: “Really then?” I said: “The [archery] range has a constant track; the targets have designated places. Even if every shot be a hit, it is not utmost mastery. But riding on open plains, racing across dense grasses, pursuing cunning beasts, intercepting light birds, ensuring the bow never be bent in vain, every shot certain to pierce through, then that would be mastery.” At the time Army Libationer Zhāng Jīng  was seated, and looking to [Xún] Yù clapped his hands and said: “Excellent!” I also learned sword fencing, and studied many masters, across the Four Quarters the techniques are each unique, but only the masters of the capital are the best. During the times of Huán and Líng, there was a Tiger Elite Wáng Yuè  who excelled in these techniques, and was praised by the capital masters. Hénán’s Shǐ Ā  said that he in the past traveled with [Wáng] Yuè, completely learned his methods, and I studied under [Shǐ] Ā to learn its essential skills. Once I was with Pacifying Caitiffs General Liú Xūn and Exerting Authority General Dèng Zhǎn and others together drinking.  Previously I had heard that [Dèng] Zhǎn was strong in arm, had learned the Five Weapons,  and also had been praised as being able to use bare hands against naked blades. I discussed swords with him for a good while, and said that the General's skills were not as said, that I had always enjoyed these things, and also had obtained excellent skills, and therefore asked him to face me. At the time we were so intoxicated that our ears burned, and just happened to be eating sugar canes, so we used them as sticks, went down from the Hall and repeatedly sparred, three times striking his arm, and those left and right greatly laughed. [Dèng] Zhǎn was dissatisfied, and requested to go again. I said that my technique was of a fast sort, difficult to use to strike the face, and therefore only struck the arms. [Dèng] Zhǎn said he wished to spar one more time. I knew he wished to charge to seek to engage the center and therefore feigned a deep advance. [Dèng] Zhǎn indeed charged ahead, but I on merely pulling back my leg struck right on his forehead, and those seated and watching were startled. I returned to my seat, and laughed and said: “In the past Yáng Qīng had Chúnyú Yì abandon his former methods, and again receive instruction in secret techniques.  Now I also wish for General Dèng [Zhǎn] to abandon his former tricks, and again receive instruction on the important principles.” All those seated were thoroughly entertained. [But] in such matters, one cannot really call oneself great. When young I learned dual wielding, and myself said that I was without match. Commonly dual halberds are called ‘sitting in iron chamber,’ side shields are called ‘the covering wooden door.’ Later I studied under Chén state’s Yuán Mǐn,  who used one [weapon] to fight dual [wielding], in every match he was like a spirit, the opponent did not know where he would strike out. In those former days if I had encountered [Yuán] Mǐn on a narrow road, [the duel] would have at once be decided [against me]! With other games I had few that I enjoyed, only in playing Dànqí  was I somewhat thorough in the skill, and when young made a rhapsody for it. In the past in the capital the foremost players were Mǎ the Marquess of Hé village, Dōngfāng Ānshì, and young noble Zhāng,  and I always regret that I could not have played against these masters. My father greatly enjoyed the Shī [jīng] and [Shàng] Shū and literature. Although he was in the army, his hands did not set aside books, and always studied them when at ease, always saying: “Men who are studious when young are able to think hard, but when grown are forgetful. Those grown up but still able to be diligent in study are only me and Yuán Bóyè.”  I therefore when young recited [from memory] the Shī [jīng] and Lún [yǔ], and when grown studied through the words of the Five Classics, the Four Genres, the Shǐ[jì] and Hàn[shū], and the Hundred Schools of thought,  and there was none I did not read.

Bówùzhì states: The Emperor was skilled in Dànqí, able to use a hand towel’s corner. At the time there was a scholar, also able to lower his head to use his cap’s hemp headscarf corner to cast the pieces.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　典論帝自敘曰：初平之元，董卓殺主鴆后，蕩覆王室。是時四海既困中平之政，兼惡卓之凶逆，家家思亂，人人自危。山東牧守，咸以春秋之義，「衛人討州吁于濮」，言人人皆得討賊。於是大興義兵，名豪大俠，富室強族，飄揚雲會，萬里相赴；兗、豫之師戰于滎陽，河內之甲軍于孟津。卓遂遷大駕，西都長安。而山東大者連郡國，中者嬰城邑，小者聚阡陌，以還相吞滅。會黃巾盛於海、岱，山寇暴於并、冀，乘勝轉攻，席卷而南，鄉邑望煙而奔，城郭睹塵而潰，百姓死亡，暴骨如莽。余時年五歲，上以世方擾亂，教余學射，六歲而知射，又教余騎馬，八歲而能騎射矣。以時之多故，每征，余常從。建安初，上南征荊州，至宛，張繡降。旬日而反，亡兄孝廉子修、從兄安民遇害。時余年十歲，乘馬得脫。夫文武之道，各隨時而用，生于中平之季，長于戎旅之間，是以少好弓馬，于今不衰；逐禽輒十里，馳射常百步，日多體健，心每不厭。建安十年，始定冀州，濊、貊貢良弓，燕、代獻名馬。時歲之暮春，勾芒司節，和風扇物，弓燥手柔，草淺獸肥，與族兄子丹獵于鄴西，終日手獲獐鹿九，雉兔三十。後軍南征次曲蠡，尚書令荀彧奉使犒軍，見余談論之末，彧言：「聞君善左右射，此實難能。」余言：「執事未睹夫項發口縱，俯馬蹄而仰月支也。」彧喜笑曰：「乃爾！」余曰：「埒有常徑，的有常所，雖每發輒中，非至妙也。若馳平原，赴豐草，要狡獸，截輕禽，使弓不虛彎，所中必洞，斯則妙矣。」時軍祭酒張京在坐，顧彧拊手曰「善」。余又學擊劍，閱師多矣，四方之法各異，唯京師為善。桓、靈之間，有虎賁王越善斯術，稱於京師。河南史阿言昔與越遊，具得其法，余從阿學之精熟。嘗與平虜將軍劉勳、奮威將軍鄧展等共飲，宿聞展善有手臂，曉五兵，又稱其能空手入白刃。余與論劍良久，謂言將軍法非也，余顧嘗好之，又得善術，因求與余對。時酒酣耳熱，方食芊蔗，便以為杖，下殿數交，三中其臂，左右大笑。展意不平，求更為之。余言吾法急屬，難相中面，故齊臂耳。展言願復一交，余知其欲突以取交中也，因偽深進，展果尋前，余卻腳鄛，正截其顙，坐中驚視。余還坐，笑曰：「昔陽慶使淳于意去其故方，更授以祕術，今余亦願鄧將軍捐棄故伎，更受要道也。」一坐盡歡。夫事不可自謂己長，余少曉持複，自謂無對；俗名雙戟為坐鐵室，鑲楯為蔽木戶；後從陳國袁敏學，以單攻複，每為若神，對家不知所出，先日若逢敏於狹路，直決耳！余於他戲弄之事少所喜，唯彈棋略盡其巧，少為之賦。昔京師先工有馬合鄉侯、東方安世、張公子，常恨不得與彼數子者對。上雅好詩書文籍，雖在軍旅，手不釋卷，每每定省從容，常言人少好學則思專，長則善忘，長大而能勤學者，唯吾與袁伯業耳。余是以少誦詩、論，及長而備歷五經、四部，史、漢、諸子百家之言，靡不畢覽。博物志曰：帝善彈棋，能用手巾角。時有一書生，又能低頭以所冠著葛巾角撇棋。
:::
:::
:::