# Biographies of Empresses and Consorts

## Preface {.unnumbered}

::: {.columns}
::: {.column width="70%"}
The Yì^[The Yì jīng "Book of Changes" is a classic divination text.] states: "The Male correct position is the exterior, the Female correct position is the interior. Male and Female correct, is the Great Principle of Heaven and Earth." Of the ancient former wise kings, none did not understand the regulation of Empresses and Consorts, follow the virtues of Heaven and Earth, therefore when the Two Consorts married to Guī, the Way of Yú completed prosperity, when Rén and Sì matched to Jī, the Zhōu House then flourished. Fall and Rise, Survival and Destruction, constantly are by this. The Chūnqiū explanations say Heaven's Son has twelve women, vassal lords nine women, examining this by sense and reason, it is an unchanging standard. But the last generations [of a dynasty] are extravagant and indulgant, unrestrained in their excessive desires, reaching to causing male and female to be resentful and unmarried, emotionally disturbing harmonious aura, only attractiveness is esteemed, not rooted in beautiful virtue, therefore moral teachings decline and the great [social] network is ruined and destroyed. Is it not lamentable? Alas, for those with state and with family, this can be an eternal reflection!
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
易稱「男正位乎外，女正位乎內；男女正，天地之大義也」。古先哲王，莫不明后妃之制，順天地之德，故二妃嬪媯，虞道克隆，任、姒配姬，周室用熙，廢興存亡，恆此之由。春秋說云天子十二女，諸侯九女，考之情理，不易之典也。而末世奢縱，肆其侈欲，至使男女怨曠，感動和氣，惟色是崇，不本淑懿，故風教陵遲而大綱毀泯，豈不惜哉！嗚呼，有國有家者，其可以永鑒矣！
:::
:::

::: {.columns}
::: {.column width="70%"}
In the Hàn system, the Emperor's paternal grandmother is called Grand Imperial Dowager Empress, the Emperor's mother called Imperial Dowager Empress, the Emperor's consort called Imperial Empress, the other inner offices [the harem] ten and four ranks. Wèi followed the Hàn laws, the titles of the mothers and Empresses, all were as the old system. From the Lady (fūrén) on down, the generations had additions and reductions. Tàizǔ established the state, first mandating the Royal Queen, those below were five ranks: having Lady (fūrén), having Zhāoyí, having Jiéyú, having Rónghuá, having Měirén. Emperor Wén added Guìpín, Shūyuán, Xiūróng, Shùnchéng, Liángrén. Emperor Míng added Shūfēi, Zhāohuá, Xiūyí; abolished the Shùnchéng office. During Tàihé [227 - 232] first restored the Mìng Fūrén, raised its position to above Shūfēi. From Fūrén on down the nobility was altogether twelve ranks: Guìpín and Fūrén positions were after the Imperial Empress, nobility without a match. Shūfēi position matched the Chancellor of State, nobility comparable to the vassal lords and kings. Shūyuán position matched the Censorate Grandee, nobility comparable to county Duke. Zhāoyí comparable to county Marquess. Zhāohuá comparable to village Marquess. Xiūróng comparable to precinct Marquess. Xiūyí comparable to Within the Passes Marquess. Jiéyú matched to Central Two Thousand Dàn. Rónghuá matched to True Two Thousand Dàn. Měirén matched to Comparable Two Thousand Dàn. Liángrén matched to Thousand Dàn.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
漢制，帝祖母曰太皇太后，帝母曰皇太后，帝妃曰皇后，其餘內官十有四等。魏因漢法，母后之號，皆如舊制，自夫人以下，世有增損。太祖建國，始命王后，其下五等：有夫人，有昭儀，有婕妤，有容華，有美人。文帝增貴嬪、淑媛、脩容、順成、良人。明帝增淑妃、昭華、脩儀；除順成官。太和中始復命夫人，登其位於淑妃之上。自夫人以下爵凡十二等：貴嬪、夫人，位次皇后，爵無所視；淑妃位視相國，爵比諸侯王；淑媛位視御史大夫，爵比縣公；昭儀比縣侯；昭華比鄉侯；脩容比亭侯；脩儀比關內侯；婕妤視中二千石；容華視真二千石；美人視比二千石；良人視千石。
:::
:::


## Wǔ-Xuān Imperial Empress Biàn {#wuxuan .unnumbered}

::: {.columns}
::: {.column width="70%"}
Wǔ-Xuān^[The posthumous name Wǔ is shared with her husband. The posthumous name Xuān "Renowned" has connotations of fame for moral conduct.] Imperial Empress Biàn was a Lángyé Kāiyáng woman, Emperor Wén's mother. Originally a performer,^["Performer" (chàngjiā) has often been mistranslated as "prostitute." The term did not gain this meaning until several centuries later during the Táng dynasty.] <a href="#annotation-1" id="source-1">[1]</a> aged twenty, Tàizǔ at Qiáo accepted the Empress^[Following standard historiography convention, Biàn is called as Empress anachronistically.] as a concubine. The Empress accompanied Tàizǔ to Luò. Reaching to Dǒng Zhuó making chaos, Tàizǔ [disguised] in humble clothing went out east to escape trouble. Yuán Shù spread rumors of Tàizǔ's misfortune, at the time Tàizǔ's Left and Right that had gone to Luò all wished to return home, the Empress stopped them saying: "Lord Cáo's fortune or misfortune cannot yet be known, if today you return home, tomorrow if he survives, how would you have to face him again? Even if disaster arrives, dying together is what bitterness?" Therefore they followed the Empress's words. Tàizǔ heard and praised this. At the beginning of Jiàn'ān (196 - 220), lady Dīng was deposed, and therefore had the Empress be the successor wife. The various sons that were without mothers, Tàizǔ all had the Empress raise them. <a href="#annotation-2" id="source-1">[2]</a> When Emperor Wén became Heir-Apparent, the Left and Right and Chief Maid^[Chángyú were senior members of the female staff if the Empress's palace] congratulated the Empress saying: "The General^[Referring to Cáo Pī by his rank at that time] is appointed Heir-Apparent, Under Heaven none are not joyous, [You, The] Queen should pour out the treasury to bestow rewards." The Empress said: "The King naturally because [Cáo] Pī's age is largest therefore emmployed him as successor. I should only consider avoiding the fault of not instructing and guiding him to be good fortune, also why should there be heavy bestowments for this?" The Chief Maid returned and provided her words to Tàizǔ. Tàizǔ was pleasued and said: "In anger to not change expression, in joy to not lose moral restraint, indeed this is the most difficut."
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
武宣卞皇后，瑯邪開陽人，文帝母也。本倡家，〔一〕年二十，太祖於譙納后為妾。後隨太祖至洛。及董卓為亂，太祖微服東出避難。袁術傳太祖凶問，時太祖左右至洛者皆欲歸，后止之曰：「曹君吉凶未可知，今日還家，明日若在，何面目復相見也？正使禍至，共死何苦！」遂從后言。太祖聞而善之。建安初，丁夫人廢，遂以后為繼室。諸子無母者，太祖皆令后養之。〔二〕文帝為太子，左右長御賀后曰：「將軍拜太子，天下莫不歡喜，后當傾府藏賞賜。」后曰：「王自以丕年大，故用為嗣，我但當以免無教導之過為幸耳，亦何為當重賜遺乎！」長御還，具以語太祖。太祖悅曰：「怒不變容，喜不失節，故是最為難。」
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-1" id="annotation-1">[1]</a> Wèi shū states: The Empress in Hàn's Yánxī Third Year Twelfth Moon Jǐsì [159 Dec 30] was born in Qí prefecture's Báitíng, having a yellow aura fill the room all day. Her father Marquess Jìng^[Jìng-hóu "Vigilant Marquess" is her father's posthumous name] was bewildered by it, and asked a diviner Wáng Dàn. Dàn said: "This is an auspicious omen."
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書曰：后以漢延熹三年十二月己巳生齊郡白亭，有黃氣滿室移日。父敬侯怪之，以問卜者王旦，旦曰：「此吉祥也。」
:::
:::
:::

::: {.callout-note appearance="minimal" #dingshi}
::: {.columns}
::: {.column width="70%"}
<a href="#source-2" id="annotation-2">[2]</a> Wèi lüè states: Tàizǔ first had lady Dīng, and also lady Liú bore [Cáo Áng] Zǐxiū and the eldest Princess of Qīnghé. Liú early died, Dīng adopted Zǐxiū. Zǐxiū died at Ráng, Dīng always said: "You killed my son, and completely no longer think of him!" Therefore she wept without restraint. Tàizǔ was angered by this, sent her back to her family, desiring to break her will. Later Tàizǔ arrived to meet her, the lady was just weaving, someone outside passed word: "His Excellency arrives." The lady sat at her loom as before. Tàizǔ arrived, caressed her back saying: "Will you look back at me and ride the carriage together to return home?" The lady did not look back, and also did not answer. Tàizǔ backed away, stood outside the door, and further said: "Is it impossible then?" Still she did not answer. Tàizǔ said: "It is really farewell." Therefore they were divorced, and he wished for her family to remarry her off, her family did not dare. Previously, lady Dīng had been the primary wife and furthermore had Zǐxiū, Dīng treated the Empress, mother and her children, as beneath her. When the Empress became the successor wife, she did not recall old grievances, took advantage of when Tàizǔ was out on campaign, to regularly in the four seasons send people with gifts, and also privately invited her, having her [Dīng] in the main seat and herself [Biàn] below her, welcoming her coming and escorting her going, like in the old days. Dīng apologized saying: "For a deposed and exiled woman [like me], how can [you, my] lady be able to always be like this?" Later when Dīng died, the Empress requested Tàizǔ bury her, he permitted it, and so she was buried to Xǔ city wall's south. Later when Tàizǔ was seriously ill, he himself realized he would not recover, and sighed and said: "In my beginning to end conduct and intentions, in my heart there has never been regrets. But supposing if the dead have awareness, if Zǐxiū asks "Where is my mother," what statement would I have to answer?"

Wèi shū states: The Empress by nature was temperate and frugal, not esteeming the flowery and magnificent, had no patterned embroidery or pearls and jade, her utensils all were black lacquer. Tàizǔ once obtained famed earrings of several sets, and mandated the Empress herself choose one set. The Empress chose a middle one. Tàizǔ asked the reason, she replied saying: "Taking the highest is greed, taking the lowest is hypocrisy, therefore I chose the middle."
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　魏略曰：太祖始有丁夫人，又劉夫人生子脩及清河長公主。劉早終，丁養子脩。子脩亡於穰，丁常言：「將我兒殺之，都不復念！」遂哭泣無節。太祖忿之，遣歸家，欲其意折。後太祖就見之，夫人方織，外人傳云「公至」，夫人踞機如故。太祖到，撫其背曰：「顧我共載歸乎！」夫人不顧，又不應。太祖卻行，立于戶外，復云：「得無尚可邪！」遂不應，太祖曰：「真訣矣。」遂與絕，欲其家嫁之，其家不敢。初，丁夫人既為嫡，加有子脩，丁視后母子不足。后為繼室，不念舊惡，因太祖出行，常四時使人饋遺，又私迎之，延以正坐而己下之，迎來送去，有如昔日。丁謝曰：「廢放之人，夫人何能常爾邪！」其後丁亡，后請太祖殯葬，許之，乃葬許城南。後太祖病困，自慮不起，歎曰：「我前後行意，於心未曾有所負也。假令死而有靈，子脩若問『我母所在』，我將何辭以答！」魏書曰：后性約儉，不尚華麗，無文繡珠玉，器皆黑漆。太祖常得名璫數具，命后自選一具，后取其中者，太祖問其故，對曰：「取其上者為貪，取其下者為偽，故取其中者。」
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Twenty-Fourth Year [219], appointed as Royal Queen, the conferment said: "Fūrén Biàn-shì fostered and raised the various sons, having the virtue of maternal ceremony. Now advance in rank to Royal Queen, the Heir-Apparent and vassal lords accompany in position, the various ministers send up longevity wishes, reduce within [Wèi] state death penalties by one degree." Twenty-Fifth Year [220], Tàizǔ passed away, Emperor Wén ascended the King's position, honored the Empress as Royal Dowager Queen, reaching to the ascension of the [Imperial] throne, honored the Empress as Imperial Dowager Empress, calleas Yǒngshòu Palace. <a href="#annotation-3" id="source-3">[3]</a> Emperor Míng succeeded the position, honored the Dowager Empress as Grand Imperial Dowager Empress.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
二十四年，拜為王后，策曰：「夫人卞氏，撫養諸子，有母儀之德。今進位王后，太子諸侯陪位，群卿上壽，減國內死罪一等。」二十五年，太祖崩，文帝即王位，尊后曰王太后，及踐阼，尊后曰皇太后，稱永壽宮。〔一〕明帝即位，尊太后曰太皇太后。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-3" id="annotation-3">[3]</a> Wèi shū states: The Empress because state expenditures were not enough, abolished and reduced her imperial meals, the various gold and silver utensils were all removed. The King of Dōng'ē [Cáo] Zhí was the Dowager Empress's youngest son and the most favored. Later [Cáo] Zhí violated law, was memorialized by relevant managers, Emperor Wén ordered the Dowager Empress's younger brother's son Serving Chariots Commandant [Biàn] Lán to take the discussions of the Excellencies and Ministers to report to the Dowager Empress. The Dowager Empress said: "Unexpectedly this boy had behavior like this, you return and tell the Emperor, that he cannot ruin the state's laws because of me." Reaching to personally meeting the Emperor, she did not speak of it.

Your Servant Sōngzhī notes: Emperor Wén dreamed of rubbing a coin, wishing to have the inscription removed but it became all the more clear and asked Zhōu Xuān about it. Xuān replied saying: "This is Your Majesty's family affairs, though your intentions wish for it, yet the Dowager Empress does not listen." Then the Dowager Empress employed her intentions, and could not be as what this book says.

Wèi shū also states: Every time the Dowager Empress accompanied the army on campaign, when seeing the highly aged and white headed, at once she stopped her chariot to call and inquire, bestowing on them fabric and silk, facing them shedding tears and saying: "I regret my father and mother did not reach our time." Every time the Dowager Empress met the [Cáo's] in-law relations [her Biàn family], she was not accommodating in countenance, always saying: "Your residences should be frugal in affairs. You should not expect rewards and bestowments or think of self indulgences. The in-law families are bewildered that my treatment as too meager. It is because I have my own constant standards. I served Emperor Wǔ for forty to fifty years, acted frugally for a long time, and cannot change myself to extravagance. If there are any violations of laws and prohibitions, I would only be able to increase the punishment by one degree. Do not expect cash or rice or gracious loans." The Emperor for the Dowager Empress's younger brother [Biàn] Bǐng raised a mansion, the mansion was completed, the Dowgaer Empress visited the mansion and invited the various families of the [Cáo's] in-law relations, set an inferior kitchen, with no exceptional delicacies. The Dowager Empress's Left and Right ate vegetables and millet, with no fish or meat. Her frugality was like this.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書曰：后以國用不足，滅損御食，諸金銀器物皆去之。東阿王植，太后少子，最愛之。後植犯法，為有司所奏，文帝令太后弟子奉車都尉蘭持公卿議白太后，太后曰：「不意此兒所作如是，汝還語帝，不可以我故壞國法。」及自見帝，不以為言。臣松之案：文帝夢磨錢，欲使文滅而更愈明，以問周宣。宣答曰：「此陛下家事，雖意欲爾，而太后不聽。」則太后用意，不得如此書所言也。魏書又曰：太后每隨軍征行，見高年白首，輒住車呼問，賜與絹帛，對之涕泣曰：「恨父母不及我時也。」太后每見外親，不假以顏色，常言「居處當務節儉，不當望賞賜，念自佚也。外舍當怪吾遇之太薄，吾自有常度故也。吾事武帝四五十年，行儉日久，不能自變為奢，有犯科禁者，吾且能加罪一等耳，莫望錢米恩貸也。」帝為太后弟秉起第，第成，太后幸第請諸家外親，設下廚，無異膳。太后左右，菜食粟飯，無魚肉。其儉如此。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
During Huángchū, Emperor Wén wished to posthumously enfeoff the Dowager Empress's father and mother. Secretariat Writer Chén Qún memorialized stating: "Your Majesty by sagely virtue answered fate to receive the Mandate, beginning the enterprise and reforming systems, and should forever be a model for posterity. Citing the writings of the canon registers, there is no system of women sharing in territory and mandated nobility. In ritual canon, the wife follows the husband's noble title. Qín violated the ancient laws, the Hàn clan followed them. It is not the excellent canon of the Former Kings." The Emperor said: "This comment is corect. Thus do not put into effect. Have the composed and written Edict sent down for storage in the Terrace Pavillions, to forever be a model for posterity." Reaching Tàihé Fourth Year [230] Spring, Emperor Míng then posthumously titled the Dowager Empress's paternal grandfather [Biàn] Guǎng as Marquess Gōng of Kāiyáng, father [Biàn] Yuǎn as Marquess Jìng, paternal grandmother Zhōu enfeoffed as Lady of Yángdū along with Marquess Jìng's consort, all bestowed Seals and Ribbons. That Year Fifth Moon, the Empressed passed away. Seventh Moon, joint burial [with Emperor Wǔ] at Gāolíng.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
黃初中，文帝欲追封太后父母，尚書陳群奏曰：「陛下以聖德應運受命，創業革制，當永為後式。案典籍之文，無婦人分土命爵之制。在禮典，婦因夫爵。秦違古法，漢氏因之，非先王之令典也。」帝曰：「此議是也，其勿施行。以作著詔下藏之臺閣，永為後式。」至太和四年春，明帝乃追諡太后祖父廣曰開陽恭侯，父遠曰敬侯，祖母周封陽都君及（恭）〔敬〕侯夫人，皆贈印綬。其年五月，后崩。七月，合葬高陵。
:::
:::

::: {.columns #bianbing #bianlan #caomaobian #caohuanbian}
::: {.column width="70%"}
Previously, the Dowager Empress's younger brother [Biàn] Bǐng for achievements was enfeoffed as a city village Marquess, Huángchū Seventh Year [226] advanced enfeoffment to Marquess of Kāiyáng, fief of one thousand two hundred households, became Shining Illustrious General. <a href="#annotation-4" id="source-4">[4]</a> When [Biàn] Bǐng died, his son [Biàn] Lán succeeded. As a youth had talent and scholarship, <a href="#annotation-5" id="source-5">[5]</a> became Serving Chariots Commandant, Roaming Strike General, additionally Cavalier Regular Attendant. when [Biàn] Lán died, his son [Biàn] Huī succeeded. <a href="#annotation-6" id="source-6">[6]</a> Also divided [Biàn] Bǐng's noble title to enfeoff [Biàn] Lán's younger brother [Biàn] Lín as a Ranked Marquess, rank reached Infantry Colonel. [Biàn] Lán's son [Biàn] Lóng's daughter became the Duke of Gāoguì village's Imperial Empress, [Biàn] Lóng as the Empress's father became Radiant Grandee, rank Specially Advanced, enfeoffed Marquess of Suīyáng village, his wife Wáng became Lady of Xiǎnyáng village. Posthumously enfeoffed [Biàn] Lóng's previous wife Liú as Lady of Shùnyáng, because she was the Empress's birth mother. [Biàn] Lín's daughter also became the King of Chénliú's Imperial Empress. At the time [Biàn] Lín was already gone, enfeoffed [Biàn] Lín's wife Liú as Lady of Guǎngyáng.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
初，太后弟秉，以功封都鄉侯，黃初七年進封開陽侯，邑千二百戶，為昭烈將軍。〔一〕秉薨，子蘭嗣。少有才學，〔二〕為奉車都尉、游擊將軍，加散騎常侍。蘭薨，子暉嗣。〔三〕又分秉爵，封蘭弟琳為列侯，官至步兵校尉。蘭子隆女為高貴鄉公皇后，隆以后父為光祿大夫，位特進，封睢陽鄉侯，妻王為顯陽鄉君。追封隆前妻劉為順陽鄉君，后親母故也。琳女又為陳留王皇后，時琳已沒，封琳妻劉為廣陽鄉君。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-4" id="annotation-4">[4]</a> Wèi lüè states: Previously, Empress Biàn's younger brother [Biàn] Bǐng during the time of Jiàn'ān was only able to become a Separate Division Major, the Empress always complained to Tàizǔ, Tàizǔ answered saying: "But to be able to be my wife's younger brother, is that not a lot?" The Empress also wished for Tàizǔ to give him cash and silk, Tàizǔ also said: "But what you steal to give him, is it not enough?" Therefore to the end of Tàizǔ's reign, [Biàn] Bǐng's office did not change, and his wealth also did not increase.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏略曰：初，卞后弟秉，當建安時得為別部司馬，后常對太祖怨言，太祖答言：「但得與我作婦弟，不為多邪？」后又欲太祖給其錢帛，太祖又曰：「但汝盜與，不為足邪？」故訖太祖世，秉官不移，財亦不益。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-5" id="annotation-5">[5]</a> Wèi lüè states: [Biàn] Lán proffered a rhapsody praising and narrating the Heir-Apparent's virtues and beauties, the Heir-Apparent replied stating: "The Rhapsody is for saying where affairs by categories are to attach. The Eulogy is for beautifying the form and appearance of flourishing virtue. Therefore the composer is not empty in the statements, the receiver certainly must match the reality. [Biàn] Lán in this rhapsody, how is it my reality? In the past Wúqiū Shòuwáng had one explanation of a treasure tripod, Hé Wǔ and his peers for this san a eulogy, and yet received bestowments of gold and silk. Although [Biàn] Lán's statements are not accurate, the intention is enough to commend. Now bestow ox of one head." From then he therefore met with intimacy and respect.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　魏略曰：蘭獻賦贊述太子德美，太子報曰：「賦者，言事類之所附也，頌者，美盛德之形容也，故作者不虛其辭，受者必當其實。蘭此賦，豈吾實哉？昔吾丘壽王一陳寶鼎，何武等徒以歌頌，猶受金帛之賜，蘭事雖不諒，義足嘉也。今賜牛一頭。」由是遂見親敬。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-6" id="annotation-6">[6]</a> In Emperor Míng's time, [Biàn] Lán observed the exterior had two difficulties, but the Emperor left his attention on the Palace Residences, always took advantage of attending and following to repeatedly harshly remonstrate. Although the Emperor did not listen, yet he accepted the sincerity. Later [Biàn] Lán suffered from alcohol-induced wasting thirst [diabetes], at the time the Emperor trusted in a witch woman who used water techniques, and sent someone to carry the water to bestow on [Biàn] Lán. [Biàn] Lán would not agree to drink. Edict asked his reasoning. [Biàn] Lán said: "Treating illness surely should use medicine, why trust in this?" The Emperor because of this changed color [in displeasure], but [Biàn] Lán to the end would not swallow it. Later the thirst gradually worsened, so that he died. Because at the time people observed that [Biàn] Lán enjoyed blunt speech, they said that the Emperor had humiliated him and so [Biàn] Lán had killed himself, but in fact it was not so.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔三〕　魏略曰：明帝時，蘭見外有二難，而帝留意於宮室，常因侍從，數切諫。帝雖不能從，猶納其誠款。後蘭苦酒消渴，時帝信巫女用水方，使人持水賜蘭，蘭不肯飲。詔問其意？蘭言治病自當以方藥，何信於此？帝為變色，而蘭終不服。後渴稍甚，以至於亡。故時人見蘭好直言，謂帝面折之而蘭自殺，其實不然。
:::
:::
:::

## Wén-Zhāo Imperial Empress Zhēn {#wenzhao .unnumbered}

::: {.columns}
::: {.column width="70%"}
Wén-Zhāo Imperial Empress Zhēn was a Zhōngshān Wújí woman, Emperor Míng's mother, Hàn's Grand Protector^[Grand Protector (tàibǎo) was one of Zhōu's Three Excellencies along with Grand Preceptor (tàishī) and Grand Tutor (tàifù). These three offices were briefly restored near the end of Former Hàn as honored positions above Hàn's regular Three Excellencies.] Zhēn Hán's posterity.^[For Zhēn Hán see Hàn shū 18 and 19.] For generations they were officials at the two thousand dàn level. Her father [Zhēn] Yì was Shàngcài Magistrate. The Empress at three years lost her father. <a href="#annotation-7" id="source-7">[7]</a> later Heaven's Under was in war and chaos, and additionally due to hunger and famine, the Hundred Surnames all sold gold and silver and pearls and jade and treasure items, at the time the Empress's family greatly had stores of grain and tended to use it to buy them. The Empress's age was over ten years, and informed her mother stating: "The present age is in chaos but to yet buy many treasure items, 'an ordinary man is without crime, hiding jade makes him a criminal.'^[This is a quote from the Zuǒ Zhuàn, Duke Huán Tenth Year. This idiom is usually interpreted to mean that possessing valuables attracts danger.] Also Left and Right all are hungry and starving, it is not as good as using grain to rouse and give to family and clan and neighbors, widely extending grace and favor." The entire family declared it good, and at once followed the Empress's advice. <a href="#annotation-8" id="source-8">[8]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
文昭甄皇后，中山無極人，明帝母，漢太保甄邯後也，世吏二千石。父逸，上蔡令。后三歲失父。〔一〕後天下兵亂，加以饑饉，百姓皆賣金銀珠玉寶物，時后家大有儲穀，頗以買之。后年十餘歲，白母曰：「今世亂而多買寶物，匹夫無罪，懷璧為罪。又左右皆飢乏，不如以穀振給親族鄰里，廣為恩惠也。」舉家稱善，即從后言。〔二〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-7" id="annotation-7">[7]</a> Wèi shū states: [Zhēn] Yì took as wife Chángshān's Zhāng-shì, begat three sons five daughters: eldest son [Zhēn] Yù, early died, next [Zhēn] Yǎn nominated Filial-Incorruptible, General-in-Chief's Assistant, Qūliáng Chief; next [Zhēn] Yáo, nominated Filial-Incorruptible; eldest daughter Jiāng, next Tuō, next Dào, next Róng, next was the Empress. The Empress in Hàn's Guānghé Fifth Year Twelfth Moon Dīngyǒu [183 Jan 26] was born. Every time she slept, in the family they seemed to faintly see someone holding jade robe to cover her, they were always togethere bewildered by it. When [Zhēn] Yì died, she wailed and mourned,^[Hàomù is a term for mourning for the parents. See the Mèng-zǐ.] inside and outside increased their surprise of her. Later the physiognomist Liú Liáng appraised the Empress and the various children, [Liú] Liáng pointed at the Empress and said: "This girl's nobility then cannot be spoken of." The Empress from youth to maturity did not enjoy playing and games. Aged eight years, outside there were standing riders and horse performances, her family members and various older sisters all went up the pavilion to watch it, the Empress alone did not go. The various elder sisters were bewildered and asked her, the Empress answered saying: "How is this what women should watch?" Aged nine years, she enjoyed books, on seeing characters at once memorized, repeatedly used her various elder brothers' brush and ink, her elder brother spoke to the Empress saying: "You should practice women's work. Using books for study, will you be a female Academic Scholar?" The Empress replied saying: "Learning of antiquity's worthy women, never did they not study the previous eras' successes and failures, to be warnings for themselves. To not know books, how is one to observe this?"
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書曰：逸娶常山張氏，生三男五女：長男豫，早終；次儼，舉孝廉，大將軍掾、曲梁長；次堯，舉孝廉；長女姜，次脫，次道，次榮，次即后。后以漢光和五年十二月丁酉生。每寢寐，家中髣彿見如有人持玉衣覆其上者，常共怪之。逸薨，加號慕，內外益奇之。後相者劉良相后及諸子，良指后曰：「此女貴乃不可言。」后自少至長，不好戲弄。年八歲，外有立騎馬戲者，家人諸姊皆上閣觀之，后獨不行。諸姊怪問之，后答言：「此豈女人之所觀邪？」年九歲，喜書，視字輒識，數用諸兄筆硯，兄謂后言：「汝當習女工。用書為學，當作女博士邪？」后答言：「聞古者賢女，未有不學前世成敗，以為己誡。不知書，何由見之？」
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-8" id="annotation-8">[8]</a> Wèi lüè states: The Empress aged fourteen was in mourning for her middle elder brother [Zhēn] Yǎn, brief and sorrow exceeding regulations, served her widowed elder brother's wife with modesty and respect, serving in her chores, nurturing and raising [Zhēn] Yǎn's child, affection and love extremely sincere. The Empress's mother by nature was strict, treating her various daughters-in-law with constant standards, the Empress repeatedly remonstrated her mother: "Elder brother by misfortune early died, sister-in-law in youth maintains widowhood, looking after the remaining one child. By great righteousness speaking of it, treating her should be like a daughter-in-law, loving her should be like a daughter. Her mother was emotionally moved by the Empress's words and shed tears, and then ordered the Empress with her sister-in-law to live together, sleeing and resting and sitting and rising all following one another, affection and love increasingly close.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　魏略曰：后年十四，喪中兄儼，悲哀過制，事寡嫂謙敬，事處其勞，拊養儼子，慈愛甚篤。后母性嚴，待諸婦有常，后數諫母：「兄不幸早終，嫂年少守節，顧留一子，以大義言之，待之當如婦，愛之宜如女。」母感后言流涕，便令后與嫂共止，寢息坐起常相隨，恩愛益密。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
During Jiàn'ān, Yuán Shào for his middle son [Yuán] Xī accepted her. [Yuán] Xī was sent out to Yōu Province, the Empress remained to care for her mother-in-law. Reaching to Jì Province's pacification, Emperor Wén accepted the Empress at Yè, she had favor, bore Emperor Míng and the Dōngxiāng princess.<a href="#annotation-9" id="source-9">[9]</a> Yánkāng Inaugural Year Standard Moon, Emperor Wén succeeded the King's throne, Sixth Moon went on southern campaign, the Empress remained at Yè. Huángchū Inaugural Year Tenth Moon, the Emperor ascended the throne. After the ascension of the throne, the Duke of Shānyáng presented two daughters to be consorts of Wèi, Empress Guō, Lǐ and Yīn Noble Ladies all had favor and visits, the Empress was increasingly frustrated, having complaints. The Emperor was greatly furious. Second Year Sixth Moon, sent envoy to bestow death, buried at Yè.<a href="#annotation-10" id="source-10">[10]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
建安中，袁紹為中子熙納之。熙出為幽州，后留養姑。及冀州平，文帝納后于鄴，有寵，生明帝及東鄉公主。〔一〕延康元年正月，文帝即王位，六月，南征，后留鄴。黃初元年十月，帝踐阼。踐阼之後，山陽公奉二女以嬪于魏，郭后、李、陰貴人並愛幸，后愈失意，有怨言。帝大怒，二年六月，遣使賜死，葬于鄴。〔二〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-9" id="annotation-9">[9]</a> Wèi lüè states: [Yuán] Xī was sent out and at Yōu Province, the Empress remained to attend to her mother-in-law. When Yè city fell, [Yuán] Shào's wife and the Empress were seated together at the top of the Imperial Hall. Emperor Wén entered [Yuán] Shào's house, met [Yuán] Shào's wife and the Empress, the Empress was afraid, and buried her head in her mother-in-law's lap, [Yuán] Shào's wife with both hands beat herself.^[Beating oneself (zìbó) was a gesture of admitting guilt to beg for mercy.] Emperor Wén spoke stating: "Madame Liú why be like this? Have your daughter-in-law lift her head." The mother-in-law then raised the Empress to have her look up, Emperor Wén then looked at her, saw her beauty was out of the ordinary, praised and sighed of her. Tàizǔ heard his intentions, and therefore for him invited a marriage.

Shìyǔ states: Tàizǔ subdued Yè, Emperor Wén was first to enter Yuán Shàng's mansion, there was a woman with disheveled hair and dirtied face, shedding tears and standing behind [Yuán] Shào's wife Liú. Emperor Wén asked about her, Liú answered: "She is [Yuán] Xī's wife." Drawing her hair back into a bun, with cloth wiping her face, her beauty was beyond compare. After he left, Liú said to the Empress: "We no longer need worry of death." Therefore she met with acceptance [into the harem], had favor.

Wèi shū states: The Empress's favor all the more increased yet she was increasingly self-effacing, in the Rear Harem those that had favor she encouraged, the rest without favor she comforted and instructed. Everytime she took advantage of leisure feasts to always encourage the Emperor saying: "In the past Huáng-dì's descendants spread abundantly, overall because the concubines and consorts were numerous, and so they obtained these blessings. What I wish is widespread seeking of virtuous beauties, for abundant posterity." The Emperor in his heart commended this. After this the Emperor wished to send away Rén-shì, the Empress pleaded to the Emperor stating: "Rén is of a local famed clan, and in virtue and beauty We Your Concubines do not compare, why send her away?" The Emperor said: "Rén by nature is impetuous and rash and not graceful or obedient, beginning to end her angering of me is not only once, and therefore I send her away." The Empress shed tears and firmly pleaded stating: "That I Your Concubine have received the favor of respectful treatment, everyone knows, and will certainly say the sending out of Rén is because of Your Concubine. Above I fear there will be ridicule of selfishness, below I bear the crime of monopolizing favor. May you again leave attention." The Emperor did not listen, and therefore sent her out. Sixteenth Year [211] Seventh Moon, Tàizǔ campaigned against Guānzhōng, Imperial Empress Wǔ-Xuān accompanied, remained at Mèngjīn, the Emperor resided at and defended Yè. At the time Imperial Empress Wǔ-Xuān's body was slightly not at ease, the Empress was not able to inquire,^[Inquire (dìng shěng) refers to the ritual filial duty of daily inquiries on one's parents.] was worried and afraid, day and night shedding tears. Her Left and Right suddenly reported news of recovery, the Empress yet did not believe it, saying: "When the madame was at home, every time her old illness recurred, then it lasted for a time, now her illness suddenly recovers, how can it be so fast? This is only a wish to reassure my thoughts." Her worry was increasingly extreme. Later she obtained Imperial Empress Wǔ-Xuān's reply letter, saying the illness had already subsided, the Empress then was joyous and pleased. Seventeenth Year [212] Standard Moon, the main army returned to Yè, the Empress went to visit Imperial Empress Wǔ-Xuān, saw the canopy and seat and was both sorrowful and happy, emotionally moving the Left and Right. Imperial Empress Wǔ-Xuān saw the Empress was like this, and also sobbed, and moreover spoke to her stating: "Did my daughter-in-law think my previous illness was as serious as former times? It was only minor this time, in over ten days it at once recovered, do you not see my appearance?" She sighed and said: "This is a truly filial daughter-in-law." Twenty-First Year [216], Tàizǔ went on eastern campaign, Imperial Empress Wǔ-Xuān, Emperor Wén with Emperor Míng, Dōngxiāng princess all accompanied, at the time the Empress due to illness remained at Yè. Twenty-Second Year [217] Ninth Moon, the main army returned, Imperial Empress Wǔ-Xuān's Left and Right attendants and maids observed the Empress's complexion was plump, were bewildered and asked her stating: "You and your two children were separated for a long time, with one's feelings for one's posterity one cannot but worry, but yet your countenance is all the more flourishing, why?" The Empress laughed and answered them stating: "[Cáo] Ruì and the rest personally accompany the madame, why would I worry?" The Empress's worthy enlightenment and self-restraint by ritual was like this.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏略曰：熙出在幽州，后留侍姑。及鄴城破，紹妻及后共坐皇堂上。文帝入紹舍，見紹妻及后，后怖，以頭伏姑膝上，紹妻兩手自搏。文帝謂曰：「劉夫人云何如此？令新婦舉頭！」姑乃捧后令仰，文帝就視，見其顏色非凡，稱歎之。太祖聞其意，遂為迎取。世語曰：太祖下鄴，文帝先入袁尚府，有婦人被髮垢面，垂涕立紹妻劉後，文帝問之，劉答「是熙妻」，顧攬髮髻，以巾拭面，姿貌絕倫。既過，劉謂后「不憂死矣」！遂見納，有寵。魏書曰：后寵愈隆而彌自挹損，後宮有寵者勸勉之，其無寵者慰誨之，每因閑宴，常勸帝，言「昔黃帝子孫蕃育，蓋由妾媵眾多，乃獲斯祚耳。所願廣求淑媛，以豐繼嗣。」帝心嘉焉。其後帝欲遣任氏，后請於帝曰：「任既鄉黨名族，德、色，妾等不及也，如何遣之？」帝曰：「任性狷急不婉順，前後忿吾非一，是以遣之耳。」后流涕固請曰：「妾受敬遇之恩，眾人所知，必謂任之出，是妾之由。上懼有見私之譏，下受專寵之罪，願重留意！」帝不聽，遂出之。十六年七月，太祖征關中，武宣皇后從，留孟津，帝居守鄴。時武宣皇后體小不安，后不得定省，憂怖，晝夜泣涕；左右驟以差問告，后猶不信，曰：「夫人在家，故疾每動，輒歷時，今疾便差，何速也？此欲慰我意耳！」憂愈甚。後得武宣皇后還書，說疾已平復，后乃懽悅。十七年正月，大軍還鄴，后朝武宣皇后，望幄座悲喜，感動左右。武宣皇后見后如此，亦泣，且謂之曰：「新婦謂吾前病如昔時困邪？吾時小小耳，十餘日即差，不當視我顏色乎！」嗟歎曰：「此真孝婦也。」二十一年，太祖東征，武宣皇后、文帝及明帝、東鄉公主皆從，時后以病留鄴。二十二年九月，大軍還，武宣皇后左右侍御見后顏色豐盈，怪問之曰：「后與二子別久，下流之情，不可為念，而后顏色更盛，何也？」后笑答之曰：「（諱）〔叡〕等自隨夫人，我當何憂！」后之賢明以禮自持如此。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-10" id="annotation-10">[10]</a> Wèi shū states: Relevant managers memorialized to establish a Chángqiū Palace, the Emperor's Ruler's Seal marked letter invited the Empress to visit where he was traveling, the Empress sent up memorial stating: "Your Concubine has heard that in the risings of former dynasties, the ways they enjoyed states for a long time, bequeathing blessings to their postiery, none were not by empresses and consorts. Therefore one certainly must examine the selection of the people, to raise the inner teachings. Now at the beginning of the ascension to the throne, truly it is appropriate to ascend and advance the worthy and virtuous, to unite and manage the Six Palaces. Your Concubine examines herself as ignorant and crude, not capable of serving the millet vessel^[The millet vessel (zīchéng) was a ritual tool in ancestral sacrifices, which the Empress would participate in.] and moreover as I am lying ill, I dare maintain my meager intentions." Ruler's Seal marked letter thrice arrived but the Empress thrice declined, words extremely earnest and cutting. At the time it was the peak of the summer heat, the Emperor wished to wait for the autumn cooling to then again invite the Empress. It happened the Empress's illness became critical, Summer Sixth Moon Dīngmǎo [221 Aug 4], passed away at Yè. The Emperor grieved and sighed, posthumously conferred Imperial Empress's Ruler's Seal and Cord.

Your Servant Sōngzhī believes: In the principles of the Chūnqiū, internal large evils are taboo, small evils are not written.^[In the classic history Chūnqiū, when recording the state's internal affairs, major bad events (assassinations, regicides, coups) are only hinted at indirectly through careful word choice and euphemisms, and minor bad events are considered details too trivial to be worth recording. The former was done to protect state dignity and political legitimacy, and the latter to keep the text concise as a high level overview. Usually the various explanatory commentaries such as the Zuǒ Zhuàn then provide more explicit explanations of taboo events and various additional minor details. To some extent this general practice continued into the Sān Guó zhì, with Chén Shòu using euphemisms for certain large scandals and generally omitting small events, and Péi Sōngzhī's annotations explaining the euphemisms and adding additional minor stories.] That Emperor Wén did not establish Zhēn-shì, and further applied killing, the matter has clear verification. If the Wèi historians believed it a large evil, then they should have concealed and not spoken, and if they said it was a small evil, then they should not have false made these statements, but yet to esteem ornamental false writings as far as this, it is different from what is expected from the old histories. Elaborating from this and speaking, the praises of the excellence of the words and conduct of the various Empresses Biàn and Zhēn, all are difficult to truly discuss. Chén-shì^[Chén Shòu was the primary compiler of the Sān Guó zhì.] deleting and omitting them had a good reason.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　魏書曰：有司奏建長秋宮，帝璽書迎后，詣行在所，后上表曰：「妾聞先代之興，所以饗國久長，垂祚後嗣，無不由后妃焉。故必審選其人，以興內教。令踐阼之初，誠宜登進賢淑，統理六宮。妾自省愚陋，不任粢盛之事，加以寢疾，敢守微志。」璽書三至而后三讓，言甚懇切。時盛暑，帝欲須秋涼乃更迎后。會后疾遂篤，夏六月丁卯，崩于鄴。帝哀痛咨嗟，策贈皇后璽綬。臣松之以為春秋之義，內大惡諱，小惡不書。文帝之不立甄氏，及加殺害，事有明審。魏史若以為大惡邪，則宜隱而不言，若謂為小惡邪，則不應假為之辭，而崇飾虛文乃至於是，異乎所聞於舊史。推此而言，其稱卞、甄諸后言行之善，皆難以實論。陳氏刪落，良有以也。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
When Emperor Míng succeeded the throne, relevant managers memorialized to request granting posthumous title, sent Excellency of Works Wáng Lǎng Holding Stave to present conferment with Grand Offering to announce and sacrifice at the tomb, also separately established a Tomb Temple. <a href="#annotation-11" id="source-11">[11]</a> Tàihé Inaugural Year [227], Third Moon, used a thousand households from Zhōngshān's Wèichāng's Ānchéng village to posthumously enfeoff [Zhēn] Yì, posthumous name called Marquess Jìng, the successor grandson [Zhēn] Xiàng inheriting the noble title. Fourth Moon, first built the Ancestral Temple, in digging found a jade Ruler's Seal, square one cùn nine fēn, its inscription stating: "Heaven's Son longingly remembers his compassionate parent." Emperor Míng because of this changed expression, used Grand Offering to report to the Temple. Also he once dreamed of seeing the Empress, and thereupon by distinguished sequencing of his maternal clan by closeness or distance [of relation] and high or low, ranked and employed each on distinct basis, the rewards and bestowments accumulated to massive tens of thousands. Appointed [Zhēn] Xiàng as Tiger Elite Central Cadet General. That Moon, the Empress's mother died, the Emperor wore mourning linen and oversaw the mourning, the hundred officials in accompanying positions. Fourth Year [230] Eleventh Moon, as the Empress's old tomb was low and inferior, sent [Zhēn] Xiàng as concurrent Grand Commandant Holding Stave to visit Yè to clearly announce [a relocation] to Lordly Earth^[Lordly Earth (hòutǔ) referred to the gods of earth, or specifically to a Goddess of Earth], Twelfth Moon, changed the burial to Cháoyánglíng. [Zhēn] Xiàng returned, promoted to Cavalier Regular Attendant. Qīnglóng Second Year [234] Spring, bestowed posthumous title on the Empress's elder brother [Zhēn] Yǎn as Ānchéng village Marquess Mù. Summer, Wú rebels invaded Yáng Province, appointed [Zhēn] Xiàng as Subduing Waves General, Holding Stave as Supervisor over the various officers on eastern campaign, returned, reverted to Shooting Sound Colonel. Third Year [235] he died, posthumously titled Guard General, changed enfeoffment to Wèichāng county, posthumous title called Marquess Zhēn, his son [Zhēn] Chàng succeeded, also enfeoffed [Zhēn] Chàng's younger brothers [Zhēn] Wēn, [Zhēn] Wěi, [Zhēn] Yàn all as Ranked Marquesses. Fourth Year [236], changed [Zhēn] Yì's and [Zhēn] Yǎn's original enfeoffments to all be called Wèichāng Marquess, the postumous names as before. Enfeoffed [Zhēn] Yǎn's wife Liú as Lady of Dōngxiāng, also posthumously enfeoffed [Zhēn] Yì's wife Zhāng as Lady of Ānxǐ
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
明帝即位，有司奏請追諡，使司空王朗持節奉策以太牢告祠于陵，又別立寢廟。〔一〕太和元年三月，以中山魏昌之安城鄉戶千，追封逸，諡曰敬侯；適孫像襲爵。四月，初營宗廟，掘地得玉璽，方一寸九分，其文曰「天子羨思慈親」，明帝為之改容，以太牢告廟。又嘗夢見后，於是差次舅氏親疏高下，敘用各有差，賞賜累鉅萬；以像為虎賁中郎將。是月，后母薨，帝制緦服臨喪，百僚陪位。四年十一月，以后舊陵庳下，使像兼太尉，持節詣鄴，昭告后土，十二月，改葬朝陽陵。像還，遷散騎常侍。青龍二年春，追諡后兄儼曰安城鄉穆侯。夏，吳賊寇揚州，以像為伏波將軍，持節監諸將東征，還，復為射聲校尉。三年薨，追贈衛將軍，改封魏昌縣，諡曰貞侯；子暢嗣。又封暢弟溫、〈華韋〉、豔皆為列侯。四年，改逸、儼本封皆曰魏昌侯，諡因故。封儼世婦劉為東鄉君，又追封逸世婦張為安喜君。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-11" id="annotation-11">[11]</a> Wèishū records the Three Excellencies' memorial stating: "Overall the Way of filial respect is devotion to one's parents, and thus how the Four Seas receives transformation, how Heaven and Earth is enlightened in perception, and so it is said when living then convey them to nuturing, when dead then glorify their spirits, recite and narrate to fulfill their beauty, raise proclamations to make prominent their names. Now Your Majesty by sagely esteemed virtue, continues and inherits a vast enterprise, utmost filial piety rising and rising, reaching to the divine intelligences, encountered the suffering of abundant grief, every time toiling in modest deference. The Former Emperor moved his spirit to the mountain tomb, the great rituals already completed, but as for the Former Empress, she does not yet have prominent posthumous name. In prostration considering the Former Empress's respectful deference was proven in the remote and subtle, utmost conduct prominent in the unspoken, cultivating flowing to country and state, virtue equal to the Two Nán,^[The Zhōu Nán and Shào Nán are two sections in the Shī jīng.] therefore able to receive auspicious blessings of the divine spirits, to be Great Wèi's generational consort. Although early in years to ascend afar, after ten thousand years, forever will spread her harmonious illustriousness, in the achievements of empresses and consorts none are able to obtain and surpass. Consulting the Shìfǎ^['The Method of Posthumous Names' is an ancient text providing guidelines on how to grant posthumous names to summarize an individual's life and achievements.]: 'Sagely Reputation Everywhere Reaching is called Zhāo,' 'Virtue Brilliant and Having Achievements is called Zhāo.' Zhāo is the utmost of light brilliance, flourishing for a long time and yet not darkening. It is appropriate to offer up honoring posthumous name called Wén-Zhāo Huánghòu." That Moon, the Three Excellencies also memorialized stating: "Since antiquity the Zhōu men had as Shǐzǔ Hòujì, and also specially established a Temple to sacrifice to Jiāng Yuán.^[Hòujì was honored as the Shǐzǔ "First Ancestor" that founded the clan that would become the Zhōu dynasty ruling house. Jiāng Yuán was the mother of Hòujì.] Now what Wén-Zhāo Huánghòu gives to ten thousand inheritances, the sagely virtue and utmost cultivation, how can it be measured? With the honor of the generational consort of the Imperial family, yet restrained and deferential thoroughly respectful, she firmly declined magnificent position, her divine spirit passed and transformed, but yet is without Tomb Temple to convey offerings and sacrifices, this is not how to repay prominent virtue, manifest filial respect. Consulting the ancient regulations, it is appropriate to comply with the Zhōu Lǐ, and for the Late Mother separately establish a Tomb Temple." Both memorials were approved.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書載三公奏曰：「蓋孝敬之道，篤乎其親，乃四海所以承化，天地所以明察，是謂生則致其養，歿則光其靈，誦述以盡其美，宣揚以顯其名者也。今陛下以聖懿之德，紹承洪業，至孝烝烝，通於神明，遭罹殷憂，每勞謙讓。先帝遷神山陵，大禮既備，至於先后，未有顯諡。伏惟先后恭讓著於幽微，至行顯於不言，化流邦國，德侔二南，故能膺神靈嘉祥，為大魏世妃。雖夙年登遐，萬載之後，永播融烈，后妃之功莫得而尚也。案諡法：『聖聞周達曰昭。德明有功曰昭。』昭者，光明之至，盛久而不昧者也。宜上尊諡曰文昭皇后。」是月，三公又奏曰：「自古周人始祖后稷，又特立廟以祀姜嫄。今文昭皇后之於萬嗣，聖德至化，豈有量哉！夫以皇家世（祀）〔妃〕之尊，而克讓允恭，固推盛位，神靈遷化，而無寢廟以承享（禮）〔祀〕，非所以報顯德，昭孝敬也。稽之古制，宜依周禮，先妣別立寢廟。」並奏可之。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Jǐngchū Inaugural Year [237] Summer, relevant managers discussed and determined the Seven Temples. Winter, also memorialized stating: Overall in the rise of Emperors and Kings, there are lords of receiving the Mandate, and also there are sagely consorts harmonizing with the divine spirits, only afterward is there successful flourishing of their descendants, to achieve the King's enterprise. In the past Gāoxīnshì divined that his sons by his four consorts would all possess Heaven's Under, and so Emperor Zhì, Táo Táng, Shāng, and the Zhōu dynasties rose. The Zhōu men above traced [their lineage] to Hòujì, matching to August Heaven, but recalling the King's beginnings, the origin was Jiāng Yuán, specially establishing Palace Temple, generation to generation enjoying sacrifices, what the Zhōu Lǐ called: 'Play the Yízé, sing the Zhōnglǚ, dance the Dàhuò, to offer to the Late Mother.' The poets eulogized her stating: 'The first birth of the people, was by Jiāng Yuán,'^[This is from the poem Shēng Mín in the Shī jīng.] to say that the root of the King's influence, is the source of the birth of the people. It also states: 'The solemn palace has silence, solid solid dense dense, dazzling dazzling Jiāng Yuán, her virtue unturning.'^[This is a quote from the song Bì Gōng in the Shī jīng.] The Shī and Lǐ so praised the magnificence of the Jī clan, its beauty was like this. Great Wèi's allotted fate is the succession from Yǒu Yú, but in esteeming the vast Emperor's Way, Three Generations all the more expanding, the count of the Temple Halls, is in fact with Zhōu the same. Now Wǔ-Xuān Huánghòu [Biàn], Wén-Dé Huánghòu [Guō] each match with blessings without bound.^[Wǔ-Xuān matches to Tàizǔ Cáo Cāo and Wén-Dé matches to Gāozǔ Cáo Pī, and thus share in their permanent Temple Name positions in the Ancestral Temples.] As for Wén-Zhāo Huánghòu, she received Heaven's spiritual signs, giving birth to the enlightened sage [Cáo Ruì], achievements relieving the living people, virtue filling the cosmos, opened the way to all posterity successions, and so she is way moral cultivation has risen. Tomb Temple special sacrifices is also the Solemn Palace of Jiāng Yuán, but yet there is not yet written regulation of no dismantling,^[Most ancestral temples were eventually dismantled to make room for more recent ancestors. The Seven Temples system maintained permanent positions for particularly distinguished ancestors that were not to be dismantled while the dynasty endured.] and one fears the principles of discussing achievements and repaying virtues after ten thousand generations may be lacking, and this is not the way to manifest filial piety to show to later generations. The Wén-Zhāo Temple should generation to generation enjoy offerings and perform music, with the Zǔ Temples the same.^[Wèi established permanent temple positions for Tàizǔ Cáo Cāo, Gāozǔ Cáo Pī, and Lièzǔ Cáo Ruì] forever written in the canon to not dismantle, to spread the airs of sagely excellence." Thereupon it with the Seven Temples discussions were all engraved on metal talleys, stored in the metal coffers.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
景初元年夏，有司議定七廟。冬，又奏曰：「蓋帝王之興，既有受命之君，又有聖妃協于神靈，然後克昌厥世，以成王業焉。昔高辛氏卜其四妃之子皆有天下，而帝摯、陶唐、商、周代興。周人上推后稷，以配皇天，追述王初，本之姜嫄，特立宮廟，世世享嘗，周禮所謂『奏夷則，歌中呂，舞大濩，以享先妣』者也。詩人頌之曰：『厥初生民，時維姜嫄。』言王化之本，生民所由。又曰：『閟宮有侐，實實枚枚，赫赫姜嫄，其德不回。』詩、禮所稱姬宗之盛，其美如此。大魏期運，繼于有虞，然崇弘帝道，三世彌隆，廟祧之數，實與周同。今武宣皇后、文德皇后各配無窮之祚，至於文昭皇后膺天靈符，誕育明聖，功濟生民，德盈宇宙，開諸後嗣，乃道化之所興也。寢廟特祀，亦姜嫄之閟宮也，而未著不毀之制，懼論功報德之義，萬世或闕焉，非所以昭孝示後世也。文昭廟宜世世享祀奏樂，與祖廟同，永著不毀之典，以播聖善之風。」於是與七廟議並勒金策，藏之金匱。
:::
:::

::: {.columns #caofangzhen}
::: {.column width="70%"}
The Emperor thought longlingly of his maternal clan without end. [Zhēn] Chàng was still young, at Jǐngchū's end, appointed [Zhēn] Chàng as Shooting Sound Colonel, added Cavalier Regular Attendant, also specially for him raised a large mansion, the Chariot Carriage personally visited it. Also in its Rear Garden for [Zhēn] Xiàng's mother raised a Tower Temple, naming its neighborhood called Wèiyáng Neighborhood,^[There is a song titled Wèiyáng in the Shī jīng, generally interpreted as a song of a son mourning his mother.] to commemorate his mother's clan. Jiāpíng Third Year [251] Standard Moon, [Zhēn] Chàng died, posthumously titled Chariots and Cavalry General, posthumous name called Marquess Gōng, his son [Zhēn] Shào succeeded. Tàihé Sixth Year [232], Emperor Míng's beloved daughter [Cáo] Shū died, posthumously enfeoffed [Cáo] Shū as Píngyuán Princess Yì, for her established a Temple, took the Empress's deceased cousin's grandson [Zhēn] Huáng for joint burial with her [in a posthumous marriage], posthumously enfeoffed [Zhēn] Huáng as a Ranked Marquess, using the consort Guō-shì's younger cousin [Guō] Dé to be their posterity, taking the Zhēn clan family name, enfeoffed [Guō/Zhēn] Dé as Marquess of Píngyuán, to inherit the princess's noble title. <a href="#annotation-12" id="source-12">[12]</a> During Qīnglóng, also enfeoffed the Empress's elder cousin's sons [Zhēn] Yì and [Zhēn] Xiàng's younger brothers, three people, to all be Ranked Marquesses. [Zhēn] Yì repeatedly sent up memorials explaining the time's governance, office reached Surpassing Cavalry Colonel.  During Jiāpíng, further enfeoffed [Zhēn] Chàng's sons, two people, as Ranked Marquesses. The Empress's elder brother [Zhēn] Yǎn's granddaughter became the King of Qí's [Cáo Fāng's] Imperial Empress, the Empress's father was already gone, enfeoffed the Empress's mother as Lady of Guǎnglè village.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
帝思念舅氏不已。暢尚幼，景初末，以暢為射聲校尉，加散騎常侍，又特為起大第，車駕親自臨之。又於其後園為像母起觀廟，名其里曰渭陽里，以追思母氏也。嘉平三年正月，暢薨，追贈車騎將軍，諡曰恭侯；子紹嗣。太和六年，明帝愛女淑薨，追封諡淑為平原懿公主，為之立廟。取后亡從孫黃與合葬，追封黃列侯，以夫人郭氏從弟德為之後，承甄氏姓，封德為平原侯，襲公主爵。〔一〕青龍中，又封后從兄子毅及像弟三人，皆為列侯。毅數上疏陳時政，官至越騎校尉。嘉平中，復封暢子二人為列侯。后兄儼孫女為齊王皇后，后父已沒，封后母為廣樂鄉君。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%" #zhende}
<a href="#source-12" id="annotation-12">[12]</a> Sūn Shèng states: By Ritual, women are without standards of enfeoffment and nobility, all the more for an infant, yet how can there be establishment of a great estate? [Guō/Zhēn] Dé was from a different clan, to be taken as successor to not his own [family] kind, had neither achievement nor blood relation, but yet to inherit [adoptive] mother's nobility title, violating emotion and turning back on canon, in this it was extreme. Although Chén Qún spoke in defiance, Yáng Fù cited [historical] events for comparison, however both were not able to thoroughly explain the Ritual of the Former Kings, enlighten the meanings of fief establishments and inheritance successions, the statements of loyal sincerity yet had deficiencies. The Shī says: 'Dazzling dazzling Shī Yǐn, the people all look to you.' The duties of the governing assistants, can they be neglected?

Jìn Zhūgōng Zàn states: [Zhēn/Guō] Dé appellation Yànsūn. When Sīmǎ [Shī] Jǐng-wáng assisted the government, he had his daughter be wife to Dé. The wife early died, [Sīmǎ Zhāo] Wén-wáng again had his daughter be the successor wife, who was the Elder Princess of Jīngzhào. Jǐng and Wén two Kings wished to bind themselves to Empress Guō, and therefore repeatedly arranged marriages. Although Dé was without talent or scholarship, but yet was respectful and attentive and modest and obedient. Zhēn Wēn appellation Zhòngshū, with Guō Jiàn and Dé and the rest all were of the Empresses's clans, and for usefulness in affairs met with favor. At Xiánxī's beginning, enfeoffed Guō Jiàn as Duke of Línwèi county, Dé as Duke of Guǎng'ān county, estates all one thousand eight hundred households. [Zhēn] Wēn was originally Marquess of a state, advanced to be Assisting the State General, added Attendant Central, designate Shooting Sound Colonel, Dé was Defending Army General-in-Chief. Tàishǐ Inaugural Year [265], Jìn received the abdication, applied on [Guō] Jiàn, [Zhēn/Guō] Dé, [Zhēn] Wēn three men position as Specially Advanced. Dé as a man was pure and unadorned, and additionally as Shìzǔ's [Sīmǎ Yán's] elder sister's husband, therefore was noble in his generation. Dé in his declining years in office again transferred to Minister of the Clan, promoted to Attendant Central. During Tàikāng, Marshal-in-Chief and King of Qí [Sīmǎ] Yōu was sent to his fief, Dé with Left Guard General Wáng Jì together remonstrated and pleaded, at the time people commended them. Shìzǔ because of this was disappointed in Dé, and because of this sent out Dé to be Minsiter Herald, added Attendant Central and Radiant Grandee. Soon he died of illness, posthumously titled Central Army General-in-Chief, Opening Office, Attendant Central as before, posthumous name Duke Gōng, his son Xǐ succeeded. Xǐ was refined and concise, had capacity and beauty, successively was Central Writers Cadet, Right Guard General, Attendant Central, position reached Assisting the State General-in-Chief, added Cavalier Regular Attendant. Xǐ with the state was related by marriage, but undergoing the incidents of the King of Zhào [Sīmǎ] Lún and the King of Qí [Sīmǎ] Jiǒng, he was able to not be entangled in the junctures, truly because his talent was lacking, however also as he retired quietly to avoid it.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　孫盛曰：於禮，婦人既無封爵之典，況于孩末，而可建以大邑乎？德自異族，援繼非類，匪功匪親，而襲母爵，違情背典，於此為甚。陳群雖抗言，楊阜引事比並，然皆不能極陳先王之禮，明封建繼嗣之義，忠至之辭，猶有闕乎！詩云：「赫赫師尹，民具爾瞻。」宰輔之職，其可略哉！晉諸公贊曰：德字彥孫。司馬景王輔政，以女妻德。妻早亡，文王復以女繼室，即京兆長公主。景、文二王欲自結于郭后，是以頻繁為婚。德雖無才學，而恭謹謙順。甄溫字仲舒，與郭建及德等皆后族，以事宜見寵。咸熙初，封郭建為臨渭縣公，德廣安縣公，邑皆千八百戶。溫本國侯，進為輔國大將軍，加侍中，領射聲校尉，德鎮軍大將軍。泰始元年，晉受禪，加建、德、溫三人位特進。德為人貞素，加以世祖姊夫，是以遂貴當世。德暮年官更轉為宗正，遷侍中。太康中，大司馬齊王攸當之藩，德與左衛將軍王濟共諫請，時人嘉之。世祖以此望德，由此出德為大鴻臚，加侍中、光祿大夫，尋疾薨，贈中軍大將軍，開府侍中如故，諡恭公，子喜嗣。喜精粹有器美，歷中書郎、右衛將軍、侍中，位至輔國大將軍，加散騎常侍。喜與國姻親，而經趙王倫、齊王冏事故，能不豫際會，良由其才短，然亦以退靜免之。
:::
:::
:::

## Wén-Dé Imperial Empress Guō {#wende .unnumbered}

::: {.columns}
::: {.column width="70%"}
Wén-Dé Imperial Empress Guō was an Ānpíng Guǎngzōng woman. Her ancestors for generations were chief clerks. <a href="#annotation-13" id="source-13">[13]</a> When the Empress was young her father [Guō] Yǒng marveled at her and said: "This is the King among my daughters." Therefore Nǚ​wáng became her appellation.^[Nǚ can mean woman, female, daughter. Nǚwáng can mean "female king."] She early lost her two parents, in the decline and chaos wandered homeless, seized and entered the household of the Marquess of Tóngdī. When Tàizǔ became Duke of Wèi, she was able to enter the East Palace.^[East Palace (dōng gōng) referred to the household of the Heir-Apparent (tàizǐ). The term is used anachronistically here to refer to Cáo Pī's household even before he was officially designated the Heir-Apparent.] The Empress had wisdom and calculations, time after time her offered [plans] were accepted. In Emperor Wén being determined as successor, the Empress had [contributing] plans. When the Heir-Apparent succeeded the King's position, the Empress became a Fūrén, and reaching to the ascension to the [Imperial] throne, she became a Guìpín. The death of Empress Zhēn was because of the favor for the Empress. Huángchū Third Year [222], when about to raise the Empress's position, Emperor Wén wished to establish her as Empress, Central Cadet Zhàn Qián sent up memorial stating: "When the past Emperors and Kings governed Heaven's Under, there was not only outer assistants [from ministers], also there were inner aid [from spouses], the origin of governance or chaos, prosperity or decline follows it. Therefore Xīlíng matched Huáng[-dì], Yīng and É descended to Guī,^[Yīng and É refer to the two daughters of Yáo who were married to Shùn at the Guī river.] all for their worthiness and enlightenment left behind fragrant [reputation] in high antiquity. Jié fleeing to Náncháo, the disaster rose from Mòxǐ;^[Mòxǐ was a consort of Jié, last of ruler of Xià. Jié was overthrown and fled, leading to the replacement of Xià by Shāng.] Zhòu used pillar branding to please Dájǐ.^[Zhòu was the last King of Shāng, overthrown in the transition from Shāng to Zhōu. In legends, Zhòu used a torture method of tying victims to a heated bronze pillar to entertain one of his consorts, Dájǐ.] Therefore the sages were cautious in establishing the primary consort, certain to choose families of the generational clans of former eras, selecting the good and virtuous to preside over the Six Palaces, to reverently serve the Ancestral Temple, feminine instruction in accordance to cultivation. The Yì states: 'The Family Way is correct and then Heaven's Under is settled.' From the inner to the outer, is the good canon of the Former Kings. The Chūnqiū writes the Clan Minister smeared blood oath on Xià Yún, to never treat a concubine with the rituals for a madame. Qí Huán's oath mandate at Kuíqiū, also stated 'Never take a concubine as wife.' Now the Rear Palace favorites all are always second to the chariot carriage.^[Chariot charriage (chéngyú) is a euphemism for the Emperor.] If because of affection she is elevated to Empress, causing a lowly woman to suddenly be noble, Your Servant fears later generations will have subordinates usurp and replace superiors, opening the way to violations of limits, chaos from above rising." Emperor Wén did not listen, and therefore established her as Imperial Empress. <a href="#annotation-14" id="source-14">[14]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
文德郭皇后，安平廣宗人也。祖世長吏。〔一〕后少而父永奇之曰：「此乃吾女中王也。」遂以女王為字。早失二親，喪亂流離，沒在銅鞮侯家。太祖為魏公時，得入東宮。后有智數，時時有所獻納。文帝定為嗣，后有謀焉。太子即王位，后為夫人，及踐阼，為貴嬪。甄后之死，由后之寵也。黃初三年，將登后位，文帝欲立為后，中郎棧潛上疏曰：「在昔帝王之治天下，不惟外輔，亦有內助，治亂所由，盛衰從之。故西陵配黃，英娥降媯，並以賢明，流芳上世。桀奔南巢，禍階末喜；紂以炮烙，怡悅妲己。是以聖哲慎立元妃，必取先代世族之家，擇其令淑以統六宮，虔奉宗廟，陰教聿修。易曰：『家道正而天下定。』由內及外，先王之令典也。春秋書宗人釁夏云，無以妾為夫人之禮。齊桓誓命于葵丘，亦曰『無以妾為妻』。今後宮嬖寵，常亞乘輿。若因愛登后，使賤人暴貴，臣恐後世下陵上替，開張非度，亂自上起也。」文帝不從，遂立為皇后。〔二〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-13" id="annotation-13">[13]</a> Wèi shū states: Her father [Guō] Yǒng's office reached Nán prefecture Administrator, posthumous name Marquess Jìng. Her mother surnamed Dǒng-shì was the Lady of Tángyáng, bore three sons two daughters: eldest son [Guō] Fú was a Gāotáng Magistrate, next daughter [Guō] Yù, next was the Empress, the Empress's younger brother [Guō] Dū, younger brother Guō [Chéng]. The Empress in Hàn's Zhōngpíng Inaugural Year Third Moon Yǐmǎo [184 Apr 8] was born, at her birth there were unusual signs.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書曰：父永，官至南郡太守，諡敬侯。母姓董氏，即堂陽君，生三男二女：長男浮，高唐令，次女昱，次即后，后弟都，弟成。后以漢中平元年三月乙卯生，生而有異常。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-14" id="annotation-14">[14]</a> Wèi shū states: The Empress sent up memorial to decline, stating: "Your Concubine is without the integrity of Huáng and Yīng descending,^[This refers to the two daughters of Yáo being granted down to Shùn.] and also is not of the level of Jiāng and Rén pondering how to match^[Jiāng was a consort of King Xuān of Zhōu, Rén was the mother of King Wén of Zhōu. 'Pondering how to match' (sīqí) refers to seeing someone of great virtue and thinking of how to reach that level.] truly not sufficient to impose on the magnificent position of the female lord, to occupy the heavy responsibility of the central offerings." The Empress from when she was in the East Palace to when she ascended the Honored Position, although she had exceptional favor, her heart was all the more respectful and solemn, caring for and nurturing the Yǒngshòu Palace,^[Referring to her mother-in-law, Dowager Biàn] famed for her filial piety. At that time Noble Lady^[Guírén, a high position in the harem.] Chái also had favor, the Empress instructued and encouraged and guided her. When the Rear Palace's various Noble Ladies at times had errors, always she would cover for them, and if there were censures and reprimands, at once she would explain to the Emperor from beginning to end. If the Emperor was greatly angered, it reached to her knocking her head [on the ground] to plead for the crime, and because of this the Six Palaces were without complaints. By nature she was frugal, did not enjoy music, always admired Hàn's Míng-Dé Empress Mǎ's^[For Empress Mǎ, consort of Hàn Emperor Míng, see Hòu Hàn shū 10.] conduct as a woman.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　魏書曰：后上表謝曰：「妾無皇、英釐降之節，又非姜、任思齊之倫，誠不足以假充女君之盛位，處中饋之重任。」后自在東宮，及即尊位，雖有異寵，心愈恭肅，供養永壽宮，以孝聞。是時柴貴人亦有寵，后教訓獎導之。後宮諸貴人時有過失，常彌覆之，有譴讓，輒為帝言其本末，帝或大有所怒，至為之頓首請罪，是以六宮無怨。性儉約，不好音樂，常慕漢明德馬后之為人。
:::
:::
:::

::: {.columns}
::: {.column width="70%" #guobiao #mengwu}
The Empress early lost her elder and younger brothers, had her elder cousin [Guō] Biǎo succeed as [Guō] Yǒng's posterity, appointed Serving Chariots Commandant. The Empress's maternal relative Liú Fěi with another state was bethrothed, the Empress heard of this, her orders said: "The various relatives in marriages should be with equal matches with families of their hometowns, and should not take advantage of their power to force marriages with people of other regions." The Empress's elder sister's son Mèng Wǔ to his hometown to seek a lesser wife [concubine], the Empress stopped him. Therefore her orders to the various families said: "In the present age women are few, and should be matched with officers and soldiers. Do not take advantage of status to take them as concubines. You should each be self-cautious, and not be the first to incur punishments. <a href="#annotation-15" id="source-15">[15]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
后早喪兄弟，以從兄表繼永後，拜奉車都尉。后外親劉斐與他國為婚，后聞之，敕曰：「諸親戚嫁娶，自當與鄉里門戶匹敵者，不得因勢，彊與他方人婚也。」后姊子孟武還鄉里，求小妻，后止之。遂敕諸家曰：「今世婦女少，當配將士，不得因緣取以為妾也。宜各自慎，無為罰首。」〔一〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-15" id="annotation-15">[15]</a> Wèi shū states: The Empress always admonished and warned [Guō] Biǎo and [Mèng] Wǔ and others stating: "The Hàn clan's [in-law] families of the Pepper Rooms [Jiāofáng "Pepper Rooms" was the name of a Hall in the Palace of the Empress during Western Hàn, reportedly from a practice of using a fragrant pepper paste to paint the walls. It became a term to refer to the Empresses and Consorts in general.] few were able to preserve themselves, all because of arrogance and extravagance.^[See the downfalls of various powerful consort families as recorded in Hòu Hàn shū 10.] Can you not be cautious?"
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏書曰：后常敕戒表、武等曰：「漢氏椒房之家，少能自全者，皆由驕奢，可不慎乎！」
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Fifth Year [224], the Emperor went on eastern campaign, the Empress remained at Xǔchāng's Yǒngshǐ Terrace. At the time it continuously rained for over a hundred days, of the city walls and towers many were damaged, relevant managers memorialized to request she relocate her residence. The Empress said: "In the past Chǔ King Zhāo went out on tour, Zhēn Jiāng remained at Jiān Terrace, the Jiāng's [flood] waters arrived, the envoy invited her [to relocate] but was without [the authentication] talismen, she did not leave, and in the end drowned. Now the Emperor is far away, I fortunately do not yet have such a crisis, but to yet relocate residence, how can it be?" Of the various ministers none dared again speak.
Sixth Year [225], the Emperor went on eastern campaign against Wú, reached Guǎnglíng the Empress remained at Qiáo Palace. At the time [Guō] Biǎo remained in the Residential Guard, and wished to restrain the waters to catch fish. The Empress said: "The water should be connected for transport canals, and also there is few timber and wood, if the slaves and retainers are not kept before your eyes, they will further privately steal government bamboo and wood to build bridges and dams. Now what the Serving Chariots [Commandant] lacks, how is it fish?"
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
五年，帝東征，后留許昌永始臺。時霖雨百餘日，城樓多壞，有司奏請移止。后曰：「昔楚昭王出游，貞姜留漸臺，江水至，使者迎而無符，不去，卒沒。今帝在遠，吾幸未有是患，而便移止，奈何？」群臣莫敢復言。六年，帝東征吳，至廣陵，后留譙宮。時表留宿衛，欲遏水取魚。后曰：「水當通運漕，又少材木，奴客不在目前，當復私取官竹木作梁遏。今奉車所不足者，豈魚乎？」
:::
:::

::: {.columns}
::: {.column width="70%"}
When Emperor Míng succeeded the throne, honored the Empress as Imperial Dowager Empress, called as Yǒng'ān Palace. Tàihé Fourth Year [230], Edict enfeoffed [Guō] Biǎo as Marquess of Ānyáng precinct, also advanced the noble title to Marquess of a village, increased estate adding to the previous [to total] five hundred households, promoted to Central Ramparts General. Appointed [Guō] Biǎo's son [Guō] Xiáng as Cavalry Commandant. That Year, the Emperor posthumously titled the Dowager Empress's father [Guō] Yǒng as Marquess Jìng of Ānyáng village, mother Dǒng as Lady of a city village. Promoted [Guō] Biǎo as Shining Virtue General, applied gold [seal] and purple [ribbon], position as Specially Advanced. [Guō] Biǎo's second son [Guō] Xùn became a Cavalry Commandant. When Mèng Wǔ's mother died, he wished to lavishly bury and raise a sacrifice hall, the Dowager Empress stopped him stating: "From the decline and chaos onward, of graves and tombs none were not excavated, all because of lavish burials. Shǒuyánglíng can be the standard."^[Shǒuyánglíng was the tomb of Cáo Pī, which used a frugal burial to avoid attracting grave robbers.] Qīnglóng Third Year [235] Spring, the Empress passed away at Xǔchāng, following [Cáo Pī's] Final Regulations built the tomb, Third Moon Gēngyín [235 Apr 16], buried at Shǒuyánglíng's west. <a href="#annotation-16" id="source-16">[16]</a> The Emperor advanced [Guō] Biǎo's noble title to Marquess of Guànjīn,^[Guànjīn county was in Ānpíng prefecture.] increased estate by five hundred, adding to the previous [to total] one thousand households. Promoted [Guō] Xiáng as Attached Horse Commandant. Fourth Year [236], posthumously changed the enfeoffment of [Guō] Yǒng to Marquess Jìng of Guànjīn, his wife Dǒng to be Lady of Tángyáng. Posthumously enfeoffed and titled the Empress's elder brother [Guō] Fú as Marquess Dài of Liánglǐ precinct,^[The posthumous name Dài "Supportive" has connotations of caring for the people and following etiquette without erring. Liánglǐ precinct may have been in Guànjīn county.] [Guō] Dū as Marquess Xiào of Wǔchéng preinct,^[The posthumous name Xiào "Filial" has connotations of filial peity. Wǔchéng precinct may have been in Guànjīn county.] [Guō] Chéng as Marquess Dìng of Xīnlè precinct,^[The posthumous name Dìng "Determined" has connotations of providing stability, Xīnlè precinct may have been in Guànjīn county.] all had sent envoys to present the conferments, sacrifices with Grand Offerings. When [Guō] Biǎo died, his son [Guō] Xiáng succeeded, also divided [Guō] Biǎo's noble title to enfeoff [Guō] Xiáng's younger brother [Guō] Shù as a Ranked Marquess. When [Guō] Xiáng died, his son [Guō] Zhāo succeeded.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
明帝即位，尊后為皇太后，稱永安宮。太和四年，詔封表安陽亭侯，又進爵鄉侯，增邑并前五百戶，遷中壘將軍。以表子詳為騎都尉。其年，帝追諡太后父永為安陽鄉敬侯，母董為都鄉君。遷表昭德將軍，加金紫，位特進，表第二子訓為騎都尉。及孟武母卒，欲厚葬，起祠堂，太后止之曰：「自喪亂以來，墳墓無不發掘，皆由厚葬也；首陽陵可以為法。」青龍三年春，后崩于許昌，以終制營陵，三月庚寅，葬首陽陵西。〔一〕帝進表爵為觀津侯，增邑五百，并前千戶。遷詳為駙馬都尉。四年，追改封永為觀津敬侯，世婦董為堂陽君。追封諡后兄浮為梁里亭戴侯，都為武城亭孝侯，成為新樂亭定侯，皆使使者奉策，祠以太牢。表薨，子詳嗣，又分表爵封詳弟述為列侯。詳薨，子釗嗣。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-16" id="annotation-16">[16]</a> Wèi lüè states: When Emperor Míng succeeded the throne, he recalled the pain of Empress Zhēn's death, and therefore the Dowager Empress in anxiety suddenly passed away. When Empress Zhēn faced death, she had the Emperor entrusted to Madame Lǐ. When the Dowager Empress passed away, the madame then explained the disaster of Empress Zhēn meeting with slander, not obtaining the main shroud, disheveled hair covering the face. The Emperor in grief and resentment shed tears, and mandated that the encoffining and burial of the Dowager Empress would all be by the precedent of Empress Zhēn.

Hàn Jìn Chūnqiū states: Previously, the execution of Empress Zhēn was because of the favor for Empress Guō. At the encoffining, it was ordered to have the disheveled hair cover the face, with chaff stuffing the mouth, and therefore established Empress Guō, having her raise Emperor Míng. The Emperor knew of it, his heart always harbored anger, repeatedly he sobbed and asked of the circumstances of Empress Zhēn's death. Empress Guō said: "The Former Emperor himself killed her, why blame and question me? Moreover you as a son of others, can you have posthumous enmity for your deceased father, or for your previous mother unjustly kill your later mother?" Emperor Míng was angry, and therefore oppressed her to death, ordering the encoffining to be by the precedent of Empress Zhēn.

Wèi shū records the Mourning Conferment stated: "On Qīnglóng Third Year Third Moon Rénshēn,^[There is a transmission error here as Qínglóng Third Year Third Moon should not contain a Rénshēn day. A possible alternative may be Second Moon Rénshēn [235 Mar 29].] the Imperial Dowager Empress's catalpa palace^[Catalpa palace (zǐgōng) is a euphemistic term for a coffin, referencing the catalpa wood used for the construction.] was opened for the encoffining, about to be buried at Shǒuyáng's West Tomb. The Grieving Son Imperial Emperor [I, Cáo] Ruì personally presented the texts for the ancestral conveyance,^[The ancestral conveyance (zǔ zǎi) is a term for the two funerary ceremonies between the encoffinment and the burial: first an ancestral sacrifice in the coffin hall, then the loading of the coffin onto a carriage to deliver to the tomb.] and then personally sent the libations, beating chest and jumping [in sorrow], wailing and looking up to complain [to Heaven], pained by the departure of the soul, sorrowful at the apperanace chariot^[The appearance chariot (róng chē) was the chariot at the front of the ceremonial funeral procession, carrying a portrait of the deceased.] heading on the road turning back on the three lights to be hidden away, into the yellow clay and quietly placed. Oh alas! In the past the two daughters were consrts to Yú, the Emperor's Way by this manifested; the three mothers were wives of Zhōu, sagely excellence all the more glorious, having received many blessings, they enjoyed the state for long. Grieving grieving for loving mother, who raised and cultivated the women's rooms, dragon flying to violet utmost, joined with the Sagely Imperial, unexpectedly in middle age, suddenly suffering disaster. Pitiable me the small son, desolate desloate broken and wounded, although the soul is forever gone, where can I look for my inquries?^[Inquiries (dìng shěng) refers to the filial duty of daily inquiries on one's parents.] Oh alas!"
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏略曰：明帝既嗣立，追痛甄后之薨，故太后以憂暴崩。甄后臨沒，以帝屬李夫人。及太后崩，夫人乃說甄后見譖之禍，不獲大斂，被髮覆面，帝哀恨流涕，命殯葬太后，皆如甄后故事。漢晉春秋曰：初，甄后之誅，由郭后之寵，及殯，令被髮覆面，以糠塞口，遂立郭后，使養明帝。帝知之，心常懷忿，數泣問甄后死狀。郭后曰：「先帝自殺，何以責問我？且汝為人子，可追讎死父，為前母枉殺後母邪？」明帝怒，遂逼殺之，敕殯者使如甄后故事。魏書載哀策曰：「維青龍三年三月壬申，皇太后梓宮啟殯，將葬于首陽之西陵。哀子皇帝叡親奉冊祖載，遂親遣奠，叩心擗踊，號咷仰訴，痛靈魂之遷幸，悲容車之向路，背三光以潛翳，就黃壚而安厝。嗚呼哀哉！昔二女妃虞，帝道以彰，三母嬪周，聖善彌光，既多受祉，享國延長。哀哀慈妣，興化閏房，龍飛紫極，作合聖皇，不虞中年，暴罹災殃。愍予小子，煢煢摧傷，魂雖永逝，定省曷望？嗚呼哀哉！」
:::
:::
:::

## Míng-Dào Imperial Empress Máo {#mingdao .unnumbered}

::: {.columns}
::: {.column width="70%" #maojia #maozeng}
Míng-Dào Imperial Empress Máo was a Hénèi woman. During Huángchū, she was selected to enter the East Palace, Emperor Míng at the time was King of Píngyuán, she was advanced to service him and had favor, going out and coming in sharing the same carriage. When he succeeded the Emperor's position, she became a Guìpín. Tàihé Inaugural Year [227], established as Imperial Empress. The Empress's father [Máo] Jiā was appointed a Cavalry Commandant, the Empress's younger brother [Máo] Zēng a Cadet Central.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
明悼毛皇后，河內人也。黃初中，以選入東宮，明帝時為平原王，進御有寵，出入與同輿輦。及即帝立，以為貴嬪。太和元年，立為皇后。后父嘉，拜騎都尉，后弟曾，郎中。
:::
:::

::: {.columns}
::: {.column width="70%"}
Previously, when Emperor Míng was King, he first accepted Hénèi's Yú-shì as a consort. When the Emperor succeeded the throne, Yú-shì was not established as Empress, Grand Imperial Dowager Empress Biàn comforted and consoled her. Yú-shì said: "The Cáo clan naturally enjoys establishing the lowly, never once able to raise by righteousness. However the Empress's duty is in inner affairs, the Lord deals with outer governance, these principles complement one another for completion. If one is not able to begin with the good, never is there the ability to have a good end. Almost certainly from this will be the destruction of the state and the loss of sacrifices." Yú-shì therefore was demoted and sent back to Yè Palace.
Advanced [Máo] Jiā to be Serving Chariots Commandant, [Máo] Zēng Cavalry Commandant, the favor and bestowments icnreasingly applied. Shortly after this, enfeoffed [Máo] Jiā as Marquess of Bópíng village, promoted to Radiant Grandee, [Máo] Zēng to Attached Horse Commandant. [Máo] Jiā originally managed chariot labor, very suddenly obtained wealth and nobility, Emperor Míng had the Court ministers gather at his house for drinking and feasting, his demeanor and movements were extremely foolish and ignorant, when speaking then he called himself "My Marquess Self," at the time people laughed at him. <a href="#annotation-17" id="source-17">[17]</a> Later also applied on [Máo] Jiā position as Specially Advanced, [Máo] Zēng promoted to Cavalier Attendant Cadet. Qīnglóng Third Year [235], [Máo] Jiā died, posthumously titled Radiant Grandee, changed enfeoffment to Marquess of Ānguó, increased estate by five hundred, adding to the previous [to total] one thousand households, posthumous name called Marquess Jié. Fourth Year [236], posthumously enfeoffed the Empress's mother Xià as Lady of Yěwáng.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
初，明帝為王，始納河內虞氏為妃，帝即位，虞氏不得立為后，太皇后卞太后慰勉焉。虞氏曰：「曹氏自好立賤，未有能以義舉者也。然后職內事，君聽外政，其道相由而成，苟不能以善始，未有能令終者也。殆必由此亡國喪祀矣！」虞氏遂絀還鄴宮。進嘉為奉車都尉，曾騎都尉，寵賜隆渥。頃之，封嘉博平鄉侯，遷光祿大夫，曾駙馬都尉。嘉本典虞車工，卒暴富貴，明帝令朝臣會其家飲宴，其容止舉動甚蚩騃，語輒自謂「侯身」，時人以為笑。〔一〕後又加嘉位特進，曾遷散騎侍郎。青龍三年，嘉薨，追贈光祿大夫，改封安國侯，增邑五百，并前千戶，諡曰節侯。四年，追封后母夏為野王君。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-17" id="annotation-17">[17]</a>
Sūn Shèng states: The ancient Kings were certain to seek the good and virtuous to match the raising of utmost virtue, expanding the royal influence to Guānjū,^[Guānjū is a song in the Shī jīng interpreted as about a noble man finding a wife, and thus a metaphor for a virtuous consort] conveying pure manner to Línzhǐ.^[Línzhǐ is a reference to a song in the Shī jīng and used as a metaphor for the prosperity of one's descendants.] Reaching to the end of the Three Dynasties,^[Referring to Xià, Shāng, Zhōu.] chaos consumed these threads, righteousness was drowned in passions, positions muddled by favoritism, noble and lowly were not distinct, subordinates usurped and replaced superiors, rise and decline and expansion and fall, all are the results. Wèi from Wǔ-wáng [Cáo Cāo] reaching to Lièzǔ [Cáo Ruì], Three Empresses in their ascension all rose from the obscure and lowly. When the roots are from the inferior, how can there be a long reign? The Shī says: 'Fine cloth or coarse cloth, frigid they are from the wind.' Is this what it speaks of?
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　孫盛曰：古之王者，必求令淑以對揚至德，恢王化於關雎，致淳風于麟趾。及臻三季，並亂茲緒，義以情溺，位由寵昏，貴賤無章，下陵上替，興衰隆廢，皆是物也。魏自武王，暨于烈祖，三后之升，起自幽賤，本既卑矣，何以長世？詩云：「絺兮綌兮，淒其以風。」其此之謂乎！
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
When the Emperor favored the Empress Guō Yuán,^[Guō is the family name, Yuán is the posthumous name. See Empress Míng-Yuán below.] the Empress's favor daily weakened. Jǐngchū Inaugural Year [237], the Emperor was touring the Rear Garden, and summoned Cáirén and above to a private feast in utmost revelry. Empress Yuán said: "It is appropriate to invite the Imperial Empress." The Emperor did not permit it, and so forbade the Left and Right, to have it not announced. The Empress learned of this, the next day, the Emperor met the Empress, the Empress said: "Yesterday's tour and feast in the North Garden, was it enjoyable?" The Emperor believed the Left and Right had leaked it, those killed were over ten people. Bestowed the Empress with death,^[Bestowal with death (cì sǐ) was forced suicide. It was called a bestowal because it was considered being granted an alternative to the disgrace of an execution.] however yet applied posthumous name, buried at Mǐnlíng. Promoted [Máo] Zēng to Cavalier Regular Attendant, later transferred to Feather Forest Tiger Elite Central Cadet General, Yuánwǔ Manager of Agriculture.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
帝之幸郭元后也，后愛寵日弛。景初元年，帝游後園，召才人以上曲宴極樂。元后曰「宜延皇后」，帝弗許。乃禁左右，使不得宣。后知之，明日，帝見后，后曰：「昨日游宴北園，樂乎？」帝以左右泄之，所殺十餘人。賜后死，然猶加諡，葬愍陵。遷曾散騎常侍，後徙為羽林虎賁中郎將、原武典農。
:::
:::

## Míng-Yuán Imperial Empress Guō {#mingyuan .unnumbered}

::: {.columns}
::: {.column width="70%"}
Míng-Yuán Imperial Empress Guō was a Xīpíng woman, for generations a powerful clan of Héyòu. During Huángchū, her home prefecture rebelled, and therefore she was taken to enter the Palace. When Emperor Míng succeeded the throne, she extremely met with affection and favor, appointed as a Madame. Her father's younger brother [Guō] Lì became a Cavalry Commandant, cousin's father [Guō] Zhī became Tiger Elite Central Cadet General. The Emperor's illness was critical, and therefore she was established as Imperial Empress. When the King of Qí succeeded the throne, honored the Empress as Imperial Dowager Empress, called as Yǒngníng Palace, posthumously enfeoffed and posthumous title on the Dowager Empress's father [Guō] Mǎn as Marquess Dìng of Xīdū, using [Guō] Lì's son [Guō] Jiàn to continue the noble rank. Enfeoffed the Dowager Empress's mother Dù as Lady of Héyáng. [Guō] Zhī was promoted to Cavalier Regular Attendant, Cháng River Colonel, <a href="#annotation-18" id="source-18">[18]</a>  [Guō] Lì to Announcing Virtue General, all enfeoffed as Ranked Marquesses. [Guō] Jiàn's elder brother [Guō] Dé was sent out to be adopted by the Zhēn clan. [Guō] Dé with [Guō] Jiàn both became Defending and Protecting Generals, all enfeoffed as Ranked Marquesses, together handling the Residential Guard. It happened that the Three Rulers were young and weak, the governing assistant controlled the government, participating and seizing great affairs, all first consulted and informed the Doager Empress and only afterward was put into effect. When Guànqiū Jiǎn and Zhōng Huì and others made chaos, all falsely claimed her mandates as their justification. Jǐngyuán Fourth Year Twelfth Moon she passed away, Fifth Year Second Moon buried at Gāopínglíng's west. <a href="#annotation-19" id="source-19">[19]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
明元郭皇后，西平人也，世河右大族。黃初中，本郡反叛，遂沒入宮。明帝即位，甚見愛幸，拜為夫人。叔父立為騎都尉，從父芝為虎賁中郎將。帝疾困，遂立為皇后。齊王即位，尊后為皇太后，稱永寧宮，追封諡太后父滿為西都定侯，以立子建紹其爵。封太后母杜為郃陽君。芝遷散騎常侍、長水校尉，〔一〕立，宣德將軍，皆封列侯。建兄德，出養甄氏。德及建俱為鎮護將軍，皆封列侯，並掌宿衛。值三主幼弱，宰輔統政，與奪大事，皆先咨啟於太后而後施行。毌丘儉、鍾會等作亂，咸假其命而以為辭焉。景元四年十二日崩，五年二月，葬高平陵西。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-18" id="annotation-18">[18]</a> Wèi lüè states: Among the various Guō, [Guō] Zhī was the most stalwart and upright. Before this time he already for another achievement was enfeoffed as a Marquess.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魏略曰：諸郭之中，芝最壯直。先時自以他功封侯。
:::
:::
:::

::: {.callout-note appearance="minimal" #guojian}
::: {.columns}
::: {.column width="70%"}
<a href="#source-19" id="annotation-19">[19]</a> Jìn Zhūgōng Zàn states: Jiàn appellation Shūshǐ had capacity and decorum and strong learning, during Tàishǐ died of illness. His son [Guō] Gǔ succeeded, became a Dispensing Affairs Central.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　晉諸公贊曰：建安叔始，有器局而彊問，泰始中疾薨。子嘏嗣，為給事中。
:::
:::
:::

## Appraisal {.unnumbered}

::: {.columns}
::: {.column width="70%"}
Appraisal states: The families of Wèi's Empresses and Consorts, although they enjoyed wealth and nobility, never once was there like in the decline of Hàn any taking of improper position or seizing control of Court governance. Reflecting on the past to change course, in this was beauty. Looking back on Chén Qún's discussion, Zhàn Qián's discourse, they are suitably sufficient to be a standard canon for a Hundred Kings, to be bequeathed as a standard model for later generations.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
評曰：魏后妃之家，雖云富貴，未有若衰漢乘非其據，宰割朝政者也。鑒往易軌，於斯為美。追觀陳群之議，棧潛之論，適足以為百王之規典，垂憲範乎後葉矣。 
:::
:::