# Biographies of Lǚ Bù and Zāng Hóng

## Lǚ Bù {.unnumbered #lvbu}

::: {.columns}
::: {.column width="70%"}
Lǚ Bù appellation Fèngxiān was a Wǔyuán prefecture Jiǔyuán man. For his valor and military ability he served in Bìng Province, the Inspector Dīng Yuán became Cavalry Commandant, garrisoned Hénèi, with [Lǚ] Bù as his Registrar, greatly meeting with close treatment. When Emperor Líng passed away, [Dīng] Yuán led troops to visit Luòyáng, <a href="#annotation-1" id="source-1">[1]</a> with Hé Jìn plotting to execute the various Yellow Gate, appointed Metal Mace Bearer. [Hé] Jìn was destroyed, Dǒng Zhuó entered the capital city, about to make chaos, wished to kill [Dīng] Yuán, take over his troops and multitudes. [Dǒng] Zhuó because [Lǚ] Bù met with trust from [Dīng] Yuán, enticed [Lǚ] Bù to have him kill [Dīng] Yuán. [Lǚ] Bù cut off [Dīng] Yuán's head and visited [Dǒng] Zhuó, [Dǒng] Zhuó appointed [Lǚ] Bù as Cavalry Commandant, extremely favored and trusted him, swore to act as father and son.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
呂布字奉先，五原郡九原人也。以驍武給并州。刺史丁原為騎都尉，屯河內，以布為主簿，大見親待。靈帝崩，原將兵詣洛陽。〔一〕與何進謀誅諸黃門，拜執金吾。進敗，董卓入京都，將為亂，欲殺原，并其兵眾。卓以布見信于原，誘布令殺原。布斬原首詣卓，卓以布為騎都尉，甚愛信之，誓為父子。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-1" id="annotation-1">[1]</a> Yīngxióng jì states: [Dīng] Yuán appellation Jiànyáng, originally came from a poor family, as a man was crude and coarse, had military valor, skilled in riding and shooting. Became a Nán county clerk,^[There was no Nán county during Hàn. This may be an error for Shā'nán county in Yúnzhōng prefecture in Bìng Province.] in receiving missions did not decline from difficulties, when there were alarms or emergencies, or pursuit of bandits or caitiffs, then at once he was at the front. He was barely literate, and rarely had clerk duties.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　英雄記曰：原子建陽。本出自寒家，為人麤略，有武勇，善騎射。為南縣吏，受使不辭難，有警急，追寇虜，輒在其前。裁知書，少有吏用。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
[Lǚ] Bù was skilled with bow and horse, his bodily strength surpassed other men, called as Flying General. Gradually promoted to reach Central Cadet General, enfeoffed a city precinct Marquess. [Dǒng] Zhuó himself knew he treated others without respect, feared others would plot against him, wherever he went or stayed he always had [Lǚ] Bù guard him. However [Dǒng] Zhuó by nature was strong-willed but narrow-minded, in anger did not think of the troubles, once for a small disappointment, he grabbed a hand halberd and threw it at [Lǚ] Bù. [Lǚ] Bù had vigor and speed and dodged it, <a href="#annotation-2" id="source-2">[2]</a> attended to and apologized to [Dǒng] Zhuó, [Dǒng] Zhuó's thoughts also resolved. Because of this he secretly hated [Dǒng] Zhuó. [Dǒng] Zhuó always [Lǚ] Bù defend the central boudoirs, [Lǚ] Bù with [Dǒng] Zhuó's attendant maid had an illicit affair, feared the matter would be discovered, in his heart was not at ease with himself.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
布便弓馬，膂力過人，號為飛將。稍遷至中郎將，封都亭侯。卓自以遇人無禮，恐人謀己，行止常以布自衛。然卓性剛而褊，忿不思難，嘗小失意，拔手戟擲布。布拳捷避之，〔一〕為卓顧謝，卓意亦解。由是陰怨卓。卓常使布守中閤，布與卓侍婢私通，恐事發覺，心不自安。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-3" id="annotation-3">[3]</a> Shī states: "No vigor no valor, precisely a source of chaos." Annotation states: "Agility is strength."
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　詩曰：「無拳無勇，職為亂階。」注：「拳，力也。」
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Before this, Excellency over the Masses Wáng Yǔn because
[Lǚ] Bù was of the same region and strong and healthy, generously treated and accepted him. Later [Lǚ] Bù visited [Wáng] Yǔn, explained the circumstances of how [Dǒng] Zhuó had almost killed him. At the time [Wáng] Yǔn with Deputy Director Shìsūn Ruì secretly plotted to execute [Dǒng] Zhuó, and therefore informed [Lǚ] Bù to have him be inner assistance. [Lǚ] Bù said: "But we are like father and son!" [Wáng] Yǔn said: "Your natural surname is Lǚ, originally not bone and flesh kin. Now you worry that death will come anytime, what is this talk of father and son?" Lǚ] Bù therefore agreed to it, with his own hand and blade stabbed [Dǒng] Zhuó. [The story is in [Dǒng] Zhuó's biography.](06.qmd#dongzhuo) [Wáng] Yǔn appointed [Lǚ] Bù as Exerting Warfare General, Lent Stave, rituals comparable to the Three Excellencies, advanced enfeoffment to Marquess of Wēn,^[Wēn county was in Hénèi prefecture.] together maintaining the Court and government. [Lǚ] Bù from since after he killed [Dǒng] Zhuó feared and hated Liáng Province men, the Liáng Province men were all resentful. Because of this Lǐ Jué and others therefore joined together and returned to attack Cháng'ān city. <a href="#annotation-4" id="source-4">[4]</a> [Lǚ] Bù could not resit, [Lǐ] Jué and the rest therefore entered Cháng'ān. Sixty days after [Dǒng] Zhuó died, [Lǚ] Bù also was defeeated. <a href="#annotation-5" id="source-5">[5]</a> He led several hundred cavalry out Wǔ Pass, wishing to visit Yuán Shù.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
先是，司徒王允以布州里壯健，厚接納之。後布詣允，陳卓幾見殺狀。時允與僕射士孫瑞密謀誅卓，是以告布使為內應。布曰：「奈如父子何！」允曰：「君自姓呂，本非骨肉。今憂死不暇，何謂父子？」布遂許之，手刃刺卓。語在卓傳。允以布為（奮威）〔奮武〕將軍，假節，儀比三司，進封溫侯，共秉朝政。布自殺卓後，畏惡涼州人，涼州人皆怨。由是李傕等遂相結還攻長安城。〔一〕布不能拒，傕等遂入長安。卓死後六旬，布亦敗。〔二〕將數百騎出武關，欲詣袁術。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-4" id="annotation-4">[4]</a> Yīngxióng jì states: Guō Sì was at the city's north. [Lǚ] Bù opened the city gate, led troops to meet [Guō] Sì, said: "For now let us withdraw troops and personally decide victory or defeat." [Guō] Sì and [Lǚ] Bù then alone together faced in battle, [Lǚ] Bù with his lance pierced and hit [Guō] Sì, [Guō] Sì's rear cavalry therefore advanced to rescue [Guō] Sì, [Guō] Sì and [Lǚ] Bù therefore each both withdrew.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　英雄記曰：郭汜在城北。布開城門，將兵就汜，言「且卻兵，但身決勝負」。汜、布乃獨共對戰，布以矛刺中汜，汜後騎遂前救汜，汜、布遂各兩罷。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-5" id="annotation-5">[5]</a> Your Servant Sōngzhī cites Yīngxióng jì stating: In the various books [Lǚ] Bù in the Fourth Moon Twenty-Third Day [192 May 22] killed [Dǒng] Zhuó, Sixth Moon First Day [192 Jun 28] defeated and fled. At the time also there was no intercalary moon, it did not reach sixty days.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　臣松之案英雄記曰：諸書，布以四月二十三日殺卓，六月一日敗走，時又無閏，不及六旬。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
[Lǚ] Bù himself believed that by killing [Dǒng] Zhuó he had avenged [Yuán] Shù and wished to be repaid for it. [Yuán] Shù hated his going back and forth, refused and would not receive him. To the north visited Yuán Shào, [Yuán] Shào with [Lǚ] Bù struck Zhāng Yān at Chángshān. [Zhāng] Yān had elite troops of over ten thousand, cavalry of several thousand. [Lǚ] Bù had a good horse called Chìtù,^[The name can be interpreted as "Red Hare"] <a href="#annotation-6" id="source-6">[6]</a> always with his close intimates Chéng Lián, Wèi Yuè and others pierced vanguards and charged formations, and therefore defeated [Zhāng] Yān's army. But he requested additional troops and multitudes, the officers and servicemen plundered and robbed, [Yuán] Shào worried of and dreaded him. [Lǚ] Bù discovered his intentions, and from [Yuán] Shào requested to leave. [Yuán] Shào feared he would return to harm him, sent strong warriors in the night to surprise and kill [Lǚ] Bù, did not capture him. The matter was exposed, [Lǚ] Bù fled to Hénèi, <a href="#annotation-7" id="source-7">[7]</a> with Zhāng Yáng joining. [Yuán] Shào ordered multitudes to purse him, all feared [Lǚ] Bù, none dared to draw near. <a href="#annotation-8" id="source-8">[8]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
布自以殺卓為術報讎，欲以德之。術惡其反覆，拒而不受。北詣袁紹，紹與布擊張燕于常山。燕精兵萬餘，騎數千。布有良馬曰赤兔。〔一〕常與其親近成廉、魏越等陷鋒突陳，遂破燕軍。而求益兵眾，將士鈔掠，紹患忌之。布覺其意，從紹求去。紹恐還為己害，遣壯士夜掩殺布，不獲。事露，布走河內，〔二〕與張楊合。紹令眾追之，皆畏布，莫敢逼近者。〔三〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-6" id="annotation-6">[6]</a> Cáo Mán zhuàn states: At the time people had a saying stating: "Among men there is Lǚ Bù, among horses there is Chìtù."
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　曹瞞傳曰：時人語曰：「人中有呂布，馬中有赤兔。」
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-7" id="annotation-7">[7]</a> Yīngxióng jì states: [Lǚ] Bù himself believed he had achievements helping the Yuán clan, was disparaging and arrogant to [Yuán] Shào's subordinate various officers, believing their office appointments of each other without authority was not worth respecting. [Lǚ] Bù requested to return to Luò, [Yuán] Shào lent [Lǚ] Bù designate authority as Director of Retainers Colonel. Outside he said he would send him off, inside he wished to kill [Lǚ] Bù. The next day when about to depart, [Yuán] Shào sent armored servicemen of thirty men, claiming to escort [Lǚ] Bù. [Lǚ] Bù had them stop beside his tent, falsely had someone inside the tent play a zither. [Yuán] Shào's troops lay down, [Lǚ] Bù soon after went out the tent and left, and the troops did not know. In the middle of the night the troops rose, chaotically chopped [Lǚ] Bù's bed and quilt, and said he was already dead. The next day [Yuán] Shào investigated, discovered [Lǚ] Bù was still alive, and so closed the city gates. [Lǚ] Bù therefore withdrew and left.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　英雄記曰：布自以有功于袁氏，輕傲紹下諸將，以為擅相署置，不足貴也。布求還洛，紹假布領司隸校尉。外言當遣，內欲殺布。明日當發，紹遣甲士三十人，辭以送布。布使止于帳側，偽使人于帳中鼓箏。紹兵臥，布無何出帳去，而兵不覺。夜半兵起，亂斫布床被，謂為已死。明日，紹訊問，知布尚在，乃閉城門。布遂引去。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-8" id="annotation-8">[8]</a> Yīngxióng jì states: [Zhāng] Yáng and his division retainers various officers all received bounty offers from [Lǐ] Jué and [Guō] Sì to together plot against [Lǚ] Bù. [Lǚ] Bù heard of this, spoke to [Zhāng] Yáng stating: "[I, Lǚ] Bù am of your home region. If you kill [me, Lǚ] Bù, it will weaken you. It is not as good as selling [me, Lǚ] Bù. You can maximize the noble ranks and favor obtained from [Guō] Sì and [Lǐ] Jué." [Zhāng] Yáng thereupon outside agreed to [Guō] Sì and [Lǐ] Jué, inside in fact protected [Lǚ] Bù. [Guō] Sì and [Lǐ] Jué worried of this, further sent down great enfeoffment Edict letter, appointing [Lǚ] Bù as Yǐngchuān Administrator.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔三〕　英雄記曰：楊及部曲諸將，皆受傕、汜購募，共圖布。布聞之，謂楊曰：「布，卿州里也。卿殺布，於卿弱。不如賣布，可極得汜、傕爵寵。」楊於是外許汜、傕，內實保護布。汜、傕患之，更下大封詔書，以布為潁川太守。
:::
:::
:::


### Zhāng Miǎo {.unnumbered #zhangmiao}

::: {.columns}
::: {.column width="70%"}
Zhāng Miǎo appellation Mèngzhuó was a Dōngpíng Shòuzhāng man. In youth for his vigilantism famed, he aided the poor and rescued those in emergencies, overturning his family wealth without favoritism, of servicemen many submitted to him. Tàizǔ /[Cáo Cāo/] and Yuán Shào both with [Zhāng] Miǎo were friends. Recruited to the Excellency's Offices, for high performance appointed Cavalry Commandant, promoted to Chénliú Administrator. In the chaos of Dǒng Zhuó, Tàizǔ with [Zhāng] Miǎo were first to raise Righteous Troops. In the battle of Biàn river, [Zhāng] Miǎo sent Wèi Zī to lead troops to accompany Tàizǔ. Yuán Shào had become Alliance Leader, had arrogant expression, [Zhāng] Miǎo with upright commentary reprimanded [Yuán] Shào. [Yuán] Shào sent Tàizǔ to kill [Zhāng] Miǎo, Tàizǔ would not listen, reprimanded [Yuán] Shào stating: "Mèngzhuó is close friend, right or wrong he should be tolerated. Now Heaven's Under is not yet settled, it is not appropriate to endager one another." [Zhāng] Miǎo learned of this, increased his respect of Tàizǔ. When Tàizǔ campaigned against Táo Qiān, he ordered his family stating: "If I do not return, go rely on Mèngzhuó." Later he returned, met [Zhāng] Miǎo, shed tears in facing him. Their closeness was like this.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
張邈字孟卓，東平壽張人也。少以俠聞，振窮救急，傾家無愛，士多歸之。太祖、袁紹皆與邈友。辟公府，以高第拜騎都尉，遷陳留太守。董卓之亂，太祖與邈首舉義兵。汴水之戰，邈遣衛茲將兵隨太祖。袁紹既為盟主，有驕矜色，邈正議責紹。紹使太祖殺邈，太祖不聽，責紹曰：「孟卓，親友也，是非當容之。今天下未定，不宜自相危也。」邈知之，益德太祖。太祖之征陶謙，敕家曰；「我若不還，往依孟卓。」後還，見邈，垂泣相對。其親如此。
:::
:::

::: {.columns}
::: {.column width="70%"}
When Lǚ Bù left Yuán Shào to follow Zhāng Yáng, he passed by [Zhāng] Miǎo and when about to separate, held hands and swore oath together. [Yuán] Shào heard of this and was greatly resentful. [Zhāng] Miǎo feared that Tàizǔ in the end would strike him for [Yuán] Shào, his heart could not be at ease. Xīngpíng Inaugural Year [194], Tàizǔ again campaigned against [Táo] Qiān, [Zhāng] Miǎo's younger brother [Zhāng] Chāo with Tàizǔ's officer Chén Gōng, Following Official Central Cadets Xǔ Sì and Wáng Kǎi togther plotted to rebel against Tàizǔ. [Chén] Gōng advised [Zhāng] Miǎo stating: "Now heroes are all rising, Heaven's Under divided and collapsed, you with the multitudes of a thousand lǐ occupy a land with battle on four sides, stroking sword and looking around, also is sufficient to to be a hero among men, but instead you are restricted by another, is it not contemptible? Now the provincial army is on eastern campaign, this position is empty. Lǚ Bù is a strong warrior, excels in battle with none ahead. If you expediently welcome him, together govern Yǎn Province, observe the circumstances Under Heaven, wait for changes in the time's affairs, this also is a time for strategic maneuvering.^[The term for maneuvering here is zònghéng, which can refer to the warp and weft in weaving, or vertical and horizontal. It came to refer to the School of Diplomacy during the Warring States period, in reference to the competing strategies of the "horizontal" alliance with Qín or "vertical" alliance against Qín.]" [Zhāng] Miǎo followed this. Tàizǔ had first sent [Chén] Gōng to lead troops to remain to garrison Dōng prefecture, therefore he led his multitudes east to invite [Lǚ] Bù to be Yǎn Province Governor, ouccpying Púyáng. The prefectures and counties all complied, only Juànchéng, Dōng'ē, and Fàn held for Tàizǔ. Tàizǔ led the army to return, with [Lǚ] Bù battled at Púyáng, Tàizǔ's army was not successful, locked together for over a hundred days. At the time the year was in dought, swarms of locusts, little grain, the Hundred Surnames at each other, [Lǚ] Bù to the east garrisoned Shānyáng. Within two years, Tàizǔ then completely recovered the various cities, struck and defeated [Lǚ] Bù at Jùyě. [Lǚ] Bù fled east to Liú Bèi. <a href="#annotation-9" id="source-9">[9]</a> [Zhāng] Miǎo followed [Lǚ] Bù, leaving [Zhāng] Chāo to command the family dependents to garrison Yōngqiū. Tàizǔ attacked and besieged for several moons, slaughtered it, beheaded [Zhāng] Chāo and his family. [Zhāng] Miǎo visited Yuán Shù to request rescue and had not yet arrived when he was himself killed by his troops. <a href="#annotation-10" id="source-10">[10]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
呂布之拾袁紹從張楊也，過邈臨別，把手共誓。紹聞之，大恨。邈畏太祖終為紹擊己也，心不自安。興平元年，太祖復征謙，邈弟超，與太祖將陳宮、從事中郎許汜、王楷共謀叛太祖。宮說邈曰：「今雄傑並起，天下分崩，君以千里之眾，當四戰之地，撫劍顧眄，亦足以為人豪，而反制于人，不以鄙乎！今州軍東征，其處空虛，呂布壯士，善戰無前，若權迎之，共牧兗州，觀天下形勢，俟時事之變通，此亦縱橫之一時也。」邈從之。太祖初使宮將兵留屯東郡，遂以其眾東迎布為兗州牧，據濮陽。郡縣皆應，唯鄄城、東阿、范為太祖守。太祖引軍還，與布戰於濮陽，太祖軍不利，相持百餘日。是時歲旱、蟲蝗、少穀，百姓相食，布東屯山陽。二年間，太祖乃盡復收諸城，擊破布于鉅野。布東奔劉備。〔一〕邈從布，留超將家屬屯雍丘。太祖攻圍數月，屠之，斬超及其家。邈詣袁術請救未至，自為其兵所殺。〔二〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-9" id="annotation-9">[9]</a> Yīngxióng jì states: [Lǚ] Bù met [Liú] Bèi, was extremely respectful to him, spoke to [Liú] Bèi stating: "You and I are both men of the borderlands. [I, Lǚ] Bù saw the east of the passes raising troops, wishing to execute Dǒng Zhuó. [I, Lǚ] Bù killed [Dǒng] Zhuó and came out east, the various officers east of the passes were without any that would give [me, Lǚ] Bù sanctuary, all only wishing to kill [me, Lǚ] Bù." He invited [Liú] Bèi into his tent, seated on his wife's couch, ordered his wife to bow toward him, poured alcohol to drink and eat, calling [Liú] Bèi as a younger brother. [Liú] Bèi saw [Lǚ] Bù's statements and words were without constancy, outwardly agreed to it but inside was not pleased.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　英雄記曰：布見備，甚敬之，謂備曰：「我與卿同邊地人也。布見關東起兵，欲誅董卓。布殺卓東出，關東諸將無安布者，皆欲殺布耳。」請備于帳中坐婦床上，令婦向拜，酌酒飲食，名備為弟。備見布語言無常，外然之而內不說。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-10" id="annotation-10">[10]</a> Xiàn-dì Chūnqiū states: Yuán Shù discussed claiming the Honored Title, [Zhāng] Miǎo spoke to [Yuán] Shù stating: "Hàn holds the Fire Virtue, though extinguished yet it again rises, its virtue and beneficence abundantly flows, begetting Your Enlightened Excellency. Your Excellency resides in an axis, in entering then enjoy the highest seats, in exiting then the mutltitudes fix their eyes, Huà and Huò [mountains] could not add to this loftiness, the deepest springs could not match this capacity, it can be said to be towering and overwhelming, with none that can be equal. Why abandon this to yet wish to declare sovereignty? One fears fortune would not fill the eyes before disaster overflows the world. Zhuāng Zhōu spoke of the Suburb Sacrifice's sacrificial ox, raised and reared for continuous years, draped in pattern embroidery, the butcher raises the phoenix knife, to enter the Temple Gate, right at this time, it wishes to be a solitary calf and cannot obtain it."

According to the base biography, [Zhāng] Miǎo visited [Yuán] Shù, had not yet arrived and died. But this says he remonstrated against declaring Honored Title, it is uncertain which is correct.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　獻帝春秋曰：袁術議稱尊號，邈謂術曰：「漢據火德，絕而復揚，德澤豐流，誕生明公。公居軸處中，入則享于上席，出則為眾目之所屬，華、霍不能增其高，淵泉不能同其量，可謂巍巍蕩蕩，無與為貳。何為捨此而欲稱制？恐福不盈眥，禍將溢世。莊周之稱郊祭犧牛，養飼經年，衣以文繡，宰執鸞刀，以入廟門，當此之時，求為孤犢不可得也！」按本傳，邈詣術，未至而死。而此云諫稱尊號，未詳孰是。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
[Liú] Bèi to the east struck [Yuán] Shù, [Lǚ] Bù surprise attacked and took Xiàpī, [Liú] Bèi returned and submitted to [Lǚ] Bù. [Lǚ] Bù sent [Liú] Bèi to garrison Xiǎopèi. [Lǚ] Bù declared himself Xú Province Inspector. <a href="#annotation-11" id="source-11">[11]</a> [Yuán] Shù sent his officer Jǐ Líng and others with infantry and cavalry of thirty thousand to attack [Liú] Bèi, [Liú] Bèi requested rescue from [Lǚ] Bù. [Lǚ] Bù's various officers spoke to [Lǚ] Bù stating: "General you have always wished to kill [Liú] Bèi, now you can leave the action to [Yuán] Shù." [Lǚ] Bù said: "Not so. If [Yuán] Shù defeats [Liú] Bèi, then to the north he will link with Tàishān's various officers, and I will be surrounded by [Yuán] Shù. We cannot not rescue." Then organized infantry of a thousand, cavalry of two hundred, galloped to go visit [Liú] Bèi. [Jǐ] Líng and the rest heard [Lǚ] Bù arrived, all restrained troops and did not dare again attack. [Lǚ] Bù to Pèi's southwest by one lǐ calmly garrisoned, sent a bell subordinate^[A bell subordinate (língxià) was a type of subordinate, usually used for announcing visitors and messages with a bell.] to invite [Jǐ] Líng and the rest, [Jǔ] Líng and the rest also invited [Lǚ] Bù to together drink and eat. [Lǚ] Bù spoke to [Jǐ] Líng and the rest stating: "Xuándé is [Lǚ] Bù's younger brother. My younger brother is being oppressed by you sirs, therefore I came to rescue him. [I, Lǚ] Bù by nature do not delight in joining fights, I only delight in resolving fights." [Lǚ] Bù ordered the gate captain to at the middle of the camp gates raise one halberd. [Lǚ] Bù said: "You sirs watch [me, Lǚ] Bù shoot the halberd's small branch. If one one shot I hit you sirs will separate and leave, if I do not hit you can remain and decide in battle." [Lǚ] Bù raised the bow and shot the halberd, exactly hitting the small branch. The various officers were all startled, saying: "General you are Heaven's authority!" The next day they again happily gathered, and then afterward each withdrew.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
備東擊術，布襲取下邳，備還歸布。布遣備屯小沛。布自稱徐州刺史。〔一〕術遣將紀靈等步騎三萬攻備，備求救于布。布諸將謂布曰：「將軍常欲殺備，今可假手於術。」布曰：「不然。術若破備，則北連太山諸將，吾為在術圍中，不得不救也。」便嚴步兵千、騎二百，馳往赴備。靈等聞布至，皆斂兵不敢復攻。布於沛西南一里安屯，遣鈴下請靈等，靈等亦請布共飲食。布謂靈等曰：「玄德，布弟也。弟為諸君所困，故來救之。布性不喜合鬥，但喜解鬥耳。」布令門候于營門中舉一隻戟，布言：「諸君觀布射戟小支，一發中者諸君當解去，不中可留決鬥。」布舉弓射戟，正中小支。諸將皆驚，言「將軍天威也」！明日復歡會，然後各罷。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-11" id="annotation-11">[11]</a> Yīngxióng jì states: When [Lǚ] Bù first entered Xú Province, he sent a letter to Yuán Shù. [Yuán] Shù's reply letter stated: "In the past Dǒng Zhuó made chaos, destroying the Royal House, brought disaster on [my, Yuán] Shù's household. [I, Yuán] Shù raised troops east of the passes, but was not able to slaughter and split apart [Dǒng] Zhuó. You General executed [Dǒng] Zhuó, sent his head, for [me, Yuán] Shù sweeping away and exterminating enemy and disgrace, allowing [me, Yuán] Shù to with clear eyes face the present age, death or life without shame, this is your achievement one. In the past when Jīn Yuánxiū was about to head toward Yǎn Province, just when he visited Fēngqiū, he was by Cáo Cāo opposed and repelled in defeat, scattered and fleeing, almost exterminated. You General captured Yǎn Province, [I, Yuán] Shù again had clear eyes to the far and near, this is your achievement two. [I, Yuán] Shù from since my year of birth onwards, had never heard of a Liú Bèi Under Heaven, [Liú] Bèi then raised troops to with [me, Yuán] Shù face in battle, [I, Yuán] Shù relied on your General's authoritative spirit, was able to defeat [Liú] Bèi. This is your achievement three. General you have three great achievements to [me, Yuán] Shù. Although [I, Yuán] Shù am not quick-witted, I will serve with life or death. General for successive years you have attacked and battled, your army provisions suffer from shortages, Now I send rice of two hundred thousand hú, welcoming and meeting on the road. It will not stop at only this, there will be relay stations to further deliver. If weapons or war equipment or others are lacking or in shortage, large or small it will only follow your command." [Lǚ] Bù obtained the letter and was greatly pleased, and therefore proceeded to Xiàpī.

Diǎnlüè states: [Jīn] Yuánxiū named Shàng was a Jīngzhào man. [Jīn] Zhàng with his same prefecture's Wéi Xiūfǔ and Dìwǔ Wénxiū all were famed, called as the Three Xiū. [Jīn] Shàng at Emperor Xiàn's beginning became Yǎn Province Inspector, went east to the prefectures, but Tàizǔ was already overseeing Yǎn Province. [Jīn] Shàng to the south depended on Yuán Shù. [Yuán] Shù usurped title, wished to appoint [Jīn] Shàng as Grand Commandant, did not dare prominently announce it, privately sent someone to hint at it, [Jīn] Shàng had no intention to yield, [Yuán] Shù also did not dare force him. At Jiàn'ān's beginning, [Jīn] Shàng fled to return, and was by [Yuán] Shù murdered. After that [Jīn] Shàng's body with Grand Tutor Mǎ Mìdī's body both arrived at the capital region. Heaven's Son commended [Jīn] Shàng's loyalty and intensity, sighed [in admiration] for him, Edict on the Hundred Offices to offer condolence sacrifices, appointed his son [Jīn] Wěi as Cadet Central, but [Mǎ] Mìdī did not share in it.

Yīngxióng jì states: [Lǚ] Bù on water and land went east downstream, the army arrived at Xiàpī's west by forty lǐ. [Liú] Bèi's Central Cadet General Dānyáng's Xǔ Dān in the night sent Major Zhāng Kuáng to come visit [Lǚ] Bù, saying: "Zhāng Yìdé with Xiàpī Chancellor Cáo Bào fought one another, Yìdé killed [Cáo] Bào, inside the city is in great chaos, no one trusting one another. The Dānyáng troops have a thousand men garrisoned Xībáimén city's interior, heard that you General are coming east, large and small leaping [in joy], as if restored to life. General if your troops head toward the city's west gate, the Dānyáng army will then open the gates to let in you General." [Lǚ] Bù therefore in the night advanced, at dawn arrived below the city wall. At day's light, the Dānyáng troops all opened the gate to let in [Lǚ] Bù's troops. [Lǚ] Bù at the gate's top sat, infantry and cavalry set fires, greatly defeated Yìdé's troops, captured [Liú] Bèi's wife and children and army resources and the family members of the division retainers and officers and clerks and servicemen. Jiàn'ān Inaugural Year Sixth Moon [196 Jul 14 - Aug 11] in the middle of the night, [Lǚ] Bù's officer Hénèi's Hǎo Méng rebelled, led troops to enter the office where [Lǚ] Bù was governing Xiàpī, visited the administrative hall side door exterior, together greatly shouted and attacked the side door, the side door was strong and could not be entered. [Lǚ] Bù did not know who was rebelling, directly led his wife, bare-headed and undressed top, led one another from the privy pushed over the wall to exit, visited Overall Supervisor Gāo Shùn's camp, directly pushed through [Gāo] Shùn's gate to enter. [Gāo] Shùn asked: "General do you have any suspicions or not?" [Lǚ] Bù said: "[There was a] Hénèi boy's sound." [Gāo] Shùn said: "This is Hǎo Méng." [Gāo] Shùn at once organized troops to enter the office, bows and crossbows all firing into [Hǎo] Méng's multitudes, [Hǎo] Méng's multitudes chaotically fled, at day's light returned to their former camp. [Hǎo] Méng's officer Cáo Xìng rebelled against [Hǎo] Méng, with him facing in battle, [Hǎo] Méng stabbed and wounded [Cáo] Xìng, [Cáo] Xìng chopped off [Hǎo] Méng's one arm. [Gāo] Shùn chopped off [Hǎo] Méng's head. On a bed carried [Cáo] Xìng, sent to visit [Lǚ] Bù. [Lǚ] Bù interrogated [Cáo] Xìng, he said: "[Hǎo] Méng joined Yuán Shù's conspiracy." "Who were the conspirators?" [Cáo] Xìng said: "Chén Gōng was a co-conspirator." At the time [Chén] Gōng was among the seated, his face reddened, the nearby people all noticed it. [Lǚ] Bù because [Chén] Gōng was a chief officer did not investigate. [Cáo] Xìng said: "[Hǎo] Méng always asked me about this, [I, Cáo] Xìng said General Lǚ is a great officer with divinity and cannot be struck. Unexpectedly [Hǎo] Méng's insanity and confusion did not end." [Lǚ] Bù spoke to [Cáo] Xìng stating: "You are a tough fellow." Well cared for and looked after him. The wound healed, sent to calm and succor [Hǎo] Méng's former camp, take over his multitudes.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　英雄記曰：布初入徐州，書與袁術。術報書曰：「昔董卓作亂，破壞王室，禍害術門戶，術舉兵關東，未能屠裂卓。將軍誅卓，送其頭首，為術掃滅讎恥，使術明目于當世，死生不愧，其功一也。昔將金元休向兗州，甫詣（封部）〔封丘〕，為曹操逆所拒破，流離迸走，幾至滅亡。將軍破兗州，術復明目於遐邇，其功二也。術生年已來，不聞天下有劉備，備乃舉兵與術對戰；術憑將軍威靈，得以破備，其功三也。將軍有三大功在術，術雖不敏，奉以生死。將軍連年攻戰，軍糧苦少，今送米二十萬斛，迎逢道路，非直此止，當駱驛復致；若兵器戰具，它所乏少，大小唯命。」布得書大喜，遂造下邳。典略曰：元休名尚，京兆人也。尚與同郡韋休甫、第五文休俱著名，號為三休。尚，獻帝初為兗州刺史，東之郡，而太祖已臨兗州。尚南依袁術。術僭號，欲以尚為太尉，不敢顯言，私使人諷之，尚無屈意，術亦不敢彊也。建安初，尚逃還，為術所害。其後尚喪與太傅馬日磾喪俱至京師，天子嘉尚忠烈，為之咨嗟，詔百官弔祭，拜子瑋郎中，而日磾不與焉。英雄記曰：布水陸東下，軍到下邳西四十里。備中郎將丹楊許耽夜遣司馬章誑來詣布，言「張益德與下邳相曹豹共爭，益德殺豹，城中大亂，不相信。丹楊兵有千人屯西白門城內，聞將軍來東，大小踊躍，如復更生。將軍兵向城西門，丹楊軍便開門內將軍矣」。布遂夜進，晨到城下。天明，丹楊兵悉開門內布兵。布于門上坐，步騎放火，大破益德兵，獲備妻子軍資及部曲將吏士家口。建安元年六月夜半時，布將河內郝萌反，將兵入布所治下邳府，詣廳事閤外，同聲大呼攻閤，閤堅不得入。布不知反者為誰，直牽婦，科頭袒衣，相將從溷上排壁出，詣都督高順營，直排順門入。順問：「將軍有所隱不？」布言「河內兒聲」。順言「此郝萌也」。順即嚴兵入府，弓弩並射萌眾；萌眾亂走，天明還故營。萌將曹性反萌，與對戰，萌刺傷性，性斫萌一臂。順斫萌首，床輿性，送詣布。布問性，言「萌受袁術謀。」「謀者悉誰？」性言「陳宮同謀。」時宮在坐上，面赤，傍人悉覺之。布以宮大將，不問也。性言「萌常以此問，性言呂將軍大將有神，不可擊也，不意萌狂惑不止。」布謂性曰：「卿健兒也！」善養視之。創愈，使安撫萌故營，領其眾。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
[Yuán] Shù wished to bind [Lǚ] Bù into being his assistance, and so for his son requested [Lǚ] Bù's daughter [in a marriage alliance], [Lǚ] Bù agreed to it. [Yuán] Shù sent envoy Hán Yìn to inform [Lǚ] Bù of the discussions to usurp title, and further seek to welcome the wife. Pèi Chancellor Chén Guī feared if [Yuán] Shù and [Lǚ] Bù completed the marriage alliance, then Xú and Yáng [provinces] would unite and become a trouble for the state, and thereupon went to advise [Lǚ] Bù stating: "Cáo-gōng served and welcomed Heaven's Son, assisting and supporting state and government, authoritative spirit commanding the age, about to campaign the Four Seas, you General should with him cooperate in strategies, to seek the security of Tài mountain. Now if you with [Yuán] Shù join in marriage alliance, you will receive a reputation of being unrighteous Under Heaven, and certainly have the precariousness of piled eggs." [Lǚ] Bù also resented [Yuán] Shù for previously not receiving him, his daughter was already on the road, pursued and retrieved her and cancelled the marriage, shackled and sent Hán Yìn, exposed the head in Xǔ market. [Chén] Guī wished to send his son [Chén] Dēng to visit Tàizǔ, [Lǚ] Bù would not agree to send him. It happened that an envoy arrived, appointed [Lǚ] Bù as Left General. [Lǚ] Bù was greatly pleased, at once agreed for [Chén] Dēng to go, and further order to present Reply to thank for the favor. <a href="#annotation-12" id="source-12">[12]</a> [Chén] Dēng met Tàizǔ, took advantage to explain that [Lǚ] Bù was valorous but without planning, reckless in abandoning and joining, and one should early plan against him. Tàizǔ said: "[Lǚ] Bù has a wolf's wild heart, truly difficult to care for long, if not you then none are able to investigate his sentiments." At once increased [Chén] Guī's salary rank to Central Two Thousand dàn, appointed [Chén] Dēng as Guǎnglíng Administrator. When about to part, Tàizǔ grasped [Chén] Dēng's hand and said: "The affairs of the east then will be entrusted to you." Ordered [Chén] Dēng to secretly unit division multitudes to be inside support.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
術欲結布為援，乃為子索布女，布許之。術遣使韓胤以僭號議告布，并求迎婦。沛相陳珪恐術、布成婚，則徐、揚合從，將為國難，於是往說布曰；「曹公奉迎天子，輔讚國政，威靈命世，將征四海，將軍宜與協同策謀，圖太山之安。今與術結婚，受天下不義之名，必有累卵之危。」布亦怨術初不己受也，女已在塗，追還絕婚，械送韓胤，梟首許市。珪欲使子登詣太祖，布不肯遣。會使者至，拜布左將軍。布大喜，即聽登往，并令奉章謝恩。〔一〕登見太祖，因陳布勇而無計，輕於去就，宜早圖之。太祖曰：「布，狼子野心，誠難久養，非卿莫能究其情也。」即增珪秩中二千石，拜登廣陵太守。臨別，太祖執登手曰：「東方之事，便以相付。」令登陰合部眾以為內應。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-12" id="annotation-12">[12]</a> Yīngxióng jì states: Previously, Heaven's Son was at Hédōng, there was hand written tablet letter to summon [Lǚ] Bù to come welcome. [Lǚ] Bù's army was without provisions and supplies, unable to themselves arrive, sent envoy to send up letter. The Court appointed [Lǚ] Bù as Pacifying East General, enfeoffed Marquess of Píngtáo.^[Píngtáo county was in Tàiyuān prefecture.] The envoy at Shānyáng's border lost the documents, Tàizǔ also handwrote letter to generously apply appreciations for labors on [Lǚ] Bù, explained his intention to mobilize to welcome Heaven's Son and pacify and settle Heaven's Under, combined with Edict letter offering rewards for the capture of Gōngsūn Zàn, Yuán Shù, Hán Xiān, Yáng Fèng and others. [Lǚ] Bù was greatly pleased, agan sent envoy to send up letter to Heaven's Son stating: "Your Servant originally should have welcomed the Great Carriage, knowing Cáo Cāo is loyal and filial, he reverently welcomed to set the capital at Xǔ. Your Servant formerly with [Cáo] Cāo engated troops, now [Cáo] Cāo is Protector and Tutor to Your Majesty, Your Servant is an exterior officer, wishing to have troops accompany me, I fear there will be suspicions, and therefore wawit for punishment in Xú Provcine, advancing and withdrawing not daring to be at ease." The answer to Tàizǔ stated: "[I, Lǚ] Bù am a guilty man, should be executed, you personally mandated appreciation for labors, I generously met with commendations and rewards. Heavily seeing the Edict letter with offered rewards for the capture of Yuán Shù and the rest, [I, Lǚ] Bù should use my life to enact it." Tàizǔ further sent Serving Chariots Commandant Wáng Zé as envoy, to present Edict letter, also with sealed Pacifying East General seal and ribbon to come appoint [Lǚ] Bù. Tàizǔ also hand wrote letter to [Lǚ] Bù that said: "The Shānyáng garrison sent the major seal lost by you General, the country is without fine gold, I myself took my family's fine gold to further make a seal for you, the country is without purple ribbon, I took the purple cord on my own belt to demonstrate my heart. General your messengers were not good. Yuán Shù declared himself Heaven's Son, you General stopped him, but the envoy did not deliver the Reply. The Court trusts you General, again send up another message, to make clear your loyal sincerity." [Lǚ] Bù then sent [Chén] Dēng to present Reply to thank for the favor, and also had one fine cord answer Tàizǔ.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　英雄記曰：初，天子在河東，有手筆版書召布來迎。布軍無畜積，不能自致，遣使上書。朝廷以布為平東將軍，封平陶侯。使人於山陽界亡失文字，太祖又手書厚加慰勞布，說起迎天子，當平定天下意，并詔書購捕公孫瓚、袁術、韓暹、楊奉等。布大喜，復遣使上書於天子曰：「臣本當迎大駕，知曹操忠孝，奉迎都許。臣前與操交兵，今操保傅陛下，臣為外將，欲以兵自隨，恐有嫌疑，是以待罪徐州，進退未敢自寧。」答太祖曰：「布獲罪之人，分為誅首，手命慰勞，厚見褒獎。重見購捕袁術等詔書，布當以命為效。」太祖更遣奉車都尉王則為使者，齎詔書，又封平東將軍印綬來拜布。太祖又手書與布曰：「山陽屯送將軍所失大封，國家無好金，孤自取家好金更相為作印，國家無紫綬，自取所帶紫綬以籍心。將軍所使不良。袁術稱天子，將軍止之，而使不通章。朝廷信將軍，使復重上，以相明忠誠。」布乃遣登奉章謝恩，并以一好綬答太祖。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
At first [Lǚ] Bù took advantage of [Chén] Dēng to request to be Xú Province Governor, [Chén] Dēng returned, [Lǚ] Bù was furious, drew halberd and chopped the table stating: "Your father urged me to cooperate with Cáo-gōng and cancel the marriage alliance with Gōnglù, now I have not obtained a single thing I requested, but you father and son are both prominently valued, I have only been sold out by you! When you spoke for me what did you say?" [Chén] Dēng did not change expression, and gently explained to him stating: "[I, Chén] Dēng met Cáo-gōng and said: 'Treating the General is like raising a tiger, it should be kept full with meat, if not full then it will devour men.' The Excellency said: 'It is not as you say. It is like raising a falcon. When hungry then it can be employed, when full then it rises and leaves.' His statement was like this." [Lǚ] Bù's thoughts then were resolved.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
始，布因登求徐州牧，登還，布怒，拔戟斫几曰：「卿父勸吾協同曹公，絕婚公路；今吾所求無一獲，而卿父子並顯重，為卿所賣耳！卿為吾言，其說云何？」登不為動容，徐喻之曰；「登見曹公言：『待將軍譬如養虎，當飽其肉，不飽則將噬人。』公曰：『不如卿言也。譬如養鷹，饑則為用，飽則揚去。』其言如此。」布意乃解。
:::
:::

::: {.columns}
::: {.column width="70%"}
[Yuán] Shù was angry, with Hán Xiān and Yáng Fèng and others joined forces, sent his chief officer Zhāng Xūn to attack [Lǚ] Bù. [Lǚ] Bù spoke to [Chén] Guī stating: "Now the arrival of [Yuán] Shù's army is because of you. What is to be done?" [Chén] Guī said: "[Hán] Xiān, [Yáng] Fèng with [Yuán] Shù are only a hastily joined army, the strategies not previously settled, they cannot maintain and support one another. My son [Chén] Dēng has analyzed them, comparing them to linked chickens: the situation is that they cannot perch together, they can be scattered." [Lǚ] Bù employed [Chén] Guī's strategy, sent someone to persuade [Hán] Xiān, [Yáng] Fèng, having them join with him to combine forces to together strike [Yuán] Shù's army, with all the army supplies entirely promised to [Hán] Xiān, [Yáng] Fèng. Thereupon [Hán] Xiān, [Yáng] Fèng followed this, [Zhāng] Xūn was greatly defeated. <a href="#annotation-13" id="source-13">[13]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
術怒，與韓暹、楊奉等連勢，遣大將張勳攻布。布謂珪曰：「今致術軍，卿之由也，為之奈何？」珪曰：「暹、奉與術，卒合之軍耳，策謀不素定，不能相維持，子登策之，比之連雞，勢不俱棲，可解離也。」布用珪策，遣人說暹、奉，使與己并力共擊術軍，軍資所有，悉許暹、奉。於是暹、奉從之，勳大破敗。〔一〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-13" id="annotation-13">[13]</a> Jiǔzhōu Chūnqiū records [Lǚ] Bù's letter to [Hán] Xiān, [Yáng] Fèng stating: "You two Generals rescued the Great Carriage to come east, having a foremost achievement to the state, and should have the merits written on bamboo and silk, for ten thousand ages never decaying. Now Yuán Shù prepares rebellion, we should together punish and suppress him, how can you with a traitor minister return to together attack [me, Lǚ] Bù. [I, Lǚ] Bù have the achievement of killing Dǒng Zhuó, with you two Generals both accomplished ministers, we can take advantage to now together strike and defeat [Yuán] Shù, establish achievements for Heaven's Under, this moment cannot be lost." [Hán] Xiān, [Yáng] Fèng obtained the letter, at once changed plans to follow [Lǚ] Bù. [Lǚ] Bù advanced the army, from [Zhāng] Xūn and the rest's camp by a hundred bù, [Hán] Xiān's and [Yáng] Fèng's troops at the same time together set out, cut off the heads of ten officers, the killed and wounded that fell into the river and died could not be counted.

Yīngxióng jì states: [Lǚ] Bù later also with [Hán] Xiān, [Yáng] Fèng's two armies headed toward Shòuchūn, on water and land both advancing, wherever they passed they captured and plundered. Arrived at Zhōnglí, with great gains returned. When they crossed the Huái north, they left a letter to [Yuán] Shù that said: "You rely on your army's strength and prosperity, always calling them fierce officers and martial servicemen, wishing to swallow and exterminate others, every time I have merely restrained and stopped it. Although [I, Lǚ] Bù am without valor, like a tiger I stride the Huái's south, in the space of a moment, you like a rat scurry to Shòuchūn, never showing your head. The fierce officers and martial servicemen, where are they all? You enjoy making great boasts to deceive Heaven's Under, how can the people of Heaven's Under be entirely deceived? In antiquity when troops engaged, envoys were between them. The initiator of strategies was not [me, Lǚ] Bù first calling, we are not far away from one another, we can resume exchanging news." [Lǚ] Bù's crossing completed, [Yuán] Shù personally commanded infantry and cavalry of five thousand to raise troops up the Huái, [Lǚ] Bù's cavalry all to the river's north greatly laughed at them and returned. At the time there was Dōnghǎi's Xiāo Jiàn who became Lángyé Chancellor, governing from Jǔ, protected the city to self defend, not communicating with [Lǚ] Bù. [Lǚ] Bù's letter to [Xiāo] Jiàn said: "Heaven's Under raised troops, originally only to execute Dǒng Zhuó. [I, Lǚ] Bù killed [Dǒng] Zhuó, came to visit the east of the passes, wishing to request troops to go west to welcome the Great Carriage, recover and restore Luò capital, the various officers themselves returned to attack one another, none agreeing to think of the state. [I, Lǚ] Bù am a Wǔyuán man, from Xú Province by over five thousand lǐ, thus in Heaven's southwest corner, now I did not come to contest the lands of Heaven's southeast with you. Jǔ and Xiàpī are not far away from one another, and it is appropriate to communicate together. You are acting as if each prefecture after prefecture has an Emperor, county after county its own King. In the past Yuè Yì attacked Qí, in a breath subduing over seventy of Qí's cities, only Jǔ and Jímò two cities were not subdued. The reason it was so, was because inside there was Tián Dān. Although [I, Lǚ] Bù am not Yuè Yì, you also are not Tián Dān, you can take [Lǚ] Bù's letter and with the wise in detail together discuss it." [Xiāo] Jiàn obtained the letter, at once sent his Registrar to present dispatch and send up gifts, tributing excellent horses of five. [Xiāo] Jiàn was by Zāng Bà raided and defeated, obtaining [Xiāo] Jiàn's supplies and stores. [Lǚ] Bù heard of this, personally commanded infantry and cavalry toward Jǔ. Gāo Shùn remonstrated stating: "General you personally killed Dǒng Zhuó, authority shaking the Yí and Dí. Sitting upright and looking around, far and near on their own naturally fear and submit. It is not appropriate to recklessly personally set out the army. If perhaps you are not victorious, the damage to your reputation would not be small." [Lǚ] Bù did not follow this. [Zāng] Bà feared [Lǚ] Bù's plunder and violence, indeed ascended city walls to resist and defend. [Lǚ] Bù could not capture it, withdrew and returned to Xiàpī. [Zāng] Bà later returned to make peace with [Lǚ] Bù.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　九州春秋載布與暹、奉書曰：「二將軍拔大駕來東，有元功於國，當書勳竹帛，萬世不朽。今袁術造逆，當共誅討，奈何與賊臣還共伐布？布有殺董卓之功，與二將軍俱為功臣，可因今共擊破術，建功於天下，此時不可失也。」暹、奉得書，即迴計從布。布進軍，去勳等營百步，暹、奉兵同時並發，斬十將首，殺傷墮水死者不可勝數。英雄記曰：布後又與暹、奉二軍向壽春，水陸並進，所過虜略。到鍾離，大獲而還。既渡淮北，留書與術曰：「足下恃軍彊盛，常言猛將武士，欲相吞滅，每抑止之耳！布雖無勇，虎步淮南，一時之閒，足下鼠竄壽春，無出頭者。猛將武士，為悉何在？足下喜為大言以誣天下，天下之人安可盡誣？古者兵交，使在其閒，造策者非布先唱也。相去不遠，可復相聞。」布渡畢，術自將步騎五千揚兵淮上，布騎皆于水北大咍笑之而還。時有東海蕭建為瑯邪相，治莒，保城自守，不與布通。布與建書曰：「天下舉兵，本以誅董卓耳。布殺卓，來詣關東，欲求兵西迎大駕，光復洛京，諸將自還相攻，莫肯念國。布，五原人也，去徐州五千餘里，乃在天西北角，今不來共爭天東南之地。莒與下邳相去不遠，宜當共通。君如自遂以為郡郡作帝，縣縣自王也！昔樂毅攻齊，呼吸下齊七十餘城，唯莒、即墨二城不下，所以然者，中有田單故也。布雖非樂毅，君亦非田單，可取布書與智者詳共議之。」建得書，即遣主簿齎牋上禮，貢良馬五匹。建尋為臧霸所襲破，得建資實。布聞之，自將步騎向莒。高順諫曰：「將軍躬殺董卓，威震夷狄，端坐顧盼，遠近自然畏服，不宜輕自出軍；如或不捷，損名非小。」布不從。霸畏布（引還）鈔暴，果登城拒守。布不能拔，引還下邳。霸後復與布和。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Jiàn'ān Third Year [195], [Lǚ] Bù again rebelled to support [Yuán] Shù, sent Gāo Shùn to attack Liú Bèi at Pèi, defeated him. Tàizǔ sent Xiàhóu Dūn to rescue [Liú] Bèi, was by [Gāo] Shùn defeated. Tàizǔ personally campaigned against [Lǚ] Bù, reached below his city walls, left [Lǚ] Bù a letter, explaining the disasters and fortunes. [Lǚ] Bù wished to surrender, Chén Gōng and others themselves believed their own crimes extreme, stopped his plan. <a href="#annotation-14" id="source-14">[14]</a> [Lǚ] Bù sent someone to request rescue from [Yuán] Shù, personally commanded over a thousand cavalry to go out to battle, was defeated and fled, returned to protect the city, not daring to come out. <a href="#annotation-15" id="source-15">[15]</a> [Yuán] Shù also could not rescue him. Although [Lǚ] Bù was valiant and fierce, however he had no planning and had many suspicions, could not control and manage his faction, only trusting his various officers. The various officers each had ulterior intentions and doubted their own positions, and therefore in every battle there were many defeats. Tàizǔ dug a moat to encircle them for three months, above and below separated in heart, his officers Hóu Chéng, Sòng Xiàn, Wèi Xù bound Chén Gōng and led their multitudes to surrender. <a href="#annotation-16" id="source-16">[16]</a> [Lǚ] Bù with his bannermen^[Bannermen (huīxià) refered to the soldiers under the direct command of the army commander.] ascended Báimén Tower. The soldiers besieged pressingly, and so they went down to surrender. Therefore bound [Lǚ] Bù alive. [Lǚ] Bù said: "The bonds are too tight, slightly loosen them." Tàizǔ said: "Binding a tiger cannot be not tight." [Lǚ] Bù requested stating: "Your Enlightened Excellency's concerns were no more than [me, Lǚ] Bù. Now I have already submitted, Heaven's Under is not worth worrying about. Your Enlightened Excellency commands the infantry, order [me, Lǚ] Bù command the cavalry, and then Heaven's Under is not difficult to settle." Tàizǔ had a doubtful expression. Liú Bèi advanced and said: "Does Your Enlightened Excellency not see [Lǚ] Bù's service to Dīng Jiànyáng and Grand Preceptor Dǒng?" Tàizǔ nodded at him. [Lǚ] Bù therefore pointed at [Liú] Bèi and said: "This boy is the most untrustworthy!" <a href="#annotation-17" id="source-17">[17]</a> Thereupon strangled and killed [Lǚ] Bù. [Lǚ] Bù with [Chén] Gōng and [Gāo] Shùn and others all had their heads exposed and sent to Xǔ, afterwards buried them. <a href="#annotation-18" id="source-18">[18]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
建安三年，布復叛為術，遣高順攻劉備於沛，破之。太祖遣夏侯惇救備，為順所敗。太祖自征布，至其城下，遺布書，為陳禍福。布欲降，陳宮等自以負罪深，沮其計。〔一〕布遣人求救于術，（術）自將千餘騎出戰，敗走，還保城，不敢出。〔二〕術亦不能救。布雖驍猛，然無謀而多猜忌，不能制御其黨，但信諸將。諸將各異意自疑，故每戰多敗。太祖塹圍之三月，上下離心，其將侯成、宋憲、魏續縛陳宮，將其眾降。〔三〕布與其麾下登白門樓。兵圍急，乃下降。遂生縛布，布曰：「縛太急，小緩之。」太祖曰：「縛虎不得不急也。」布請曰：「明公所患不過於布，今已服矣，天下不足憂。明公將步，令布將騎，則天下不足定也。」太祖有疑色。劉備進曰：「明公不見布之事丁建陽及董太師乎！」太祖頷之。布因指備曰：「是兒最叵信者。」〔四〕於是縊殺布。布與宮、順等皆梟首送許，然後葬之。〔五〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-14" id="annotation-14">[14]</a> Xiàn-dì Chūnqiū states: Tàizǔ's army reached Péngchéng. Chén Gōng said to [Lǚ] Bù: "It is appropriately to oppose and strike them. Using the rested to strike the weary, nothing is not conquered." [Lǚ] Bù said: "It is not as good as waiting for them coming to attack, and push them into the Sì river." When Tàizǔ's army attacked them pressingly, [Lǚ] Bù at Báimén tower's top spoke to the army servicemen stating: "You all need not distress each other, I will give up myself to his Enlightened Excellency." Chén Gōng said: "Rebel traitor Cáo Cāo, how is he an Enlightened Excellency? Today to surrender to him, is like an egg throwing at a rock, how can it be able to survive?"
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　獻帝春秋曰：太祖軍至彭城。陳宮謂布：「宜逆擊之，以逸擊勞，無不克也。」布曰：「不如待其來攻，蹙著泗水中。」及太祖軍攻之急，布于白門樓上謂軍士曰：「卿曹無相困，我（自首當）〔當自首〕明公。」陳宮曰：「逆賊曹操，何等明公！今日降之，若卵投石，豈可得全也！」
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-15" id="annotation-15">[15]</a> Yīngxióng jì states: [Lǚ] Bù sent Xǔ Sì, Wáng Kǎi to report the emergency to [Yuán] Shù. [Yuán] Shù said: "[Lǚ] Bù did not send me his daughter, reasonably he assuredly should be defeated, why again come to exchange news?" [Xǔ] Sì and [Wáng] Kǎi said: "Your Enlightened Superior if now you do not rescue [Lǚ] Bù, it is only to defeat yourself. If [Lǚ] Bù is destroyed, Your Enlightened Superior also is destroyed." [Yuán] Shù at the time usurped title, therefore they called him as Enlightened Superior.^[Superior (shàng) was a term for referring to an Emperor.] [Yuán] Shù then organized troops to make a sound of support for [Lǚ] Bù. [Lǚ] Bù feared [Yuán] Shù, because his daughter had not arrived, therefore would not send troops to rescue, used cotton to wrap around his daughter's body, tied her on top of a horse, in the night personally escorting his daughter out to send to [Yuán] Shù, with Tàizǔ's defending troops encountered one another, enganged and shot and could not get through, and returned to the city. [Lǚ] Bù wished to order Chén Gōng and Gāo Shùn to defend the city, and personally command cavalry to cut off Tàizǔ's supply route. [Lǚ] Bù's wife spoke stating: "General you personally going out to cut off Cáo-gōng's supply route is correct. [Chén] Gōng and [Gāo] Shùn previously are not harmonious. General once you go out, [Chén] Gōng and [Gāo] Shùn certainly will not be united in heart and together defend the city, if there is a mistep, General how will you maintain yourself? May you General carefully consider it, and not be misled by [Chén] Gōng and the rest. Your Consort in the past was at Cháng'ān, already have been abandoned by you General, only by fortune obtaining Páng Shū's secret hiding did Your Consort survive, now you need not consider Your Consort." [Lǚ] Bù obtained his wife's advice, was anxious and depressed and unable to himself decide.


Wèi-shì Chūnqiū states: Chén Gōng spoke to [Lǚ] Bù stating: "Cáo-gōng from afar came, his momentum cannot last for long. If you General with infantry and cavalry go out to garrison, to be momentum to the exterior, [I, Chén] Gōng will command the remaining multitudes to shut and defend the interior. If they head toward you General, [I, Chén] Gōng will lead troops and attack their back. If they come to attack the city, you General will be the rescue to the exterior. In no more than ten days, their arm's provisions will certainly be exhausted, striking them they can be destroyed." [Lǚ] Bù agreed to this. [Lǚ] Bù's wife said: "In the past Cáo-shì treated Gōngtái like an infant, yet he still abandoned them and came to us. Now General your generosity to Gōngtái does not exceed that of Cáo-gōng, but yet you wish to entrust the entire city, leaving wife and children, with isolated army distantly set out, if one morning there is a change, how would Your Consort be able to remain your General's wife?" [Lǚ] Bù thus stopped.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　英雄記曰：布遣許汜、王楷告急于術。術曰：「布不與我女，理自當敗，何為復來相聞邪？」汜、楷曰：「明上今不救布，為自敗耳！布破，明上亦破也。」術時僭號，故呼為明上。術乃嚴兵為布作聲援。布恐術為女不至，故不遣兵救也，以綿纏女身，縛著馬上，夜自送女出與術，與太祖守兵相觸，格射不得過，復還城。布欲令陳宮、高順守城，自將騎斷太祖糧道。布妻謂曰：「將軍自出斷曹公糧道是也。宮、順素不和，將軍一出，宮、順必不同心共城守也，如有蹉跌，將軍當於何自立乎？願將軍諦計之，無為宮等所誤也。妾昔在長安，已為將軍所棄，賴得龐舒私藏妾身耳，今不須顧妾也。」布得妻言，愁悶不能自決。魏氏春秋曰：陳宮謂布曰：「曹公遠來，勢不能久。若將軍以步騎出屯，為勢於外，宮將餘眾閉守於內，若向將軍，宮引兵而攻其背，若來攻城，將軍為救於外。不過旬日，軍食必盡，擊之可破。」布然之。布妻曰：「昔曹氏待公臺如赤子，猶舍而來。今將軍厚公臺不過於曹公，而欲委全城，捐妻子，孤軍遠出，若一旦有變，妾豈得為將軍妻哉！」布乃止。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-16" id="annotation-16">[16]</a> Jiǔzhōu Chūnqiū states: Previously, [Lǚ] Bù's cavalry officer Hóu Chéng sent a retainer to herd horses of fifteen, the retainer galloped all the horses to leave, heading toward Pèi city, wishing to submit to Liú Bèi. [Hóu] Chéng personally commanded cavalry to pursue them, obtained all the horses and returned. The various officers gathered with gifts to congratulate [Hóu] Chéng, [Hóu] Chéng brewed five to six hú of alcohol, hunted and obtained over ten heads of pigs, had not yet drank and feasted, first holding half a pig and five dǒu of alcohol to personally enter to visit [Lǚ] Bù's front, knelt and said: "Immersed in your General's favor, I pursued and obtained my lost horses, the various officers came to exchange congratulations, I personally brewed a little alcohol, hunted and obtained pigs, have not yet dared to drink and feast, first offering up my humble intentions." [Lǚ] Bù was greatly furious and said: "[I, Lǚ] Bù have banned alcohol,^[Based on records of other alcohol bans, this may have been due to rationing during food shortages or while under siege: grain used for alochol brewing was grain that was not being eaten.] you brewed alcohol, the various officers together drink and feast becoming brothers, are you together plotting to kill [me, Lǚ] Bù?" [Hóu] Chéng was greatly afraid and left, discarded the brewed alcohol, treturned the various officers' gifts. Because of this he doubted his own position, it happened that Tàizǔ besieged Xiàpī, [Hóu] Chéng therefore led his multitudes to surrender.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔三〕　九州春秋曰：初，布騎將侯成遣客牧馬十五匹，客悉驅馬去，向沛城，欲歸劉備。成自將騎逐之，悉得馬還。諸將合禮賀成，成釀五六斛酒，獵得十餘頭豬，未飲食，先持半豬五斗酒自入詣布前，跪言：「閒蒙將軍恩，逐得所失馬，諸將來相賀，自釀少酒，獵得豬，未敢飲食，先奉上微意。」布大怒曰：「布禁酒，卿釀酒，諸將共飲食作兄弟，共謀殺布邪？」成大懼而去，棄所釀酒，還諸將禮。由是自疑，會太祖圍下邳，成遂領眾降。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-17" id="annotation-17">[17]</a> Yīngxióng jì states: [Lǚ] Bù spoke to Tàizǔ stating: "[I, Lǚ] Bù treated the various officers generously, only for the various officers when facing an emergency to all betray [me, Lǚ] Bù." Tàizǔ said: "You abandoned your wife and favored the women of the various officers, how is this generosity?" [Lǚ] Bù was silent.

Xiàn-dì Chūnqiū states: [Lǚ] Bù asked Tàizǔ: "Why has Your Enlightened Excellency gotten thin?" Tàizǔ said: "How did you recognize me?" [Lǚ] Bù said: "In the past at Luò, we met at the Wēn clan's garden." Tàizǔ said: "Right. I had forgotten that. The reason I have thinned is because I regret not having earlier obtained you." [Lǚ] Bù said: "Qí Huán forgave the shooting of hook, employing Guǎn Zhòng as his Chancellor,^[Before his enthronment, Duke Huán of Qí was involved in a succession struggle with his brother. Guǎn Zhòng was a subordinate of his brother, and once shot an arrow that hit the hook of Duke Huán's belt. Nevertheless, after his enthronment, Duke Huán forgave and employed Guǎn Zhòng due to Guǎn Zhòng's great talent.] now send [me, Lǚ] Bù to exhaust the strenght of my legs and arms, to be Your Excellency's advance guard, is it permissible?" [Lǚ] Bù's bindings were tight, he spoke to Liú Bèi stating: "Xuándé, you are a seated guest, I am a captured caitiff, can you not say one word to have me loosened?" Tàizǔ laughed and said: "Why not speak to me, but complain to his Enlightened Inspectorship?"^[Inspectorship (shǐjūn) is the term of address for a provincial Governor or Inspector. At this time Liú Bèi claimed office as Inspector of Yù Province.] His intention was to wish to spare him, and ordered to have the bindings loosened. Registrar Wáng Bì hastened to advance and said: "[Lǚ] Bù is a powerful caitiff. His multitudes are nearby outside, he cannot be loosened." Tàizǔ said: "Originally I wished to loosen you, the Registrar will not listen, what can be done?"
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔四〕　英雄記曰：布謂太祖曰：「布待諸將厚也，諸將臨急皆叛布耳。」太祖曰：「卿背妻，愛諸將婦，何以為厚？」布默然。獻帝春秋曰：布問太祖：「明公何瘦？」太祖曰：「君何以識孤？」布曰：「昔在洛，會溫氏園。」太祖曰：「然。孤忘之矣。所以瘦，恨不早相得故也。」布曰：「齊桓舍射鉤，使管仲相；今使布竭股肱之力，為公前驅，可乎？」布縛急，謂劉備曰：「玄德，卿為坐客，我為執虜，不能一言以相寬乎？」太祖笑曰：「何不相語，而訴明使君乎？」意欲活之，命使寬縛。主簿王必趨進曰：「布，勍虜也。其眾近在外，不可寬也。」太祖曰：「本欲相緩，主簿復不聽，如之何？」
:::
:::
:::

::: {.callout-note appearance="minimal" #gaoshun}
::: {.columns}
::: {.column width="70%"}
<a href="#source-18" id="annotation-18">[18]</a> Yīngxióng jì states: [Gāo] Shùn as a man was pure and had stern dignity, did not drink alcohol, did not accept gifts. Those he commanded were over seven hundred troops, called as a thousand men, armor and fighting equipment all refined and orderly, whenever they attacked and struck none were not broken through, called as the Formation-Breaking Batallion. [Gāo] Shùn every time remonstrated [Lǚ] Bù saying: "Generally the ruination of family and destruction of state is not that there are no loyal ministers or intelligent men, it is merely the problem of not meeting with employment. General in your actions you do not willingly think in detail, invariably delight in speaking in error, the errors cannot be counted." [Lǚ] Bù understood his loyalty, but was not able to employ this. After [Lǚ] Bù's follower Hǎo Méng rebelled, he further distanced from [Gāo] Shùn. As Wèi Xù had inner and outer family relations,^[Inner refers to paternal same-surname kinship, outer to maternal different-surname kinship.] seized away all the troops commanded by [Gāo] Shùn to give to [Wèi] Xù. Reaching to when about to attack and battle, therefore ordered [Gāo] Shùn to command [Wèi] Xù's managed troops, [Gāo] Shùn also to the end was without resentment.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔五〕　英雄記曰：順為人清白有威嚴，不飲酒，不受饋遺。所將七百餘兵，號為千人，鎧甲鬥具皆精練齊整，每所攻擊無不破者，名為陷陳營。順每諫布，言「凡破家亡國，非無忠臣明智者也，但患不見用耳。將軍舉動，不肯詳思，輒喜言誤，誤不可數也」。布知其忠，然不能用。布從郝萌反後，更疏順。以魏續有外內之親，悉奪順所將兵以與續。及當攻戰，故令順將續所領兵，順亦終無恨意。
:::
:::
:::

### Chén Gōng {.unnumbered #chengong}

::: {.columns}
::: {.column width="70%"}
When Tàizǔ captured [Chén] Gōng, he asked [Chén] Gōng: "Do you wish for your aged mother and your daughter to be spared or not?" [Chén] Gōng replied stating: "[I, Chén] Gōng have heard that filial piety governing Heaven's Under is to not sever a man from parents, benevolence distributed on the Four Seas is to not extinguish a man's sacrifices. My aged mother is on Your Excellency, not on [me, Chén] Gōng." Tàizǔ summoned and cared for the mother to the end of her life, married of the daughter. <a href="#annotation-19" id="source-19">[19]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
太祖之禽宮也，問宮欲活老母及女不？宮對曰：「宮聞孝治天下者不絕人之親，仁施四海者不乏人之祀，老母在公，不在宮也。」太祖召養其母終其身，嫁其女。〔一〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-19" id="annotation-19">[19]</a> Yú-shì's Diǎnlüè states: Chén Gōng appellation Gōngtái was a Dōng prefecture man. Firmly upright and intensely resolute, in youth he formed relationships with all the famed servicemen Within the Seas. Reaching to Heaven's Under in chaos, he first joined Tàizǔ, later doubted his own position, and so followed [Lǚ] Bù, drawing up strategies for [Lǚ] Bù, [Lǚ] Bù every time did not follow his plans. When Xiàpī fell, the army servicemen seized [Lǚ] Bù and [Chén] Gōng, Tàizǔ met them both, talked with them about their lives, and therefore [Lǚ] Bù had words of requesting to be spared. Tàizǔ spoke to [Chén] Gōng stating: "Gōngtái, you usually say you have intelligence and planning in abundance, now what has become of it?" [Chén] Gōng looked back to point at [Lǚ] Bù stating: "Merely in connection to this man not following [Chén] Gōng's advice, it came to this. If they had been followed, also we would not necessarily have been captured." Tàizǔ laughed and said: "In today's affairs what do you say should be done?" [Chén] Gōng said: "As a servant not loyal, as a son not filial, death is the natural allotment." Tàizǔ said: "If you are like this, what of your aged mother?" [Chén] Gōng said: "[I, Chén] Gōng have heard that to use filial piety to govern Heaven's Under is to not harm a man's parents. Whether my aged mother survives or not is on Your Enlightened Excellency." Tàizǔ said: "What of your wife and children?" [Chén] Gōng said: "[I, Chén] Gōng have heard that to distribute benevolent government on Heaven's Under is to not sever a man's sacrifices. Whether my wife and children survive or not, also is on Your Enlightened Excellency." Tàizǔ did not speak again. [Chén] Gōng said: "I request to go out and meet execution, to make clear the military law." Therefore he hastened to go out, and could not be stopped. Tàizǔ wept and escorted him, [Chén] Gōng did not look back. After [Chén] Gōng died, Tàizǔ treated his family all with more generosity than before.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　魚氏典略曰：陳宮字公臺，東郡人也。剛直烈壯，少與海內知名之士皆相連結。及天下亂，始隨太祖，後自疑，乃從呂布，為布畫策，布每不從其計。下邳敗，軍士執布及宮，太祖皆見之，與語平生，故布有求活之言。太祖謂宮曰：「公臺，卿平常自謂智計有餘，今竟何如？」宮顧指布曰：「但坐此人不從宮言，以至于此。若其見從，亦未必為禽也。」太祖笑曰：「今日之事當云何？」宮曰：「為臣不忠，為子不孝，死自分也。」太祖曰：「卿如是，奈卿老母何？」宮曰：「宮聞將以孝治天下者不害人之親，老母之存否，在明公也。」太祖曰：「若卿妻子何？」宮曰：「宮聞將施仁政於天下者不絕人之祀，妻子之存否，亦在明公也。」太祖未復言。宮曰：「請出就戮，以明軍法。」遂趨出，不可止。太祖泣而送之，宮不還顧。宮死後，太祖待其家皆厚於初。
:::
:::
:::

### Chén Dēng {.unnumbered #chendeng}

::: {.columns}
::: {.column width="70%"}
As for Chén Dēng, appellation Yuánlóng, in Guǎnglíng he had prestige and fame. Also in dragging and horning [Lǚ] Bù he had achievements,^[Dragging (jǐ) and horning (jiǎo) refer to the strategy of attacking the front and rear simultaneously, in the metaphor of engaging a beast's horns at the front while dragging their legs from behind.] added Subduing Waves General, aged thirty-nine he died. Later Xǔ Sì with Liú Bèi both were with Jīng Province Governor Liú Biǎo seated, [Liú] Biǎo with [Liú] Bèi together discussed the men of Heaven's Under, [Xǔ] Sì said: "Chén Yuánlóng was a serviceman of the lakes and seas, his arrogant spirit did not abate." [Liú] Bèi spoke to [Liú] Biǎo stating: "Is Xǔ-jūn's opinion right or wrong?" [Liú] Biǎo said: "If I wish to say wrong, this gentleman \[Xǔ Sì\] is an excellent serviceman, and it is not appropriate to call him a liar. If I wish to say right, Yuánlóng's fame is weighty Under Heaven." [Liú] Bèi asked [Xǔ] Sì: "That you say arrogant, was it that there was an incident?" [Xǔ] Sì said: "In the past in encountering the chaos I passed through Xiàpī, met Yuánlóng. Yuánlóng was without the attitude of a host to guests, for a long time would not speak with me, himself atop a large bed lying down, having the guest lie on a lower bed." [Liú] Bèi said: "You have the reputation of a state serviceman, now Heaven's Under is in great chaos, the Emperor Ruler lost his place. One would expect you to worry for the state to the point of forgetting family, having the intention to rescue the world, but yet you request fields and investigate houses, your words had nothing worth considering. That was what Yuánlóng avoided discussing. For what reason should he speak with you? If it was a petty man, he'd wish to lie atop a hundred chǐ tower and have you lie on the ground, why only make a distinction of upper and lower bed?" [Liú] Biǎo greatly laughed. [Liú] Bèi took advantage to speak stating: "As for Yuánlóng's civil and martial courage and ambition, one should only compare it to antiquity, in the present it is difficult to find one comparable. <a href="#annotation-20" id="source-20">[20]</a>
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
陳登者，字元龍，在廣陵有威名。又掎角呂布有功，加伏波將軍，年三十九卒。後許汜與劉備並在荊州牧劉表坐，表與備共論天下人，汜曰：「陳元龍湖海之士，豪氣不除。」備謂表曰：「許君論是非？」表曰：「欲言非，此君為善士，不宜虛言；欲言是，元龍名重天下。」備問汜：「君言豪，寧有事邪？」汜曰：「昔遭亂過下邳，見元龍。元龍無客主之意，久不相與語，自上大床臥，使客臥下床。」備曰：「君有國士之名，今天下大亂，帝主失所，望君憂國忘家，有救世之意，而君求田問舍，言無可采，是元龍所諱也，何緣當與君語？如小人，欲臥百尺樓上，臥君於地，何但上下床之間邪？」表大笑。備因言曰：「若元龍文武膽志，當求之於古耳，造次難得比也。」〔一〕
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-20" id="annotation-20">[20]</a> Xiānxián Xíngzhuàng states: [Chén] Dēng was loyal and bright, lofty and clear, profound and deep, having great strategy, in youth he had the ambition to support the world and rescue the people. He widely read records and registers, elegant and having literary and artistic ability, the old canon and literary essays, none did he not go through and synthesize. Aged twenty-five, nominated Filial-Incorruptible, appointed Dōngyáng Chief,^[Dōngyáng county was in Guǎnglíng prefecture] cared for the eldery and raised the orphaned, looking after the people as if for the wounded. At the time, the world was desolate and the people hungry, Provincial Governor Táo Qiān memorialized [Chén] Dēng as Managing Agriculture Colonel, and so he toured the suitable lands and fields, thoroughly exploited the digging of irrigation, rice abundantly accumulated. Served as envoy to arrive in Xǔ, Tàizǔ appointed [Chén] Dēng as Guǎnglíng Administrator, ordered to secretly gather multitudes to plot against Lǚ Bù. [Chén] Dēng in Guǎnglíng clearly administered rewards and punishments, his authority and faith widely spread. Sea pirate Xuē Zhōu's crowds of over ten thousand households bound hands and submitted to command. Not even reaching a full year, his achievements and influence were accomplished, the Hundred Surnames feared and yet loved him. [Chén] Dēng said: "They can be employed." Tàizǔ arrived at Xiàpī, [Chén] Dēng led the prefecture troops as the army's advance force. At the time [Chén] Dēng's various younger brothers were inside Xiàpī city, [Lǚ] Bù thus took hostage three of [Chén] Dēng's younger brothers, wishing to request peace and unity. [Chén] Dēng maintained affairs without yielding, advanced and besieged for days pressingly. [Lǚ] Bù's Inspector of Treason^[Inspector of Treason (cìjiān) was an official in charge of detecting treachery and espionage.] Zhāng Hóng feared there would be later consequences, in the night led [Chén] Dēng's three younger brothers to go out to join [Chén] Dēng. When [Lǚ] Bù had been submitted to execution, [Chén] Dēng for the achievement was additionally appointed Subduing Waves General, extremely obtained pleased hearts between the Jiāng and Huái, and thereupon had the ambition to absorb and conquer the Jiāng's south. Sūn Cè sent an army to attack [Chén] Dēng at Kuāngqí city. When the rebels first arrived, the banners and armor covered the river, the crowds of subordinates all believed: "The present rebel multitudes are ten times that of the prefecture troops, we fear they cannot resist. We can withdraw the army to avoid them, leaving them an empty city. People of the water residing on land cannot stay for long and will certainly soon withdraw and leave." [Chén] Dēng in stern voice said: "I received the state's mandate, to come defend this land. In the past Mǎ Wényuān was in this position, he was able to in the south pacify the Hundred Yuè, in the north exterminate the crowds of Dí.^[Mǎ Yuán appellation Wényuān was a famed officer of early Later Hàn. He had previously held the rank of Subduing Waves General.] If I cannot restrain and eliminate the vicious and evil, what is the point of fleeing from bandits? I will thus send out my life to repay the state, wield righteousness to set order to chaos, Heaven's Way is with the obedient, subduing them is certain." Thus he shut the gates and self defended, appearing weak and not seeking battle, the officers and servicemen restrained voices, silent as if there were no people. [Chén] Dēng went up the city walls to watch the situation, and knew they could be struck. Then he extended orders to the officers and servicemen, in the night organized weapons, at twilight opened the south gate, led the army to go to the rebel camp, infantry and cavalry raiding their rear. The rebels were confused, about to join formations, could not return to their ships. [Chén] Dēng hand beat the army drums, unleashed the troops to overrun them, the rebels therefore were greatly defeated, all abandoned ships and scattered and fled. [Chén] Dēng followed up on the victory to pursue, beheading caitiffs in the tens of thousands. The rebels were furious to have lost an army, and soon again greatly mobilized troops to head toward [Chén] Dēng. [Chén] Dēng, because the troops wer eno match, sent Merit Officer Chén Jiǎo to request rescue from Tàizǔ. [Chén] Dēng secretly from the city by ten lǐ built an army camp position, ordering to obtain much firewood, two bundles per pile, spaced from one another by ten bù, forming vertical and horizontal lines, ordered in the night to all set fire, the fire burning the piles. Atop the city walls they declared celebrations, as if the main army had arrived. The rebels saw the fires and panicked and collapsed, [Chén] Dēng organized troops to pursue, cutting off heads in the tens of thousands. Transferred [Chén] Dēng to Dōngchéng Administrator. Guǎnglíng's clerks and people cherished his grace and virtue, together uprooted the prefecture to accompany [Chén] Dēng, old and young carried on backs to pursue him. [Chén] Dēng explained to have them return, stating: "When the Administrator was at your prefecture, repeatedly it attracked Wú bandits, by good fortune was there success and rescue. How can you sirs worry of not having a good leader?" Sūn Quán eventually strode and possessed the Jiāng's exterior. Tàizǔ every time on overlooking the Great Jiāng then sighed, regretting that he did not earlier use Chén Yuánlóng's plans, and so allowed a fearsome boar to grow its claws and teeth. Emperor Wén in recollection of [Chén] Dēng's achievements appointed [Chén] Dēng's son [Chén] Sù as a Cadet Central.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　先賢行狀曰：登忠亮高爽，沈深有大略，少有扶世濟民之志。博覽載籍，雅有文藝，舊典文章，莫不貫綜。年二十五，舉孝廉，除東陽長，養耆育孤，視民如傷。是時，世荒民飢，州牧陶謙表登為典農校尉，乃巡土田之宜，盡鑿溉之利，秔稻豐積。奉使到許，太祖以登為廣陵太守，令陰合眾以圖呂布。登在廣陵，明審賞罰，威信宣布。海賊薛州之群萬有餘戶，束手歸命。未及期年，功化以就，百姓畏而愛之。登曰：「此可用矣。」太祖到下邳，登率郡兵為軍先驅。時登諸弟在下邳城中，布乃質執登三弟，欲求和同。登執意不撓，進圍日急。布刺姦張弘，懼於後累，夜將登三弟出就登。布既伏誅，登以功加拜伏波將軍，甚得江、淮閒歡心，於是有吞滅江南之志。孫策遣軍攻登于匡琦城。賊初到，旌甲覆水，群下咸以今賊眾十倍於郡兵，恐不能抗，可引軍避之，與其空城。水人居陸，不能久處，必尋引去。登厲聲曰：「吾受國命，來鎮此土。昔馬文淵之在斯位，能南平百越，北滅群狄，吾既不能遏除凶慝，何逃寇之為邪！吾其出命以報國，仗義以整亂，天道與順，克之必矣。」乃閉門自守，示弱不與戰，將士銜聲，寂若無人。登乘城望形勢，知其可擊。乃申令將士，宿整兵器，昧爽，開南門，引軍詣賊營，步騎鈔其後。賊周章，方結陳，不得還船。登手執軍鼓，縱兵乘之，賊遂大破，皆棄船迸走。登乘勝追奔，斬虜以萬數。賊忿喪軍，尋復大興兵向登。登以兵不敵，使功曹陳矯求救於太祖。登密去城十里治軍營處所，令多取柴薪，兩束一聚，相去十步，縱橫成行，令夜俱起火，火然其聚。城上稱慶，若大軍到。賊望火驚潰，登勒兵追奔，斬首萬級。遷登為東城太守。廣陵吏民佩其恩德，共拔郡隨登，老弱襁負而追之。登曉語令還，曰：「太守在卿郡，頻致吳寇，幸而克濟。諸卿何患無令君乎？」孫權遂跨有江外。太祖每臨大江而歎，恨不早用陳元龍計，而令封豕養其爪牙。文帝追美登功，拜登息肅為郎中。
:::
:::
:::

## Zāng Hóng {.unnumbered #zanghong}

::: {.columns}
::: {.column width="70%"}
Zāng Hóng appellation Zǐyuán was a Guǎnglíng Shèyáng man. His father [Zāng] Mín successively was Xiōngnú Central Cadet General, Zhōngshān and Tàiyuán Administrator, wherever he was he had fame. <a href="#annotation-21" id="source-21">[21]</a> [Zāng] Hóng in body and appearance was imposing and sturdy, having distinguishment from others. Nominated Filial-Incorruptible, became a Cadet. At the time there was selections from the Three Bureaus of Cadets to fill vacancies as county Chiefs;^[Counties with populations below ten thousand were headed by a Chief (zhǎng) instead of a Magistrate (lìng).] Lángyé's Zhào Yù became Jǔ Chief,^[Jǔ county was in Lángyé prefecture.] Dōnglái's Liú Yáo Xiàyì Chief,^[Xiàyì county was in Liáng prefecture.] Dōnghǎi's Wáng Lǎng Zīqiū Chief,^[Zīqiū was in Péngchéng prefecture.] Hóng Jíqiū Chief.^[Jíqiū county was in Lángyé prefecture.] At the end of Emperor Líng, abandoned office and returned home, the Administrator Zhāng Chāo invited [Zāng] Hóng to be Merit Officer.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
臧洪字子源，廣陵射陽人也。父旻，歷匈奴中郎將、中山、太原太守，所在有名。〔一〕洪體貌魁梧，有異於人，舉孝廉為郎。時選三署郎以補縣長；瑯邪趙昱為莒長，東萊劉繇下邑長，東海王朗菑丘長，洪即丘長。靈帝末，棄官還家，太守張超請洪為功曹。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-21" id="annotation-21">[21]</a> Xiè Chéng's Hòu Hàn shū states: [Zāng] Mín had administrative talent, understanding in engaging in government, became a Hàn excellent clerk. First from Xú Province Following Official he was recruited to the Office of the Excellency over the Masses, appointed Lúnú Magistrate,^[Lúnú county was in Zhōnghsān prefecture.] Jì Province nominated him as Exceptionally Distinguished, promoted to Yáng Province Inspector, Dānyáng Administrator. At the time the frontier regions had alarms, the Qiāng and Hú set out to invade, the Three Offices nominated the capable, promoted [Zāng] Mín to Xiōngnú Central Cadet General, suppressed rebels and had achievements, summoned and appointed Consultant Cadet, returning to the capital region. Met Grand Commandant Yuán Féng, [Yuán] Féng asked him about the Western Regions various states' lands, customs, people, and tribes. [Zāng] Mín completely answered saying: "The Western Regions originally were thirty-six states, later divided into fifty-five, gradually scattering to reach over a hundred states." Their states large or small, the roads near or far, the people count many or few, the customs dry or wet, mountains and rivers, vegetation and trees, birds and beasts, different things and famed tribes, things not the same with the Central States, he all orally explained their circumstances, hand drew the topography. [Yuán] Féng was amazed with his talent, sighed and said: "Even Bān Gù's' composed Xīyù zhuàn,^[Xīyù zhuàn "Biographies of the Western Regions" is a chapter in the Hàn shū.] what could it add to this?" [Zāng] Mín was transferred and appointed Cháng River Colonel, ended as Tàiyuán Administrator.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　謝承後漢書曰：旻有幹事才，達於從政，為漢良吏。初從徐州從事辟司徒府，除盧奴令，冀州舉尤異，遷揚州刺史、丹楊太守。是時邊方有警，羌、胡出寇，三府舉能，遷旻匈奴中郎將。討賊有功，徵拜議郎，還京師。見太尉袁逢，逢問其西域諸國土地、風俗、人物、種數。旻具答言西域本三十六國，後分為五十五，稍散至百餘國；其國大小，道里近遠，人數多少，風俗燥濕，山川、草木、鳥獸、異物名種，不與中國同者，悉口陳其狀，手畫地形。逢奇其才，歎息言：「雖班固作西域傳，何以加此？」旻轉拜長水校尉，終太原太守。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Dǒng Zhuó killed the Emperor, plotting to endager the State Altars. [Zāng] Hóng advised [Zhāng] Chāo stating: "Your Enlightened Office^[Enlightened Office (míngfǔ) is a term of address for a prefecture Administrator (tàishǒu).] for successive generations received favor, elder and younger brothers all occupy large prefectures,^[Zhāng Chāo's elder brother Zhāng Miǎo was Administrator of Chénliú.] now the Royal House is just in danger, a traitor minister not yet beheaded,^[The term xiāo in this context refers to the punishment of cutting off and hanging up the head] this truly is the autumn for the righteous and ardent Under Heaven to repay favor by dedicating lives. Now the prefecture borders are still secure, clerks and civilians ample and wealthy, if we mobilize and beat the drums, we can obtain twenty thousand men, by this execute and eliminate the state traitor, to be the lead and first Under Heaven, it is the greatest of righteousness." [Zhāng] Chāo agreed to these words, with [Zāng] Hóng went west reaching Chénliú, meeting his elder brother [Zhāng] Miǎo to calculate affairs. [Zhāng] Miǎo also originally had intentions, gathered at Suānzǎo, [Zhāng] Miǎo spoke to [Zhāng] Chāo stating: "I hear that you, younger brother, as a prefecture Administrator, the government and instruction and authority and grace are not decided by you personally, but are entirely entrusted to Zāng Hóng. What sort of man is Zāng Hóng?" [Zhāng] Chāo said: "[Zāng] Hóng's talent and strategy, wisdom and resourcefulness surpass [me, Zhāng] Chāo. [I, Zhāng] Chāo extremely favor him. He is an exceptional serviceman Within the Seas." [Zhāng] Miǎo at once summoned and met [Zāng] Hóng, spoke with him and was greatly impressed with him. Introduced him to Liú Yǎnzhōu Gōngshān^[Liú Dài appellation Gōngshān was Inspector of Yǎn Province (Yǎnzhōu).] and Kǒng Yùzhōu Gōngxù,^[Kǒng Zhòu appellation Gōngxù was Inspector of Yù Province (Yùzhōu).] both became close and friendly with [Zāng] Hóng. Thus they set Platform Stage, preparing to together swear oath of alliance, the various provinces and prefectures deferred to one another, none daring to be first, all together nominated [Zāng] Hóng. [Zāng] Hóng thus ascended the platform, held the basin, smeared the blood^[The ritual involved smearing blood on the mouth.] and swore oath stating: "The Hàn House was not fortunate, the Imperial Network lost connection, traitor minister Dǒng Zhuó took advantage of openings to unleash harms, disaster applied on the Utmost Honored, brutality flowing to the Hundred Surnames, greatly fearing the loss and ruin of the State Altars, cutting down and overturning of the Four Seas. Yǎn Province Inspector [Liú] Dài, Yù Province Inspector [Kǒng] Zhòu, Chénliú Administrator [Zhāng] Miǎo, Dōng Prefecture Administrator [Qiáo] Mào, Guǎnglíng Administrator [Zhāng] Chāo and others, join together Righteous Troops, to together rush to the State's troubles. All of our same alliance unite heart and join strength, to deliver a servant's integrity, to lose our heads^[Yǔn shǒu and sāng yuán are both terms for losing one's head.] certainly without second thoughts. If any violate this oath, it will cause loss of their life, with no surviving descendants. Imperial Heaven and Lordly Earth, ancestral brilliant spirits, truly all witness this!" [Zāng] Hón'gs words and spirit were fierce and fervent, tears flowing down, all that heard his words, even the common soldiers and menial servants, none were not excited and roused, every man thinking to convey integrity. <a href="#annotation-22" id="source-22">[22]</a> Shortly after this, of the various armies none would be first to advance, and the food was exhausted and the multitudes scattered.^[I think Chén Shòu had a sense of humor here.]
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
董卓殺帝，圖危社稷，洪說超曰：「明府歷世受恩，兄弟並據大郡，今王室將危，賊臣未梟，此誠天下義烈報恩效命之秋也。今郡境尚全，吏民殷富，若動枹鼓，可得二萬人，以此誅除國賊，為天下倡先，義之大者也。」超然其言，與洪西至陳留，見兄邈計事。邈亦素有心，會于酸棗，邈謂超曰：「聞弟為郡守，政教威恩，不由己出，動任臧洪，洪者何人？」超曰：「洪才略智數優超，超甚愛之，海內奇士也。」邈即引見洪，與語大異之。致之于劉兗州公山、孔豫州公緒，皆與洪親善。乃設壇場，方共盟誓，諸州郡更相讓，莫敢當，咸共推洪。洪乃升壇操槃歃血而盟曰：「漢室不幸，皇綱失統，賊臣董卓乘釁縱害，禍加至尊，虐流百姓，大懼淪喪社稷，翦覆四海。兗州刺史岱、豫州刺史伷、陳留太守邈、東郡太守瑁、廣陵太守超等，糾合義兵，並赴國難。凡我同盟，齊心戮力，以致臣節，殞首喪元，必無二志。有渝此盟，俾墜其命，無克遺育。皇天后土，祖宗明靈，實皆鑒之！」洪辭氣慷慨，涕泣橫下，聞其言者，雖卒伍廝養，莫不激揚，人思致節。〔一〕頃之，諸軍莫適先進，而食盡眾散。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-22" id="annotation-22">[22]</a> Your Servant Sōngzhī notes: At the time this alliance stopped at having Liú Dài and the rest of five people and no more. Wèi-shì Chūnqiū absuredly includes Liú Biǎo and others of several people, all not the true facts. [Liú] Biǎo protected and occupied the Jiāng and Hàn, personally never once leaving the borders, how could he have been with [Zāng] Hóng together on the altar and swearing oath?
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　臣松之案：于時此盟止有劉岱等五人而已。魏氏春秋橫內劉表等數人，皆非事實。表保據江、漢，身未嘗出境，何由得與洪同壇而盟乎？
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
[Zhāng] Chāo sent [Zāng] Hóng to visit Marshal-in-Chief Liú Yú to plan, there happened to be the troubles of Gōngsūn Zàn, reached Héjiān, encountered Yōu and Jì two provinces engaging troops, his envoy mission could not be delivered. However Yuán Shào met [Zāng] Hóng, also was amazed and valued him, with him joining in friendship. It happened that Qīng Province Inspector Jiāo Hé died, [Yuán] Shào sent [Zāng] Hóng to manage Qīng Province to succor its multitudes. <a href="#annotation-23" id="source-23">[23]</a> [Zāng] Hóng was in the province for two years, the crowds of bandits fled away. [Yuán] Shào sighed at his ability, transferred him to Dōng Prefecture Administrator, governing at Dōngwǔyáng.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
超遣洪詣大司馬劉虞謀，值公孫瓚之難，至河間，遇幽、冀二州交兵，使命不達。而袁紹見洪，又奇重之，與結分合好。會青州刺史焦和卒，紹使洪領青州以撫其眾。〔一〕洪在州二年，群盜奔走。紹歎其能，徙為東郡太守，治東武陽。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-23" id="annotation-23">[23]</a> Jiǔzhōu Chūnqiū states: During Chūpíng, Jiāo Hé became Qīng Province Inspector. At the time outstanding heroes were all rising, Huángjīn bandits violet, [Jiāo] Hé attended to joining the alliance, entirely focused on entering the capital region, with no attention on protecting the people, led the army to cross the Hé and go west. Not long after Yuán and Cáo two Excellencies with [Dǒng] Zhuó's officers battled at Xíngyáng, defeated utterly. Huángjīn therefore spread, slaughtered and split apart cities and towns. [Jiā] Hé could not resist, however the army equipment was still sharp, the battle servicemen still numerous, but ears and eyes of scouts and patrols were not set in place, reports of fear and disturbance rashly arrived, on seeing bandits he fled, never once facing the winds and dusts of engaging banners and drums. He wished to make breaking ice pills to drop in the rivers to make bandits unable to cross, make prayers to various deities, requesting every use of troops to be certainly successful, elderly stalk-diviners always were arrayed at the front, shamans did not leave his side. Entering one saw his pure conversation touching the clouds, exiting then it was muddled chaos, commands could not be understood.^["Mìng bù kě zhī" can also be translated as "his fate could not be known," but I personally favor interpreting "mìng" as "command" as it ties into the previous statements on his skill in pure conversation inside but the total chaos outside.] The province therefore was desolate, all became ruins.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　九州春秋曰：初平中，焦和為青州刺史。是時英雄並起，黃巾寇暴，和務及同盟，俱入京畿，不暇為民保障，引軍踰河而西。未久而袁、曹二公卓將戰于滎陽，敗績。黃巾遂廣，屠裂城邑。和不能禦，然軍器尚利，戰士尚眾，而耳目偵邏不設，恐動之言妄至，望寇奔走，未嘗接風塵交旗鼓也。欲作陷冰丸沈河，令賊不得渡，禱祈群神，求用兵必利，耆筮常陳於前，巫祝不去於側；入見其清談干雲，出則渾亂，命不可知。州遂蕭條，悉為丘墟也。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
Tàizǔ besieged Zhāng Chāo at Yōngqiū, [Zhāng] Chāo said: "I only rely on Zāng Hóng, he will come rescue me." Everyone believed: "Yuán and Cáo are now amicable, and [Zāng] Hóng has been by [Yuán] Shào memorialized^[Memorialized (biǎo) reflects the legal fiction that government appointments required approval by the Hàn Imperial Court. Legally speaking, the powerful warlords were "memorializing recommendations to the Court" rather than appointing their subordinates to government positions.] and employed, and certainly will not destroy good relations to provoke disaster, and from afar come rushing here." [Zhāng] Chāo said: "Zǐyuán is a righteous serviceman Under Heaven, to the end he will not turn back on his roots, I only fear he will meet with restraints, and not reach us in time." [Zāng] Hóng heard of this, and indeed went barefooted, wailing and sobbing, gathering and orgnizing the troops he managed, and also from [Yuán] Shào requested troops and horses, begging to rescue [Zhāng] Chāo, but [Yuán] Shào to the end would not listen and permit it. [Zhāng] Chāo therefore was clan exterminated. [Zāng] Hóng because of this resented [Yuán] Shào, cut off and would not communicate. [Yuán] Shào raised troops to beseige him, for successive years did not subdue him. [Yuán] Shào had [Zāng] Hóng's fellow townsman Chén Lín write a letter to [Zāng] Hóng, explaining the disasters and fortunes, reproaching with grace and righteousness. [Zāng] Hóng's answer stated:
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
太祖圍張超于雍丘，超言：「唯恃臧洪，當來救吾。」眾人以為袁、曹方睦，而洪為紹所表用，必不敗好招禍，遠來赴此。超曰：「子源，天下義士，終不背本者，但恐見禁制，不相及逮耳。」洪聞之，果徒跣號泣，並勒所領兵，又從紹請兵馬，求欲救超，而紹終不聽許。超遂族滅。洪由是怨紹，絕不與通。紹興兵圍之，歷年不下。紹令洪邑人陳琳書與洪，喻以禍福，責以恩義。洪答曰：
:::
:::

::: {.columns}
::: {.column width="70%"}
Separated apart I think of you whether awake or asleep. By fortune we are separated from one another by only footsteps, but yet as our choices^[Here the term qùshě can be understood as what one pursues (qù) and what one abandons (shě).] follow different standards, we are unable to see one another, it is mounrful and sad, how can one's heart bear it? In previous days you did not forget me, and recently I was indebted by your gracious gift,^[This refers to Chén Lín's letter.] explaining the disasters and fotunes, public and private earnest and urgent. That I did not at once present an answer, was that my learning is shallow and talent dull and insufficient to counter your interrogations, and also that you sir bring along your side rooms^[Side rooms (cèshì) can refer to one's women and concubines.] and rest with a master,^[This refers to Yuán Shào.] family in the eastern provinces, and I^[Zāng Hóng uses the first person pronoun pú, which can mean "servant." The Japanese first person pronoun "boku" derives from this.] am /[Yuán Shào's/] enemy. To like this serve another, even if it is draped in internal feelings, spilling my liver and guts, yet my body is estranged and has crimes, sweet words will meet with suspicion. When head and tail cannot rescue one another, how can one sympathize with another? Moreover with your talents, exhaustively learned in the canon and registers, how can you be ignorant of the great Way, and not understand my intentions? However yet you resume speaking on and on, and I from this know that your words in fact do not come from your heart, and are to avert disaster. If you certainly wish to calculate strengths and shortcomings, debate and ask right or wrong, the discourses on right or wrong, the words fill Heaven's Under, laying them out does not make things clearer, and not speaking is of no detriment. Also you speak of damaging the obligations to announce a severing of relations, that is not what I could bear to do, and therefore I abandoned paper and pen, without a single answer, also hoping that from afar you would guess my heart, understand my plans are settled, with no further changes. Agan I receiving your coming message, citing antiquity and the present, tangled across six pages, though I wish to not speak, how can I do so?

I am a petty man, originally took advantage of going on campaign, seized a great province,^[The phrase kòu qiè dà zhōu is also commonly interpreted as "bandits stealing a great province" in reference to the cause of the military campaign, but I prefer to interpret it as referring to Zāng Hóng's tenure as Inspector of Qīng Province. The variant version of this letter in Hòu Hàn shū 58 supports this interpretation.] favor deep and relationship thick, how can I delight in today personally returning to cross blades? Every time I ascend the city walls and organize troops, I look out to our master's banners and drums, emotionally moved that old friends are among them, stroking bow string and holding arrow, unconsciously tears overflow my face. Why is this? From since I assisted the master, there were no regrets. The master's treatment of me surpassed all standards. At the beginning of receiving appointment, I myself said we would accomplish great affairs, together honoring the Royal House. How could one expect that Heaven's Son would be displeased, our home province meet with invasion, the prefecture commander encounter the danger of Yǒulǐ,^[The danger of Yǒulǐ refers to the story that the future King Wén of Zhōu was imprisoned for seven years at Yǒulǐ.] Chénliú devising military schemes? Plans being delayed ruins a name of loyalty and filial piety, cracking whip to turn away and leave destroys a relationship of friends. Considering these two, with one unable to do as one wishes, to ruin a name of loyalty and filial piety or to destroy a way of friendship, the lightness or heaviness are different, the closeness or distance of different forms, and therefore I then collect my tears and announce severing of relations. Supposing if the master had slightly considered an old friend, those staying given side seats, those leaving allowed to do so, not eager to separate friends, trust in punishments to support himself then I would have maintained the will of Jì Zhá,^[Jì Zhá was a Spring and Autumn era son of the ruling family of Wú state. He famously refused the offered throne of Wú state.] and not fighting battle today. How to prove this? In the past Zhāng Jǐngmíng personally ascended the platform to smear blood, served command to run and rush, in the end causing Governor Hán to yield seal and the master to obtain the territory, but afterward merely for submitting Reply to the Court Ruler and receiving bestowal of noble title and obtaining transfer, within a short time, he was not immersed in pardons for perceived transgressions and received the disaster of extermination. <a href="#annotation-24" id="source-24">[24]</a> Lǚ [Bù] Fèngxiān suppressed [Dǒng] Zhuó and came fleeing, requested troops and did not obtain them, in announcing his departure what was the crime? Yet he met with chopping and stabbing, to the brink of death. Liú Zǐqí^[Zǐqí seems to be a transcription error for Zǐhuáng. The corresponding Péi Sōngzhī annotation and the version of this letter in Hòu Hàn shū 58 both have Zǐhuáng instead of Zǐqí.] served as envoy for extended time, resigned but did not obtain permission, feared authority but missed family, resorted to deception to request to return, could be said to have had commitment to loyalty and filial piety, with no detriment to the Hegemon's WAy, however immediately he fell dead beneath the banners, not immersed in reduction or exemption. <a href="#annotation-25" id="source-25">[25]</a> Although I am not quick-witted, and always am unable to from the beginning see the end or from the subtle understand the clear, I humbly measured the master's heart, how could he say the three sirs should have died, and the punishments correct to the crimes? In fact it was a desire to unify the east of the mountains, increase troops to suppress enemies, fearing the battle servicemen would be suspicious, with no way to discourage or encourage, therefore he suppressed and disregarded the Royal Mandates to esteem his delegated authority,^[The term chéngzhì "carried regulations" refers to being granted authority by the ruler to act on the ruler's behalf.] those who embraced his cause were immersed in honor, those who waited for release were killed, this then was to the advantage of the master, not the hopes of wandering servicemen. Therefore I reflected on the warnings of past men, driven by desperation to fight to the death. Although I am inferior and foolish, I also have at least heard the words of noble men. This truly was not of my heart. It was the master that incurred it. The entire reason I turn back and abandon state and people and give my life to this city, is precisely because when a noble man departs he does not go over to an enemy state. Therefore I obtained the master's punishment, meeting with attack for extended time, but yet you sir further cite this principle to admonish me, is this not statements being the same while the directions differ, not how a noble man shares fortunes or sorrows?

I have heard that righteousness is not to turn back on kin, loyalty is not to disobey lord, therefore in the ast I regarded my home province as my kin's assistance, in the middle I supported the prefecture commander to secure the State Altars, in one motion two gains of enacting loyalty and filial piety, how could it be wrong? But yet you sir wish me to think lightly of roots and dstroy family, and treat equally lord and master. The master to me in years was like my elder brother, in relationship was a genuine friend, when the paths diverged I announced my departure, to secure lord and kin, it can be called obedience. By your words, then Bāoxū should have sacrificed his life for Wǔ Yuán and should not have wailed in Qín's Court.^[In the Spring and Autumn era, Shēn Bāoxū and Wǔ Yuán were friends from rival states. When Wǔ Yuán's home state of Wú invaded Bāoxū's home state of Chǔ, Shēn Bāoxū went to Qín state to beg for their assistance to rescue Chǔ.] If you narrowfuly focus on avoiding disaster, you do not understand your words have diverged from reason. Perhaps you observe that the city's besiegement is not resolved, rescue troops do not arrive, and are emotionally moved by relationship through marriage, thinking of lifelong friendship, believing that compromising integrity to pointlessly live is better than maintaining righteousness to topple and fall. In the past Yán Yīng did not surrender his will to naked blade, the Southern Scribe did not bend brush to save his life, and therefore their bodily form is painted in portraits, their names bequeathed to later generations, all the more when I occupy the hardness of a metal city, drive the strength of servicemen and civilians, distribute three years of stores to be one year's resources, assisting the destitute and mending the deficient, to please Heaven's Under, how can I plan to build houses and return to plowing? I only fear the autumn winds raising dust, Bóguī's horses heads turning south,^[Gōngsūn Zàn appellation Bóguī was the warlord to the north of Yuán Shào.] Zhāng Yáng and Fei Yàn^[Zhāng Yáng was a warlord to the west of Yuán Shào. Zhāng Yàn was a bandit warlord also known as Fēi Yàn "Flying Swallow," also to the west of Yuán Shào.] mustering strength to make trouble, the northern borders about to announce the emergency of falling counties, legs and arms^[Legs and arms (gǔgōng) are a metaphor for trusted ministers and supporters.] memorializing sincere requests to return. The master should take warning from us, turn banners and withdraw brigades, drill troops at Yè's walls, why should he for a long time indulge in overwhelming rage, displaying violent power below our city walls? You sir ridicule me for relying on the Hēishān as rescue,^[The Hēishān "Black Mountain" were a bandit confederation to the west of Yuán Shào.] do you alone not remember the gathering followers of the Huángjīn? Moreover Fēi Yàn and his associates all have received Royal Commands. In the past Gāozǔ recruited Péng Yuè at Jùyě, Guāng-Wǔ initiated his foundations at Lùlín,^[Péng Yuè was originally a bandit warlord during the collapse of Qín and rise of Former Hàn. Lùlín "Green Woods" was originally a bandit group during the Former Hàn-Xīn-Later Hàn transition period.] in the end able to like a dragon soar in the Internal Restoration, to achieve the Emperor's enterprise. If one can assist the ruler in raising transformation, whwy have suspicions? All the more when I personally serve Ruler's Seal marked letter to with them undertake affairs.

Go Kǒngzhāng! You sir will seek profits on the outside, Zāng Hóng will give life for lord and kin. You entrust body to the alliance master, Zāng Hóng enrolls his name to Cháng'ān. You say my body will die and my name extinguished, I also laugh that living or dead you will not be heard of. A sorrow! The roots the same but the tips separate, strive hard, strive hard, what else is to be said?
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
隔闊相思，發于寤寐。幸相去步武之間耳，而以趣舍異規，不得相見，其為愴悢，可為心哉！前日不遺，比辱雅貺，述敘禍福，公私切至。所以不即奉答者，既學薄才鈍，不足塞詰；亦以吾子攜負側室，息肩主人，家在東州，僕為仇敵。以是事人，雖披中情，墮肝膽，猶身疏有罪，言甘見怪，方首尾不救，何能恤人？且以子之才，窮該典籍，豈將闇于大道，不達余趣哉！然猶復云云者，僕以是知足下之言，信不由衷，將以救禍也。必欲算計長短，辯諮是非，是非之論，言滿天下，陳之更不明，不言無所損。又言傷告絕之義，非吾所忍行也，是以捐棄紙筆，一無所答。亦冀遙忖其心，知其計定，不復渝變也。重獲來命，援引古今，紛紜六紙，雖欲不言，焉得已哉！

　　僕小人也，本因行役，寇竊大州，恩深分厚，寧樂今日自還接刃！每登城勒兵，望主人之旗鼓，感故友之周旋，撫弦搦矢，不覺流涕之覆面也。何者？自以輔佐主人，無以為悔。主人相接，過絕等倫。當受任之初，自謂究竟大事，共尊王室。豈悟天子不悅，本州見侵，郡將遘牖里之厄，陳留克創兵之謀，謀計棲遲，喪忠孝之名，杖策攜背，虧交友之分。揆此二者，與其不得已，喪忠孝之名與虧交友之道，輕重殊塗，親疏異畫，故便收淚告絕。若使主人少垂故人，住者側席，去者克己，不汲汲于離友，信刑戮以自輔，則僕抗季札之志，不為今日之戰矣。何以效之？昔張景明親登壇喢血，奉辭奔走，卒使韓牧讓印，主人得地；然後但以拜章朝主，賜爵獲傳之故，旋時之間，不蒙觀過之貸，而受夷滅之禍。〔一〕呂奉先討卓來奔，請兵不獲，告去何罪？復見斫刺，濱于死亡。劉子琪奉使踰時，辭不獲命，畏威懷親，以詐求歸，可謂有志忠孝，無損霸道者也；然輒僵斃麾下，不蒙虧除。〔二〕僕雖不敏，又素不能原始見終，睹微知著，竊度主人之心，豈謂三子宜死，罰當刑中哉？實且欲一統山東，增兵討讎，懼戰士狐疑，無以沮勸，故抑廢王命以崇承制，慕義者蒙榮，待放者被戮，此乃主人之利，非游士之願也。故僕鑒戒前人，困窮死戰。僕雖下愚，亦嘗聞君子之言矣。此實非吾心也。乃主人招焉。凡吾所以背棄國民，用命此城者，正以君子之違，不適敵國故也。是以獲罪主人，見攻踰時，而足下更引此義以為吾規，無乃辭同趨異，非君子所為休戚者哉！

　　吾聞之也，義不背親，忠不違君，故東宗本州以為親援，中扶郡將以安社稷，一舉二得以徼忠孝，何以為非？而足下欲吾輕本破家，均君主人。主人之於我也，年為吾兄，分為篤友，道乖告去，以安君親，可謂順矣。若子之言，則包胥宜致命於伍員，不當號哭於秦庭矣。苟區區於攘患，不知言乖乎道理矣。足下或者見城圍不解，救兵未至，感婚姻之義，惟平生之好，以屈節而苟生，勝守義而傾覆也。昔晏嬰不降志於白刃，南史不曲筆以求生，故身著圖象，名垂後世，況僕據金城之固，驅士民之力，散三年之畜，以為一年之資，匡困補乏，以悅天下，何圖築室反耕哉！但懼秋風揚塵，伯珪馬首南向，張楊、飛燕，膂力作難，北鄙將告倒縣之急，股肱奏乞歸之誠耳。主人當鑒我曹輩，反旌退師，治兵鄴垣，何宜久辱盛怒，暴威於吾城下哉？足下譏吾恃黑山以為救，獨不念黃巾之合從邪！加飛燕之屬悉以受王命矣。昔高祖取彭越于鉅野，光武創基兆于綠林，卒能龍飛中興，以成帝業，苟可輔主興化，夫何嫌哉！況僕親奉璽書，與之從事。

　　行矣孔璋！足下徼利於境外，臧洪授命於君親；吾子託身於盟主，臧洪策名於長安。子謂余身死而名滅，僕亦笑子生死而無聞焉，悲哉！本同而末離，努力努力，夫復何言！
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-24" id="annotation-24">[24]</a> Your Servant Sōngzhī notes Yīngxióng jì says "Yuán Shào sent Zhāng Jǐngmíng, Guō Gōngzé, Gāo Yuáncái and others to persuade Hán Fù, having him yield Jì Province." That being the case, in [Hán] Fù's yielding of position, Jǐngmíng also had this achievement. The remaining matters are not certain.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　臣松之案英雄記云：「袁紹使張景明、郭公則、高元才等說韓馥，使讓冀州。」然〔則〕馥之讓位，景明亦有其功。其餘之事未詳。
:::
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-25" id="annotation-25">[25]</a> Your Servant Sōngzhī notes: Gōngsūn Zàn's memorial listing [Yuán] Shào's crimes and transgressions says: "[Yuán] Shào with former Tiger Fang General Liú Xūn first together raised troops, [Liú] Xūn repeatedly proved himself, but yet for a petty anger he unjustly murdered [Liú] Xūn, this is [Yuán] Shào's crime seven." One suspects this as Zǐhuáng.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔二〕　臣松之案：公孫瓚表列紹罪過云：「紹與故虎牙將軍劉勳首共造兵，勳仍有效，而以小忿枉害于勳，紹罪七也。」疑此是子璜也。
:::
:::
:::

::: {.columns}
::: {.column width="70%"}
[Yuán] Shào saw [Zāng] Hóng's letter, knew he had no intention to surrender, increased troops and urgently attacked. Inside the city the provisions and grain were exhausted, outside there was no strong rescue, [Zāng] Hóng himself judged he certainly would not survive, called his clerks and servicemen and spoke stating: "Yuán-shì is without morality, what he plots treasonous, and moreover did not rescue [Zāng] Hóng's prefecture commander. [I, Zāng] Hóng for great righteousness cannot not die, now you sirs have no reason to in vain share in this calamity. You can in advance when the city has not yet fallen lead your wives and children to go out." The officers and clerks and servicemen and civilians all shed tears and said: "Your Enlightened Office with Yuán-shì originally were without resentment or discord, now for the sake of the prefecture commander appointed by the Current Court, you bring on yourself ruin and destitution, how can we clerks and civilians bear to abandon Your Englightened Office and leave?" At first they yet dug up rats and boiled sinews and horns, later there was nothing left that could be eaten. The Registrar reported the inner kitchen had rice of three dǒu, and requested it be divided among them slightly to make gruel. [Zāng] Hóng sighed and said: "How can I alone eat this?" He had them make a thin gruel, everyone divided and drank it, and killed his favorite concubine to feed the officers and servicemen. The officers and servicemen all shed tears, with none able to look up. Males and feamles of seven to eight thousand people laid down on one another and died, none deserted or rebelled.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
紹見洪書，知無降意，增兵急攻。城中糧穀以盡，外無彊救，洪自度必不免，呼吏士謂曰：「袁氏無道，所圖不軌，且不救洪郡將。洪於大義，不得不死，今諸君無事空與此禍！可先城未敗，將妻子出。」將吏士民皆垂泣曰：「明府與袁氏本無怨隙，今為本朝郡將之故，自致殘困，吏民何忍當舍明府去也！」初尚掘鼠煮筋角，後無可復食者。主簿啟內廚米三斗，請中分稍以為糜粥，洪歎曰：「獨食此何為！」使作薄粥，眾分歠之，殺其愛妾以食將士。將士咸流涕，無能仰視者。男女七八千人相枕而死，莫有離叛。
:::
:::

::: {.columns #chenrong}
::: {.column width="70%"}
The city fell, [Yuán] Shào captured [Zāng] Hóng alive. [Yuán] Shào formerly was close with [Zāng] Hóng, lavishly set curtain tents, in a great assembly of the various officers met with [Zāng] Hóng, spoke stating: "Zāng Hóng, how could you betray me like this? Today will you submit or not?" [Zāng] Hóng stood his ground and angrily glared, stating: "The various Yuán served Hàn, in four generations five excellencies, can can be said to have received favor. Now the Royal House is feeble and weak, you are without intentions to support and assist, wish to take advantage of an opportunity, hoping for what should not be hoped for, killing many of the loyal and good to establish treacherous power. [I, Zāng] Hóng personally saw you call Zhāng Chénliú as your elder brother,^[Zhāng Miǎo was Administrator of Chénliú.], then [Zāng] Hóng's Office Lord^[Office Lord (fǔjūn) is a term of respect for an Administrator, in this case Zhāng Miǎo's younger brother Zhāng Chāo, Administrator of Guǎnglíng.] also should be your younger brother, to together combined strength to for the state eliminate harm, how could you hold your multitudes to watch another be slaughtered and exterminated? Regrettably [Zāng] Hóng's strength is inferior, unable to advance blade to for Heaven's Under take revenge, how can you speak of submitting?" [Yuán] Shào originally favored [Zāng] Hóng and wished to force him to submit and pardon him. Seeing that [Zāng] Hóng's statements were definite, he knew that in the end he \[Zāng Hóng\] could not be employed by him \[Yuán Shào\] and so killed him. <a href="#annotation-26" id="source-26">[26]</a> [Zāng] Hóng's townsman Chén Róng from youth was a scholar, personally admired [Zāng] Hóng, accompanied [Zāng] Hóng as Dōng Prefecture Deputy.^[Deputy (chéng) was an assistant to the Administrator of a prefecture.] When the city was not yet defeated, [Zāng] Hóng had sent him out. [Yuán] Shào had him among the seated, on seeing [Zāng] Hóng was about to die, he rose and spoke to [Yuán] Shào stating: "General you have undertaken a great affair, wishing to for Heaven's Under eliminate the violent, but yet you instead first execute the loyal and righteous, how is it in accord with Heaven's will? Zāng Hóng mobilized for his prefecture's commander, how can you kill him?" [Yuán] Shào was ashamed, the Left and Right had someone lead [Chén Róng] out, and spoke stating: "You are not Zāng Hóng's peer, why act like this for nothing?" [Chén] Ròng looked back and said: "Benevolence and righteousness, how do they have constancy? To walk it then is to be a noble man, to turn back on it then is to be a petty man. Today I would rather die on the same day with Zāng Hóng, then live on the same day with you General!" He also was killed. Of those seated with [Yuán] Shào none did not sigh, and secretly spoke with one another stating: "How could he kill two martyrs in one day?" Before this, [Zāng] Hóng had sent Majors of two men out,^[Major (sīmǎ) was a chief of staff for military affairs used by higher ranking military officers.] to request rescue from Lǚ Bù. By the time they returned, the city had already fallen, both charged the enemy and died.
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
城陷，紹生執洪。紹素親洪，盛施幃幔，大會諸將見洪，謂曰：「臧洪，何相負若此！今日服未？」洪據地瞋目曰：「諸袁事漢，四世五公，可謂受恩。今王室衰弱，無扶翼之意，欲因際會，希冀非望，多殺忠良以立姦威。洪親見呼張陳留為兄，則洪府君亦宜為弟，同共戮力，為國除害，何為擁眾觀人屠滅！惜洪力劣，不能推刃為天下報仇，何謂服乎！」紹本愛洪，意欲令屈服，原之；見洪辭切，知終不為己用，乃殺之。〔一〕洪邑人陳容少為書生，親慕洪，隨洪為東郡丞；城未敗，洪遣出。紹令在坐，見洪當死，起謂紹曰：「將軍舉大事，欲為天下除暴，而專先誅忠義，豈合天意！臧洪發舉為郡將，奈何殺之！」紹慚，左右使人牽出，謂曰：「汝非臧洪儔，空復爾為！」容顧曰：「夫仁義豈有常，蹈之則君子，背之則小人。今日寧與臧洪同日而死，不與將軍同日而生！」復見殺。在紹坐者無不歎息，竊相謂曰：「如何一日殺二烈士！」先是，洪遣司馬二人出，求救于呂布；比還，城已陷，皆赴敵死。
:::
:::

::: {.callout-note appearance="minimal"}
::: {.columns}
::: {.column width="70%"}
<a href="#source-26" id="annotation-26">[26]</a> Xú Zhòng's Sān Guó píng states: [Zāng] Hóng esteemed reptuations for righteousness Under Heaven, rescued his former lord from danager, his kindness sufficient to move people's feelings, his righteousness sufficient to encourage declined customs. However Yuán also was a close friend who understood him,^[Zhījǐ "know oneself" is a term for a true close friend who truly knows and understands you.] conveyed him to position in province and prefecture, although they were not lord and servant, yet he was truly the Alliance Leader, and having accepted his mandates, by righteousness he should not have betrayed him. Yuán and Cáo where then amicable, on each side supporting the Royal House, Lǚ Bù was vacillating and without righteousness, ambitions in rebellion and chaos, and yet [Zhāng] Miǎo and [Zhāng] Chāo usurped authority to establish [Lǚ] Bù as Provincial Governor, and in regards to Royal Law, then he was simply a criminal. Cáo-gōng suppressing him, Yuán-shì not rescuing, was not unreasonable. [Zāng] Hóng originally should not have gone to Yuán to request troops, and also should not have returned to become a resentful enemy. Calculating for [Zāng] Hóng, if his strength was insufficient, he could flee to another state to request to go rescue, and if his plans and strength were not yet deployed in order to wait for opportunities, then he should have slowly further watched for an opening, and devote himself to the death for [Zhāng] Chāo, why did he need to swear to defend a doomed city without any adaptability, killing himself and destroying his people, achievement and reputation not established, it is truly lamentable!"
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
〔一〕　徐眾三國評曰：洪敦天下名義，救舊君之危，其恩足以感人情，義足以勵薄俗。然袁亦知己親友，致位州郡，雖非君臣，且實盟主，既受其命，義不應貳。袁、曹方睦，夾輔王室，呂布反覆無義，志在逆亂，而邈、超擅立布為州牧，其於王法，乃一罪人也。曹公討之，袁氏弗救，未為非理也。洪本不當就袁請兵，又不當還為怨讎。為洪計者，苟力所不足，可奔他國以求赴救，若謀力未展以待事機，則宜徐更觀釁，效死於超。何必誓守窮城而無變通，身死殄民，功名不立，良可哀也！
:::
:::
:::

## Appraisal {.unnumbered}

::: {.columns}
::: {.column width="70%"}
Appraisal states: Lǚ Bù had the valor of a ferocious tiger, but was without outstanding or unique strategy, frivilous and crafty and vacillating, only profits were regarded. From antiqtuity to the present, never once was there one like this who was not exterminated. In the past Hàn Guāng-Wǔ was mistaken with Páng Méng, more recently Wèi Tàizǔ also was deceived by Zhāng Miǎo. "To know men then is wisdom, even an Emperor finds it difficult,"^[This is a quote from the Shàng Shū.] true indeed! Chén Dēng and Zāng Hóng both had heroic spirit and strong integrity, [Chén] Dēng's allotted years were early to perish, achievements and enterprirse not completed, [Zāng] Hóng because his troops were eak and the enemy strong, ardent resolve not established, a pity!
:::
::: {.column width="5%"}
:::
::: {.column width="25%"}
評曰：呂布有虓虎之勇，而無英奇之略，輕狡反覆，唯利是視。自古及今，未有若此不夷滅也。昔漢光武謬於龐萌，近魏太祖亦蔽于張邈。知人則哲，唯帝難之，信矣！陳登、臧洪並有雄氣壯節，登降年夙隕，功業未遂，洪以兵弱敵彊，烈志不立，惜哉！ 
:::
:::
